objects/Account.object
<CustomObject>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platinum_Email__c</fullName>
        <label>Platinum Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platinum_Password__c</fullName>
        <label>Platinum Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platinum_Wordpress_Id__c</fullName>
        <label>Platinum Wordpress Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/wordpressUpdatePlatinumUserTest.cls
@isTest
public class wordpressUpdatePlatinumUserTest {
    
     @testSetup static void createTestData() {
        
        Account a = new Account();
        a.First_Name__c = 'Bob';
        a.Last_Name__c = 'Apples';
        a.Name = '123';
        a.E_Mail__c = 'bazam123@gmail.com';
        insert a;
        
        Contact c = new Contact();
        c.AccountId = a.id;
        c.FirstName = 'Bob';
        c.LastName = 'Apples';
        c.Email = 'bazam123@gmail.com';
        c.Account_Roles__c = 'Primary Contact';
        c.Platinum_Wordpress_Id__c = '1';
        c.Platinum_Email__c = 'bazam123@gmail.com';
        c.Platinum_Password__c = 'supersecurepassword';
        insert c;
        
        Opportunity o = new Opportunity();
        o.AccountId = a.Id;
        o.Name = 'Platinum Subscription';
        o.CloseDate = system.today();
        o.StageName = 'Closed Won';
        o.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Platinum Subscription').getRecordTypeId();
        insert o;
        
    }
    
    @isTest
    public static void runTestOne() {
        
        List<Contact> conList = [SELECT Platinum_Wordpress_Id__c, Platinum_Email__c, Platinum_Password__c, FirstName, LastName FROM Contact];
        
        wordpressUpdatePlatinumUser.processContacts(conList);
             wordpressUpdatePlatinumUser.processContactsforreset(conList);
        
    }
    
    @isTest static void testPostCallout() {
		
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new wordpressUpdatePlatinumUserCalloutMock());
        
        HttpResponse response = wordpressUpdatePlatinumUser.serverSendmessage('1','Bob','Apples', 'bazam123@gmail.com');
        // HttpResponse response = wordpressUpdatePlatinumUser.serverSendmessage('1','Bob','Apples', 'bazam123@gmail.com', 'masterpassword');
        String contentType = response.getHeader('Content-Type');
        system.assert(contentType == 'application/json');
        System.assertEquals(201, response.getStatusCode());
        test.stopTest();
        
    }
     @isTest static void testPostCalloutReset() {
		
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new wordpressUpdatePlatinumUserCalloutMock());
        
       // HttpResponse response = wordpressUpdatePlatinumUser.serverSendmessage('1','Bob','Apples', 'bazam123@gmail.com');
       HttpResponse response = wordpressUpdatePlatinumUser.serverSendmessageforreset('1','Bob','Apples', 'masterpassword');
        String contentType = response.getHeader('Content-Type');
        system.assert(contentType == 'application/json');
        System.assertEquals(201, response.getStatusCode());
        test.stopTest();
        
    }

}