objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Credit_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Detail</relationshipLabel>
        <relationshipName>Credit_Card_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Zip_Postal__c</fullName>
        <label>Billing Zip / Postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>AMEX: first digit = 3, second digit = 4 or 7. Valid length: 15 digits.
VISA: first digit = 4. Valid length: 13 or 16 digits.
MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</description>
        <inlineHelpText>AMEX: first digit = 3, second digit = 4 or 7.  Valid length: 15 digits.

VISA: first digit = 4.  Valid length: 13 or 16 digits.

MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</inlineHelpText>
        <label>Card Number</label>
        <length>19</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <description>American Express cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</description>
        <inlineHelpText>AMEX cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</inlineHelpText>
        <label>Card Security Code</label>
        <length>5</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Card Detail</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <label>Card Security</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestctrlAddCardInformation.cls
@isTest

private class TestctrlAddCardInformation{

     @testSetup static void setup() {
        // Create common test accounts
       Account testAccount = new Account();
            testAccount.Name='Bobby Apples' ;
            testAccount.First_Name__c='Bobby';
            testAccount.Last_Name__c='Apples';
        testAccount.phone='123456782';
         
            insert testAccount;        
    }
    
   @isTest static void ctrlAddCardInformationTest() {
      
      Account acct = [SELECT Id FROM Account WHERE First_Name__c ='Bobby' LIMIT 1];
    
      Credit_Card_Detail__c ccd = new Credit_Card_Detail__c();
      ccd.Name = 'Test Credit';
      ccd.Account__c = acct.Id;
      ccd.Card_Type__c='Test1';
      ccd.Card_Number__c='42222';
      ccd.Card_Security__c='2222';
        ccd.Billing_Zip_Postal__c='89052';
      
      insert ccd;
   
       Opportunity opp = new Opportunity();
      opp.Name = 'Test Opp';
      opp.AccountId = acct.Id;
      opp.StageName = 'Qualification';
      opp.CloseDate = system.today();
       opp.RecordTypeID='012U0000000g5s4';
            insert opp;
        test.startTest();
       PageReference pageRef = Page.AddCardInformation;
  	pageRef.getParameters().put('id', String.valueOf(opp.Id));
  		Test.setCurrentPage(pageRef);      

      ApexPages.StandardController stdSR = new ApexPages.StandardController(opp);
     ctrlAddCardInformation Cardinfo=new ctrlAddCardInformation(stdSR);
       
	Cardinfo.informationcard();
       
       
       System.assertEquals('Test Credit-2222',Cardinfo.Selectcard, 'Please check !!! ');
        test.stopTest();
        
    }
       @isTest static void NoCardInformationTest() {
      
      Account acct = [SELECT Id FROM Account WHERE First_Name__c ='Bobby' LIMIT 1];
    
      Credit_Card_Detail__c ccd = new Credit_Card_Detail__c();
      ccd.Name = 'Test Credit';
      ccd.Account__c = acct.Id;
      ccd.Card_Type__c='Test1';
      ccd.Card_Number__c='';
      ccd.Card_Security__c='2222';
        ccd.Billing_Zip_Postal__c='89052';
      
      insert ccd;
   
       Opportunity opp = new Opportunity();
      opp.Name = 'Test Opp';
      opp.AccountId = acct.Id;
      opp.StageName = 'Qualification';
      opp.CloseDate = system.today();
       opp.RecordTypeID='012U0000000g5s4';
            insert opp;
        test.startTest();
       PageReference pageRef = Page.AddCardInformation;
  	pageRef.getParameters().put('id', String.valueOf(opp.Id));
  		Test.setCurrentPage(pageRef);      

      ApexPages.StandardController stdSR = new ApexPages.StandardController(opp);
     ctrlAddCardInformation Cardinfo=new ctrlAddCardInformation(stdSR);
       
	Cardinfo.informationcard();
       
       
       System.assertEquals('Test Credit',Cardinfo.Selectcard, 'Please check !!! ');
        test.stopTest();
        
    }
}