objects/Account.object
<CustomObject>
    <fields>
        <fullName>Reason_for_Follow_Up__c</fullName>
        <label>Reason for Follow Up</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sell Pension</fullName>
                </value>
                <value>
                    <fullName>Sell Living Trust ?</fullName>
                </value>
                <value>
                    <fullName>Sell Corporation ?</fullName>
                </value>
                <value>
                    <fullName>Sell LLC ?</fullName>
                </value>
                <value>
                    <fullName>Sell LP ?</fullName>
                </value>
                <value>
                    <fullName>Transfer Entities into Living Trust ?</fullName>
                </value>
                <value>
                    <fullName>Transfer LLC Units to Holding LLC ?</fullName>
                </value>
                <value>
                    <fullName>Client Needs Land Trust ?</fullName>
                </value>
                <value>
                    <fullName>Client Needs a Deed ?</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Bookkeeping</businessProcess>
        <description>Used for Bookkeeping Cases</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <businessProcess>Operation Help desk</businessProcess>
        <label>Email</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</description>
        <inlineHelpText>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anderson</fullName>
                    <default>true</default>
                    <label>Anderson</label>
                </value>
                <value>
                    <fullName>Client Formed</fullName>
                </value>
                <value>
                    <fullName>Shelf</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_for_Follow_Up__c</fullName>
        <label>Reason for Follow Up</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sell Pension</fullName>
                </value>
                <value>
                    <fullName>Sell Living Trust ?</fullName>
                </value>
                <value>
                    <fullName>Sell Corporation ?</fullName>
                </value>
                <value>
                    <fullName>Sell LLC ?</fullName>
                </value>
                <value>
                    <fullName>Sell LP ?</fullName>
                </value>
                <value>
                    <fullName>Transfer Entities into Living Trust ?</fullName>
                </value>
                <value>
                    <fullName>Transfer LLC Units to Holding LLC ?</fullName>
                </value>
                <value>
                    <fullName>Client Needs Land Trust ?</fullName>
                </value>
                <value>
                    <fullName>Client Needs a Deed ?</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/To_Do__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>To Do&apos;s</relationshipLabel>
        <relationshipName>To_Do_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>To Do</label>
    <nameField>
        <label>To Do</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Do&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trust__c.object
<CustomObject>
    <description>Object to hold Trust information.</description>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Trusts (Entity)</relationshipLabel>
        <relationshipName>Trusts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Filing State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <inlineHelpText>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anderson</fullName>
                </value>
                <value>
                    <fullName>Client Formed</fullName>
                </value>
                <value>
                    <fullName>Shelf</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trust</label>
    <nameField>
        <label>Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateEntityTaskTest.cls
@isTest(SeeAllData=true)
private class CreateEntityTaskTest {
    
    public static testmethod void testQuestionItemMethod()
    {
        test.startTest();
        Entities__c et = new Entities__c();
        et.RecordTypeId = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where Name = 'Limited Liability Company (LLC)' and SobjectType = 'Entities__c'].Id; 
        et.Name = 'abc';
        et.Organization_State__c = 'Wyoming';
        et.Origin__c = 'Anderson';
        et.Status__c = 'Sent To Processing';
        et.Reason_for_Follow_Up__c = 'Sell Pension';
        insert et;
        et.Name = 'abcd';
        update et;
        To_Do__c toDoItem = new To_Do__c();
        
        toDoItem.Name =  et.Reason_for_Follow_Up__c;
        toDoItem.Entity__c = et.id;
        toDoItem.Date__c = System.today();
        
        insert toDoItem;
        
        Trust__c tr = new Trust__c();
        tr.RecordTypeId = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where Name = 'Land Trust' and SobjectType = 'Trust__c'].Id; 
        tr.Name = 'abc';
        tr.Status__c = 'Sent To Processing';
        insert tr;
        test.stopTest();
        /*  UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
User thisUser = [select Id, AccountId from User where UserRoleId = :portalRole.Id Limit 1];  
// System.runAs ( thisUser ) {
Test.StartTest(); 
Integer cseLstSze = 10;
Id p = [select id from profile where name='Partner Community User'].id;
Campaign cmp = new Campaign();
cmp.Name = 'Steve';
insert cmp;        
Account testAccount = new Account();
testAccount.Name='Test Account' ;
testAccount.First_Name__c='Edward';
testAccount.Last_Name__c='Lee';
testAccount.Campaign__c = cmp.Id;
testAccount.OwnerId = thisUser.Id;
testAccount.Assigned_CAM__c = 'Sara Winter';
testAccount.Assigned_CSR__c = 'Ambria Tibbs';
testAccount.Bookkeeper__c = thisUser.Id;
testAccount.phone='123456782';
insert testAccount;              
Contact cont = new Contact ();
cont.FirstName = 'FirstName';
cont.LastName = 'LastName';
cont.Email='email@email.com';
cont.phone='12345678';
cont.AccountId=testAccount.Id;
insert cont;
Case cse = new Case();
cse.AccountId = testAccount.Id;
cse.ContactId = cont.Id;
cse.Subject = 'Platinum Bookkeeping Question';
cse.Description = 'Testing Descritpion';
cse.CreatedDate = system.now();
cse.Status = 'New';
cse.OwnerId = thisUser.Id;
insert cse;
String cN = cse.Case_Number__c;        
CaseComment cc = new CaseComment();
cc.CommentBody = 'Testing Comment';
cc.CreatedById = UserInfo.getUserId();
cc.ParentId = cse.Id;
insert cc;  
Integer Casetotal_size=[Select count() From Case where AccountId = :thisUser.AccountId];
ApexPages.StandardController controller = new ApexPages.StandardController(cse);
CaseController CseController = new CaseController(controller);
CseController.getItems();*/
        // }
    }
    
    
}