objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper_Reviewer__c</fullName>
        <label>Bookkeeper Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Ashley Cloutier</fullName>
                </value>
                <value>
                    <fullName>Blanca Lemus</fullName>
                </value>
                <value>
                    <fullName>Christina Chavez</fullName>
                </value>
                <value>
                    <fullName>Crystal Moyer</fullName>
                </value>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Lanzi Reel</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Rebecca Gallegos</fullName>
                </value>
                <value>
                    <fullName>Tracy Cooklin</fullName>
                </value>
                <value>
                    <fullName>Trisha Cullinane</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abraham Carrillo</fullName>
                </value>
                <value>
                    <fullName>Alishia Greene-Jenkins</fullName>
                </value>
                <value>
                    <fullName>Antoinette Reid</fullName>
                </value>
                <value>
                    <fullName>Ashley Cloutier</fullName>
                </value>
                <value>
                    <fullName>Austin Stephens</fullName>
                </value>
                <value>
                    <fullName>Becky Arnold</fullName>
                </value>
                <value>
                    <fullName>Blanca Lemus</fullName>
                </value>
                <value>
                    <fullName>Brenda Guzman</fullName>
                </value>
                <value>
                    <fullName>Brenda Navarrette</fullName>
                </value>
                <value>
                    <fullName>Christina Chavez</fullName>
                </value>
                <value>
                    <fullName>Cindy Mejorado</fullName>
                </value>
                <value>
                    <fullName>Crystal Moyer</fullName>
                </value>
                <value>
                    <fullName>Danny On</fullName>
                </value>
                <value>
                    <fullName>Dawn Popa</fullName>
                </value>
                <value>
                    <fullName>Imelda Hilario</fullName>
                </value>
                <value>
                    <fullName>Jacquie Wallace-Small</fullName>
                </value>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Jennifer Soikowski</fullName>
                </value>
                <value>
                    <fullName>Jessica Turner</fullName>
                </value>
                <value>
                    <fullName>Jonathan Salyer</fullName>
                </value>
                <value>
                    <fullName>Kayla Fleming</fullName>
                </value>
                <value>
                    <fullName>Keanu Rhodes</fullName>
                </value>
                <value>
                    <fullName>Kenneth Harrah</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Kimberly Smiley</fullName>
                </value>
                <value>
                    <fullName>Kingstone Mashingaidze</fullName>
                </value>
                <value>
                    <fullName>Lanzi Reel</fullName>
                </value>
                <value>
                    <fullName>Mandrell Hahn</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Melissa McBride</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Completing_Books_for_Tax_Year__c</fullName>
        <label>Completing Books for Tax Year</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Info_Sent_to_ABA_By__c</fullName>
        <formula>IF(INCLUDES( Case__r.Info_Sent_to_ABA_By__c , &quot;Access&quot;), &quot;Access&quot;, NULL)  + BR() + 
IF(INCLUDES( Case__r.Info_Sent_to_ABA_By__c , &quot;Box&quot;), &quot;Box&quot;, NULL)  + BR() + 
IF(INCLUDES( Case__r.Info_Sent_to_ABA_By__c , &quot;Mail&quot;), &quot;Mail&quot;, NULL)  + BR() + 
IF(INCLUDES( Case__r.Info_Sent_to_ABA_By__c , &quot;Other&quot;), &quot;Box&quot;, NULL)  + BR() + 
IF(INCLUDES( Case__r.Info_Sent_to_ABA_By__c , &quot;Email&quot;), &quot;Email&quot;, NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Info Sent to ABA By</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Entities__c</fullName>
        <formula>TEXT(Case__r.Number_of_Entities__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Entities</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Set_of_Books__c</fullName>
        <label>Set of Books</label>
        <referenceTo>Set_of_Books__c</referenceTo>
        <relationshipLabel>Entity Bookkeeping Records</relationshipLabel>
        <relationshipName>Bookkeeping_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Admin</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Info_Sent_to_ABA_By__c</fullName>
        <description>How the client gives us access to their documentation to do their books.</description>
        <inlineHelpText>How the client gives us access to their documentation to do their books.</inlineHelpText>
        <label>Info Sent to ABA By</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Box</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Entities__c</fullName>
        <inlineHelpText>Number of Quickbook files the client has us work on.</inlineHelpText>
        <label>Number of Entities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QuickBooks_Version__c</fullName>
        <label>QuickBooks Version</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QB Desktop</fullName>
                </value>
                <value>
                    <fullName>QBO</fullName>
                </value>
                <value>
                    <fullName>QB Enterprise</fullName>
                </value>
                <value>
                    <fullName>Remote In</fullName>
                </value>
                <value>
                    <fullName>Portable Copy</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Set_of_Books__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Admin</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeping_Reviewer__c</fullName>
        <label>Bookkeeping Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Reviewer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Entities__c</fullName>
        <label>Number of Entities</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Set of Books</label>
    <nameField>
        <label>Set of Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Set of Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Bookkeeping_Admin.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abdur Rehman</fullName>
    </customValue>
    <customValue>
        <fullName>Abraham Carrillo</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Hendershot</fullName>
    </customValue>
    <customValue>
        <fullName>Angela Berrow</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Langer</fullName>
    </customValue>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>awais khan</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Arnold</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Bobby Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Bruce Williams</fullName>
    </customValue>
    <customValue>
        <fullName>Carol Spagnoletta</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Conrad Gomez</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Dawson Phipps</fullName>
    </customValue>
    <customValue>
        <fullName>Doug Guard</fullName>
    </customValue>
    <customValue>
        <fullName>Hebert Romero</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Petrunyak</fullName>
    </customValue>
    <customValue>
        <fullName>Jerome Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Joel Evans</fullName>
    </customValue>
    <customValue>
        <fullName>John Doe</fullName>
    </customValue>
    <customValue>
        <fullName>Jonna States</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Fleming</fullName>
    </customValue>
    <customValue>
        <fullName>Kelly Van Middlesworth</fullName>
    </customValue>
    <customValue>
        <fullName>Kenneth Harrah</fullName>
    </customValue>
    <masterLabel>Bookkeeping Admin</masterLabel>
</GlobalValueSet>

globalValueSets/Bookkeeping_Reviewer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Kiera Dunphy</fullName>
    </customValue>
    <customValue>
        <fullName>Lanzi Reel</fullName>
    </customValue>
    <customValue>
        <fullName>Ryan On</fullName>
    </customValue>
    <customValue>
        <fullName>Trisha Cullinane</fullName>
    </customValue>
    <customValue>
        <fullName>Troy Butler</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Nancy Naraine</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Kevin Dennis</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Flemming</fullName>
    </customValue>
    <customValue>
        <fullName>Tesia Owen</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
        <isActive>false</isActive>
        <label>Bethany Castleberry</label>
    </customValue>
    <customValue>
        <fullName>Christine Zimmerman</fullName>
        <isActive>false</isActive>
        <label>Christine Zimmerman</label>
    </customValue>
    <customValue>
        <fullName>Rebecca Gallegos</fullName>
        <isActive>false</isActive>
        <label>Rebecca Gallegos</label>
    </customValue>
    <customValue>
        <fullName>Marie Pues</fullName>
        <isActive>false</isActive>
        <label>Marie Pues</label>
    </customValue>
    <customValue>
        <fullName>Maria Boone</fullName>
        <isActive>false</isActive>
        <label>Maria Boone</label>
    </customValue>
    <masterLabel>Bookkeeping Reviewer</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/BookkeepingctrlTest.cls
@istest
public class BookkeepingctrlTest {
   @testSetup
    public static void createData() {
       
        
        Account a = new Account();
        a.Name = 'Test Account';
        a.First_Name__c='Test';
        a.Last_Name__c='Account';
        insert a;
        
         Contact con = new Contact();
        con.FirstName='Test';
        con.LastName='Contact';
        con.AccountId=a.id;
        insert con;
        
         case c=new case();
        c.Subject='Test Subject';
        c.AccountId=a.id;
        c.ContactId=con.id;
        c.RecordTypeId='012U0000000g6UYIAY';
        c.Info_Sent_to_ABA_By__c='Access';
        c.Number_of_Entities__c='7';
        c.QuickBooks_Version__c='QBO';
        insert c;
        
           case c1=new case();
        c1.Subject='Second case';
       
        
        insert c1;
        
        Set_of_Books__c bookset = new Set_Of_Books__c();
        bookset.Client__c = a.id;
        bookset.Name = 'Test Bookset';
         bookset.Bookkeeper__c='Abraham Carrillo';
        bookset.Bookkeeping_Reviewer__c='Blanca Lemus';
        insert bookset;
        
        Bookkeeping__c bk = new Bookkeeping__c();
        bk.Name = 'Test BK Record';
        bk.Set_of_Books__c = bookset.id;
        bk.Bookkeeper__c='Abraham Carrillo';
        bk.Bookkeeper_Reviewer__c='Blanca Lemus';
        bk.Completing_Books_for_Tax_Year__c='2019';
        bk.Fiscal_Year_End__c='Dec';
        insert bk;
        
    }
     @isTest
    public static void bookkeeperChange() {
        Case c=[Select id from Case where Subject='Test Subject' Limit 1];
         Case c2=[Select id from Case where Subject='Second case' Limit 1];
        User u = [SELECT Id FROM User WHERE id ='0050B000006o1gqQAA' Limit 1];
        string Name='Test';
               List<Set_of_Books__c> SetofbooksList=new List<Set_of_Books__c>();
        List<Set_of_Books__c> SetofbooksList2=new List<Set_of_Books__c>();
        test.startTest();
        System.runAs(u) {
     
    SetofbooksList= BookkeepingCtrl.getSetofbooks(c.id,u.id);
            	BookkeepingCtrl.getbookkeepingRecords(c.id,u.id);
            	BookkeepingCtrl.getClientId(c.id);
            BookkeepingCtrl.getcontactId(c.id);
            	BookkeepingCtrl.findByNameSetofBooks(Name,c.id,u.id);
            BookkeepingCtrl.findByNameBookkeepingRecords(Name,c.id,u.id);
           System.assertEquals(1,SetofbooksList.size() , 'Please Check!');
            
           SetofbooksList2= BookkeepingCtrl.getSetofbooks(c2.id,u.id);
            	BookkeepingCtrl.getbookkeepingRecords(c2.id,u.id);
            	BookkeepingCtrl.getClientId(c2.id);
             BookkeepingCtrl.getcontactId(c2.id);
            	BookkeepingCtrl.findByNameSetofBooks(Name,c2.id,u.id);
            BookkeepingCtrl.findByNameBookkeepingRecords(Name,c2.id,u.id);
      
        }
        test.stopTest();
        
        
     
    }

    
}