objects/Account.object
<CustomObject>
    <fields>
        <fullName>Accounting_Coordinators__c</fullName>
        <label>Client Tax Coordinator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alex Price</fullName>
                </value>
                <value>
                    <fullName>Alicefaye Camper</fullName>
                </value>
                <value>
                    <fullName>Andrew Grigsby</fullName>
                </value>
                <value>
                    <fullName>Andy Romero</fullName>
                    <isActive>false</isActive>
                    <label>Andy Romero</label>
                </value>
                <value>
                    <fullName>Angelica Nance</fullName>
                    <isActive>false</isActive>
                    <label>Angelica Nance</label>
                </value>
                <value>
                    <fullName>Anthony Espada</fullName>
                </value>
                <value>
                    <fullName>Ashley Silafau-Sanitoa</fullName>
                    <isActive>false</isActive>
                    <label>Ashley Silafau-Sanitoa</label>
                </value>
                <value>
                    <fullName>Azia Brown</fullName>
                    <isActive>false</isActive>
                    <label>Azia Brown</label>
                </value>
                <value>
                    <fullName>Brina DeLeon</fullName>
                </value>
                <value>
                    <fullName>Candy Adauto</fullName>
                    <isActive>false</isActive>
                    <label>Candy Adauto</label>
                </value>
                <value>
                    <fullName>Carisma James</fullName>
                </value>
                <value>
                    <fullName>Carly McClean</fullName>
                    <isActive>false</isActive>
                    <label>Carly McClean</label>
                </value>
                <value>
                    <fullName>Chloe Freeman</fullName>
                </value>
                <value>
                    <fullName>Christos Zattas</fullName>
                </value>
                <value>
                    <fullName>Corbin Roache</fullName>
                </value>
                <value>
                    <fullName>Erica Kelly</fullName>
                    <isActive>false</isActive>
                    <label>Erica Kelly</label>
                </value>
                <value>
                    <fullName>Eric Harding</fullName>
                    <isActive>false</isActive>
                    <label>Eric Harding</label>
                </value>
                <value>
                    <fullName>Freddi Mitchell</fullName>
                </value>
                <value>
                    <fullName>Gatsby Darwin</fullName>
                    <isActive>false</isActive>
                    <label>Gatsby Darwin</label>
                </value>
                <value>
                    <fullName>Holly Hartman</fullName>
                </value>
                <value>
                    <fullName>Jazmine Gonzalez</fullName>
                    <isActive>false</isActive>
                    <label>Jazmine Gonzalez</label>
                </value>
                <value>
                    <fullName>Julianna Jones</fullName>
                    <isActive>false</isActive>
                    <label>Julianna Jones</label>
                </value>
                <value>
                    <fullName>Kaitlyn Scrivener</fullName>
                </value>
                <value>
                    <fullName>Kelly Andrews</fullName>
                </value>
                <value>
                    <fullName>Marissa Yadao</fullName>
                </value>
                <value>
                    <fullName>Megan Harris</fullName>
                </value>
                <value>
                    <fullName>Micah Wyllie</fullName>
                </value>
                <value>
                    <fullName>Michael Kemp</fullName>
                    <isActive>false</isActive>
                    <label>Michael Kemp</label>
                </value>
                <value>
                    <fullName>Olga Kochubey</fullName>
                    <isActive>false</isActive>
                    <label>Olga Kochubey</label>
                </value>
                <value>
                    <fullName>Paul Scarnechia</fullName>
                    <isActive>false</isActive>
                    <label>Paul Scarnechia</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <description>Cam Assigned to the account</description>
        <label>Assigned CAM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CAM</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <label>Assigned Client Success Coordinator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CSR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original source of the client.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <formula>TEXT(Account.Assigned_CAM__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned CAM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <formula>TEXT(Account.Assigned_CSR__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original Campaign associated with the Contact when converted from a Lead.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/CAM.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alexandria Lessard</fullName>
    </customValue>
    <customValue>
        <fullName>Mary Borden</fullName>
    </customValue>
    <customValue>
        <fullName>Matthew Smidowicz</fullName>
    </customValue>
    <customValue>
        <fullName>Team Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 6</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 7</fullName>
    </customValue>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Brown</fullName>
        <isActive>false</isActive>
        <label>Christina Brown</label>
    </customValue>
    <customValue>
        <fullName>Danielle Blair</fullName>
        <isActive>false</isActive>
        <label>Danielle Blair</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <customValue>
        <fullName>Joseph Sacco</fullName>
        <isActive>false</isActive>
        <label>Joseph Sacco</label>
    </customValue>
    <customValue>
        <fullName>Erica Terrell</fullName>
        <isActive>false</isActive>
        <label>Erica Terrell</label>
    </customValue>
    <customValue>
        <fullName>Savannah Wallace</fullName>
        <isActive>false</isActive>
        <label>Savannah Wallace</label>
    </customValue>
    <customValue>
        <fullName>Crystal Smerdel</fullName>
        <isActive>false</isActive>
        <label>Crystal Smerdel</label>
    </customValue>
    <description>Cams assigned</description>
    <masterLabel>CAM</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/CSR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aaron Bernhardt</fullName>
    </customValue>
    <customValue>
        <fullName>Adrienne Harper</fullName>
    </customValue>
    <customValue>
        <fullName>Alexa Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Alyssa Hoopii</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Zipprich</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Yadao</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Seguin</fullName>
    </customValue>
    <customValue>
        <fullName>Branden Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Brittany Rains</fullName>
    </customValue>
    <customValue>
        <fullName>Carly Coons</fullName>
    </customValue>
    <customValue>
        <fullName>Carrie J. Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Channell Palmer</fullName>
    </customValue>
    <customValue>
        <fullName>Chase Foster</fullName>
    </customValue>
    <customValue>
        <fullName>Christian DeField</fullName>
    </customValue>
    <customValue>
        <fullName>Claire Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Colette Grier</fullName>
    </customValue>
    <customValue>
        <fullName>Dana Heckathorn</fullName>
    </customValue>
    <customValue>
        <fullName>Deborah Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Domanick Page-Whitaker</fullName>
    </customValue>
    <customValue>
        <fullName>Duncan Bjerke</fullName>
    </customValue>
    <customValue>
        <fullName>Gabby Esteban</fullName>
    </customValue>
    <customValue>
        <fullName>Hayley Karlson</fullName>
    </customValue>
    <customValue>
        <fullName>Jade Comer</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Lundquist</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Nelson</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Seibert</fullName>
    </customValue>
    <customValue>
        <fullName>Jessica Thornton</fullName>
    </customValue>
    <customValue>
        <fullName>Kaila Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Katherine Baez</fullName>
    </customValue>
    <customValue>
        <fullName>Kim Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Ambria Tibbs</fullName>
        <isActive>false</isActive>
        <label>Ambria Tibbs</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <description>Assigned CSR</description>
    <masterLabel>CSR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/CustomLandingControllerTest.cls
@isTest(SeeAllData=false)
private class CustomLandingControllerTest {
    
    public static testmethod void testEntityFetchMethod()
    {
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, AccountId, ContactId from User where UserRoleId = :portalRole.Id Limit 1];  
        Id p = [select id from profile where name='Partner Community User'].id;
        Campaign cmp = new Campaign();
        cmp.Name = 'Steve';
        insert cmp;        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        testAccount.First_Name__c = 'Edward';
        testAccount.Last_Name__c = 'Lee';
        testAccount.Name='Test Account' ;
        testAccount.Campaign__c = cmp.Id;
        testAccount.OwnerId = thisUser.Id;
        //testAccount.Assigned_CAM__c = 'Sara Winter';
        testAccount.Assigned_CSR__c = 'Ambria Tibbs';
        testAccount.Accounting_Coordinators__c='Marissa Yadao';
        testAccount.Bookkeeper__c = thisUser.Id;
        testAccount.phone='123456782';
        try{
        insert testAccount;  
        }
        catch (DMLException e){
            System.debug('DML exception:::: ' + e);
        }
        Contact cont = new Contact ();
        cont.FirstName = 'FirstName';
        cont.LastName = 'LastName';
        cont.Email='email@email.com';
        cont.phone='12345678';
        cont.AccountId=testAccount.Id;
        insert cont;        
        User uzr = new User();
        uzr.FirstName='Steve';
        uzr.LastName='Mark';
        uzr.Email='stevemark@gmail.com';
        uzr.Username='stevemark@gmail.com';
        uzr.Alias='autocase';
        uzr.CommunityNickname='Partner_Panelsss';
        uzr.TimeZoneSidKey='GMT';
        uzr.LocaleSidKey='en_US';
        uzr.EmailEncodingKey='UTF-8';
        uzr.ProfileId=p;
        uzr.LanguageLocaleKey='en_US';
        uzr.ContactId = cont.Id;
        uzr.ProfileId = p;
        // uzr.AccountId = testAccount.Id;
        uzr.IsActive =true;
        insert uzr;
        System.runAs ( uzr ) {
            Test.StartTest();
            User u = [select Name from user where id=:testAccount.Bookkeeper__c];        
            ApexPages.StandardController controller = new ApexPages.StandardController(uzr);
            CustomLandingController customLandingController = new CustomLandingController(controller);
            customLandingController.getEntityRecord();
            Test.stopTest();
        }
    }
    public static testmethod void testGetLinkMethod()
    {
        Test.StartTest();
        User uzr = new User();
        ApexPages.StandardController controller = new ApexPages.StandardController(uzr);
        CustomLandingController customLandingController = new CustomLandingController(controller);
        customLandingController.GetLink();
        Test.stopTest();
    }
    public static testmethod void testGroupFetchMethod()
    {
        Test.StartTest();
        GroupMember gm = new GroupMember(Id = '011U0000003hNo7IAE');
        ApexPages.StandardController controller = new ApexPages.StandardController(gm);
        CustomLandingController customLandingController = new CustomLandingController(controller);
        customLandingController.getClientGroup();
        Test.stopTest();
    }
    
    public static testmethod void testUpdateUserMethod()
    {
        Id p = [select id from profile where name='Partner Community User'].id;
        Test.StartTest();
        User uzr = new User();
        uzr.FirstName='Steve';
        uzr.LastName='Mark';
        uzr.Email='stevemark@gmail.com';
        uzr.Username='stevemark@gmail.com';
        uzr.Alias='autocase';
        uzr.CommunityNickname='Partner_Panelsss';
        uzr.TimeZoneSidKey='GMT';
        uzr.LocaleSidKey='en_US';
        uzr.EmailEncodingKey='UTF-8';
        uzr.ProfileId=p;
        uzr.LanguageLocaleKey='en_US';
        uzr.IsActive =true;        
        try {
            insert uzr;
        } catch (DMLException e){
            System.debug('DML exception:::: ' + e);
        }
        PageReference pageRef = Page.MyEntities;
        Test.setCurrentPage(pageRef);
        User conv=new User();
        ApexPages.StandardController controller = new ApexPages.StandardController(conv);
        CustomLandingController customLandingController = new CustomLandingController(controller);
        customLandingController.updateUser();
        Test.stopTest();
        
    }
    
    public static testmethod void testUpdateAccountMethod()
    {
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, AccountId, ContactId from User where UserRoleId = :portalRole.Id Limit 1];  
        Id p = [select id from profile where name='Partner Community User'].id;
        Test.StartTest();
        Campaign cmp = new Campaign();
        cmp.Name = 'Steve';
        insert cmp; 
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        testAccount.First_Name__c = 'Edward';
        testAccount.Last_Name__c = 'Lee';
        testAccount.Name='Test Account' ;
        testAccount.Campaign__c = cmp.Id;
        testAccount.OwnerId = thisUser.Id;
        testAccount.Assigned_CAM__c = 'Sara Winter';
        testAccount.Assigned_CSR__c = 'Ambria Tibbs';
        testAccount.Bookkeeper__c = thisUser.Id;
        testAccount.phone='123456782';
        
        try {
            insert testAccount;
        } catch (DMLException e){
            System.debug('DML exception:::: ' + e);
        }
        /*Account a =[select Id,First_Name__c from Account where Id =: testAccount.Id ];          
        a.First_Name__c = 'Testing';
        try {
            update a;
        } catch (DMLException e){
            System.debug('DML exception:::: ' + e);
        }*/
        PageReference pageRef = Page.MyEntities;
        Test.setCurrentPage(pageRef);
        Account conv = new Account();
        ApexPages.StandardController controller = new ApexPages.StandardController(conv);
        CustomLandingController customLandingController = new CustomLandingController(controller);
        customLandingController.updateAccount();
        Test.stopTest();
        
    }
    
    public static testmethod void testCountentitiesMethod()
    { 
        Test.StartTest();
        User uzr=new User(); 
        ApexPages.StandardController controller = new ApexPages.StandardController(uzr);
        CustomLandingController customLandingController = new CustomLandingController(controller);
        customLandingController.getCountentities();
        Test.stopTest();
    }
    
    public static testmethod void testforwardToCustomAuthPageMethod()
    {
        Test.StartTest();
        User uzr=new User(); 
        ApexPages.StandardController controller = new ApexPages.StandardController(uzr);
        CustomLandingController customLandingController = new CustomLandingController(controller);
        customLandingController.forwardToCustomAuthPage();
        Test.stopTest();       
    }
}