objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auditor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The person responsible for completing the most recent audit.</inlineHelpText>
        <label>Auditor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platinum_Sale_Closed_Won__c</fullName>
        <description>Counts the number of Closed Won Platinum Sales.</description>
        <label>Platinum Sale - Closed Won</label>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Platinum Subscription</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Does_Not_Need_Blueprint__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Does Not Need Blueprint</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Transaction__c</fullName>
        <description>Date of first approved transaction.</description>
        <inlineHelpText>Date of first approved transaction.</inlineHelpText>
        <label>First Transaction</label>
        <summarizedField>ChargentSFA__Transaction__c.ChargentSFA__Gateway_Date__c</summarizedField>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Response_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Type__c</field>
            <operation>equals</operation>
            <value>Charge</value>
        </summaryFilterItems>
        <summaryForeignKey>ChargentSFA__Transaction__c.ChargentSFA__Opportunity__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/QCassignment_Scheduled.cls
public class QCassignment_Scheduled implements Schedulable{
    public void execute(SchedulableContext sc)
    {
        QCassignment();
    }
    
    public void QCassignment(){
        
        List<User> QC = new List<User>([SELECT Id FROM User WHERE Title = 'Quality Control Specialist' 
                                        AND IsActive = TRUE]);
        Integer t = QC.size();
        
        List<Account> accounts = new List<Account>([SELECT Id, Auditor__c FROM Account WHERE Id NOT IN 
                                                    (SELECT AccountId FROM Opportunity WHERE 
                                                     RecordType.Name = 'Entity Formation' AND 
                                                     (Amount >=1500 OR Does_Not_Need_Blueprint__c = FALSE) 
                                                     AND First_Transaction__c >= LAST_N_MONTHS:4) 
                                                    AND Platinum_Sale_Closed_Won__c > 0 AND LastActivityDate >= LAST_N_MONTHS:18 
                                                    AND Auditor__c = NULL
                                                    LIMIT 12
                                                   ]);
        
        if(!accounts.isEmpty() && t > 0) {
            for(Integer i = 0; i < t; i++){
                for(Account acc : accounts){
                    acc.Auditor__c = QC[i].Id;              
                }
                
                update accounts;  
            }
            
        }
        
    }
}