objects/Account.object
<CustomObject>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platinum_Wordpress_Id__c</fullName>
        <label>Platinum Wordpress Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PlatinumSale.cls
public class PlatinumSale {
    
    @AuraEnabled @future(callout=true)
    public static void prepareCallout(Id accountId, Id opportunityId) {

        Account a = [SELECT Id, First_Name__c, Last_Name__c, E_Mail__c FROM Account WHERE Id = :accountId];
        contact c = getPrimaryOrOldestContact(accountId);
        
        if(c.Platinum_Wordpress_Id__c == null) {
        
        	String username = a.E_mail__c;
        	String email = a.E_mail__c;
            String firstName = a.First_Name__c;
            String lastName = a.Last_Name__c;
        	String password;
        	String accId = accountId;
        	String oppId = opportunityId;
        	String conId = c.Id;
        
       	 if(!Test.isRunningTest()) {
            try{ 
        		createPlatinumUserCallout.makePostCallout(username, email, password, accId, oppId, conId, firstName, lastName);
            } catch (Exception e) {
            debugInfo.createDebugLog(e);
            }
         }
       }
    }
    
    private static Contact getPrimaryOrOldestContact(Id accountId) {

        List<Contact> conList = new List<Contact>();
        
        for (Contact con : [SELECT Id, Account_Roles__c, Platinum_Wordpress_Id__c FROM Contact WHERE AccountId = :accountId ORDER BY CreatedDate ASC]) {
            
            if (con.Account_Roles__c == 'Primary Contact') {
                conList.add(con);
            } 
            
            if (conList.size() == 0) {
                conList.add(con);
            }
         
        }
        
        return conList[0];

    }

}