objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <description>Cam Assigned to the account</description>
        <label>Assigned CAM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CAM</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <label>Assigned Client Success Coordinator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CSR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original source of the client.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <formula>TEXT(Account.Assigned_CAM__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned CAM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <formula>TEXT(Account.Assigned_CSR__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original Campaign associated with the Contact when converted from a Lead.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Article_category_type__c</fullName>
        <label>Article category type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Forms</fullName>
                </value>
                <value>
                    <fullName>Videos</fullName>
                </value>
                <value>
                    <fullName>Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Knowledge_Video_Link__c</fullName>
        <inlineHelpText>You can upload Knowledge article link, video link, box video link and google drive link</inlineHelpText>
        <label>Knowledge Link (Video/Document/Form)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Knowledge_video_category__c</fullName>
        <label>Knowledge video category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Article_category_type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Courses</fullName>
                </value>
                <value>
                    <fullName>FAQs</fullName>
                </value>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Stock Trading</fullName>
                </value>
                <value>
                    <fullName>Tax Strategies</fullName>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                </value>
                <value>
                    <fullName>Entrepreneurship</fullName>
                </value>
                <value>
                    <fullName>Past Webinars</fullName>
                </value>
                <value>
                    <fullName>Tax Tuesday</fullName>
                </value>
                <value>
                    <fullName>Podcasts</fullName>
                </value>
                <value>
                    <fullName>Espanol</fullName>
                </value>
                <value>
                    <fullName>Coffee with Carl</fullName>
                </value>
                <value>
                    <fullName>Toni Talks</fullName>
                </value>
                <value>
                    <fullName>Tax Tuesday Q &amp; A</fullName>
                    <isActive>false</isActive>
                    <label>Tax Tuesday Q &amp; A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permissions__c</fullName>
        <label>Permissions</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

globalValueSets/CAM.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alexandria Lessard</fullName>
    </customValue>
    <customValue>
        <fullName>Mary Borden</fullName>
    </customValue>
    <customValue>
        <fullName>Matthew Smidowicz</fullName>
    </customValue>
    <customValue>
        <fullName>Team Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 6</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 7</fullName>
    </customValue>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Brown</fullName>
        <isActive>false</isActive>
        <label>Christina Brown</label>
    </customValue>
    <customValue>
        <fullName>Danielle Blair</fullName>
        <isActive>false</isActive>
        <label>Danielle Blair</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <customValue>
        <fullName>Joseph Sacco</fullName>
        <isActive>false</isActive>
        <label>Joseph Sacco</label>
    </customValue>
    <customValue>
        <fullName>Erica Terrell</fullName>
        <isActive>false</isActive>
        <label>Erica Terrell</label>
    </customValue>
    <customValue>
        <fullName>Savannah Wallace</fullName>
        <isActive>false</isActive>
        <label>Savannah Wallace</label>
    </customValue>
    <customValue>
        <fullName>Crystal Smerdel</fullName>
        <isActive>false</isActive>
        <label>Crystal Smerdel</label>
    </customValue>
    <description>Cams assigned</description>
    <masterLabel>CAM</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/CSR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aaron Bernhardt</fullName>
    </customValue>
    <customValue>
        <fullName>Adrienne Harper</fullName>
    </customValue>
    <customValue>
        <fullName>Alexa Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Alyssa Hoopii</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Zipprich</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Yadao</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Seguin</fullName>
    </customValue>
    <customValue>
        <fullName>Branden Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Brittany Rains</fullName>
    </customValue>
    <customValue>
        <fullName>Carly Coons</fullName>
    </customValue>
    <customValue>
        <fullName>Carrie J. Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Channell Palmer</fullName>
    </customValue>
    <customValue>
        <fullName>Chase Foster</fullName>
    </customValue>
    <customValue>
        <fullName>Christian DeField</fullName>
    </customValue>
    <customValue>
        <fullName>Claire Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Colette Grier</fullName>
    </customValue>
    <customValue>
        <fullName>Dana Heckathorn</fullName>
    </customValue>
    <customValue>
        <fullName>Deborah Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Domanick Page-Whitaker</fullName>
    </customValue>
    <customValue>
        <fullName>Duncan Bjerke</fullName>
    </customValue>
    <customValue>
        <fullName>Gabby Esteban</fullName>
    </customValue>
    <customValue>
        <fullName>Hayley Karlson</fullName>
    </customValue>
    <customValue>
        <fullName>Jade Comer</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Lundquist</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Nelson</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Seibert</fullName>
    </customValue>
    <customValue>
        <fullName>Jessica Thornton</fullName>
    </customValue>
    <customValue>
        <fullName>Kaila Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Katherine Baez</fullName>
    </customValue>
    <customValue>
        <fullName>Kim Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Ambria Tibbs</fullName>
        <isActive>false</isActive>
        <label>Ambria Tibbs</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <description>Assigned CSR</description>
    <masterLabel>CSR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/KnowledgeCustomSearchControllerTest.cls
@isTest(SeeAllData=true)
public class KnowledgeCustomSearchControllerTest {
    /**
* This method is used to get code coverage of  doSearch, getUserKeywords, getArticleDetails and sendmail method.
* 
* @author prateeks
* @date Dec 26, 2018
*/
    public static TestMethod void unitTest(){
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, AccountId, ContactId from User where UserRoleId = :portalRole.Id Limit 1];  
        Id p = [select id from profile where name='Partner Community User'].id;
        Campaign cmp = new Campaign();
        cmp.Name = 'Steve';
        insert cmp;        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        testAccount.First_Name__c = 'Edward';
        testAccount.Last_Name__c = 'Lee';
        testAccount.Name='Test Account' ;
        testAccount.Campaign__c = cmp.Id;
        testAccount.OwnerId = thisUser.Id;
        testAccount.Assigned_CAM__c = 'Sara Winter';
        testAccount.Assigned_CSR__c = 'Ambria Tibbs';
        testAccount.Bookkeeper__c = thisUser.Id;
        testAccount.phone='123456782';
        insert testAccount;              
        Contact cont = new Contact ();
        cont.FirstName = 'FirstName';
        cont.LastName = 'LastName';
        cont.Email='email@email.com';
        cont.phone='12345678';
        cont.AccountId=testAccount.Id;
        cont.Account_Roles__c = 'Primary Contact';
        insert cont;        
        User uzr = new User();
        uzr.FirstName='Steve';
        uzr.LastName='Mark';
        uzr.Email='stevemark@gmail.com';
        uzr.Username='stevemark@gmail.com';
        uzr.Alias='autocase';
        uzr.CommunityNickname='Partner_Panelsss';
        uzr.TimeZoneSidKey='GMT';
        uzr.LocaleSidKey='en_US';
        uzr.EmailEncodingKey='UTF-8';
        uzr.ProfileId=p;
        uzr.LanguageLocaleKey='en_US';
        uzr.ContactId = cont.Id;
        uzr.ProfileId = p;
        // uzr.AccountId = testAccount.Id;
        uzr.IsActive =true;
        insert uzr;
        Knowledge__kav objknowledge = new Knowledge__kav ();
        objknowledge.UrlName = 'Testing';
        objknowledge.Article_category_type__c = 'Videos';
        objknowledge.Permissions__c = 'Both';
        objknowledge.Title = 'Testing';
        objknowledge.Summary = 'Testing';
        objknowledge.Knowledge_video_category__c = 'Courses';
        objknowledge.Knowledge_Video_Link__c = 'Testing';
        insert objknowledge;
     /*   knowledge__kav obj1 = [SELECT Id,Title,KnowledgeArticleId FROM knowledge__kav WHERE id =: objknowledge.Id];
        KbManagement.PublishingService.publishArticle(obj1.KnowledgeArticleId, true);*/
        Test.StartTest();
        system.runAs(uzr){
            ApexPages.StandardController controller = new ApexPages.StandardController(uzr);
            KnowledgeCustomSearchController CustomSearchController = new KnowledgeCustomSearchController(controller);
            CustomSearchController.searchArticle = 'test';
            CustomSearchController.doSearch(); 
            KnowledgeCustomSearchController.getUserKeywords();   
            //CustomSearchController.getArticleDetails(objknowledge.Id);   
            String myPageVal = '1';
            //String searchArticle = 'Test';
           /*  KnowledgeCustom1SearchController CustomSearch1Controller = new KnowledgeCustom1SearchController();
             CustomSearch1Controller.doSearch();  */
            
            
         CustomSearchController.getnxt();
         CustomSearchController.getprev();
         CustomSearchController.LastPage();
         CustomSearchController.nextRow();
        
         CustomSearchController.previousRow(); 
         CustomSearchController.FirstPage();    
         CustomSearchController.searchArt();    
             
        }
        KnowledgeCustomSearchController.sendMail(objknowledge.Id,cont.Id);
       
        Test.stopTest();
    } 
    
   public static TestMethod void PaginationArticleController(){
       UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, AccountId, ContactId from User where UserRoleId = :portalRole.Id Limit 1];  
        Id p = [select id from profile where name='Partner Community User'].id;
        Campaign cmp = new Campaign();
        cmp.Name = 'Steve';
        insert cmp;        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        testAccount.First_Name__c = 'Edward';
        testAccount.Last_Name__c = 'Lee';
        testAccount.Name='Test Account' ;
        testAccount.Campaign__c = cmp.Id;
        testAccount.OwnerId = thisUser.Id;
        testAccount.Assigned_CAM__c = 'Sara Winter';
        testAccount.Assigned_CSR__c = 'Ambria Tibbs';
        testAccount.Bookkeeper__c = thisUser.Id;
        testAccount.phone='123456782';
        insert testAccount;              
        Contact cont = new Contact ();
        cont.FirstName = 'FirstName';
        cont.LastName = 'LastName';
        cont.Email='email@email.com';
        cont.phone='12345678';
        cont.AccountId=testAccount.Id;
        cont.Account_Roles__c = 'Primary Contact';
        insert cont;        
       
       // Second Contact Insert here
        Contact cont1 = new Contact();
        cont1.FirstName = 'FirstName1';
        cont1.LastName = 'LastName1';
        cont1.Email='email1@email.com';
        cont1.phone='123456781';
        cont1.AccountId=testAccount.Id;
        cont1.Account_Roles__c = 'Primary Contact';
        insert cont1; 
       // Second Contact Insert here
        User uzr = new User();
        uzr.FirstName='Steve';
        uzr.LastName='Mark';
        uzr.Email='stevemark@gmail.com';
        uzr.Username='stevemark@gmail.com';
        uzr.Alias='autocase';
        uzr.CommunityNickname='Partner_Panelsss';
        uzr.TimeZoneSidKey='GMT';
        uzr.LocaleSidKey='en_US';
        uzr.EmailEncodingKey='UTF-8';
        uzr.ProfileId=p;
        uzr.LanguageLocaleKey='en_US';
        uzr.ContactId = cont.Id;
        uzr.ProfileId = p;
        // uzr.AccountId = testAccount.Id;
        uzr.IsActive =true;
        insert uzr;
        Knowledge__kav objknowledge = new Knowledge__kav ();
        objknowledge.UrlName = 'Testing';
        objknowledge.Article_category_type__c = 'Videos';
        objknowledge.Permissions__c = 'Both';
        objknowledge.Title = 'Testing';
        objknowledge.Summary = 'Testing';
        objknowledge.Knowledge_video_category__c = 'Courses';
        objknowledge.Knowledge_Video_Link__c = 'Testing';
        insert objknowledge;
     /*   knowledge__kav obj1 = [SELECT Id,Title,KnowledgeArticleId FROM knowledge__kav WHERE id =: objknowledge.Id];
        KbManagement.PublishingService.publishArticle(obj1.KnowledgeArticleId, true);*/
        Test.StartTest();
        system.runAs(uzr){
            ApexPages.StandardController controller = new ApexPages.StandardController(uzr);
            PaginationArticleController CustomSearchController = new PaginationArticleController(controller);
            CustomSearchController.searchArticle = 'test';
            CustomSearchController.searchArticles(); 
           PaginationArticleController.getUserKeywords();   
         //  CustomSearchController.getArticleDetails(objknowledge.Id);    
            String myPageVal = '1';
            //String searchArticle = 'Test';
           /*  KnowledgeCustom1SearchController CustomSearch1Controller = new KnowledgeCustom1SearchController();
             CustomSearch1Controller.doSearch();  */
            
            
         CustomSearchController.getnxt();
        CustomSearchController.getprev();
         CustomSearchController.LastPage();
         CustomSearchController.next();
        
         CustomSearchController.previous(); 
         CustomSearchController.FirstPage();    
         CustomSearchController.searchArt();    
             
        }
        PaginationArticleController.sendMail(objknowledge.Id,testAccount.Id); 
       
        Test.stopTest(); 
      
    }
    
    
    
    public static TestMethod void KeywordController(){
       UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, AccountId, ContactId from User where UserRoleId = :portalRole.Id Limit 1];  
        Id p = [select id from profile where name='Partner Community User'].id;
        Campaign cmp = new Campaign();
        cmp.Name = 'Steve';
        insert cmp;        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        testAccount.First_Name__c = 'Edward';
        testAccount.Last_Name__c = 'Lee';
        testAccount.Name='Test Account' ;
        testAccount.Campaign__c = cmp.Id;
        testAccount.OwnerId = thisUser.Id;
        testAccount.Assigned_CAM__c = 'Sara Winter';
        testAccount.Assigned_CSR__c = 'Ambria Tibbs';
        testAccount.Bookkeeper__c = thisUser.Id;
        testAccount.phone='123456782';
        insert testAccount;              
        Contact cont = new Contact ();
        cont.FirstName = 'FirstName';
        cont.LastName = 'LastName';
        cont.Email='email@email.com';
        cont.phone='12345678';
        cont.AccountId=testAccount.Id;
        cont.Account_Roles__c = 'Primary Contact';
        insert cont;        
       
       // Second Contact Insert here
        Contact cont1 = new Contact();
        cont1.FirstName = 'FirstName1';
        cont1.LastName = 'LastName1';
        cont1.Email='email1@email.com';
        cont1.phone='123456781';
        cont1.AccountId=testAccount.Id;
        cont1.Account_Roles__c = 'Primary Contact';
        insert cont1; 
       // Second Contact Insert here
        User uzr = new User();
        uzr.FirstName='Steve';
        uzr.LastName='Mark';
        uzr.Email='stevemark@gmail.com';
        uzr.Username='stevemark@gmail.com';
        uzr.Alias='autocase';
        uzr.CommunityNickname='Partner_Panelsss';
        uzr.TimeZoneSidKey='GMT';
        uzr.LocaleSidKey='en_US';
        uzr.EmailEncodingKey='UTF-8';
        uzr.ProfileId=p;
        uzr.LanguageLocaleKey='en_US';
        uzr.ContactId = cont.Id;
        uzr.ProfileId = p;
        // uzr.AccountId = testAccount.Id;
        uzr.IsActive =true;
        insert uzr;
        Knowledge__kav objknowledge = new Knowledge__kav ();
        objknowledge.UrlName = 'Testing';
        objknowledge.Article_category_type__c = 'Videos';
        objknowledge.Permissions__c = 'Both';
        objknowledge.Title = 'Testing';
        objknowledge.Summary = 'Testing';
        objknowledge.Knowledge_video_category__c = 'Courses';
        objknowledge.Knowledge_Video_Link__c = 'Testing';
        insert objknowledge;
     /*   knowledge__kav obj1 = [SELECT Id,Title,KnowledgeArticleId FROM knowledge__kav WHERE id =: objknowledge.Id];
        KbManagement.PublishingService.publishArticle(obj1.KnowledgeArticleId, true);*/
        Test.StartTest();
        
            ApexPages.StandardController controller = new ApexPages.StandardController(uzr);
            KeywordSearchController CustomSearchController = new KeywordSearchController();
            CustomSearchController.getPrevRequired();
            CustomSearchController.getNextRequired();
            CustomSearchController.getCurrentPageNumber();
            CustomSearchController.next();
            CustomSearchController.previous(); 
             
      
       
       
        Test.stopTest(); 
      
    }
    
    
   
}