objects/Account.object
<CustomObject>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Primary_Contact__r.Email</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platinum_Wordpress_Id__c</fullName>
        <label>Platinum Wordpress Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <description>Used with LearnDash and the Platinum website to provide course access.</description>
        <inlineHelpText>Used with LearnDash and the Platinum website to provide course access.</inlineHelpText>
        <label>Service Item List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Digital_Course__mdt.object
<CustomObject>
    <fields>
        <fullName>ASID__c</fullName>
        <label>ASID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Digital Course</label>
    <pluralLabel>Digital Courses</pluralLabel>
</CustomObject>

objects/Infinity_Subscription_Product__mdt.object
<CustomObject>
    <fields>
        <fullName>ASID__c</fullName>
        <label>ASID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Infinity_Membership__c</fullName>
        <label>Infinity Membership</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Infinity Subscription Product</label>
    <pluralLabel>Infinity Subscription Products</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_First_Name__c</fullName>
        <description>Used in Facebook Purchase Events - Integration with Zapier. Please do not delete.</description>
        <formula>Account.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Last_Name__c</fullName>
        <description>Used in Facebook Purchase Events - Integration with Zapier. Please do not delete.</description>
        <formula>Account.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Used in Facebook Purchase Events - Integration with Zapier. Please do not delete.</description>
        <formula>Account.E_Mail__c</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <label>Service Item List</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ASID__c</fullName>
        <formula>PricebookEntry.Product2.ASID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Welcome_Call__c</fullName>
        <formula>PricebookEntry.Product2.Welcome_Call__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Welcome Call</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ASID__c</fullName>
        <description>A unique identifier for each service item.</description>
        <displayFormat>A{00000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Anderson Service ID</inlineHelpText>
        <label>ASID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Service_Fulfillment_Weight__c</fullName>
        <inlineHelpText>Measurement of fulfillment difficulty</inlineHelpText>
        <label>Service Fulfillment Weight</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Anderson Services</fullName>
                </value>
                <value>
                    <fullName>Annual List</fullName>
                </value>
                <value>
                    <fullName>BK Consult</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping - Misc</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Tax Form</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Virtual</fullName>
                </value>
                <value>
                    <fullName>Certified Copy</fullName>
                </value>
                <value>
                    <fullName>Charitable Registration</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Corp Formation</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Deed</fullName>
                </value>
                <value>
                    <fullName>Dissolution</fullName>
                </value>
                <value>
                    <fullName>Doc Drafting</fullName>
                </value>
                <value>
                    <fullName>Estate</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Foreign Filing</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                </value>
                <value>
                    <fullName>Informational Only</fullName>
                </value>
                <value>
                    <fullName>IRS Form</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>LLC Formation</fullName>
                </value>
                <value>
                    <fullName>LP Formation</fullName>
                </value>
                <value>
                    <fullName>Meeting Minutes</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Formation</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>Pensions</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Welcome_Call__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Welcome Call</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WordPressUserCreationUtilityTest.cls
@isTest
public class WordPressUserCreationUtilityTest {
    @testSetup static void createTestData() {
        List<opportunity> oppList=new List<Opportunity>();
        List<OpportunityLineItem> opLineitemlist=new List<OpportunityLineItem>();
        Id pricebookId = Test.getStandardPricebookId();
        Account a = new Account();
        a.First_Name__c = 'Bob';
        a.Last_Name__c = 'Apple Test';
        a.Name = 'Test1234';
        a.E_Mail__c = 'bobappletest123@gmail.com';
        insert a;
        
        Contact c = new Contact();
        c.AccountId = a.id;
        c.FirstName = 'Bob';
        c.LastName = 'Apple Test';
        c.Email = 'bobappletest123@gmail.com';
        c.Account_Roles__c = 'Primary Contact';
        c.Service_Item_List__c='A09275';
        insert c;
        Opportunity opp=new Opportunity();
        opp.Name='Test Sale 1';
        opp.AccountId=a.id;
        
        opp.RecordTypeId='012U0000000DhZQIA0';
        opp.StageName='Qualification';
        opp.CloseDate = Date.Today();
        oppList.add(opp);
        
        Opportunity opp2=new Opportunity();
        opp2.Name='Test Sale 2';
        opp2.AccountId=a.id;
        opp2.RecordTypeId='012U0000000DhZzIAK';
        opp2.StageName='Closed Won';
        opp2.CloseDate = Date.Today();
        oppList.add(opp2);
        
        Opportunity opp3=new Opportunity();
        opp3.Name='Test Sale 3';
        opp3.AccountId=a.id;
        opp3.RecordTypeId='012U0000000DFSx';
        opp3.StageName='Closed Won';
        opp3.CloseDate = Date.Today();
        oppList.add(opp3);
        
        Opportunity o = new Opportunity();
        o.AccountId = a.Id;
        o.Name = 'Platinum Subscription';
        o.CloseDate = system.today();
        o.StageName = 'Closed Won';
        o.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Platinum Subscription').getRecordTypeId();
        oppList.add(o);
        
        insert oppList;
        
        List<Product2> products=new List<Product2>();
        Product2 prod = new Product2(
            Name = 'Tax Toolbox',
            ProductCode = 'Pro-X',
            isActive = true,
            welcome_call__c=true,
            Type__c ='Tax',
            Service_Fulfillment_Weight__c='1'
            
        );
        products.add(prod);
        Product2 prod1 = new Product2(
            Name = 'Anderson Funding Community',
            ProductCode = 'Pro-X',
            isActive = true,
            welcome_call__c=true,
            Type__c ='Law',
            Service_Fulfillment_Weight__c='1'
            
            
        );
        products.add(prod1);
        
        insert products;
        List<PricebookEntry> pbList=new List<PricebookEntry>();
        PricebookEntry pbEntry1 = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = products[0].Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        pbList.add(pbEntry1);  
        PricebookEntry pbEntry2 = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = products[1].Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        pbList.add(pbEntry2);  
        
        insert pbList;
        OpportunityLineItem oli1 = new OpportunityLineItem(
            OpportunityId = oppList[0].Id,
            
            Quantity = 5,
            PricebookEntryId = pbList[0].Id,
            TotalPrice =  pbList[0].UnitPrice
        );
        opLineitemlist.add(oli1);
        
        OpportunityLineItem oli2 = new OpportunityLineItem(
            OpportunityId = oppList[1].Id,
            Quantity = 5,
            PricebookEntryId =pbList[1].Id,
            TotalPrice =  pbList[1].UnitPrice
        );
        insert opLineitemlist; 
        
        
    }
    @isTest
    public static void testWordpressUserCreate(){
     //  String response = '{"id":"15555",  "username" : "test",   "email" : "test","password" : "test", "first_name" : "test", "last_name" : "test", "roles" : "services;bbp"}';
      PlatinumUser.newUser brandNewUser = new PlatinumUser.newUser();
        Opportunity opp = [select id,service_item_list__c,Email__c,AccountId,Account_First_Name__c,Account_Last_Name__c from opportunity limit 1];
        Contact con = [select id, service_item_list__c,Platinum_Wordpress_Id__c from contact limit 1];
        List<Digital_Course__mdt> digitalList = [select id, ASID__c from Digital_Course__mdt limit 50000];
        List<Infinity_Subscription_Product__mdt> infinityList = [select id, ASID__c,Infinity_Membership__c from Infinity_Subscription_Product__mdt limit 50000];
     WordpressUserCalloutRequestWrapp usercalloutwrapinst = new WordpressUserCalloutRequestWrapp(opp,'Platinum',con.Id);
       String bodydata = JSON.serialize(usercalloutwrapinst);
        test.startTest();
        WordpressUserCreationUtility.createServiceUser(opp);
        WordpressUserCreationUtility.createServiceUser(opp, infinityList, digitalList);
         WordpressUserCreationUtility.performCallout(bodydata, con.Platinum_Wordpress_Id__c, con.Id);
        WordpressUserCreationUtility.createPlatinumUser(opp);
        WordpressUserCreationUtility.updateContact(brandNewUser, con.Id);
        WordpressUserCreationUtility.updateContactServiceItemList(opp.Service_Item_List__c, opp.AccountId, con.Id, infinityList, digitalList, con.Service_Item_List__c);
        test.stopTest();
    }
}