objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <description>Cam Assigned to the account</description>
        <label>Assigned CAM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CAM</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <label>Assigned Client Success Coordinator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CSR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original source of the client.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ClientReferralCampaign</relationshipLabel>
        <relationshipName>ClientReferralCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Admin</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <businessProcess>Operation Help desk</businessProcess>
        <label>Email</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <formula>TEXT(Account.Assigned_CAM__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned CAM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <formula>TEXT(Account.Assigned_CSR__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original Campaign associated with the Contact when converted from a Lead.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Detail</relationshipLabel>
        <relationshipName>Credit_Card_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>AMEX: first digit = 3, second digit = 4 or 7. Valid length: 15 digits.
VISA: first digit = 4. Valid length: 13 or 16 digits.
MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</description>
        <inlineHelpText>AMEX: first digit = 3, second digit = 4 or 7.  Valid length: 15 digits.

VISA: first digit = 4.  Valid length: 13 or 16 digits.

MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</inlineHelpText>
        <label>Card Number</label>
        <length>19</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <description>American Express cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</description>
        <inlineHelpText>AMEX cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</inlineHelpText>
        <label>Card Security Code</label>
        <length>5</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Mail_Check__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Mail Check</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Platinum_Subscription_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if uses for platinum payment.</inlineHelpText>
        <label>Platinum Subscription Card</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card Detail</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Bookkeeping_Admin.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abdur Rehman</fullName>
    </customValue>
    <customValue>
        <fullName>Abraham Carrillo</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Hendershot</fullName>
    </customValue>
    <customValue>
        <fullName>Angela Berrow</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Langer</fullName>
    </customValue>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>awais khan</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Arnold</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Bobby Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Bruce Williams</fullName>
    </customValue>
    <customValue>
        <fullName>Carol Spagnoletta</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Conrad Gomez</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Dawson Phipps</fullName>
    </customValue>
    <customValue>
        <fullName>Doug Guard</fullName>
    </customValue>
    <customValue>
        <fullName>Hebert Romero</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Petrunyak</fullName>
    </customValue>
    <customValue>
        <fullName>Jerome Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Joel Evans</fullName>
    </customValue>
    <customValue>
        <fullName>John Doe</fullName>
    </customValue>
    <customValue>
        <fullName>Jonna States</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Fleming</fullName>
    </customValue>
    <customValue>
        <fullName>Kelly Van Middlesworth</fullName>
    </customValue>
    <customValue>
        <fullName>Kenneth Harrah</fullName>
    </customValue>
    <masterLabel>Bookkeeping Admin</masterLabel>
</GlobalValueSet>

globalValueSets/CAM.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alexandria Lessard</fullName>
    </customValue>
    <customValue>
        <fullName>Mary Borden</fullName>
    </customValue>
    <customValue>
        <fullName>Matthew Smidowicz</fullName>
    </customValue>
    <customValue>
        <fullName>Team Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 6</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 7</fullName>
    </customValue>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Brown</fullName>
        <isActive>false</isActive>
        <label>Christina Brown</label>
    </customValue>
    <customValue>
        <fullName>Danielle Blair</fullName>
        <isActive>false</isActive>
        <label>Danielle Blair</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <customValue>
        <fullName>Joseph Sacco</fullName>
        <isActive>false</isActive>
        <label>Joseph Sacco</label>
    </customValue>
    <customValue>
        <fullName>Erica Terrell</fullName>
        <isActive>false</isActive>
        <label>Erica Terrell</label>
    </customValue>
    <customValue>
        <fullName>Savannah Wallace</fullName>
        <isActive>false</isActive>
        <label>Savannah Wallace</label>
    </customValue>
    <customValue>
        <fullName>Crystal Smerdel</fullName>
        <isActive>false</isActive>
        <label>Crystal Smerdel</label>
    </customValue>
    <description>Cams assigned</description>
    <masterLabel>CAM</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/CSR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aaron Bernhardt</fullName>
    </customValue>
    <customValue>
        <fullName>Adrienne Harper</fullName>
    </customValue>
    <customValue>
        <fullName>Alexa Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Alyssa Hoopii</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Zipprich</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Yadao</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Seguin</fullName>
    </customValue>
    <customValue>
        <fullName>Branden Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Brittany Rains</fullName>
    </customValue>
    <customValue>
        <fullName>Carly Coons</fullName>
    </customValue>
    <customValue>
        <fullName>Carrie J. Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Channell Palmer</fullName>
    </customValue>
    <customValue>
        <fullName>Chase Foster</fullName>
    </customValue>
    <customValue>
        <fullName>Christian DeField</fullName>
    </customValue>
    <customValue>
        <fullName>Claire Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Colette Grier</fullName>
    </customValue>
    <customValue>
        <fullName>Dana Heckathorn</fullName>
    </customValue>
    <customValue>
        <fullName>Deborah Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Domanick Page-Whitaker</fullName>
    </customValue>
    <customValue>
        <fullName>Duncan Bjerke</fullName>
    </customValue>
    <customValue>
        <fullName>Gabby Esteban</fullName>
    </customValue>
    <customValue>
        <fullName>Hayley Karlson</fullName>
    </customValue>
    <customValue>
        <fullName>Jade Comer</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Lundquist</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Nelson</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Seibert</fullName>
    </customValue>
    <customValue>
        <fullName>Jessica Thornton</fullName>
    </customValue>
    <customValue>
        <fullName>Kaila Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Katherine Baez</fullName>
    </customValue>
    <customValue>
        <fullName>Kim Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Alexandria Lessard</fullName>
        <isActive>false</isActive>
        <label>Alexandria Lessard</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <description>Assigned CSR</description>
    <masterLabel>CSR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/Send_email_to_CSRTest.cls
@isTest(SeeAllData = false)
public class Send_email_to_CSRTest {
	private static testMethod void sendEmailToCSRTest(){
        
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, Name,  AccountId from User where UserRoleId = :portalRole.Id Limit 1];  
        RecordType rt = [SELECT Id, Name, SobjectType FROM RecordType where name = 'Community Platinum Case' and SobjectType = 'Case'];
        //System.runAs ( thisUser ) {
            Test.StartTest();  
            Integer cseLstSze = 10; 
            Id p = [select id from profile where name='Partner Community User'].id;
            Campaign cmp = new Campaign();
            cmp.Name = 'Steve';
            insert cmp;        
            Account testAccount = new Account();
            testAccount.Name='Test Account' ;
            testAccount.First_Name__c='Edward';
            testAccount.Last_Name__c='Lee';
            testAccount.Campaign__c = cmp.Id;
            testAccount.OwnerId = thisUser.Id;
            testAccount.Assigned_CAM__c = 'Sara Winter';
            testAccount.Bookkeeper__c = thisUser.Id;
            testAccount.phone='123456782';
        	testAccount.Assigned_CSR__c = 'Alexandria Lessard';
            insert testAccount;              
            Contact cont = new Contact ();
            cont.FirstName = 'FirstName';
            cont.LastName = 'LastName';
            cont.Email='email@email.com';
            cont.phone='12345678';
            cont.AccountId=testAccount.Id;
            insert cont;
            Credit_Card_Detail__c  ccd = new Credit_Card_Detail__c ();
            ccd.Account__c = testAccount.Id;
            ccd.Card_Month__c = '04';
            ccd.Card_Number__c = '1234567896541236';
            ccd.Card_Security__c = '777';
            ccd.Card_Type__c = 'visa';
            ccd.Card_Year__c = '2020'; 
        	ccd.Mail_Check__c = 1;
        	ccd.Platinum_Subscription_Card__c = true;
            insert ccd;
            Test.stopTest();
       // }
        
    }
    	private static testMethod void sendEmailToCSRTest2(){
        
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, Name,  AccountId from User where UserRoleId = :portalRole.Id Limit 1];  
        RecordType rt = [SELECT Id, Name, SobjectType FROM RecordType where name = 'Community Platinum Case' and SobjectType = 'Case'];
        //System.runAs ( thisUser ) {
            Test.StartTest();  
            Integer cseLstSze = 10;
            Id p = [select id from profile where name='Partner Community User'].id;
            Campaign cmp = new Campaign();
            cmp.Name = 'Steve';
            insert cmp;        
            Account testAccount = new Account();
            testAccount.Name='Test Account' ;
            testAccount.First_Name__c='Edward';
            testAccount.Last_Name__c='Lee';
            testAccount.Campaign__c = cmp.Id;
            testAccount.OwnerId = thisUser.Id;
            testAccount.Assigned_CAM__c = 'Sara Winter';
            testAccount.Bookkeeper__c = thisUser.Id;
            testAccount.phone='123456782';
        	testAccount.Assigned_CSR__c = 'Alexandria Lessard';
            insert testAccount;              
            Contact cont = new Contact ();
            cont.FirstName = 'FirstName';
            cont.LastName = 'LastName';
            cont.Email='email@email.com';
            cont.phone='12345678';
            cont.AccountId=testAccount.Id;
            insert cont;
            Credit_Card_Detail__c  ccd = new Credit_Card_Detail__c ();
            ccd.Account__c = testAccount.Id;
            ccd.Card_Month__c = '04';
            ccd.Card_Number__c = '1234567896541236';
            ccd.Card_Security__c = '777';
            ccd.Card_Type__c = 'visa';
            ccd.Card_Year__c = '2020'; 
        	ccd.Platinum_Subscription_Card__c = true;
            insert ccd;
            ccd.Card_Month__c = '05';
            update ccd;
            Test.stopTest();
       // }
        
    }
    
    
    private static testMethod void sendEmailToCSRTest3(){
        
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, Name,  AccountId from User where UserRoleId = :portalRole.Id Limit 1];  
        RecordType rt = [SELECT Id, Name, SobjectType FROM RecordType where name = 'Community Platinum Case' and SobjectType = 'Case'];
        //System.runAs ( thisUser ) {
            Test.StartTest();  
            Integer cseLstSze = 10; 
            Id p = [select id from profile where name='Partner Community User'].id;
            Campaign cmp = new Campaign();
            cmp.Name = 'Steve';
            insert cmp;        
            Account testAccount = new Account();
            testAccount.Name='Test Account' ;
            testAccount.First_Name__c='Edward';
            testAccount.Last_Name__c='Lee';
            testAccount.Campaign__c = cmp.Id;
            testAccount.OwnerId = thisUser.Id;
            testAccount.Assigned_CAM__c = 'Sara Winter';
            testAccount.Bookkeeper__c = thisUser.Id;
            testAccount.phone='123456782';
        	testAccount.Assigned_CSR__c = '';
            insert testAccount;              
            Contact cont = new Contact ();
            cont.FirstName = 'FirstName';
            cont.LastName = 'LastName';
            cont.Email='email@email.com';
            cont.phone='12345678';
            cont.AccountId=testAccount.Id;
            insert cont;
            Credit_Card_Detail__c  ccd = new Credit_Card_Detail__c ();
            ccd.Account__c = testAccount.Id;
            ccd.Card_Month__c = '04';
            ccd.Card_Number__c = '1234567896541236';
            ccd.Card_Security__c = '777';
            ccd.Card_Type__c = 'visa';
            ccd.Card_Year__c = '2020'; 
        	ccd.Mail_Check__c = 1;
        	ccd.Platinum_Subscription_Card__c = true;
            insert ccd;
        	ccd.Card_Number__c = '1234577896541236';
        	update ccd;
            Test.stopTest();
       // }
        
    }
}