objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Infinity_Calculator__c.object
<CustomObject>
    <description>Calculator for the Mastermind group.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Infinity Calculator</relationshipLabel>
        <relationshipName>Infinity_Calculator</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>first_name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last_name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Infinity Calculator</label>
    <nameField>
        <label>Infinity Calculator</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Infinity Calculator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RestrictMultipleRecordTest.cls
@isTest
private class RestrictMultipleRecordTest {
    
    static testmethod void testRestrictedRecord(){
        Account acc = new Account(name='infinite');
        acc.First_Name__c='test account';
        acc.Last_Name__c='chetu';
        insert acc;
        acc.Name='calculator';
        update acc;
        Infinity_Calculator__c  infintcal = new Infinity_Calculator__c();
        infintcal.Account__c = acc.id;
        infintcal.Name ='testcal';
        infintcal.first_name__c ='test';
        infintcal.last_name__c='infinite';
        insert infintcal;
        
    }
    
}