objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Sales Team</businessProcess>
        <description>Used for Bookkeeping overages.</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Filing_Changes_Test.cls
@isTest
public class Filing_Changes_Test {
    @testSetup    
   public static void createTestData() {
         Id devoppBkRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Bookkeeping').getRecordTypeId();
        Account a = new Account();
       a.Name = 'Bob Apples';
       a.First_Name__c='Bob';
       a.Last_Name__c='Apples';
          insert a;
       
       Opportunity opp=new Opportunity();
       opp.RecordTypeId=devoppBkRecordTypeId;
       opp.CloseDate=system.today();
       opp.StageName='Closed Won';
       opp.AccountId=a.id;
       opp.Name='Test Bk Sale';
       insert opp;
   }
    @isTest
   static void TestaccordionDisplay(){
         Opportunity o =[Select id,Name from Opportunity where Name='Test Bk Sale' limit 1];
       test.startTest();
      Filing_Changes.getSale(o.id);
       test.stopTest();
   }

}