objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teams__c</fullName>
        <description>Team Assigned to Client</description>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Teams</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>CampaignID__c</fullName>
        <formula>Contact.CampaignID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CampaignID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/ChargentSFA__Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Gateway_Date__c</fullName>
        <label>Gateway Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Gateway_ID__c</fullName>
        <label>Gateway ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Client Referral Credit</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Credit to be used</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Wire Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Response_Status__c</fullName>
        <label>Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>ChargentSFA__Opportunity__r.Account.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>ChargentSFA__Opportunity__r.Account.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CampaignID__c</fullName>
        <label>CampaignID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                    <default>true</default>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Welcome_Call__c</fullName>
        <formula>PricebookEntry.Product2.Welcome_Call__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Welcome Call</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Anderson Services</fullName>
                </value>
                <value>
                    <fullName>Annual List</fullName>
                </value>
                <value>
                    <fullName>BK Consult</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping - Misc</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Tax Form</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Virtual</fullName>
                </value>
                <value>
                    <fullName>Certified Copy</fullName>
                </value>
                <value>
                    <fullName>Charitable Registration</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Corp Formation</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Deed</fullName>
                </value>
                <value>
                    <fullName>Dissolution</fullName>
                </value>
                <value>
                    <fullName>Doc Drafting</fullName>
                </value>
                <value>
                    <fullName>Estate</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Foreign Filing</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                </value>
                <value>
                    <fullName>Informational Only</fullName>
                </value>
                <value>
                    <fullName>IRS Form</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>LLC Formation</fullName>
                </value>
                <value>
                    <fullName>LP Formation</fullName>
                </value>
                <value>
                    <fullName>Meeting Minutes</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Formation</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>Pensions</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Welcome_Call__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Welcome Call</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Team 1</fullName>
    </customValue>
    <customValue>
        <fullName>Team 2</fullName>
    </customValue>
    <customValue>
        <fullName>Team 3</fullName>
    </customValue>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Team Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>Team 4</fullName>
    </customValue>
    <customValue>
        <fullName>Team 5</fullName>
    </customValue>
    <customValue>
        <fullName>Team 6</fullName>
    </customValue>
    <customValue>
        <fullName>Team 7</fullName>
    </customValue>
    <customValue>
        <fullName>Temp Team</fullName>
        <isActive>false</isActive>
        <label>Temp Team</label>
    </customValue>
    <description>Teams</description>
    <masterLabel>Teams</masterLabel>
</GlobalValueSet>

classes/PlatinumOnbargingBatchCallTest.cls
@isTest(SeeAllData=false)
public class PlatinumOnbargingBatchCallTest {

    static testmethod void test() {        
       
        String CRON_EXP = '0 0 0 15 3 ? *';
        
        // Create your test data
               List<Campaign> CampaignList = new List<Campaign>();
        List<Account> accounts = new List<Account>();
        List<opportunity> oppList=new List<Opportunity>();
        List<OpportunityLineItem> opLineitemlist=new List<OpportunityLineItem>();
     
        
        List<Contact> contacts = new List<Contact>();
        Campaign c1=new campaign();
        c1.Name='New Client Law and Tax Sale';
        CampaignList.add(c1);
       
        Campaign c2=new campaign();
        c2.Name='New Client Tax Sale';
        CampaignList.add(c2);
        
        Campaign c3=new campaign();
        c3.Name='New Client Law Sale';
        CampaignList.add(c3);
      
       
        insert CampaignList;
        
        
    
        
        
        for (Integer i=0;i<5;i++) {
            accounts.add(new Account(name='Apples '+i,Last_Name__c='Bobby '+i,First_Name__c='Apples'+i,Teams__c='Team 5'
                ));
        }
        insert accounts;
       
        for (Account account : [select id from account]) {
            contacts.add(new Contact(firstname='Bobby', 
                lastname='Apples', accountId=account.id,
                                    Account_Roles__c='Primary Contact'));
        }
        insert contacts;
        CampaignMember cm=new  CampaignMember();
        cm.ContactId=contacts[0].id;
        cm.CampaignId=c2.id;
        insert cm;
        contacts[1].CampaignID__c='New Client Law Sale';
        update contacts;
        Opportunity opp=new Opportunity();
        opp.Name='Test Sale 1';
        opp.AccountId=accounts[0].id;
        opp.RecordTypeId='012U0000000DFSx';
        opp.StageName='Closed Won';
        opp.CloseDate = Date.Today();
        oppList.add(opp);
        
         Opportunity opp2=new Opportunity();
        opp2.Name='Test Sale 2';
        opp2.AccountId=accounts[1].id;
        opp2.RecordTypeId='012U0000000DFSx';
         opp2.StageName='Closed Won';
        opp2.CloseDate = Date.Today();
        oppList.add(opp2);
        
        Opportunity opp3=new Opportunity();
        opp3.Name='Test Sale 3';
        opp3.AccountId=accounts[2].id;
        opp3.RecordTypeId='012U0000000DFSx';
         opp3.StageName='Closed Won';
        opp3.CloseDate = Date.Today();
        oppList.add(opp3);
       
      
        
   insert oppList;
        
        Id pricebookId = Test.getStandardPricebookId();

List<Product2> products=new List<Product2>();
Product2 prod = new Product2(
     Name = 'Test2',
     ProductCode = 'Pro-X',
     isActive = true,
    welcome_call__c=true,
    Type__c ='Tax'
    
);
        products.add(prod);
        Product2 prod1 = new Product2(
     Name = 'Test 1',
     ProductCode = 'Pro-X',
     isActive = true,
    welcome_call__c=true,
    Type__c ='Law'
    
);
         products.add(prod1);
        
insert products;

List<PricebookEntry> pbList=new List<PricebookEntry>();
PricebookEntry pbEntry1 = new PricebookEntry(
     Pricebook2Id = pricebookId,
     Product2Id = products[0].Id,
     UnitPrice = 100.00,
     IsActive = true
);
        pbList.add(pbEntry1);  
        PricebookEntry pbEntry2 = new PricebookEntry(
     Pricebook2Id = pricebookId,
     Product2Id = products[1].Id,
     UnitPrice = 100.00,
     IsActive = true
);
      pbList.add(pbEntry2);  

insert pbList;

OpportunityLineItem oli1 = new OpportunityLineItem(
     OpportunityId = oppList[0].Id,
     Quantity = 5,
     PricebookEntryId = pbList[0].Id,
     TotalPrice =  pbList[0].UnitPrice
);
        opLineitemlist.add(oli1);
        
        OpportunityLineItem oli2 = new OpportunityLineItem(
     OpportunityId = oppList[1].Id,
     Quantity = 5,
     PricebookEntryId =pbList[1].Id,
     TotalPrice =  pbList[1].UnitPrice
);
        opLineitemlist.add(oli2);
             OpportunityLineItem oli3 = new OpportunityLineItem(
     OpportunityId = oppList[1].Id,
     Quantity = 5,
     PricebookEntryId = pbList[0].Id,
     TotalPrice =  pbList[0].UnitPrice
);
       opLineitemlist.add(oli3);
             OpportunityLineItem oli4 = new OpportunityLineItem(
     OpportunityId = oppList[2].Id,
     Quantity = 5,
     PricebookEntryId = pbList[1].Id,
     TotalPrice =  pbList[1].UnitPrice
);
        opLineitemlist.add(oli4);
		insert opLineitemlist;
        List <ChargentSFA__Transaction__c> transactions=new List<ChargentSFA__Transaction__c>();
        ChargentSFA__Transaction__c t1= new ChargentSFA__Transaction__c();
       t1.ChargentSFA__Amount__c=100.00;
        t1.ChargentSFA__Opportunity__c=oppList[0].Id;
          t1.ChargentSFA__Payment_Method__c='Credit Card';
        t1.ChargentSFA__Response_Status__c='Approved';
        t1.ChargentSFA__Gateway_Date__c=System.today();
      
        t1.ChargentSFA__Gateway_ID__c='a0P6C000000cwEp';
        transactions.add(t1);
        ChargentSFA__Transaction__c t2= new ChargentSFA__Transaction__c();
       t2.ChargentSFA__Amount__c=200.00;
        t2.ChargentSFA__Opportunity__c=oppList[1].Id;
        t2.ChargentSFA__Response_Status__c='Approved';
        t2.ChargentSFA__Payment_Method__c='Credit Card';
         t2.ChargentSFA__Response_Status__c='Approved';
        t2.ChargentSFA__Gateway_Date__c=System.today();
          transactions.add(t2);
         ChargentSFA__Transaction__c t3= new ChargentSFA__Transaction__c();
       t3.ChargentSFA__Amount__c=100.00;
        t3.ChargentSFA__Opportunity__c=oppList[2].Id;
        t3.ChargentSFA__Response_Status__c='Approved';
        t3.ChargentSFA__Payment_Method__c='Credit Card';
         t3.ChargentSFA__Response_Status__c='Approved';
        t3.ChargentSFA__Gateway_Date__c=System.today();
          transactions.add(t3);
        insert transactions;
        
               /* Datetime modifiedDatetime = Datetime.now().addDays(-90);     
Test.setCreatedDate(accounts[3].id, modifiedDatetime);
        Test.setCreatedDate(accounts[4].id, modifiedDatetime);
        Test.setCreatedDate(accounts[5].id, modifiedDatetime);*/
        Test.startTest();
   

        
            String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new PlatinumOnboadingBatchCall());
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(CRON_EXP, ct.CronExpression);
            System.assertEquals(0, ct.TimesTriggered);

        Test.stopTest();
     
        
      
    }
    
}