objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inactive_Client__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This field is updated once per night through an automated process. Clients will be marked inactive or active depending on whether they meet Sales criteria at the end of the business day. It is not meant to be changed manually.</inlineHelpText>
        <label>Inactive Client</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Value_of_All_Sales__c</fullName>
        <description>Total dollar value of all won sales from client, net of fees.</description>
        <inlineHelpText>Total dollar value of all won sales from client, net of fees.</inlineHelpText>
        <label>Total Value of All Sales</label>
        <summarizedField>Opportunity.Net_Transactions_net_of_Fees__c</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Sales Team</businessProcess>
        <description>Used for Bookkeeping overages.</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FlagActiveClientsbatchCls.cls
global class FlagActiveClientsbatchCls implements Database.Batchable<sObject>{
  private String query; 
      global FlagActiveClientsbatchCls(string query){
            this.query = query;
            
        }
     global database.QueryLocator start(Database.BatchableContext BC) {
    
       return Database.getQueryLocator(this.query);    

        
    }  
     global void execute(Database.BatchableContext bc,List<account> flagactiveclients){
        List <account> flagactivetoinactiveClientList = New List <account>();
       
        for(account flagactiveClient : flagactiveclients)
        {
            flagactiveClient.Inactive_Client__c  = TRUE; 
            flagactivetoinactiveClientList.add(flagactiveClient);
    }
         if(!flagactivetoinactiveClientList.isEmpty()){
             update flagactivetoinactiveClientList;
         }

         
     }
    
         global void finish(Database.BatchableContext BC){
        system.debug('Batch execution completed.');
    }                          
   
    
  /*  public void flagInactiveClients(){
        
        
        List<Account> accountsareactive = new List<Account>([ Select Id, Inactive_Client__c, Total_Value_of_All_Sales__c  FROM Account
                                                            WHERE 
                                                            Inactive_Client__c=false AND
                                                            NAME!='Advisors, Anderson' AND
                                                            
                                                            Id NOT IN(
                                                            SELECT AccountId
                                                            FROM Opportunity
                                                            
                                                            WHERE
                                                            
                                                            Account.Total_Value_of_All_Sales__c >= 1500 AND
                                                            
                                                            (((RecordType.Name = 'State Renewal' OR RecordType.Name = 'Standard Renewal') 
                                                            AND ( ( StageName = 'Qualification' OR ( StageName =  'Closed Won' AND CloseDate = LAST_N_days:365 ))) )
                                                            
                                                            OR ((RecordType.Name = 'Platinum Subscription' OR RecordType.Name = 'Bookkeeping Subscription') 
                                                            AND StageName != 'Closed Lost')
                                                            
                                                            OR ((RecordType.Name = 'Entity Formation' OR RecordType.Name = 'Tax Compliance')
                                                            AND (StageName = 'Closed Won' OR StageName = 'Fulfillment/Partial Payment')
                                                            AND CloseDate = LAST_N_days:365) ))                                                        
                                                            ]);
                
        if(!accountsareactive.isEmpty()) {
            for(Account acc : accountsareactive){
                acc.Inactive_Client__c  = TRUE;              
            }
            
            update accountsareactive;
            
        }
        
           List<Account> accountsareInactive = new List<Account>([ Select Id, Name, Inactive_Client__c, LastModifiedDate, Total_Value_of_All_Sales__c  FROM Account
                                                        WHERE 
                                                        Inactive_Client__c=true AND
                                                        NAME!='Advisors, Anderson' AND
                                                        
                                                        
                                                        Id IN(
                                                        SELECT AccountId
                                                        FROM Opportunity
                                                        
                                                        WHERE
                                                        Account.Total_Value_of_All_Sales__c >= 1500 AND
                                                        
                                                        (((RecordType.Name = 'State Renewal' OR RecordType.Name = 'Standard Renewal') 
                                                        AND ( ( StageName = 'Qualification' OR ( StageName =  'Closed Won' AND CloseDate = LAST_N_days:365 ))) )
                                                        
                                                        OR ((RecordType.Name = 'Platinum Subscription' OR RecordType.Name = 'Bookkeeping Subscription') 
                                                        AND StageName != 'Closed Lost')
                                                        
                                                        OR ((RecordType.Name = 'Entity Formation' OR RecordType.Name = 'Tax Compliance')
                                                        AND (StageName = 'Closed Won' OR StageName = 'Fulfillment/Partial Payment')
                                                        AND CloseDate = LAST_N_days:365) ))                                                         
                                                            ]);
        if(!accountsareInactive.isEmpty()) {
            for(Account acc : accountsareInactive){
                acc.Inactive_Client__c  = FALSE;              
            }
            
            update accountsareInactive;
            
        }
        
    }

    public void flagActiveClients(){
        
        
     
        
    }*/
}