objects/Account.object
<CustomObject>
    <fields>
        <fullName>Entity_Count__c</fullName>
        <label>Entity Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Snapshot__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Event Snapshot</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EntityCount.cls
public class EntityCount {
    
    public static boolean alreadyProcessed = false;
    
    public static void countEntities(List<Account> newList, Map<Id,Account> oldMap) {
        
        if (alreadyProcessed == true) return;
        alreadyProcessed = true;
        
        for (Account acc : newList) {
			
            if(acc.Event_Snapshot__c == oldMap.get(acc.Id).Event_Snapshot__c) {
            
            Integer count = [Select count() FROM Entities__c Where Primary_Client__c = :acc.Id AND Status__c != 'Inactive'];
            acc.Entity_Count__c = count;
            
            }
        }
  
    }

}