objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Lead Source used for the general area of where the client came from. The campaign shows specific area.</description>
        <inlineHelpText>2018 Lead Source Main</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Campaign Source</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Accounts (Original Campaign Source)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <description>Used for Affiliates, not to be used for clients.</description>
        <label>Affiliate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Feedback__c.object
<CustomObject>
    <description>SCH-0114 - Feedback records for Client Submissions, NPS Surveys, Calls, or Internal Submissions.</description>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Lead Source being used</description>
        <inlineHelpText>lead source for 2018 - general category of where the client came from. For specifics look at campaign.</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Campaign Source</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads (Original Campaign Source)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Main Lead Source - general</description>
        <inlineHelpText>2018 Main Lead Source - general</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <formula>Account.Original_Campaign_Source__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original Campaign Source</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Sales Team</businessProcess>
        <description>Used for Bookkeeping overages.</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Main_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adduco Media</fullName>
    </customValue>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson Event</fullName>
    </customValue>
    <customValue>
        <fullName>Big Dog-Love American Homes</fullName>
    </customValue>
    <customValue>
        <fullName>Calendly</fullName>
    </customValue>
    <customValue>
        <fullName>Dani Johnson</fullName>
    </customValue>
    <customValue>
        <fullName>Dave Lindahl</fullName>
    </customValue>
    <customValue>
        <fullName>Don Pendleton</fullName>
    </customValue>
    <customValue>
        <fullName>Elite Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>Gene Guarino</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Lending</fullName>
    </customValue>
    <customValue>
        <fullName>Nick Vertucci-NVREA</fullName>
    </customValue>
    <customValue>
        <fullName>Online Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Online Marketing</fullName>
        <label>Online Paid</label>
    </customValue>
    <customValue>
        <fullName>Pat James</fullName>
    </customValue>
    <customValue>
        <fullName>Real Wealth Network</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Royal Media</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
        <isActive>false</isActive>
        <label>Website</label>
    </customValue>
    <description>2018 lead sources</description>
    <masterLabel>Main Lead Source</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/OwnerChangeComponentComCtrlTest.cls
@isTest
public class OwnerChangeComponentComCtrlTest {
    @testSetup
    public static void createTestData() {
        Id devoppBkRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Bookkeeping').getRecordTypeId();
        Account a = new Account();
        a.Name = 'Bob Apples';
        a.First_Name__c='Bob';
        a.Last_Name__c='Apples';
        insert a;
        
        Opportunity opp=new Opportunity();
        opp.RecordTypeId=devoppBkRecordTypeId;
        opp.CloseDate=system.today();
        opp.StageName='Closed Won';
        opp.AccountId=a.id;
        opp.Name='Test Bk Sale';
        insert opp;
    }
    @isTest
    static void changeOwnerMethodTest()
    {
        Opportunity o =[Select id,Name from Opportunity where Name='Test Bk Sale' limit 1];
        test.startTest();
        Profile p=[Select id from profile where name ='System Administrator' limit 1];
        user u=[Select id from user where profileid =:p.id limit 1];
        OwnerChangeComponentComCtrl.changeOwnerMethod(o.id, u.id,'Opportunity');
        test.stopTest();
    }
    @isTest
    static void changeOwnerMethodLeadTest()
    {
        Campaign newCampaign = new Campaign();
        newCampaign.IsActive = True;
        newCampaign.Name = 'Code Coverage';
        newCampaign.Status = 'In Progress';
        insert newCampaign;
        
        Lead newLead = new Lead() ;
        newLead.FirstName = 'Swain';
        newLead.LastName = 'Cole';
        newLead.Company = 'Bluewave';
        newLead.Status = 'New Lead';
        newLead.Main_Lead_Source__c = 'Affiliate';
        newLead.Original_Campaign_Source__c = newCampaign.id;
        insert newLead;
        
        test.startTest();
        Profile p=[Select id from profile where name ='System Administrator' limit 1];
        user u=[Select id from user where profileid =:p.id limit 1];
        OwnerChangeComponentComCtrl.changeOwnerMethod(newLead.id, u.id,'Lead');
        test.stopTest();
    }
    @isTest
    static void changeOwnerMethodFeedbackTest()
    {
        System.assertEquals(false, FeatureManagement.checkPermission('Allow_Change_Owner_Feedback_Record'));
        
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Allow_Change_Owner_Feedback_Record'];
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = UserInfo.getUserId(),
            PermissionSetId = ps.Id
        );
        //Id devoppBkRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        Account a = new Account();
        a.Name = 'Bob Apples';
        a.First_Name__c='Bob';
        a.Last_Name__c='Apples';
        a.OwnerId = psa.AssigneeId;
        insert a;
        
        // Account getAccountFromSetup = [Select id, name from Account where name='Bob Apple' limit 1];
        Id AdvisorAdminProfileID=[Select Id,name from profile where name='Anderson Profile' limit 1].id;
        
        //Id Advisoreuser=[select id from user where profileId=:AdvisorAdminProfileID limit 1].id;
        
        Id generalFeedbackRecordTypeId = Schema.SObjectType.Feedback__c.getRecordTypeInfosByName().get('NPS Survey Submission').getRecordTypeId();
        Feedback__c fb=new Feedback__c();
        fb.Name='Testing GF';
        fb.Client__c=a.Id;
        fb.RecordTypeId = generalFeedbackRecordTypeId;
        //fb.OwnerId = Advisoreuser;
        insert fb;
        test.startTest();
        Profile p=[Select id from profile where name ='System Administrator' limit 1];
        user u=[Select id from user where profileid =:p.id limit 1];
        //user u=[Select id from user where id='0056f00000AH2EzAAL' limit 1];
        OwnerChangeComponentComCtrl.changeOwnerMethod(fb.id, u.id,'Feedback__c');
        test.stopTest();
    }
    
    
}