objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper_Reviewer__c</fullName>
        <label>Bookkeeper Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Ashley Cloutier</fullName>
                </value>
                <value>
                    <fullName>Blanca Lemus</fullName>
                </value>
                <value>
                    <fullName>Christina Chavez</fullName>
                </value>
                <value>
                    <fullName>Crystal Moyer</fullName>
                </value>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Lanzi Reel</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Rebecca Gallegos</fullName>
                </value>
                <value>
                    <fullName>Tracy Cooklin</fullName>
                </value>
                <value>
                    <fullName>Trisha Cullinane</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abraham Carrillo</fullName>
                </value>
                <value>
                    <fullName>Alishia Greene-Jenkins</fullName>
                </value>
                <value>
                    <fullName>Antoinette Reid</fullName>
                </value>
                <value>
                    <fullName>Ashley Cloutier</fullName>
                </value>
                <value>
                    <fullName>Austin Stephens</fullName>
                </value>
                <value>
                    <fullName>Becky Arnold</fullName>
                </value>
                <value>
                    <fullName>Blanca Lemus</fullName>
                </value>
                <value>
                    <fullName>Brenda Guzman</fullName>
                </value>
                <value>
                    <fullName>Brenda Navarrette</fullName>
                </value>
                <value>
                    <fullName>Christina Chavez</fullName>
                </value>
                <value>
                    <fullName>Cindy Mejorado</fullName>
                </value>
                <value>
                    <fullName>Crystal Moyer</fullName>
                </value>
                <value>
                    <fullName>Danny On</fullName>
                </value>
                <value>
                    <fullName>Dawn Popa</fullName>
                </value>
                <value>
                    <fullName>Imelda Hilario</fullName>
                </value>
                <value>
                    <fullName>Jacquie Wallace-Small</fullName>
                </value>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Jennifer Soikowski</fullName>
                </value>
                <value>
                    <fullName>Jessica Turner</fullName>
                </value>
                <value>
                    <fullName>Jonathan Salyer</fullName>
                </value>
                <value>
                    <fullName>Kayla Fleming</fullName>
                </value>
                <value>
                    <fullName>Keanu Rhodes</fullName>
                </value>
                <value>
                    <fullName>Kenneth Harrah</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Kimberly Smiley</fullName>
                </value>
                <value>
                    <fullName>Kingstone Mashingaidze</fullName>
                </value>
                <value>
                    <fullName>Lanzi Reel</fullName>
                </value>
                <value>
                    <fullName>Mandrell Hahn</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Melissa McBride</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bookkeepings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Bookkeeping Records</relationshipLabel>
        <relationshipName>Bookkeeping_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_End__c</fullName>
        <label>Fiscal Year End</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Jan</fullName>
                </value>
                <value>
                    <fullName>Feb</fullName>
                </value>
                <value>
                    <fullName>Mar</fullName>
                </value>
                <value>
                    <fullName>Apr</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>Jun</fullName>
                </value>
                <value>
                    <fullName>Jul</fullName>
                </value>
                <value>
                    <fullName>Aug</fullName>
                </value>
                <value>
                    <fullName>Sep</fullName>
                </value>
                <value>
                    <fullName>Oct</fullName>
                </value>
                <value>
                    <fullName>Nov</fullName>
                </value>
                <value>
                    <fullName>Dec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Set_of_Books__c</fullName>
        <label>Set of Books</label>
        <referenceTo>Set_of_Books__c</referenceTo>
        <relationshipLabel>Entity Bookkeeping Records</relationshipLabel>
        <relationshipName>Bookkeeping_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Admin</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>client_name__c</fullName>
        <label>Client First Name</label>
        <length>208</length>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Set_of_Books__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Admin</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeping_Reviewer__c</fullName>
        <label>Bookkeeping Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Reviewer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_End__c</fullName>
        <label>Fiscal Year End</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Jan</fullName>
                </value>
                <value>
                    <fullName>Feb</fullName>
                </value>
                <value>
                    <fullName>Mar</fullName>
                </value>
                <value>
                    <fullName>Apr</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>Jun</fullName>
                </value>
                <value>
                    <fullName>Jul</fullName>
                </value>
                <value>
                    <fullName>Aug</fullName>
                </value>
                <value>
                    <fullName>Sep</fullName>
                </value>
                <value>
                    <fullName>Oct</fullName>
                </value>
                <value>
                    <fullName>Nov</fullName>
                </value>
                <value>
                    <fullName>Dec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Entity_Set_of_Books__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Set of Books</label>
    <nameField>
        <label>Set of Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Set of Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Bookkeeping_Admin.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abdur Rehman</fullName>
    </customValue>
    <customValue>
        <fullName>Abraham Carrillo</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Hendershot</fullName>
    </customValue>
    <customValue>
        <fullName>Angela Berrow</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Langer</fullName>
    </customValue>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>awais khan</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Arnold</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Bobby Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Bruce Williams</fullName>
    </customValue>
    <customValue>
        <fullName>Carol Spagnoletta</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Conrad Gomez</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Dawson Phipps</fullName>
    </customValue>
    <customValue>
        <fullName>Doug Guard</fullName>
    </customValue>
    <customValue>
        <fullName>Hebert Romero</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Petrunyak</fullName>
    </customValue>
    <customValue>
        <fullName>Jerome Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Joel Evans</fullName>
    </customValue>
    <customValue>
        <fullName>John Doe</fullName>
    </customValue>
    <customValue>
        <fullName>Jonna States</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Fleming</fullName>
    </customValue>
    <customValue>
        <fullName>Kelly Van Middlesworth</fullName>
    </customValue>
    <customValue>
        <fullName>Kenneth Harrah</fullName>
    </customValue>
    <masterLabel>Bookkeeping Admin</masterLabel>
</GlobalValueSet>

globalValueSets/Bookkeeping_Reviewer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Kiera Dunphy</fullName>
    </customValue>
    <customValue>
        <fullName>Lanzi Reel</fullName>
    </customValue>
    <customValue>
        <fullName>Ryan On</fullName>
    </customValue>
    <customValue>
        <fullName>Trisha Cullinane</fullName>
    </customValue>
    <customValue>
        <fullName>Troy Butler</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Nancy Naraine</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Kevin Dennis</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Flemming</fullName>
    </customValue>
    <customValue>
        <fullName>Tesia Owen</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
        <isActive>false</isActive>
        <label>Bethany Castleberry</label>
    </customValue>
    <customValue>
        <fullName>Christine Zimmerman</fullName>
        <isActive>false</isActive>
        <label>Christine Zimmerman</label>
    </customValue>
    <customValue>
        <fullName>Rebecca Gallegos</fullName>
        <isActive>false</isActive>
        <label>Rebecca Gallegos</label>
    </customValue>
    <customValue>
        <fullName>Marie Pues</fullName>
        <isActive>false</isActive>
        <label>Marie Pues</label>
    </customValue>
    <customValue>
        <fullName>Maria Boone</fullName>
        <isActive>false</isActive>
        <label>Maria Boone</label>
    </customValue>
    <masterLabel>Bookkeeping Reviewer</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/BookkeepingCtrl.cls
public class BookkeepingCtrl {
@AuraEnabled
    public static List<Set_of_Books__c> getSetofbooks(Id CaseID,Id userId) {
        
        ID CaseClientId=[Select AccountId from Case Where id=:CaseID].AccountId;
        string Username=[select Name from user where id=:userId].Name;
        List<Set_of_Books__c> RelatedToSetofbooks=[Select id,Name,Bookkeeper__c,Bookkeeping_Reviewer__c,Fiscal_Year_End__c from Set_of_Books__c where Client__c=:CaseClientId and (Bookkeeper__c=:Username or Bookkeeping_Reviewer__c=:Username) ];
        System.debug('Size--'+RelatedToSetofbooks.size());
        if(RelatedToSetofbooks.size()>0){
            return RelatedToSetofbooks;
        }else{
       		return null;
        }
        
    }
    @AuraEnabled
      public static List<Bookkeeping__c> getbookkeepingRecords(Id CaseID,Id userId) {
        
        ID CaseClientId=[Select AccountId from Case Where id=:CaseID].AccountId;
        string Username=[select Name from user where id=:userId].Name;
        List<Bookkeeping__c> RelatedToBookKeepingRecords=[Select id,Name,Bookkeeper__c,Bookkeeper_Reviewer__c,Set_of_Books__c,Set_of_Books__r.Name,Entity__c,Entity__r.Name,Fiscal_Year_End__c from Bookkeeping__c where Client_Name__c=:CaseClientId and (Bookkeeper__c=:Username or Bookkeeper_Reviewer__c=:Username) ];
        System.debug('Size--'+RelatedToBookKeepingRecords.size());
        if(RelatedToBookKeepingRecords.size()>0){
            return RelatedToBookKeepingRecords;
        }else{
       		return null;

        
    }
}
      @AuraEnabled
    public static String getClientId(Id CaseID) {
        
        String CaseClientId=[Select AccountId from Case Where id=:CaseID].AccountId;
        List<Account> RelatedToClient=[Select id,Name from Account Where id=:CaseClientId];
        if(RelatedToClient.size()>0){
            return CaseClientId;
        }else{
       		return null;
        }
        
    }
       @AuraEnabled
    public static String getcontactId(Id CaseID) {
        
        String CasecontactId=[Select ContactId from Case Where id=:CaseID].ContactId;
        List<contact> RelatedToContact=[Select id,Name from contact Where id=:CasecontactId];
        if(RelatedToContact.size()>0){
            return CasecontactId;
        }else{
       		return null;
        }
        
    }
        @AuraEnabled
public static List<Set_of_Books__c> findByNameSetofBooks(String searchKey, Id CaseID,Id userId) {
    ID CaseClientId=[Select AccountId from Case Where id=:CaseID].AccountId;
        string Username=[select Name from user where id=:userId].Name;
   
   String name = '%' + searchKey + '%';
   return [Select id,Name,Bookkeeper__c,Bookkeeping_Reviewer__c,Fiscal_Year_End__c from Set_of_Books__c where Client__c=:CaseClientId and (Bookkeeper__c=:Username or Bookkeeping_Reviewer__c=:Username) and (Name LIKE :name or Fiscal_Year_End__c Like:name ) ];
}
     @AuraEnabled
public static List<Bookkeeping__c> findByNameBookkeepingRecords(String searchKey, Id CaseID,Id userId) {
    List<Id> sodIDs=new List<ID>();
    ID CaseClientId=[Select AccountId from Case Where id=:CaseID].AccountId;
        string Username=[select Name from user where id=:userId].Name;
     String name = '%' + searchKey + '%';
   List<Set_of_Books__c> setofBooks=[Select id from Set_of_Books__c where Name like :name];
    for(Set_of_Books__c sof:setofBooks){
        sodIDs.add(sof.id);
    }
  
   return [Select id,Name,Bookkeeper__c,Bookkeeper_Reviewer__c,Set_of_Books__c,Set_of_Books__r.Name,Entity__c,Entity__r.Name,Fiscal_Year_End__c from Bookkeeping__c where Client_Name__c=:CaseClientId and (Bookkeeper__c=:Username or Bookkeeper_Reviewer__c=:Username) and (Name LIKE :name or Fiscal_Year_End__c Like:name or Set_of_Books__c In : sodIDs ) ];
}
}