objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <description>Cam Assigned to the account</description>
        <label>Assigned CAM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CAM</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <label>Assigned Client Success Coordinator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CSR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper_Pic__c</fullName>
        <formula>IF(ISBLANK(Bookkeeper_ImageURL__c),  IMAGE(&quot;https://drive.google.com/uc?&amp;id=0B05cYQRrxSNYZHRNN2R3RUZQUE0&quot;, &quot;Anderson&quot;,75,75),
IMAGE(Bookkeeper_ImageURL__c ,&quot;Bookkeeper Pic&quot;,75,75)
			)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bookkeeper Pic</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CAM_Email__c</fullName>
        <formula>CAM_Email_add__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CAM Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CAM_Ext__c</fullName>
        <formula>CAM_Extn__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CAM Ext</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CAM_Pic__c</fullName>
        <formula>IF(ISBLANK(CAM_ImageURL__c), IMAGE(&quot;https://drive.google.com/uc?&amp;id=0B05cYQRrxSNYZHRNN2R3RUZQUE0&quot;, &quot;Anderson&quot;,75,75), 
IMAGE(CAM_ImageURL__c ,&quot;Bookkeeper Pic&quot;,75,75) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CAM Pic</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSR_Email__c</fullName>
        <formula>Assigned_Law_Coordinator_Email__c

/* changed by shobi -LC_email__c*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSR_Ext__c</fullName>
        <formula>LC_ext__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator Ext</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSR_Pic__c</fullName>
        <formula>IF(ISBLANK(LC_ImageURL__c),  IMAGE( &quot;https://drive.google.com/uc?&amp;id=0B05cYQRrxSNYZHRNN2R3RUZQUE0&quot;, &quot;Anderson0&quot;,75,75),
IMAGE(LC_ImageURL__c ,&quot;Law Coordinator Pic&quot;,75,75)
			)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator Pic</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platinum_Client_View__c</fullName>
        <label>Platinum Client View</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Lifetime Platinum</fullName>
                </value>
                <value>
                    <fullName>Infinity Only</fullName>
                </value>
                <value>
                    <fullName>Infinity &amp; Platinum</fullName>
                </value>
                <value>
                    <fullName>Tax Team</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>NVREA Platinum</fullName>
                    <isActive>false</isActive>
                    <label>NVREA Platinum</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Senior_Advisor_Pic__c</fullName>
        <formula>IF(ISBLANK(SeniorAdvisor_ImageURL__c),  IMAGE( &quot;https://drive.google.com/uc?&amp;id=0B05cYQRrxSNYZHRNN2R3RUZQUE0&quot; , &quot;Anderson&quot;,75,75),
IMAGE(SeniorAdvisor_ImageURL__c ,&quot;Senior Advisor Pic&quot;,75,75)
			)


/* &quot;https://c.na48.content.force.com/servlet/servlet.ImageServer?id=0150B0000069qgh&amp;oid=00D8J0000008aJl&amp;lastMod=1520894235000&quot; */</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Senior Advisor Pic</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Senior_Advisor__c</fullName>
        <description>*****Should No Longer Be Used - Instead Use: Senior_Advisor_Picklist__c*****</description>
        <label>Senior Advisor (old, don&apos;t use)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Preparer_Pic__c</fullName>
        <formula>IF(ISBLANK(Tax_Preparer_ImageURL__c),  IMAGE(&quot;https://drive.google.com/uc?&amp;id=0B05cYQRrxSNYZHRNN2R3RUZQUE0&quot;, &quot;Anderson&quot;,75,75),
IMAGE(Tax_Preparer_ImageURL__c ,&quot;Bookkeeper Pic&quot;,75,75)
			)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Preparer Pic</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Preparer__c</fullName>
        <label>Tax Preparer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Brittany Stuck</fullName>
                </value>
                <value>
                    <fullName>Christia Thompson</fullName>
                </value>
                <value>
                    <fullName>Christopher Alejandre</fullName>
                </value>
                <value>
                    <fullName>Christos Zattas</fullName>
                </value>
                <value>
                    <fullName>Connor Haye</fullName>
                </value>
                <value>
                    <fullName>Cynthia Haley</fullName>
                </value>
                <value>
                    <fullName>Drew Young</fullName>
                </value>
                <value>
                    <fullName>Dutch Dochev</fullName>
                </value>
                <value>
                    <fullName>Dwight Tisby</fullName>
                </value>
                <value>
                    <fullName>Gavino Hufano</fullName>
                </value>
                <value>
                    <fullName>Henry Polledo</fullName>
                </value>
                <value>
                    <fullName>Ian Hanuscin</fullName>
                </value>
                <value>
                    <fullName>Ianthia Henson</fullName>
                </value>
                <value>
                    <fullName>Jared Riggs</fullName>
                </value>
                <value>
                    <fullName>Jeffery Webb</fullName>
                </value>
                <value>
                    <fullName>Jeff Liang</fullName>
                </value>
                <value>
                    <fullName>Jenae Barona</fullName>
                </value>
                <value>
                    <fullName>Jennifer Phipps</fullName>
                </value>
                <value>
                    <fullName>Jennifer Ransom</fullName>
                </value>
                <value>
                    <fullName>Jessica Santos</fullName>
                </value>
                <value>
                    <fullName>Katlyn Hartig</fullName>
                </value>
                <value>
                    <fullName>Kingstone Mashingaidze</fullName>
                </value>
                <value>
                    <fullName>Kristen Avila</fullName>
                </value>
                <value>
                    <fullName>Kulea Pelekai-Wai</fullName>
                </value>
                <value>
                    <fullName>Maria Mendiola</fullName>
                </value>
                <value>
                    <fullName>Martin Gallegos</fullName>
                </value>
                <value>
                    <fullName>Piao Sam</fullName>
                </value>
                <value>
                    <fullName>Roby Gray</fullName>
                </value>
                <value>
                    <fullName>Savannah Thompson</fullName>
                </value>
                <value>
                    <fullName>Sebastian Samuels</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Tax_Preparer__c</fullName>
        <label>Tax Preparer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tax_Preparer</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <formula>TEXT(Account.Assigned_CAM__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned CAM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <formula>TEXT(Account.Assigned_CSR__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Client_Image__c</fullName>
        <label>Client Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/CAM.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alexandria Lessard</fullName>
    </customValue>
    <customValue>
        <fullName>Mary Borden</fullName>
    </customValue>
    <customValue>
        <fullName>Matthew Smidowicz</fullName>
    </customValue>
    <customValue>
        <fullName>Team Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 6</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 7</fullName>
    </customValue>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Brown</fullName>
        <isActive>false</isActive>
        <label>Christina Brown</label>
    </customValue>
    <customValue>
        <fullName>Danielle Blair</fullName>
        <isActive>false</isActive>
        <label>Danielle Blair</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <customValue>
        <fullName>Joseph Sacco</fullName>
        <isActive>false</isActive>
        <label>Joseph Sacco</label>
    </customValue>
    <customValue>
        <fullName>Erica Terrell</fullName>
        <isActive>false</isActive>
        <label>Erica Terrell</label>
    </customValue>
    <customValue>
        <fullName>Savannah Wallace</fullName>
        <isActive>false</isActive>
        <label>Savannah Wallace</label>
    </customValue>
    <customValue>
        <fullName>Crystal Smerdel</fullName>
        <isActive>false</isActive>
        <label>Crystal Smerdel</label>
    </customValue>
    <description>Cams assigned</description>
    <masterLabel>CAM</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/CSR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aaron Bernhardt</fullName>
    </customValue>
    <customValue>
        <fullName>Adrienne Harper</fullName>
    </customValue>
    <customValue>
        <fullName>Alexa Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Alyssa Hoopii</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Zipprich</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Yadao</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Seguin</fullName>
    </customValue>
    <customValue>
        <fullName>Branden Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Brittany Rains</fullName>
    </customValue>
    <customValue>
        <fullName>Carly Coons</fullName>
    </customValue>
    <customValue>
        <fullName>Carrie J. Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Channell Palmer</fullName>
    </customValue>
    <customValue>
        <fullName>Chase Foster</fullName>
    </customValue>
    <customValue>
        <fullName>Christian DeField</fullName>
    </customValue>
    <customValue>
        <fullName>Claire Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Colette Grier</fullName>
    </customValue>
    <customValue>
        <fullName>Dana Heckathorn</fullName>
    </customValue>
    <customValue>
        <fullName>Deborah Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Domanick Page-Whitaker</fullName>
    </customValue>
    <customValue>
        <fullName>Duncan Bjerke</fullName>
    </customValue>
    <customValue>
        <fullName>Gabby Esteban</fullName>
    </customValue>
    <customValue>
        <fullName>Hayley Karlson</fullName>
    </customValue>
    <customValue>
        <fullName>Jade Comer</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Lundquist</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Nelson</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Seibert</fullName>
    </customValue>
    <customValue>
        <fullName>Jessica Thornton</fullName>
    </customValue>
    <customValue>
        <fullName>Kaila Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Katherine Baez</fullName>
    </customValue>
    <customValue>
        <fullName>Kim Austin</fullName>
    </customValue>
    <description>Assigned CSR</description>
    <masterLabel>CSR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Tax_Preparer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bradley Calvert</fullName>
    </customValue>
    <customValue>
        <fullName>Brittany Stuck</fullName>
    </customValue>
    <customValue>
        <fullName>Chad Bolosan</fullName>
    </customValue>
    <customValue>
        <fullName>Christia Thompson</fullName>
    </customValue>
    <customValue>
        <fullName>Christopher Alejandre</fullName>
    </customValue>
    <customValue>
        <fullName>Christos Zattas</fullName>
    </customValue>
    <customValue>
        <fullName>Connor Haye</fullName>
    </customValue>
    <customValue>
        <fullName>Cynthia Haley</fullName>
    </customValue>
    <customValue>
        <fullName>Dana Cummings</fullName>
    </customValue>
    <customValue>
        <fullName>Dinah Larkai</fullName>
    </customValue>
    <customValue>
        <fullName>Drew Young</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch Dochev</fullName>
    </customValue>
    <customValue>
        <fullName>Dwight Tisby</fullName>
    </customValue>
    <customValue>
        <fullName>Eliot Thomas</fullName>
    </customValue>
    <customValue>
        <fullName>Gary McHenry</fullName>
    </customValue>
    <customValue>
        <fullName>Gavino Hufano</fullName>
    </customValue>
    <customValue>
        <fullName>George Demos</fullName>
    </customValue>
    <customValue>
        <fullName>Grant Grajek</fullName>
    </customValue>
    <customValue>
        <fullName>Harry Sorensen</fullName>
    </customValue>
    <customValue>
        <fullName>Henry Polledo</fullName>
    </customValue>
    <customValue>
        <fullName>Ian Hanuscin</fullName>
    </customValue>
    <customValue>
        <fullName>Ianthia Henson</fullName>
    </customValue>
    <customValue>
        <fullName>Ivonne Delao</fullName>
    </customValue>
    <customValue>
        <fullName>Jared Riggs</fullName>
    </customValue>
    <customValue>
        <fullName>Jeffery Webb</fullName>
    </customValue>
    <customValue>
        <fullName>Jeff Liang</fullName>
    </customValue>
    <customValue>
        <fullName>Jenae Barona</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Phipps</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Ransom</fullName>
    </customValue>
    <customValue>
        <fullName>Jesse Martinez</fullName>
    </customValue>
    <masterLabel>Tax Preparer</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/MessageController.cls
/**
* A controller class used to fetch Message page data.
* 
* @author prateeks
* @version 1.0 - Jan 30, 2018
*/
public without sharing class MessageController {
    
    Public User usObj{get;set;}
    Public Contact con{get;set;}
    Public Account acc{get;set;}
    
    public MessageController(ApexPages.StandardController controller) {          
        usObj=[Select id,Username,AboutMe,Name,FirstName,LastName,Phone,ContactId,SmallPhotoUrl,FullPhotoUrl,AccountId,Email,Alias,ProfileId,Title,MobilePhone,LastLoginDate,CreatedDate,Client_Image__c,IsActive from User where Id=:UserInfo.getUserId() Limit 1];
        system.debug('UserObj=='+usObj);
        con=new Contact();
        acc=new Account();
        try{
            if(usObj.contactid!=null) {    
                con=[Select id,Name,Email,accountid,account.Platinum_Client_View__c,account.Assigned_CAM__c,account.Assigned_CSR__c,account.Phone,account.CAM_Pic__c,account.CAM_Ext__c,account.CAM_Email__c,account.CSR_Pic__c,account.CSR_Ext__c,account.CSR_Email__c,account.Senior_Advisor__c,account.Senior_Advisor_Pic__c,account.Bookkeeper__c,account.Bookkeeper_Pic__c,account.Tax_Preparer__c,account.Tax_Preparer_Pic__c,FirstName, LastName From contact where id =:usObj.contactid limit 1];
                system.debug('con=='+con);
                acc=[Select id,Name,Platinum_Client_View__c,Assigned_CAM__c,Assigned_CSR__c,Account_Number__c,First_Name__c,Last_Name__c From Account where id =:con.accountid limit 1];
            }    
        }catch(Exception e){
            system.debug('==== Exception  ====' + e);
        }        
    }
    /**
* This method is used to show activity history of User on Message page.
* 
* @author prateeks
* @date Dec 20, 2017
* @return <code>Email Activity</code>
*/
    public List<ActivityHistory> getIncomingTaskHistory() {
      
       /* List<ActivityHistory> listacti=new List<ActivityHistory>();
        for(Account lstaccounthist:[SELECT id,(SELECT Id, Status, ActivityType, Description, Subject, CreatedDate FROM ActivityHistories where ActivityType = 'Email' ORDER BY ActivityDate DESC, LastModifiedDate DESC) FROM Account WHERE id =:con.Accountid  LIMIT 1000]){
            try{
                listacti=lstaccounthist.ActivityHistories;
                system.debug('==listacti=='+listacti);
                System.debug('Try==size=='+listacti.size());
            }
            catch(QueryException e)
            {
                for(ActivityHistory ah:lstaccounthist.ActivityHistories)
                {
                    listacti.add(ah);
                    system.debug('==listacti=='+listacti);
                    System.debug('Catch==size=='+listacti.size());
                }
            }
        }*/
        
        try{      
            system.debug('==== con.Accountid  ====' + con.Accountid);
            List<Account>lstaccounthist=[SELECT id,(SELECT Id, Status, ActivityType, Description, Subject, CreatedDate FROM ActivityHistories where ActivityType = 'Email' ORDER BY ActivityDate DESC, LastModifiedDate DESC LIMIT 200) FROM Account WHERE id =:con.Accountid  LIMIT 1000]; 
            system.debug('lstaccount==='+lstaccounthist);
            List<ActivityHistory>listacti=new List<ActivityHistory>();	
            for(Account acc: lstaccounthist){
                listacti.addall(acc.ActivityHistories);
            }
            system.debug('==== listacti  ====' + listacti);
            return listacti;
        } catch(Exception e){
            system.debug('==== Exception  ====' + e);
            return null;
        }
        
        
    }
    
    
    @RemoteAction
    public static List<ActivityHistory> getTaskDescription(Id hisId,Id contAcctId) {
        try{                
            List<Account> activityList = [SELECT id,(SELECT Id, Description FROM ActivityHistories WHERE Id =:hisId ORDER BY ActivityDate DESC, LastModifiedDate DESC) FROM Account WHERE id =:contAcctId LIMIT 1000];
            List<ActivityHistory>activityDesc=new List<ActivityHistory>();	
            for(Account acc: activityList){
                activityDesc.addall(acc.ActivityHistories);
            }
            return activityDesc;
        } catch(Exception e){
            system.debug('==== Exception  ====' + e);
            return null;
        }
        
    }
    
}