objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platinum_Client_View__c</fullName>
        <label>Platinum Client View</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Lifetime Platinum</fullName>
                </value>
                <value>
                    <fullName>Infinity Only</fullName>
                </value>
                <value>
                    <fullName>Infinity &amp; Platinum</fullName>
                </value>
                <value>
                    <fullName>Tax Team</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>NVREA Platinum</fullName>
                    <isActive>false</isActive>
                    <label>NVREA Platinum</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ConvertExistingContactAsPartnerTest.cls
@isTest(seeAlldata = true)
private class ConvertExistingContactAsPartnerTest {
    
    static testMethod  void testConvertExistingContactAsPartner(){
        // UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        // User thisUser = [select Id, AccountId from User where UserRoleId = :portalRole.Id Limit 1];  
        // System.RunAs(thisUser)
        
        Test.startTest();
        Account partnerAccount = new Account(Name = 'Test Partner Account',First_Name__c='Edward',Last_Name__c='Lee',Platinum_Client_View__c ='Platinum Elite');                                                                           
        insert partnerAccount; 
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Opportunity' and Name = 'Platinum Subscription'].Id;
        Opportunity opp = new Opportunity();
        opp.AccountId = partnerAccount.id;
        opp.RecordTypeId = strRecordTypeId;
        opp.StageName ='Closed Won';
        opp.Name ='Platinum Subscription';
        opp.CloseDate = Date.Today().addDays(1);
        insert opp;
        partnerAccount.Platinum_Client_View__c = 'Platinum';
        update partnerAccount;
        Contact partnerContact = new Contact(FirstName = 'Test Contact',LastName = 'Test Contact',Account_Roles__c ='Primary Contact',
                                             AccountId = partnerAccount.Id,Email = 'testemail@chetu.com');
        insert partnerContact;
        
        String communityNick = Math.round(Math.random()*Math.pow(10, 7))+'';
        Profile p = [Select p.Name, p.Id From Profile p where p.Name ='Partner Community User' Limit 1];
        // Create Partner Users
        User partnerUser1 = new User();
        partnerUser1.LastName ='Test name';
        partnerUser1.Alias ='tetest';
        partnerUser1.Email ='testemail'+Math.round(Math.random()*Math.pow(10, 7))+'@testemail.com';
        partnerUser1.Username ='testemail'+Math.round(Math.random()*Math.pow(10, 7))+'@testemai.com';
        partnerUser1.CommunityNickname = 'TestCommunityName1'+communityNick.substring(0,4);
        partnerUser1.ProfileId = p.Id;
        partnerUser1.ContactId = partnerContact.Id;
        partnerUser1.TimeZoneSidKey ='Asia/Kolkata';
        partnerUser1.LocaleSidKey ='en_IN';
        partnerUser1.EmailEncodingKey ='UTF-8';
        partnerUser1.LanguageLocaleKey ='en_US';
        partnerUser1.isActive = true;
        insert partnerUser1; 
        partnerContact.LastName ='Test2 Contact';
        partnerContact.Email ='';
        update partnerContact;
        Test.stopTest();  
        //}
    }
    
    static testMethod void testConvertExisting(){
        Test.startTest();
        Account partnerAccount = new Account(Name = 'Test Partner Account',First_Name__c='Edward',Last_Name__c='Lee',Platinum_Client_View__c ='Platinum Elite');                                                                           
        insert partnerAccount; 
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Opportunity' and Name = 'Platinum Subscription'].Id;
        Opportunity opp = new Opportunity();
        opp.AccountId = partnerAccount.id;
        opp.RecordTypeId = strRecordTypeId;
        opp.StageName ='Closed Lost';
        opp.Name ='Platinum Subscription';
        opp.CloseDate = Date.Today().addDays(1);
        insert opp;
        Test.stopTest();  
        
    }
    
}