objects/Account.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Lead Source used for the general area of where the client came from. The campaign shows specific area.</description>
        <inlineHelpText>2018 Lead Source Main</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Campaign Source</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Accounts (Original Campaign Source)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <description>Used for Affiliates, not to be used for clients.</description>
        <label>Affiliate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Main Lead Source</description>
        <inlineHelpText>2018 Main Lead source - general</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <label>Original Campaign Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Lead Source being used</description>
        <inlineHelpText>lead source for 2018 - general category of where the client came from. For specifics look at campaign.</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Campaign Source</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads (Original Campaign Source)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Main_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adduco Media</fullName>
    </customValue>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson Event</fullName>
    </customValue>
    <customValue>
        <fullName>Big Dog-Love American Homes</fullName>
    </customValue>
    <customValue>
        <fullName>Calendly</fullName>
    </customValue>
    <customValue>
        <fullName>Dani Johnson</fullName>
    </customValue>
    <customValue>
        <fullName>Dave Lindahl</fullName>
    </customValue>
    <customValue>
        <fullName>Don Pendleton</fullName>
    </customValue>
    <customValue>
        <fullName>Elite Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>Gene Guarino</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Lending</fullName>
    </customValue>
    <customValue>
        <fullName>Nick Vertucci-NVREA</fullName>
    </customValue>
    <customValue>
        <fullName>Online Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Online Marketing</fullName>
        <label>Online Paid</label>
    </customValue>
    <customValue>
        <fullName>Pat James</fullName>
    </customValue>
    <customValue>
        <fullName>Real Wealth Network</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Royal Media</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
        <isActive>false</isActive>
        <label>Website</label>
    </customValue>
    <description>2018 lead sources</description>
    <masterLabel>Main Lead Source</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/TestAutoConvertLeadsWithAcc.cls
@isTest
public class TestAutoConvertLeadsWithAcc {
    static testMethod void myUnitTest()   
    {
        Campaign newCampaign = new Campaign();
        newCampaign.IsActive = True;
        newCampaign.Name = 'Code Coverage';
        newCampaign.Status = 'In Progress';
        insert newCampaign;
       
        //create the data
        Lead newLead = new Lead() ;
        newLead.FirstName = 'Swain';
        newLead.LastName = 'Cole';
        newLead.Company = 'Bluewave';
        newLead.Status = 'New Lead';
        newLead.Main_Lead_Source__c = 'Affiliate';
        newLead.Original_Campaign_Source__c = newCampaign.id;
        insert newLead;
        
        Lead newLead2 = new Lead() ;
        newLead2.FirstName = 'Swain2';
        newLead2.LastName = 'Cole2';
        newLead2.Company = 'Bluewave2';
        newLead2.Status = 'New Lead';  
        newLead2.Main_Lead_Source__c = 'Affiliate';
        newLead2.Original_Campaign_Source__c = newCampaign.id;
        insert newLead2;
        
        Lead newLead3 = new Lead() ;
        newLead3.FirstName = 'Cole3';
        newLead3.LastName = 'Swain3';
        newLead3.Company = 'BlueWave3';
        newLead3.Status = 'New Lead';
        newLead3.Main_Lead_Source__c = 'Affiliate';
        newLead3.Original_Campaign_Source__c = newCampaign.id;
        insert newLead3;
        
        //Account
        Account newAccount = new Account();
        newAccount.Name = 'Bluewave'; 
        insert newAccount;
        
        Account newAccount2 = new Account();
        newAccount2.Name = 'Bluewave2'; 
        insert newAccount2;
        
        //Contact
        Contact newContact = new Contact();
        newContact.AccountId = newAccount.id;
        newContact.FirstName = 'Anderson';
        newContact.LastName = 'Cole2';
        insert newContact;
        
        List<List<Id>> OutterListIds = new List<List<Id>>();
        List<Id> LeadIds = new List<Id>();
        LeadIds.add(newLead.id);
        LeadIds.add(newAccount.id);
        LeadIds.add(newContact.id); 
        OutterListIds.add(LeadIds);
         
        AutoConvertLeadsWithAcc.LeadAssign(OutterListIds);
        /*
        List<List<Id>> Outter2ListIds = new List<List<Id>>();
        List<Id> Inner2Ids = new List<Id>();
        Inner2Ids.add(newLead2.id);
        Inner2Ids.add(newAccount2.id);
        Outter2ListIds.add(Inner2Ids);
        
        AutoConvertLeadsWithAcc.LeadAssign(Outter2ListIds);
        
        List<List<Id>> Outter3ListIds = new List<List<Id>>();
        List<Id> Inner3Ids = new List<Id>();
        Inner3Ids.add(newLead3.id);
        Outter3ListIds.add(Inner3Ids);
        
        AutoConvertLeadsWithAcc.LeadAssign(Outter3ListIds);
*/
    }
}