objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TaxTeamSaleRealtedListPdfCtrlTest.cls
@isTest
public class TaxTeamSaleRealtedListPdfCtrlTest {
    static testMethod void SaleRealtedListTest() {
        Account acc=new Account ();
        acc.Name='Bobby Apples';
        acc.First_Name__c='Bobby';
        acc.Last_Name__c='Apples';
        insert acc;
        opportunity opp=new opportunity();
        opp.Name='Test Sale';
        opp.RecordTypeId='012U0000000g5X1IAI';
        opp.StageName='Closed Won';
        opp.CloseDate=system.today();
        opp.AccountId=acc.id;
        insert opp;
         ApexPages.StandardController stdSR = new ApexPages.StandardController(acc);
       
      System.currentPageReference().getParameters().put('id',acc.id); 
        TaxTeamSaleRealtedListPdfCtrl objoppList = new TaxTeamSaleRealtedListPdfCtrl(stdSR);
    }    

}