objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Entity_Formation_or_Tax_Sale__c</fullName>
        <label>First Entity Formation or Tax Sale</label>
        <summarizedField>Opportunity.First_Transaction__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Entity Formation, Tax Compliance</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.ChargentSFA__Transaction_Total__c</field>
            <operation>greaterOrEqual</operation>
            <value>1500</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_NPS_Sent__c</fullName>
        <label>Last NPS Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Transaction__c</fullName>
        <label>Last Transaction</label>
        <summarizedField>Opportunity.Last_Transaction__c</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Entity_Formation_or_Tax_Sale__c</fullName>
        <formula>Account.First_Entity_Formation_or_Tax_Sale__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Entity Formation or Tax Sale</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NPS_Recipient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the contact is currently receiving or is scheduled to receive a NPS survey.</description>
        <inlineHelpText>If checked, the contact is currently receiving or is scheduled to receive a NPS survey.</inlineHelpText>
        <label>NPS Recipient</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Default Record Type for All users</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Last_Transaction__c</fullName>
        <description>Most recent approved transaction.</description>
        <inlineHelpText>Most recent approved transaction.</inlineHelpText>
        <label>Last Transaction</label>
        <summarizedField>ChargentSFA__Transaction__c.ChargentSFA__Gateway_Date__c</summarizedField>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Response_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Type__c</field>
            <operation>equals</operation>
            <value>Charge</value>
        </summaryFilterItems>
        <summaryForeignKey>ChargentSFA__Transaction__c.ChargentSFA__Opportunity__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Sales Team</businessProcess>
        <description>Used for Bookkeeping overages.</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NPSenrollment_Scheduled.cls
public class NPSenrollment_Scheduled implements Schedulable{
    public void execute(SchedulableContext sc)
    {
        NPSenrollment();
    }
    
    public void NPSenrollment(){
        
        List<Contact> currentNPSRecipients = [SELECT Id FROM Contact WHERE NPS_Recipient__c = TRUE];
        
        Set<Account> accountSet = new Set<Account>();
        
        List<Contact> contacts = new List<Contact>([SELECT Id, AccountId, NPS_Recipient__c FROM Contact WHERE AccountId IN (  SELECT AccountId FROM Opportunity WHERE
                                                                                                                            
                                                                                                                            // Entity Formation Sales - 6 week
                                                                                                                            ((RecordType.Name = 'Entity Formation' OR RecordType.Name = 'Tax Compliance') 
                                                                                                                             AND Amount >=1500
                                                                                                                             AND StageName = 'Closed Won' 
                                                                                                                             AND CloseDate <= N_DAYS_AGO:43
                                                                                                                             AND CloseDate > N_DAYS_AGO:181
                                                                                                                             AND Account.First_Entity_Formation_or_Tax_Sale__c <= N_DAYS_AGO:43 
                                                                                                                             AND Account.First_Entity_Formation_or_Tax_Sale__c > N_DAYS_AGO:181)
                                                                                                                            
                                                                                                                            OR
                                                                                                                            
                                                                                                                            // Entity Formation Sales - 6 month
                                                                                                                            ((RecordType.Name = 'Entity Formation' OR RecordType.Name = 'Tax Compliance') 
                                                                                                                             AND Amount >=1500
                                                                                                                             AND StageName = 'Closed Won' 
                                                                                                                             AND CloseDate >= N_DAYS_AGO:31
                                                                                                                             AND Account.First_Entity_Formation_or_Tax_Sale__c < N_DAYS_AGO:182)
                                                                                                                            
                                                                                                                            OR
                                                                                                                            
                                                                                                                            // Subscription Sales - 6 month
                                                                                                                            ((RecordType.Name = 'Platinum Subscription' OR RecordType.Name = 'Bookkeeping Subscription')
                                                                                                                             AND StageName = 'Closed Won'
                                                                                                                             AND Last_Transaction__c >= N_DAYS_AGO:35
                                                                                                                             AND Account.First_Entity_Formation_or_Tax_Sale__c < N_DAYS_AGO:182)
                                                                                                                            
                                                                                                                            OR
                                                                                                                            
                                                                                                                            // Renewals - 6 month
                                                                                                                            ((RecordType.Name = 'State Renewal' OR RecordType.Name = 'Standard Renewal')
                                                                                                                             AND (CloseDate >= NEXT_N_DAYS:365 OR CloseDate = YESTERDAY)
                                                                                                                             AND (StageName = 'Closed Won' OR StageName = 'Qualification')
                                                                                                                             AND Account.First_Entity_Formation_or_Tax_Sale__c < N_DAYS_AGO:182)
                                                                                                                           )
                                                    
                                                    
                                                    
                                                    AND NPS_Recipient__c = FALSE 
                                                    AND Account_Roles__c = 'Primary Contact'
                                                    AND AccountId != null
                                                    AND (Account.Last_NPS_Sent__c <= N_DAYS_AGO:181 OR Account.Last_NPS_Sent__c = null)
                                                    ORDER BY Account.First_Entity_Formation_or_Tax_Sale__c DESC
                                                    LIMIT 16]);
        
        if(currentNPSRecipients.size() <= 112) {
            
            if(!contacts.isEmpty()) {
                for(Contact con : contacts){
                    con.NPS_Recipient__c = TRUE;
                    
                    for(Account acc : [SELECT Last_NPS_Sent__c FROM Account WHERE Id = :con.AccountId]){
                        acc.Last_NPS_Sent__c = Date.today();
                        accountSet.add(acc);
                    }
                }
                
                
                update contacts;
            }
        }
        if(currentNPSRecipients.size() <= 112) { 
            
            if(!accountSet.isEmpty()){
                List<account> accounts = new List<Account>(accountSet);
                update accounts;
            }
        }
        
    }
}