objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Infinity</fullName>
        <active>true</active>
        <label>Infinity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Credit_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Detail</relationshipLabel>
        <relationshipName>Credit_Card_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>AMEX: first digit = 3, second digit = 4 or 7. Valid length: 15 digits.
VISA: first digit = 4. Valid length: 13 or 16 digits.
MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</description>
        <inlineHelpText>AMEX: first digit = 3, second digit = 4 or 7.  Valid length: 15 digits.

VISA: first digit = 4.  Valid length: 13 or 16 digits.

MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</inlineHelpText>
        <label>Card Number</label>
        <length>19</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <description>American Express cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</description>
        <inlineHelpText>AMEX cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</inlineHelpText>
        <label>Card Security Code</label>
        <length>5</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Infinity_Subscription_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if the client would like this card to be used for their monthly/yearly Infinity subscription.</inlineHelpText>
        <label>Infinity Subscription Card</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Platinum_Subscription_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if uses for platinum payment.</inlineHelpText>
        <label>Platinum Subscription Card</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card Detail</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <label>Card Security</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Name__c</fullName>
        <inlineHelpText>Name on the card to be charged - will default to Client First and Last</inlineHelpText>
        <label>Card Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Number__c</fullName>
        <inlineHelpText>Please enter the complete credit card number without spaces or dashes</inlineHelpText>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ChargentSFA__Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Start_Date__c</fullName>
        <label>Payment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Stopped</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Infinity</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Infinity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestUpdateInfinitySubscriptionSale.cls
@isTest
public class TestUpdateInfinitySubscriptionSale {
	@testSetup static void dataSetup() {
        Account a = new Account();
        a.Name = 'Test Account';
        insert a;
        
        Opportunity o = new Opportunity();
        o.Name = 'Infinity Subscription';
        o.CloseDate = system.today()+1;
        o.ChargentSFA__Payment_Start_Date__c = system.today();
        o.AccountId = a.id;
        o.StageName = 'Closed Won';
        o.ChargentSFA__Payment_Status__c = 'Recurring';
        o.RecordTypeId = '0120B000000N8E5QAK';
        insert o;   
    	
        Credit_Card_Detail__c infc = new Credit_Card_Detail__c();
        infc.Account__c = a.id;
        infc.Name = 'Infinity Card 1';
        infc.Card_Type__c = 'Visa';
        infc.Card_Number__c = '1234567891234567';
        infc.Card_Month__c = '08';
        infc.Card_Year__c = '2024';
        infc.Card_Security__c = '411';
        infc.Infinity_Subscription_Card__c = True;
        insert infc;
        
        Credit_Card_Detail__c infc2 = new Credit_Card_Detail__c();
        infc2.Account__c = a.id;
        infc2.Name = 'Infinity Card 2';
        infc2.Card_Type__c = 'Visa';
        infc2.Card_Number__c = '1234567891234567';
        infc2.Card_Month__c = '08';
        infc2.Card_Year__c = '2024';
        infc2.Card_Security__c = '411';
        infc2.Infinity_Subscription_Card__c = False;
        insert infc2;
    }
    
    @isTest
    public static void newPlatinumCard() {
        
        Account a = [Select Id From Account LIMIT 1];
        
        Credit_Card_Detail__c infinC1 = [Select Id From Credit_Card_Detail__c Where Infinity_Subscription_Card__c = True Limit 1];
        Credit_Card_Detail__c infinC2 = [Select Id From Credit_Card_Detail__c Where Infinity_Subscription_Card__c = False Limit 1];
        
        Opportunity opp = [Select Id,ChargentSFA__Card_Type__c,ChargentSFA__Card_Month__c,Card_Number__c,ChargentSFA__Card_Year__c,ChargentSFA__Card_Number__c,ChargentSFA__Card_Name__c FROM Opportunity];
        System.debug('opp: '+opp);
        
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(opp);
        CreditCardInfo.processOpp(oppList);
        
        System.debug('infinC2: '+infinC2);
		infinC2.Infinity_Subscription_Card__c = True;
        update infinC2;
        System.debug('infinC2: '+infinC2);
        
        infinC1.Card_Security__c = '555';
        infinC1.Platinum_Subscription_Card__c = False;
        update infinC1;
        
        System.assertequals(True,infinC2.Infinity_Subscription_Card__c);
            
    }
}