objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Primary Contact Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UpdateAccountsPrimaryContactBatchcall.cls
global class UpdateAccountsPrimaryContactBatchcall  implements Schedulable{
 global void execute(SchedulableContext sc) {
      Id batchJobId1 = Database.executeBatch(new UpdateAccountsPrimaryContact('Select id,Name,(select id,Account_Roles__c from contacts) from Account where (Primary_Contact_Count__c=null or Primary_Contact_Count__c=0)  and CreatedDate = LAST_WEEK'), 200);
System.debug('Batch1--'+batchJobId1);
    

    }
}