objects/Account.object
<CustomObject>
    <fields>
        <fullName>Important_Notes__c</fullName>
        <inlineHelpText>Extremely important information regarding a client&apos;s account goes here.  Marriage, divorce, separation from business partner, deaths, etc.  Notes regarding renewals or general phone calls get logged in the activity history.</inlineHelpText>
        <label>Important Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Managing_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managing Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Entities (Managing Entity)</relationshipLabel>
        <relationshipName>Entities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_State_1__c</fullName>
        <label>Organization State 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State_2__c</fullName>
        <label>Organization State 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State_3__c</fullName>
        <label>Organization State 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State_4__c</fullName>
        <label>Organization State 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signor_Title_1__c</fullName>
        <label>Signor Title 1</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Signor_Title_2__c</fullName>
        <label>Signor Title 2</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Signor_Title_3__c</fullName>
        <label>Signor Title 3</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Signor_Title_4__c</fullName>
        <label>Signor Title 4</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Signor_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signor Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Structure__c</fullName>
        <label>Structure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member-managed</fullName>
                </value>
                <value>
                    <fullName>Manager-managed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trust_Member_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust Member 1</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Entities (Trust Member 1)</relationshipLabel>
        <relationshipName>Entities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trust_Member_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust Member 2</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Entities (Trust Member 2)</relationshipLabel>
        <relationshipName>Entities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trust_Member_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust Member 3</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Entities (Trust Member 3)</relationshipLabel>
        <relationshipName>Entities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trust_Member_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust Member 4</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Entities (Trust Member 4)</relationshipLabel>
        <relationshipName>Entities5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trust__c.object
<CustomObject>
    <description>Object to hold Trust information.</description>
    <fields>
        <fullName>First_Trustee_Name__c</fullName>
        <label>First Trustee Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Trustee_Type__c</fullName>
        <label>Initial Trustee Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Entity</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Clint</fullName>
                    <label>Nominee</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Filing State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trusts</relationshipLabel>
        <relationshipName>Trusts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trust__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Trusts</relationshipLabel>
        <relationshipName>Trusts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Trust</label>
    <nameField>
        <label>Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestTrustBinder.cls
@isTest

public class TestTrustBinder {
    
    static testMethod void testmethod1(){
{
     Account acc=new account();
        acc.Name='test name';
        acc.Important_Notes__c='test important notes';
        insert acc;
               
        Trust__c tr= new Trust__c();
    List<Trust__c> Litr= new list<Trust__c>();
             Id devoppLivingTrustobjRecordTypeId = Schema.SObjectType.Trust__c.getRecordTypeInfosByName().get('Living Trust').getRecordTypeId();
             tr.RecordTypeId=devoppLivingTrustobjRecordTypeId;
        tr.Name='Test Living Trust';
     tr.First_Trustee_Type__c='Individual';
    tr.First_Trustee_Name__c='TestfirstName';
        tr.Primary_Client__c=acc.id;
      insert tr;
      system.debug('>>>Size of tr1>>'+tr) ;
    
    Trust__c tr1= new Trust__c();
     Id devoppLivingTrustobjRecordTypeId1 = Schema.SObjectType.Trust__c.getRecordTypeInfosByName().get('Living Trust').getRecordTypeId();
             tr1.RecordTypeId=devoppLivingTrustobjRecordTypeId1;
        tr1.Name='Test Living Trust2';
     tr1.First_Trustee_Type__c='Individual';
    tr1.First_Trustee_Name__c='TestfirstName2';
        tr1.Primary_Client__c=acc.id;
  insert tr1;
    system.debug('>>>Size of tr1>>'+tr1) ;
    
    List<Entities__c> enList=new  List<Entities__c>();
    List<id> enids=new list<id>();
    List<id> Updatedenids=new list<id>();
    
        Entities__c en2=new Entities__c();
    en2.Primary_Client__c=acc.id;
    en2.Name='Top Entity';
    en2.RecordTypeId='012U0000000DE8m';
    en2.Organization_State__c='Georgia';
    en2.Organization_State_1__c= '';
    en2.Trust_Member_1__c=tr1.id;
    en2.Signor_Update__c=false;
    en2.Structure__c='Manager-managed';
     insert en2;
    
    Entities__c en=new Entities__c();
    en.Primary_Client__c=acc.id;
    en.Name='Base Entity';
    en.RecordTypeId='012U0000000DE8m';
    en.Organization_State_1__c= '';
    en.Organization_State__c='Georgia';
     en.Structure__c='Manager-managed';
        en.Trust_Member_2__c=tr.id;
    en.Signor_Update__c=false;
    en.Managing_Entity__c=en2.id;
      insert  en;
     
     enList =[select id,Name,Trust_Member_1__c ,Organization_State_1__c,Organization_State_2__c,Organization_State_3__c,Organization_State_4__c,Signor_Update__c ,Trust_Member_1__r.First_Trustee_Name__c,Trust_Member_2__r.First_Trustee_Name__c,Trust_Member_3__r.First_Trustee_Name__c,Trust_Member_4__r.First_Trustee_Name__c,Trust_Member_2__c,Trust_Member_3__c,Trust_Member_4__c,
                          Signor_Title_1__c,Signor_Title_2__c,Signor_Title_3__c,Signor_Title_4__c from Entities__c];
     
          Map<Id, Entities__c> mapFromList = new Map<Id, Entities__c>(enList);    
     list<Entities__c> Uplist=new  list<Entities__c>();  
    	
    
For ( Entities__c Testet:[select id,Name,Trust_Member_1__c ,Organization_State_1__c,Organization_State_2__c,Organization_State_3__c,Organization_State_4__c,Signor_Update__c ,Trust_Member_1__r.First_Trustee_Name__c,Trust_Member_2__r.First_Trustee_Name__c,Trust_Member_3__r.First_Trustee_Name__c,Trust_Member_4__r.First_Trustee_Name__c,Trust_Member_2__c,Trust_Member_3__c,Trust_Member_4__c,
                          Signor_Title_1__c,Signor_Title_2__c,Signor_Title_3__c,Signor_Title_4__c from Entities__c where ID IN : enList ]) 
                   
                            {
                                
                       Testet.Signor_Update__c   =true; 
                          Testet.Trust_Member_1__c=tr.id;
                           Testet.Trust_Member_2__c=tr.id;
                            Testet.Trust_Member_3__c=tr.id;
                             Testet.Trust_Member_4__c=tr.id;                                   
                             Uplist.add(Testet);
                                system.debug('Uplist'+ Uplist);
                          }


     update Uplist;       
    					  
       try {
           system.debug('>>>enList>>'+enList);
           system.debug('>>>mapFromList>>'+mapFromList);
           system.debug('>>>Uplist>>'+Uplist);
    TrustBinder.updateTrustMember(Uplist,mapFromList );
    
    }  catch (Exception e) { System.debug('Exception occured during TrustBinder: ' + e); } 
                                                    }
}
}