objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Will hold last name of an entity.</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <recordTypes>
        <fullName>Corporation</fullName>
        <active>true</active>
        <description>Corporation</description>
        <label>Corporation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sale_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Anderson Services</fullName>
                </value>
                <value>
                    <fullName>Annual List</fullName>
                </value>
                <value>
                    <fullName>BK Consult</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping - Misc</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Tax Form</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Virtual</fullName>
                </value>
                <value>
                    <fullName>Certified Copy</fullName>
                </value>
                <value>
                    <fullName>Charitable Registration</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Corp Formation</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Deed</fullName>
                </value>
                <value>
                    <fullName>Dissolution</fullName>
                </value>
                <value>
                    <fullName>Doc Drafting</fullName>
                </value>
                <value>
                    <fullName>Estate</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Foreign Filing</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                </value>
                <value>
                    <fullName>Informational Only</fullName>
                </value>
                <value>
                    <fullName>IRS Form</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>LLC Formation</fullName>
                </value>
                <value>
                    <fullName>LP Formation</fullName>
                </value>
                <value>
                    <fullName>Meeting Minutes</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Formation</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>Pensions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SaleEntity__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Sale Entities</relationshipLabel>
        <relationshipName>Sale_Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Entity__r.Primary_Client__r.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Entity__r.Primary_Client__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sale Entities</relationshipLabel>
        <relationshipName>Sale_Entities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Charitable Remainder Trust</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Deed</fullName>
                </value>
                <value>
                    <fullName>Irrevocable Life Insurance Trust</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company (LLC)</fullName>
                </value>
                <value>
                    <fullName>Limited Partnership (LP)</fullName>
                </value>
                <value>
                    <fullName>Living Trust</fullName>
                </value>
                <value>
                    <fullName>Nominee Other</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Entity</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pension Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sale Entity</label>
    <nameField>
        <label>Sale Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/unlimitedNomineeWYNVTest.cls
@isTest
public class unlimitedNomineeWYNVTest {
    
    public static String CRON_EXP = '0 0 0 1 1 ? 2024';
    
    static testmethod void testScheduledJob() {
        Test.startTest();
        
        List<Opportunity> opplist = new List<Opportunity>();
        List<SaleEntity__c> saleEnts = new List<SaleEntity__c>();
        Campaign camp = new Campaign(Name = 'Test Campaign', IsActive = TRUE);
        
        Account a = new Account(
            Name = 'Test',
            First_Name__c = 'Test', 
            Last_Name__c = 'AccountA');
        insert a;
        
        Opportunity CAP = new Opportunity();
        CAP.Name = 'Corporate Assistance Program Renewal';
        CAP.StageName = 'Qualification';
        CAP.CloseDate = Date.today().addDays(7);
        CAP.Amount = 1092;
        CAP.AccountId = a.Id;
        CAP.Sale_Campaign__c = camp.Id;
        CAP.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Renewal').getRecordTypeId();
        CAP.Pricebook2Id = Test.getStandardPricebookId();
        oppList.add(CAP);
        
        Opportunity NOM = new Opportunity();
        NOM.Name = 'WY Nom';
        NOM.StageName = 'Qualification';
        NOM.CloseDate = Date.today().addDays(7);
        NOM.Amount = 500;
        NOM.AccountId = a.Id;
        NOM.Sale_Campaign__c = camp.Id;
        NOM.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('State Renewal').getRecordTypeId();
        NOM.Pricebook2Id = Test.getStandardPricebookId();
        oppList.add(NOM);
        insert oppList;
        
        Entities__c entity = new Entities__c(
            Organization_State__c = 'Wyoming',
            Name = 'Test Entity');
        insert entity;
        
        SaleEntity__c se = new SaleEntity__c(
            Opportunity__c = CAP.Id,
            Entity__c = entity.Id,
            Type__c = 'Corporation'
        );
        saleEnts.add(se);
        
        SaleEntity__c se2 = new SaleEntity__c(
            Opportunity__c = NOM.Id,
            Entity__c = entity.Id,
            Type__c = 'Corporation'
        );
        saleEnts.add(se2);
        insert saleEnts;
        
        Product2 p = new Product2(
            Name = 'Nominee Service Annual Renewal',
            Service_Fulfillment_Weight__c = '1',
            Type__c = 'LAW',
            IsActive = TRUE,
            Subscription_Product__c = TRUE
        );
        insert p;
        
        PricebookEntry pe = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = p.Id,
            UnitPrice = 500,
            IsActive = TRUE);
        insert pe;
        
        OpportunityLineItem li = new OpportunityLineItem(
            OpportunityId = NOM.Id,
            Product2Id = p.Id,
            PricebookEntryId = pe.Id,
            UnitPrice = 500,
            Quantity = 1);
        insert li;
        
        
        
        unlimitedNomineeWYNV sh1 = new unlimitedNomineeWYNV();
        String jobId = system.schedule('Test unlimitedNomineeWYNV class', CRON_EXP, sh1);
        
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id =:jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        System.assertEquals('2024-01-01 00:00:00', string.valueof(ct.NextFireTime));
        
        Test.stopTest();
        
    }
}