objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ChargentBase__Gateway__c.object
<CustomObject>
    <description>Configuration object. The administrator should create ONE account for the appropriate payment gateway.</description>
    <fields>
        <fullName>ChargentBase__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Available_Payment_Methods__c</fullName>
        <inlineHelpText>In Payment Console this field controls which Payment Methods are available to users.</inlineHelpText>
        <label>Available Payment Methods</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>eCheck</fullName>
                </value>
                <value>
                    <fullName>Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>Cash Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentBase__Default_Payment_Method_for_PC__c</fullName>
        <label>Default Payment Method for PC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                    <default>true</default>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>eCheck</fullName>
                </value>
                <value>
                    <fullName>Bank Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ChargentSFA__Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Gateway_Date__c</fullName>
        <label>Gateway Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Response_Status__c</fullName>
        <label>Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Response__c</fullName>
        <label>Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Charge</fullName>
                    <default>true</default>
                    <label>Charge</label>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>ChargentSFA__Opportunity__r.Account.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>ChargentSFA__Opportunity__r.Account.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Detail</relationshipLabel>
        <relationshipName>Credit_Card_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>AMEX: first digit = 3, second digit = 4 or 7. Valid length: 15 digits.
VISA: first digit = 4. Valid length: 13 or 16 digits.
MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</description>
        <inlineHelpText>AMEX: first digit = 3, second digit = 4 or 7.  Valid length: 15 digits.

VISA: first digit = 4.  Valid length: 13 or 16 digits.

MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</inlineHelpText>
        <label>Card Number</label>
        <length>19</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <description>American Express cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</description>
        <inlineHelpText>AMEX cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</inlineHelpText>
        <label>Card Security Code</label>
        <length>5</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Platinum_Subscription_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if uses for platinum payment.</inlineHelpText>
        <label>Platinum Subscription Card</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card Detail</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <label>Card Security</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Number__c</fullName>
        <inlineHelpText>Please enter the complete credit card number without spaces or dashes</inlineHelpText>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>QB_Invoice_Number__c</fullName>
        <displayFormat>{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </fields>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Call</fullName>
        <active>true</active>
        <description>Used for Calls.</description>
        <label>Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <description>Tax Task</description>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ChargeTest.cls
@isTest
public class ChargeTest {
    
    @testSetup
    static void dataSetup() {
        Account acctest = new Account(
            Name='Test Account1',
            First_Name__c='Edward',
            Last_Name__c='Lee'
           );
        insert acctest;
        Credit_Card_Detail__c  ccd = new Credit_Card_Detail__c ();
        ccd.Account__c = acctest.Id;
        ccd.Card_Month__c = '04';
        ccd.Card_Number__c = '1234567896541236';
        ccd.Card_Security__c = '777';
        ccd.Card_Type__c = 'visa';
        ccd.Card_Year__c = '2020'; 
        ccd.Platinum_Subscription_Card__c = true;
        insert ccd;
        ChargentBase__Gateway__c cb = new ChargentBase__Gateway__c ();
        cb.Name = 'AuthorizeNetTestPayment';
        cb.ChargentBase__Active__c = true;
        cb.ChargentBase__Available_Payment_Methods__c = 'Credit Card';
        //cb.ChargentBase__Default_Payment_Method_for_PC__c = 'Credit Card';
        insert cb;
        /*ChargentBase__Gateway__c cbb = new ChargentBase__Gateway__c ();
        cbb.Name = 'Platinum';
        cbb.ChargentBase__Active__c = true;
        cb.ChargentBase__Available_Payment_Methods__c = 'Credit Card';
        insert cbb;*/
        String cardnumberVal= '123456789654';
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Closed Won';
        opp.AccountId = acctest.Id;
        opp.CloseDate = Date.newInstance(2018, 09, 1);
        opp.Amount=0.01;
   
        //opp.QB_Invoice_Number__c = '1234';
        opp.ChargentSFA__Card_Number__c = cardnumberVal;
        insert opp;
          ChargentSFA__Transaction__c trans = new ChargentSFA__Transaction__c();
        trans.ChargentSFA__Type__c = 'Charge';
        trans.ChargentSFA__Response_Status__c = 'Success';
        trans.ChargentSFA__Amount__c = 35;
        trans.ChargentSFA__Gateway_Date__c=Date.newInstance(2020, 11, 10);
         trans.ChargentSFA__Response__c='Approved';
        trans.ChargentSFA__Opportunity__c=opp.id;
        insert trans;
        
        Opportunity opp2 = new Opportunity();
        opp2.Name = 'Testing';
        opp2.StageName = 'Closed Won';
        opp2.AccountId = acctest.Id;
        opp2.CloseDate = Date.newInstance(2018, 09, 10);
        //opp.QB_Invoice_Number__c = '12345';
        opp.ChargentSFA__Card_Number__c = cardnumberVal;
        insert opp2;
        
        ChargentSFA__Transaction__c obj = new ChargentSFA__Transaction__c();
        obj.ChargentSFA__Type__c = 'Charge';
        obj.ChargentSFA__Response_Status__c = 'Success';
        obj.ChargentSFA__Amount__c = 100;
        obj.ChargentSFA__Opportunity__c=opp2.id;
        obj.ChargentSFA__Response__c='Approved';
         obj.ChargentSFA__Gateway_Date__c=Date.newInstance(2020, 11, 10);
        insert obj;
        
        Task tsk=new Task();
        tsk.WhatId = acctest.id;
        tsk.Subject = 'Tax Payment Received';
        tsk.Status = 'open';
        tsk.Priority = 'Normal';
        insert tsk;
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Task' AND Name = 'Call'];
    }
    static testMethod void testCharge() {
        Account acc = [ SELECT Id FROM Account LIMIT 1 ];
        Opportunity opp=[select id,RecordTypeId from Opportunity LIMIT 1];
        RecordType rId = [SELECT Id, Name FROM RecordType where Id = :opp.RecordTypeId LIMIT 1];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();              
        req.requestURI = '/services/apexrest/Charge/' + opp.Id;
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        String ch = ChargeAPI.Charge();    
            
    }
      static testMethod void testChargePlatinumReinstatementAPI() {
        Account acc = [ SELECT Id FROM Account LIMIT 1 ];
        Opportunity opp=[select id,RecordTypeId from Opportunity LIMIT 1];
        RecordType rId = [SELECT Id, Name FROM RecordType where Id = :opp.RecordTypeId LIMIT 1];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();              
        req.requestURI = '/services/apexrest/ChargePlatinumReinstatement/' + opp.Id;
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        String ch = ChargePlatinumReinstatementAPI.ChargePlatinumReinstatement();    
            
    }
}