objects/Account.object
<CustomObject>
    <fields>
        <fullName>Accounting_Coordinators__c</fullName>
        <label>Client Tax Coordinator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alex Price</fullName>
                </value>
                <value>
                    <fullName>Alicefaye Camper</fullName>
                </value>
                <value>
                    <fullName>Andrew Grigsby</fullName>
                </value>
                <value>
                    <fullName>Andy Romero</fullName>
                    <isActive>false</isActive>
                    <label>Andy Romero</label>
                </value>
                <value>
                    <fullName>Angelica Nance</fullName>
                    <isActive>false</isActive>
                    <label>Angelica Nance</label>
                </value>
                <value>
                    <fullName>Anthony Espada</fullName>
                </value>
                <value>
                    <fullName>Ashley Silafau-Sanitoa</fullName>
                    <isActive>false</isActive>
                    <label>Ashley Silafau-Sanitoa</label>
                </value>
                <value>
                    <fullName>Azia Brown</fullName>
                    <isActive>false</isActive>
                    <label>Azia Brown</label>
                </value>
                <value>
                    <fullName>Brina DeLeon</fullName>
                </value>
                <value>
                    <fullName>Candy Adauto</fullName>
                    <isActive>false</isActive>
                    <label>Candy Adauto</label>
                </value>
                <value>
                    <fullName>Carisma James</fullName>
                </value>
                <value>
                    <fullName>Carly McClean</fullName>
                    <isActive>false</isActive>
                    <label>Carly McClean</label>
                </value>
                <value>
                    <fullName>Chloe Freeman</fullName>
                </value>
                <value>
                    <fullName>Christos Zattas</fullName>
                </value>
                <value>
                    <fullName>Corbin Roache</fullName>
                </value>
                <value>
                    <fullName>Erica Kelly</fullName>
                    <isActive>false</isActive>
                    <label>Erica Kelly</label>
                </value>
                <value>
                    <fullName>Eric Harding</fullName>
                    <isActive>false</isActive>
                    <label>Eric Harding</label>
                </value>
                <value>
                    <fullName>Freddi Mitchell</fullName>
                </value>
                <value>
                    <fullName>Gatsby Darwin</fullName>
                    <isActive>false</isActive>
                    <label>Gatsby Darwin</label>
                </value>
                <value>
                    <fullName>Holly Hartman</fullName>
                </value>
                <value>
                    <fullName>Jazmine Gonzalez</fullName>
                    <isActive>false</isActive>
                    <label>Jazmine Gonzalez</label>
                </value>
                <value>
                    <fullName>Julianna Jones</fullName>
                    <isActive>false</isActive>
                    <label>Julianna Jones</label>
                </value>
                <value>
                    <fullName>Kaitlyn Scrivener</fullName>
                </value>
                <value>
                    <fullName>Kelly Andrews</fullName>
                </value>
                <value>
                    <fullName>Marissa Yadao</fullName>
                </value>
                <value>
                    <fullName>Megan Harris</fullName>
                </value>
                <value>
                    <fullName>Micah Wyllie</fullName>
                </value>
                <value>
                    <fullName>Michael Kemp</fullName>
                    <isActive>false</isActive>
                    <label>Michael Kemp</label>
                </value>
                <value>
                    <fullName>Olga Kochubey</fullName>
                    <isActive>false</isActive>
                    <label>Olga Kochubey</label>
                </value>
                <value>
                    <fullName>Paul Scarnechia</fullName>
                    <isActive>false</isActive>
                    <label>Paul Scarnechia</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ChargentSFA__Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Response_Message__c</fullName>
        <label>Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Response_Status__c</fullName>
        <label>Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>ChargentSFA__Opportunity__r.Account.Name</formula>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Tax_Compliance</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <description>Tax Compliance</description>
        <label>Tax Compliance</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Call</fullName>
        <active>true</active>
        <description>Used for Calls.</description>
        <label>Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <description>Tax Task</description>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ChargeAPI.cls
/** A Rest webservice class is used to make the payment.
* @author Sharukh khan
* @version 1.0 - apr 20, 2020
*/

@RestResource(urlmapping='/Charge/*')
global class ChargeAPI {
    
    @HttpGet
    global static String Charge()
    {
        RestResponse res=RestContext.response;
        RestRequest req=RestContext.request;
        String opportunityId=req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        system.debug('opportunityId:'+opportunityId);
        String accountingCoordinator = '';
        Map<String,string> tranMap=new Map<String,string>();
        Final String Tax_Compliance = 'Tax Compliance';
        Final String Task_Subject = 'Tax Payment Received';
        Final String Kambria = 'Kambria Stephen';
        Final String Approved = 'Approved';
        boolean trans_approved = False;
        String transactionId;
        String transactionStatus;
        String transactionMsg;
        Decimal transactionAmount;
        try
        {  
            Opportunity opp = [SELECT Id, RecordTypeId,RecordType.Name, Name, AccountId, Account.Name, Account.Accounting_Coordinators__c, Account.OwnerId FROM Opportunity where Id = :opportunityId Limit 1];
            system.debug('Lstopp'+Opp.AccountId);
            RecordType tskRecTyp = [SELECT Id, Name, Description, IsActive, SobjectType FROM RecordType where Name = 'Call' and SobjectType = 'Task' LIMIT 1];
            if(opp.Account.Accounting_Coordinators__c != null && opp.Account.Accounting_Coordinators__c != ''){
                accountingCoordinator = opp.Account.Accounting_Coordinators__c;
            }
            else {
                accountingCoordinator = Kambria;
            }
            
            ChargentSFA.TChargentOperations.TChargentResult result= ChargentSFA.TChargentOperations.ChargeOpportunity_click(opportunityId); 
            system.debug('=== Billing Result ===' + result);
            ChargentSFA__Transaction__c transLog = [Select Id,Name,ChargentSFA__Response_Status__c,ChargentSFA__Response_Message__c,ChargentSFA__Opportunity__c,ChargentSFA__Amount__c,Client__c  from ChargentSFA__Transaction__c where ChargentSFA__Opportunity__c = :opportunityId Order By CreatedDate Desc Limit 1];
            system.debug('=== transLog.size() ===' + transLog);
            if(transLog != Null) {         
                if(transLog.ChargentSFA__Response_Status__c == Approved){
                    trans_approved = True;
                }
                transactionId = transLog.Name;
                transactionStatus = transLog.ChargentSFA__Response_Status__c;
                transactionMsg = transLog.ChargentSFA__Response_Message__c;
                transactionAmount = transLog.ChargentSFA__Amount__c;
                                
                if((trans_approved && opp.RecordType.Name == Tax_Compliance) || Test.isRunningTest()){
                    Id usr = [Select Id,Name from User where Name = :accountingCoordinator].Id; 
                    system.debug('creating task == ');
                    Task tsk = new Task();
                    tsk.WhatId = opp.AccountId;
                    tsk.RecordTypeId = tskRecTyp.Id;
                    tsk.Subject = Task_Subject;
                    tsk.OwnerId = usr;
                    tsk.Date_Due__c = Date.today().addDays(1);
                    tsk.Status = 'open';
                    tsk.Priority = 'Normal';
                    try{
                    	insert tsk;
                    }
                    catch(DMLException e){
                        system.debug('The following exception has occurred: ' + e.getMessage());
                    }
                }
                
                tranMap.put('ID',transactionId);
                tranMap.put('Status',transactionStatus);
                tranMap.put('Amount',String.valueOf(transactionAmount));
                tranMap.put('Message',transactionMsg);
                system.debug('tranMap=='+tranMap);
                string jsonstring = JSON.serialize(tranMap);
                system.debug('jsonstring=='+jsonstring);
                return jsonstring;
            }  
            else {
                return null;
            }
            
        }
        catch(Exception e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
            return null;
        }  
    }
    
}