objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Clients</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ClientReferralCampaign</relationshipLabel>
        <relationshipName>ClientReferralCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities (Account)</relationshipLabel>
        <relationshipName>Entities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organizational_Date__c</fullName>
        <label>Organizational Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CampBatchActiveNonprofitClientsTest.cls
@istest
public class CampBatchActiveNonprofitClientsTest {
    
    @testSetup 
    static void setup() {
        
        // insert Campaign
        Campaign camp=new Campaign(name='Active Nonprofit Clients', isActive=true);
        
        insert camp;
        
        //Insert Account
        List<Account> acLst= new List<Account>();
        for(Integer i=0;i<9;i++){
          Account ac= new Account();
          ac.Name='testaccount'+i;
          acLst.add(ac);
        }
        insert acLst;
        
        List<Contact> ctLst=new List<Contact>();
        for(Integer i=0;i<7;i++){
          Contact ct=new contact();
          ct.LastName='testcontact' + i;
          ct.Account_Roles__c = 'Primary Contact'; 
          ct.AccountId=acLst.get(i).Id;
          ctLst.add( ct );
        }

        insert ctLst;

        List<Contact> nonPrimary=new List<Contact>();
        for(Integer i=7;i<9;i++){
          Contact ct=new contact();
          ct.LastName='testcontact' + i;
          ct.AccountId=acLst.get(i).Id;
          nonPrimary.add( ct );
        }

        insert nonPrimary;

        list<Entities__c> etlist =new LIST<Entities__c>();
        for(Integer i=0;i<9;i++){
          Entities__c et=new Entities__c();
          et.Name='testentity'+i;
          et.Primary_Client__c=acLst.get(i).Id;
          et.Organizational_Date__c=system.today();
          et.Organization_State__c='Alabama';
          et.RecordTypeId=Schema.SobjectType.Entities__c.getRecordTypeInfosByName().get('Non-Profit Entity').getRecordTypeId();
          et.Status__c='Active';
          etlist.add(et);
        }
        insert etlist;

        /**
         * Insert old members to campaign
         */

        list<CampaignMember> cmpMembers= new list<CampaignMember>();
        for(Integer i=0;i<5;i++){
          cmpMembers.add(new CampaignMember( 
            CampaignId=camp.id,
            Account__c  = acLst.get(i).Id,
            ContactId=ctLst.get(i).Id
          ));
        }
        insert cmpMembers;

    }
    static testmethod void test() {    
        Test.startTest();
          CampBatchANCSchedular c = new CampBatchANCSchedular();
          c.execute(null);

          Campaign cmpT = ( [Select Id, Name From Campaign Where Name = 'Active Nonprofit Clients' AND IsActive = true Limit 1].size() > 0 ) ?
          [Select Id, Name From Campaign Where Name = 'Active Nonprofit Clients' AND IsActive = true Limit 1] : 
          null;
          String query = 'Select Id, Name, Account__c From CampaignMember Where CampaignId = \'' + cmpT.Id+'\'';

          Entities__c entOld= [Select Id, Name, Status__c From Entities__c Limit 1];
          entOld.Status__c = 'Inactive';
          Update entOld;
          Id deleteJob = Database.executeBatch(new DeleteCampBatchActiveNonprofitClients(query),200);
          
          Entities__c entNew= [Select Id, Name, Status__c From Entities__c Where Id !=: entOld.Id  Limit 1];
          entNew.Status__c = 'Inactive';
          Update entNew;
        
          System.schedule('DeleteCampBatchActiveNonprofitClients Test', '0 00 05 ? * 2',  new DeleteCampBatchActiveNonprofitClients() );
          
        Test.stopTest();

        List<CronTrigger> ctDel = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name = 'DeleteCampBatchActiveNonprofitClients Test'];

        System.assert( deleteJob != null, 'Delete batch did not run');
        System.assert( ctDel.size() > 0, 'Delete Job is not scheduled');
    }
}