objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Clients</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ClientReferralCampaign</relationshipLabel>
        <relationshipName>ClientReferralCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities (Account)</relationshipLabel>
        <relationshipName>Entities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When this entity is not owned by the primary client listed above, select a contact from this Client&apos;s account page who is the owner, and put their name here.</inlineHelpText>
        <label>Business Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dissolution_Date__c</fullName>
        <label>Dissolution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organizational_Date__c</fullName>
        <label>Organizational Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subscriptions_Entities__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipName>Entities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Platinum Subscriptions  Entities</label>
    <nameField>
        <label>Deals &amp; Entities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platinum Subscriptions  Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CampBatchActiveNonprofitClients.cls
global class CampBatchActiveNonprofitClients implements Database.Batchable<sObject>, Database.Stateful {
    private string query;
    public List<Campaign> cmpid;
    public List<Contact> newMembers;
    global CampBatchActiveNonprofitClients(string query){
        this.query=query;
        this.cmpid = ( [Select Id, Name From Campaign Where Name = 'Active Nonprofit Clients' AND IsActive = true Limit 1].size() > 0 ) ?
        [Select Id From Campaign Where Name = 'Active Nonprofit Clients' AND IsActive = true Limit 1] : 
        null;
        newMembers = new List<Contact>();
    }
    
    global database.QueryLocator start(Database.BatchableContext BC){
        return database.getQueryLocator(query);
    }
    global void execute( Database.BatchableContext bc, List<Account> mainList ){
        
        list<Id> acids= new list<Id>(); 
        Set<Contact> lstcontact=new Set<Contact>();
        
        if( this.cmpid.size() > 0  ) {
            Map<Id, CampaignMember> oldMemMap = new Map<Id, CampaignMember>(); 
            for( CampaignMember oldMembers : [Select ContactId From CampaignMember Where CampaignId =: cmpid.get(0).Id ]) {
                oldMemMap.put( oldMembers.ContactId, oldMembers );
            }

            for( Account ietrator : mainList ) {
                Boolean addContact = false;
                for ( Entities__c entity : ietrator.Entities__r ) {
                    /**
                     * Verify that all entities lie under the same condition
                     */
                    if ( 
                        entity.Organizational_Date__c != null && 
                        entity.Organization_State__c != null && 
                        entity.Dissolution_Date__c == null && 
                        entity.RecordType.name == 'Non-Profit Entity' && 
                        entity.Status__c !='Inactive' && 
                        entity.Status__c !='Terminated' && 
                        entity.Status__c !='Future Planned' && 
                        entity.Status__c !='Missing Information' && 
                        entity.Status__c !='Expedited' && 
                        entity.Status__c !='Sent To Processing'
                    ){
                        addContact = true;
                        break;
                    }
                }
                
                if( ietrator.Contacts.size() > 0 && addContact == true ) {
                    if( !oldMemMap.containsKey( ietrator.Contacts.get(0).Id ) ) {
                        newMembers.add( ietrator.Contacts );
                    }
                }
                else if( ietrator.Contacts.size() == 0 && addContact == true ) {
                    /**
                     * Get list of contact Ids to fetch non primary contacts
                     */
                    acids.add(ietrator.Id);
                }
            }

            for( Account acc : [ Select Id, ( Select id, Accountid from Contacts Order By LastModifiedDate ASC Limit 1  ) From Account Where Id in: acids  ] ){
                if( acc.Contacts.size() > 0 ){
                    if( !oldMemMap.containsKey( acc.Contacts.get(0).Id ) ){
                        newMembers.add( acc.Contacts );
                    }
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC){
        system.debug('Batch execution completed: ');
        if( newMembers.size() > 0 && cmpid.size() > 0 ) {
            List<CampaignMember> membersList = new List<CampaignMember>();
            for( Contact member : newMembers ) {
                CampaignMember campaignMem = new CampaignMember(
                    Account__c  = member.AccountId,
                    CampaignId  = cmpid.get(0).Id,
                    ContactId   = member.Id,
                    Status      = 'Sent'
                );
                membersList.add(campaignMem);
            }

            if( membersList.size() > 0 ) {
                System.debug('membersList.size: '+ membersList.size() );
                insert membersList;
            }
        }

        /**
         * Scheduleing job for delete
         */
        String hour = String.valueOf(Datetime.now().hour() + 2 );
        String min = String.valueOf(Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second());

        String nextFireTime = ss + ' ' + min + ' ' + hour + ' * * ?';
        System.schedule('DeleteCampBatchActiveNonprofitClients One Time', nextFireTime,  new DeleteCampBatchActiveNonprofitClients() );
    }
    
}