objects/Account.object
<CustomObject>
    <fields>
        <fullName>Teams__c</fullName>
        <description>Team Assigned to Client</description>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Teams</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Using_Teams__c</fullName>
        <label>Using Teams</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Team 1</fullName>
                </value>
                <value>
                    <fullName>Team 3</fullName>
                </value>
                <value>
                    <fullName>Team 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Team 1</fullName>
    </customValue>
    <customValue>
        <fullName>Team 2</fullName>
    </customValue>
    <customValue>
        <fullName>Team 3</fullName>
    </customValue>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Team Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>Team 4</fullName>
    </customValue>
    <customValue>
        <fullName>Team 5</fullName>
    </customValue>
    <customValue>
        <fullName>Team 6</fullName>
    </customValue>
    <customValue>
        <fullName>Team 7</fullName>
    </customValue>
    <customValue>
        <fullName>Temp Team</fullName>
        <isActive>false</isActive>
        <label>Temp Team</label>
    </customValue>
    <description>Teams</description>
    <masterLabel>Teams</masterLabel>
</GlobalValueSet>

classes/FetchPlatinumTeamTest.cls
@isTest
public class FetchPlatinumTeamTest {
    @testsetup
    public static void testData(){
        Account acc = new Account();
        acc.name = 'Test Account';
        acc.Teams__c = 'Team 1';
        acc.Using_Teams__c = 'Yes';
        insert acc;
        Id profId = [select id from profile where name = 'System Administrator' limit 1].id; 
        User u = new User();
        u.FirstName = 'Test';
        u.LastName = 'User';
        u.ProfileId = profId;
        u.Username = 'testUser@teams.com';
        u.email = 'testUser@sf.com';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.Alias = 'tu';
        u.Title = 'Advisor Admin';
        u.Team__c = 'Team 1';
        u.TimeZoneSidKey = 'America/Los_Angeles';  
        u.LocaleSidKey = 'en_US';  
        u.LanguageLocaleKey = 'en_US';
        insert u;
    }
    @isTest
    public static void testFetchUserTeam(){
        Id accId = [select id from Account limit 1].id;
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri ='https://andersonadvisors--octopus.my.salesforce.com/services/apexrest/AccountTeam/'+accId;
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response= res;
        FetchPlatinumTeam.getTeamDetails();
        system.assertEquals(true, true, 'success');
      
    }
    @isTest
    public static void testFetchUserTeamNegative(){
        Account acc = [select id,teams__c from Account limit 1];
        acc.teams__c = 'VIP';
        update acc;
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri ='https://andersonadvisors--octopus.my.salesforce.com/services/apexrest/AccountTeam/'+acc.Id;
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response= res;
        FetchPlatinumTeam.getTeamDetails();
        system.assertEquals(true, true, 'success');
      
    }

}