objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original source of the client.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Admin</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <description>VOD SR-2637: Create Round Robin Case Assignment Rule</description>
        <displayFormat>{0}</displayFormat>
        <label>RR Case Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Made_By_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Made By Automation</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Bookkeeping</businessProcess>
        <description>Used for Bookkeeping Cases</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <businessProcess>Operation Help desk</businessProcess>
        <label>Email</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original Campaign associated with the Contact when converted from a Lead.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Bookkeeping_Admin.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abdur Rehman</fullName>
    </customValue>
    <customValue>
        <fullName>Abraham Carrillo</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Hendershot</fullName>
    </customValue>
    <customValue>
        <fullName>Angela Berrow</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Langer</fullName>
    </customValue>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>awais khan</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Arnold</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Bobby Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Bruce Williams</fullName>
    </customValue>
    <customValue>
        <fullName>Carol Spagnoletta</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Conrad Gomez</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Dawson Phipps</fullName>
    </customValue>
    <customValue>
        <fullName>Doug Guard</fullName>
    </customValue>
    <customValue>
        <fullName>Hebert Romero</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Petrunyak</fullName>
    </customValue>
    <customValue>
        <fullName>Jerome Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Joel Evans</fullName>
    </customValue>
    <customValue>
        <fullName>John Doe</fullName>
    </customValue>
    <customValue>
        <fullName>Jonna States</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Fleming</fullName>
    </customValue>
    <customValue>
        <fullName>Kelly Van Middlesworth</fullName>
    </customValue>
    <customValue>
        <fullName>Kenneth Harrah</fullName>
    </customValue>
    <masterLabel>Bookkeeping Admin</masterLabel>
</GlobalValueSet>

classes/Send_email_to_case_creatorTest.cls
@isTest(SeeAllData = true)
private class Send_email_to_case_creatorTest {
    
    private static testMethod void sendEmailCase(){
        
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, AccountId from User where UserRoleId = :portalRole.Id Limit 1];  
        RecordType rt = [SELECT Id, Name, SobjectType FROM RecordType where name = 'Community Platinum Case' and SobjectType = 'Case'];
        //System.runAs ( thisUser ) {
            Test.StartTest(); 
            Integer cseLstSze = 10;
            Id p = [select id from profile where name='Partner Community User'].id;
            Campaign cmp = new Campaign();
            cmp.Name = 'Steve';
            insert cmp;        
            Account testAccount = new Account();
            testAccount.Name='Test Account' ;
            testAccount.First_Name__c='Edward';
            testAccount.Last_Name__c='Lee'; 
            testAccount.Campaign__c = cmp.Id;
            testAccount.OwnerId = thisUser.Id;
           
            testAccount.Bookkeeper__c = thisUser.Id;
            testAccount.phone='123456782';
            insert testAccount;              
            Contact cont = new Contact ();
            cont.FirstName = 'FirstName';
            cont.LastName = 'LastName';
            cont.Email='email@email.com';
            cont.phone='12345678';
            cont.AccountId=testAccount.Id;
            insert cont;
            Case cse = new Case();
            cse.AccountId = testAccount.Id;
            cse.ContactId = cont.Id;
            cse.Subject = 'Platinum Bookkeeping Question';
            cse.Description = 'Testing Descritpion';
            cse.CreatedDate = system.now();
            cse.Status = 'New';
        cse.Made_By_Automation__c =true;
            cse.OwnerId = thisUser.Id;
            cse.RecordTypeId = rt.Id;
            insert cse;
            String cN = cse.Case_Number__c;        
            CaseComment cc = new CaseComment();
            cc.CommentBody = 'Testing Comment';
            cc.CreatedById = UserInfo.getUserId();
            cc.ParentId = cse.Id;
        	cc.IsPublished = true;
            insert cc; 
        cc.CommentBody='Testing Comment update';
        update cc;
            Test.stopTest();
       // }
        
    }
}