objects/Account.object
<CustomObject>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Events__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will hold the event name and it&apos;s associated price values</description>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Coupon_Name_2__c</fullName>
        <label>Coupon Name 2</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Coupon_Name__c</fullName>
        <label>Coupon Name 1</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Percent_2__c</fullName>
        <label>Discount Percent 2</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <label>Discount Percent 1</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_cost__c</fullName>
        <label>Event cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Events</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Company_Street__c</fullName>
        <label>Billing Company Street</label>
        <length>210</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>210</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_FirstName__c</fullName>
        <label>Billing FirstName</label>
        <length>210</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_LastName__c</fullName>
        <label>Billing LastName</label>
        <length>210</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Postal_Code__c</fullName>
        <label>Billing Postal Code</label>
        <length>210</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Address__c</fullName>
        <label>Billing Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Company__c</fullName>
        <label>Billing Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Email__c</fullName>
        <label>Billing Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Fax__c</fullName>
        <label>Billing Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_First__c</fullName>
        <label>Billing First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Last__c</fullName>
        <label>Billing Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Phone__c</fullName>
        <label>Billing Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Postcode__c</fullName>
        <label>Deprecated (Billing Postcode)</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_State__c</fullName>
        <label>Billing State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Number__c</fullName>
        <inlineHelpText>Please enter the complete credit card number without spaces or dashes</inlineHelpText>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ChargentSFA__Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Count__c</fullName>
        <inlineHelpText>If &quot;Payment Stop&quot; is set to &quot;Count&quot; please enter the number of total payments in the series</inlineHelpText>
        <label>Payment Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_End_Date__c</fullName>
        <label>Payment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Frequency__c</fullName>
        <label>Payment Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Once</fullName>
                    <default>true</default>
                    <label>Once</label>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Bimonthly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                    <default>true</default>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Start_Date__c</fullName>
        <label>Payment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Stopped</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Stop__c</fullName>
        <inlineHelpText>For any payment frequency other than &quot;Once&quot; please choose the date to end the payment series, or the total number of transactions. You can also run the series until the Balance Due is $0 or choose &quot;Unending&quot;.</inlineHelpText>
        <label>Payment Stop</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ChargentSFA__Payment_Frequency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Count</fullName>
                </value>
                <value>
                    <fullName>Balance Due</fullName>
                </value>
                <value>
                    <fullName>Unending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>C-Corporation</fullName>
                </value>
                <value>
                    <fullName>S-Corporation</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>CRT</fullName>
                </value>
                <value>
                    <fullName>GRT</fullName>
                </value>
                <value>
                    <fullName>QPRT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entrity_Name__c</fullName>
        <label>Entrity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TesteventFormExtension.cls
@isTest
private class TesteventFormExtension
{
	@isTest
	static void itShould()
	{

                            Events__c  event=new Events__c ();
                            event.Name='test event';
                            event.Event_cost__c=100;
                            event.Coupon_Name__c='test';
                            event.Coupon_Name_2__c='test1';
                            event.Discount_Percent__c ='10';
                            event.Discount_Percent_2__c='10';
                            event.Campaign_Name__c='test cam';
                            insert event;

                            eventFormExtension efe=new eventFormExtension();

                            Test.setCurrentPage(Page.eventForm);

                            efe.checkCreditCard();

                            efe.opp.ChargentSFA__Card_Number__c=null;

                            List<Apexpages.Message> msgs = ApexPages.getMessages();

                             boolean isErrorMessage = false;


                             for(Apexpages.Message msg : msgs) {
                                      if (msg.getDetail().contains('Please enter a credit card number'))
                                       isErrorMessage  = true;

                            }

                             //Assert that the Page Message was Properly Displayed
                             system.assert(isErrorMessage);




                             efe.opp.Billing_FirstName__c='test first name';

                             efe.opp.Billing_LastName__c='test last name';

                             efe.opp.Billing_Company_Street__c='test street name';

                             efe.opp.Billing_Postal_Code__c='100';

                             efe.opp.Billing_Country__c='India';

                             efe.opp.ChargentSFA__Card_Number__c='1234567891234567';

                              efe.listValue='test event';



                              efe.saveEvent();

                              efe.discount='test';

                              efe.quantity=10;

                              efe.calculatePrice();


                              efe.quantity=1;
                              efe.discount='test1';

                              efe.calculatePrice();


                               efe.discount='test2';

                              efe.calculatePrice();


                                efe.listValue='--None--';

                                efe.calculatePrice();


                                eventFormExtension efe1=new eventFormExtension();








                                efe1.opp.Billing_Company_Street__c=null;

                                efe1.opp.Billing_FirstName__c='test first name';

                                efe1.opp.Billing_LastName__c='test last name';

                                efe1.opp.Billing_Postal_Code__c='100';

                                efe1.opp.Billing_Country__c='India';

                                efe1.opp.ChargentSFA__Card_Number__c='1234567891234567';

                                 efe1.listValue='test event';



                                 efe1.saveEvent();

                                 efe1.discount='test';

                                 efe1.quantity=10;



                                 efe1.calculatePrice();

                                 List<Apexpages.Message> msgs1 = ApexPages.getMessages();

                                  boolean isErrorMessage1 = false;


                                  for(Apexpages.Message msg : msgs1) {
                                           if (msg.getDetail().contains('Please fill Address'))
                                            isErrorMessage1  = true;

                                 }

                                  //Assert that the Page Message was Properly Displayed
                                  system.assert(isErrorMessage1);


                                  //efe1.chargeCredit();


                                  //efe1.transactionStatus='Approved';

                                  //efe1.sendMail();




                                // account acc = new account();
                                // acc.Name = 'test';
                                // acc.E_Mail__c = 'test@test.com';
                                // acc.RecordTypeId = '012U0000000D8qm';
                                // insert acc;


                                //Opportunity opp = new Opportunity();
                                //  opp.Name = 'test';
                                //  opp.AccountId = acc.Id;
                                //  opp.CloseDate = System.today();
                                //  opp.StageName = 'Prospecting';
                                //  opp.Amount = 1079.90;
                                //  opp.Entity_Type__c = 'S-Corporation';
                                //  opp.Entrity_Name__c = 'Test';
                                //  opp.ChargentSFA__Billing_Address__c = 'Test';
                                //  opp.ChargentSFA__Billing_City__c = 'Test';
                                //  opp.ChargentSFA__Billing_Company__c = 'Test';
                                //  opp.ChargentSFA__Billing_Country__c = 'Test';
                                //  opp.ChargentSFA__Billing_State__c = 'test';
                                //  opp.ChargentSFA__Billing_Fax__c = '123456';
                                //  opp.ChargentSFA__Billing_First__c = 'test';
                                //  opp.ChargentSFA__Billing_Last__c = 'test';
                                //  opp.ChargentSFA__Billing_Phone__c = '1234567890';
                                //  opp.ChargentSFA__Billing_Postcode__c = '123456';
                                //  opp.ChargentSFA__Payment_Method__c = 'Credit Card';
                                //  opp.ChargentSFA__Card_Type__c = 'Visa';
                                //  opp.ChargentSFA__Billing_Email__c = 'test@test.com';
                                //  opp.ChargentSFA__Payment_Count__c = 25;
                                //  opp.ChargentSFA__Payment_Start_Date__c = system.today();
                                //  opp.ChargentSFA__Payment_End_Date__c = system.today().adddays(2);
                                //  opp.ChargentSFA__Payment_Stop__c = 'Count';
                                //  opp.ChargentSFA__Payment_Status__c = 'Partial';
                                //  opp.ChargentSFA__Payment_Frequency__c = 'Daily';
                                //  opp.ChargentSFA__Payment_Status__c = 'Recurring';
                                //   insert opp;


                                //  ChargentSFA.TChargentOperations.TChargentResult Charge=ChargentSFA.TChargentOperations.ChargeOpportunity_Click(opp.id);

                                //  efe1.ChargentResult=Charge;


                             //List<Apexpages.Message> msgs1 = ApexPages.getMessages();

                             // boolean isErrorMessage1 = false;


                             // for(Apexpages.Message msg : msgs1) {
                             //          if (msg.getDetail().contains('Please enter a valid credit card number'))
                             //           isErrorMessage1  = true;

                             //}

                             ////Assert that the Page Message was Properly Displayed
                             //system.assert(isErrorMessage1);

                             //  efe.checkCreditCard();




	}
}