objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Blueprint__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Blueprint</label>
    <nameField>
        <label>Blueprint_Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blueprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BlueprintTest.cls
@isTest
public class BlueprintTest {
    @testSetup
    static void dataSetup() {
        Account acctest = new Account(
            Name='Test Account',
            First_Name__c='Edward',
            Last_Name__c='Lee'
            );
        insert acctest;
         Attachment a= new Attachment();         
        a.ParentId = acctest.Id;
        a.Name = 'editBlueprint.png';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        a.Body=bodyBlob;
        insert a;
        Blueprint__c bp = new Blueprint__c();         
        bp.Name = 'test.png';
        bp.AccountId__c = acctest.Id;
        bp.AttachmentId__c = a.Id;
        insert bp;
    }
    static testMethod void testGet() {
        Account acc = [ SELECT Id FROM Account LIMIT 1 ];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
        req.requestURI = '/services/apexrest/BlueprintAttachement/' + acc.Id;
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
       List<string> blueprintstr = BlueprintAPI.getAttachement();        
    }
   
}