objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <inlineHelpText>How is budgeting done for this project?</inlineHelpText>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No budget</fullName>
                    <default>true</default>
                    <label>No budget</label>
                </value>
                <value>
                    <fullName>Total project hours</fullName>
                </value>
                <value>
                    <fullName>Total project fees</fullName>
                </value>
                <value>
                    <fullName>Hours per task</fullName>
                </value>
                <value>
                    <fullName>Hours per person</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bookkeepings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Set_of_Books__c</fullName>
        <label>Set of Books</label>
        <referenceTo>Set_of_Books__c</referenceTo>
        <relationshipLabel>Entity Bookkeeping Records</relationshipLabel>
        <relationshipName>Bookkeeping_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/H2S__HarvestProject__c.object
<CustomObject>
    <description>HarvestSync for Salesforce - Project object used by the HarvestSync for Salesforce system integration when client does not already have a custom object for managing projects.</description>
    <fields>
        <fullName>H2S__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>H2S__Budget__c</fullName>
        <inlineHelpText>How is budgeting done for this project?</inlineHelpText>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No budget</fullName>
                </value>
                <value>
                    <fullName>Total project hours</fullName>
                </value>
                <value>
                    <fullName>Total project fees</fullName>
                </value>
                <value>
                    <fullName>Hours per task</fullName>
                </value>
                <value>
                    <fullName>Hours per person</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>H2S__InvoiceMethod__c</fullName>
        <label>Invoice Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>This project is not billable</fullName>
                </value>
                <value>
                    <fullName>This project is billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>H2S__SyncStatus__c</fullName>
        <inlineHelpText>Indicates the status of pairing the salesforce.co HarvestProject record to an associated Project record in Harvest.</inlineHelpText>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Status Unknown</fullName>
                    <default>true</default>
                    <label>Status Unknown</label>
                </value>
                <value>
                    <fullName>Harvest Project Linked</fullName>
                </value>
                <value>
                    <fullName>Harvest Project Not Found</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>H2S__TotalProjectHours__c</fullName>
        <inlineHelpText>If this project is budgeted by hours, what is the budget in hours for the project.  Leave blank otherwise.</inlineHelpText>
        <label>Total Project Hours</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Set_of_Books__c.object
<CustomObject>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Set of Books</label>
    <nameField>
        <label>Set of Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Set of Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax__c.object
<CustomObject>
    <description>Object for the Tax Team</description>
    <fields>
        <fullName>Budget__c</fullName>
        <inlineHelpText>How is budgeting done for this project?</inlineHelpText>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No budget</fullName>
                    <default>true</default>
                    <label>No budget</label>
                </value>
                <value>
                    <fullName>Total project hours</fullName>
                </value>
                <value>
                    <fullName>Total project fees</fullName>
                </value>
                <value>
                    <fullName>Hours per task</fullName>
                </value>
                <value>
                    <fullName>Hours per person</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Taxes</relationshipLabel>
        <relationshipName>Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateInformationOnTaxAndBookkeepingTest.cls
/**
* @author            :Chetu India Developer Team
* @Created date      :6/05/2018
* @Last Modified By  :Chetu India Team
* @Last Modified Date:05/19/2018 
* @Description       :This Class is used to test the Code Cover of UpdateInfomationOnTaxBookkeeping trigger.
**/
@IsTest
Public class UpdateInformationOnTaxAndBookkeepingTest {
    
               //test method to test the code coverage..
    public static testMethod  void testocc(){
             
        Account testAccount = new Account();//Insert Account
        testAccount.Name='Test Account' ;
        testAccount.First_Name__c='test1'; 
        testAccount.Last_Name__c ='testAccount';
        insert testAccount;  
        //create the harvestproject object..
        H2S__HarvestProject__c  HP = new H2S__HarvestProject__c(); // insert Project      
        //set all the required field..
        HP.name = 'Test project';
        HP.H2S__Account__c = testAccount.id;
        HP.H2S__Budget__c = 'Total project hours';
        HP.H2S__SyncStatus__c ='Harvest Project Not Found';	
        HP.H2S__InvoiceMethod__c ='This project is billable';
        HP.H2S__TotalProjectHours__c = 4000;
        //create the tax object..
        Tax__c tax = new Tax__c();
        //set all the required field..
        tax.Name =  'test';
        tax.Client_Name__c = testAccount.id;
        tax.Budget__c = 'Total project fees';
        //insert the tax object..
        insert tax;
        Set_of_Books__c sob=new Set_of_Books__c();
        sob.name='2020 set';
        sob.Client__c=testAccount.id;
        insert sob;
        //create the bookkeeping object..
        Bookkeeping__c bk = new Bookkeeping__c();
        //set all the required field..
        bk.Name = 'test';
        bk.Client_Name__c = testAccount.id;
        bk.Set_of_Books__c=sob.id;
        //insert bookkeeping..
        insert bk;
         //insert harvestproject..
        insert HP;
      
      
    }

}