objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Clients</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ClientReferralCampaign</relationshipLabel>
        <relationshipName>ClientReferralCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <description>Used with LearnDash and the Platinum website to provide course access.</description>
        <inlineHelpText>Used with LearnDash and the Platinum website to provide course access.</inlineHelpText>
        <label>Service Item List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/H2S__HarvestProject__c.object
<CustomObject>
    <description>HarvestSync for Salesforce - Project object used by the HarvestSync for Salesforce system integration when client does not already have a custom object for managing projects.</description>
    <fields>
        <fullName>Bookkeeper_Assigned__c</fullName>
        <description>Links to Case, congruently updates.</description>
        <label>Bookkeeper Assigned</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Donna Hill</fullName>
                </value>
                <value>
                    <fullName>John Loncar</fullName>
                </value>
                <value>
                    <fullName>Justin Claus</fullName>
                </value>
                <value>
                    <fullName>Marie Galligan</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Sara Winter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper_Time__c</fullName>
        <label>Bookkeeper Time</label>
        <summarizedField>H2S__HarvestTimeEntry__c.H2S__Duration__c</summarizedField>
        <summaryFilterItems>
            <field>H2S__HarvestTimeEntry__c.H2S__Task_Type__c</field>
            <operation>contains</operation>
            <value>Bookkeep</value>
        </summaryFilterItems>
        <summaryForeignKey>H2S__HarvestTimeEntry__c.H2S__HarvestProject__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>H2S__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>H2S__Budget__c</fullName>
        <inlineHelpText>How is budgeting done for this project?</inlineHelpText>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No budget</fullName>
                </value>
                <value>
                    <fullName>Total project hours</fullName>
                </value>
                <value>
                    <fullName>Total project fees</fullName>
                </value>
                <value>
                    <fullName>Hours per task</fullName>
                </value>
                <value>
                    <fullName>Hours per person</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>H2S__ClientProjectManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact record who is serving as our point-contact at the Client for this project.</inlineHelpText>
        <label>Client Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>H2S__InvoiceMethod__c</fullName>
        <label>Invoice Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>This project is not billable</fullName>
                </value>
                <value>
                    <fullName>This project is billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>H2S__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Time_Entry_Date__c</fullName>
        <description>Max date on Time Entry object</description>
        <label>Max Time Entry Date</label>
        <summarizedField>H2S__HarvestTimeEntry__c.H2S__Date__c</summarizedField>
        <summaryForeignKey>H2S__HarvestTimeEntry__c.H2S__HarvestProject__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/H2S__HarvestTimeEntry__c.object
<CustomObject>
    <description>HarvestSync for Salesforce - Time entries mirrored from Harvest using HarvestSync for Salesforce.</description>
    <fields>
        <fullName>H2S__Date__c</fullName>
        <inlineHelpText>Date of time entry if tracking time by duration vs. start and end time.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>H2S__EndTime__c</fullName>
        <inlineHelpText>If time is tracked by start and end time vs. duration, this is the end time.</inlineHelpText>
        <label>EndTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>H2S__HarvestProject__c</fullName>
        <inlineHelpText>Project time is related to.</inlineHelpText>
        <label>HarvestProject</label>
        <referenceTo>H2S__HarvestProject__c</referenceTo>
        <relationshipName>HarvestTimeCards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>H2S__StartTime__c</fullName>
        <inlineHelpText>If time is tracked by start and end time vs. duration, this is the start time.</inlineHelpText>
        <label>StartTime</label>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{YYYY}-{MM}-{0}</displayFormat>
        <label>Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <label>Service Item List</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AddMembersToCampaignDailyBatchTest.cls
@isTest
public class AddMembersToCampaignDailyBatchTest {
    @testSetup
    static void setup()
    { 
        try{
            Account firstAcc = null;
            List<Account> accList = new List<Account>();
            for( Integer i = 1; i <=5; i++  ) {
                firstAcc = new Account();
                firstAcc.Name = 'Test Campaign Account - ' + i;
                accList.add(firstAcc);
            }
            insert accList;
            
            List<Contact> oldContacts = new List<Contact>();
            List<H2S__HarvestProject__c> projList = new List<H2S__HarvestProject__c>();
            List<Opportunity> oppList = new List<Opportunity>();
            Integer i = 0;
            for( Account acc : accList  ) {
                /**
* Add contacts to newly created accounts
*/
                Contact con = new Contact( 
                    FirstName = 'Test Campaign', 
                    LastName = 'Contact' + i , 
                    Account_Roles__c = 'Primary Contact', 
                    AccountId = acc.Id 
                );
                oldContacts.add( con );
                
                /**
* Also add projects to those accounts
*/
                H2S__HarvestProject__c project = new H2S__HarvestProject__c(
                    Name = 'Test project' + i,
                    H2S__Account__c = acc.Id,
                    H2S__Budget__c = 'No budget',
                    H2S__InvoiceMethod__c = 'This project is not billable'
                );
                projList.add( project );
                
                /**
* Also add opportunities to those opps
*/
                Opportunity op = new Opportunity(
                    Name = 'Test opp' + i,
                    AccountId = acc.Id,
                    Service_Item_List__c = 'A00397;A11746;',
                    StageName = 'Qualification',
                    CloseDate = date.today()
                    
                );
                oppList.add(op);
                
                i++;
            }
            insert oldContacts;
            insert projList;
            insert oppList;
            System.debug('oldContacts: '+oldContacts);
            System.debug('projList: '+projList);
            System.debug('oppList: '+oppList);
            
            /**
* For all those projects, add time enteries
*/
            List<H2S__HarvestTimeEntry__c> timeEntriesList = new List<H2S__HarvestTimeEntry__c>(); 
            for( H2S__HarvestProject__c projs : projList ) {
                H2S__HarvestTimeEntry__c timeEntry = new H2S__HarvestTimeEntry__c(
                    H2S__Date__c = date.parse('1/1/2022'),
                    H2S__HarvestProject__c = projs.Id,
                    H2S__StartTime__c = date.parse('1/1/2022'),
                    H2S__EndTime__c = date.parse('1/1/2022')
                );
                timeEntriesList.add(timeEntry);
            }
            
            insert timeEntriesList;
            
            Campaign cmp = new Campaign( Name = 'Active Tax Clients', IsActive = true );
            insert cmp;
            
            /**
* Insert campaign members in the above created campaign
*/
            
            List<CampaignMember> cmpMemberList = new List<CampaignMember>();
            for( Integer j = 0; j < 2; j++  ) {
                CampaignMember cmpMember = new CampaignMember(
                    Account__c  = accList.get(j).Id,
                    CampaignId  = cmp.Id,
                    ContactId   = oldContacts.get(j).Id,
                    Status      = 'Sent'
                );
                cmpMemberList.add(cmpMember);
            }
            insert cmpMemberList;
            
            Account forDeletion = new Account( Name = 'For Deletion Account' );
            insert forDeletion;
            
            H2S__HarvestProject__c delProj = new H2S__HarvestProject__c( Name = 'Delete Project', H2S__Account__c = forDeletion.Id, H2S__Budget__c = 'No budget', H2S__InvoiceMethod__c = 'This project is not billable'  );
            insert delProj;
            
            Contact delContact = new Contact( FirstName = 'For Deletion', LastName = 'Contact', AccountId = forDeletion.Id );
            insert delContact;
            
            Opportunity delOpp = new Opportunity( Name = 'Delete Opp', Service_Item_List__c = '', AccountId = forDeletion.Id, StageName = 'Qualification', CloseDate = date.today() );
            insert delOpp;
            
            CampaignMember cmpMember = new CampaignMember(Account__c  = forDeletion.Id, CampaignId  = cmp.Id, ContactId = delContact.Id, Status = 'Sent' );
            insert cmpMember;
            
        }
        catch(Exception ex)
        {
            system.debug('getLineNumber>>'+ ex.getLineNumber());
            system.debug('getCause>>'+ ex.getCause());
            system.debug('getMessage>>'+ ex.getMessage());
        }
    }
    
    static testMethod void testCampaignBatch(){
        try{
            
            Set<Id> accIds = new Set<Id>();
            for(Opportunity ag : [Select AccountId From Opportunity Where Service_Item_List__c Like '%A00397%' OR Service_Item_List__c Like '%A11746%'] ){
                accIds.add(ag.AccountId);
            }
            
            for(H2S__HarvestProject__c project : [Select H2S__Account__c From H2S__HarvestProject__c Where Max_Time_Entry_Date__c != null]){
                accIds.add(project.H2S__Account__c);
            }
            String query = 'Select Id, Name, (Select Id, Bookkeeper_Assigned__c, Bookkeeper_Time__c, Max_Time_Entry_Date__c From H2S__HarvestProjects__r ), (Select Id, Account_Roles__c, AccountId from Contacts Where Account_Roles__c = \'Primary Contact\'), (Select Id, Service_Item_List__c From Opportunities Where Service_Item_List__c Like \'%A00397%\' OR Service_Item_List__c Like \'%A11746%\') From Account Where Id in: accIds';
            
            System.debug('Query Chk: '+database.query( query ));
            
            List<Campaign> cmp = [Select Id, Name From Campaign Where Name = 'Active Tax Clients' Limit 1];
            String deleteQuery = 'Select Id, Name, Account__c From CampaignMember Where CampaignId = \'' + cmp.get(0).Id+'\'';
            
            // Test.startTest();
            Id batchJobId1 = Database.executeBatch(new AddMembersToCampaignDailyBatch(query, accIds),200);
            
            Opportunity opDel1 = [Select Id, Service_Item_List__c From Opportunity Limit 1];
            opDel1.Service_Item_List__c = '';
            update opDel1;
            
            Id deleteBatchJobId1 = Database.executeBatch(new DeleteMembersFromCampaignDailyBatch(deleteQuery),200);
            Test.startTest();
            System.schedule('AddMembersToCampaignDailyBatch Test', '0 00 05 ? * 2',  new AddMembersToCampaignDailyBatch() );
            
            Opportunity opDel2 = [Select Id, Service_Item_List__c From Opportunity Where Id !=: opDel1.Id Limit 1];
            opDel2.Service_Item_List__c = '';
            update opDel2;
            
            System.schedule('DeleteMembersFromCampaignDailyBatch Test', '0 00 05 ? * 2',  new DeleteMembersFromCampaignDailyBatch() );
            
            
            List<CronTrigger> ctAdd = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name = 'AddMembersToCampaignDailyBatch Test'];
            List<CronTrigger> ctDel = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name = 'DeleteMembersFromCampaignDailyBatch Test'];
            Test.stopTest();
            System.debug('ctAdd: '+ctAdd);
            System.debug('ctDel: '+ctDel);
        }
        catch(Exception ex)
        {
            system.debug('getLineNumber>>'+ ex.getLineNumber());
            system.debug('getCause>>'+ ex.getCause());
            system.debug('getMessage>>'+ ex.getMessage());
        }
        
        // System.assert( batchJobId1 != null, 'Add batch did not run');
        // System.assert( deleteBatchJobId1 != null, 'Delete batch did not run');
        // System.assert( ctAdd.size() > 0, 'Add Job is not scheduled');
        // System.assert( ctDel.size() > 0, 'Delete Job is not scheduled');
        // Test.stopTest();
    }
}