objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Entity_Formation_Sale__c</fullName>
        <label>First Entity Formation Sale</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Transaction_Total__c</fullName>
        <inlineHelpText>Total of all Charges with a Response of &quot;Approved&quot;</inlineHelpText>
        <label>Transaction Total</label>
        <summarizedField>ChargentSFA__Transaction__c.ChargentSFA__Amount__c</summarizedField>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Response_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Type__c</field>
            <operation>equals</operation>
            <value>Charge, Refund, Credit</value>
        </summaryFilterItems>
        <summaryForeignKey>ChargentSFA__Transaction__c.ChargentSFA__Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>First_Transaction__c</fullName>
        <description>Date of first approved transaction.</description>
        <inlineHelpText>Date of first approved transaction.</inlineHelpText>
        <label>First Transaction</label>
        <summarizedField>ChargentSFA__Transaction__c.ChargentSFA__Gateway_Date__c</summarizedField>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Response_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Type__c</field>
            <operation>equals</operation>
            <value>Charge</value>
        </summaryFilterItems>
        <summaryForeignKey>ChargentSFA__Transaction__c.ChargentSFA__Opportunity__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FirstEFSale_Scheduled.cls
public class FirstEFSale_Scheduled implements Schedulable{
    public void execute(SchedulableContext sc)
    {
        FirstEFSale();
    }
    
    public void FirstEFSale(){
        
        Map<Id, AggregateResult> firstEFsale = new Map<Id, AggregateResult>([SELECT Id, AccountId, MIN(First_Transaction__c) 
                       FROM Opportunity 
                       WHERE Account.First_Entity_Formation_Sale__c = NULL 
                       AND Account.LastModifiedDate = TODAY 
                       AND RecordType.Name = 'Entity Formation' 
                       AND ChargentSFA__Transaction_Total__c >= 1000 
                       GROUP BY AccountId, Id]);
        
        List<Opportunity> opps = new List<Opportunity>([Select Id, AccountId, First_Transaction__c
                                 FROM Opportunity
                                 WHERE Id =:firstEFsale.keySet()]);
        
        List<Account> accIds = new List<Account>();
        Map<Id, DateTime> AccMap = new Map<Id, DateTime>();
        
		if(!opps.isEmpty()) {
            for(Opportunity oppsB : opps){
                 AccMap.put(oppsB.AccountId, oppsB.First_Transaction__c);               
            }
            
            for(account acc: [SELECT Id, First_Entity_Formation_Sale__c FROM Account WHERE Id in: AccMap.keyset()]){
                acc.First_Entity_Formation_Sale__c = AccMap.get(acc.Id);
                accIds.add(acc);
            }
                      
         
            update accIds;
        }
        
    }
}