objects/Account.object
<CustomObject>
    <fields>
        <fullName>Platinum_Sale_Count__c</fullName>
        <label>Platinum Sale Count</label>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Platinum Subscription</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Infinity_Memebership__c</fullName>
        <label>Infinity Membership</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Free</fullName>
                </value>
                <value>
                    <fullName>Stock</fullName>
                    <label>Stock Pro</label>
                </value>
                <value>
                    <fullName>Real</fullName>
                    <label>Real Estate Pro</label>
                </value>
                <value>
                    <fullName>360</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Infinity_Sale_Dataload__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Infinity Sale Dataload</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sale_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_User_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service User Created</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/InfinityUserCreationBtachClassCall.cls
public class InfinityUserCreationBtachClassCall implements Schedulable {
    public void execute(SchedulableContext sc) {
        
       String taskQuery='';
         Id batchJobId1;
        if(!Test.isRunningTest()){
        taskQuery='select id, Name, CreatedBy.Name, Infinity_Memebership__c, Account.name, Sale_Campaign__c,Infinity_Sale_Dataload__c from opportunity where Infinity_Memebership__c=\'Free\' and RecordTypeID=\'0120B000000N8E5QAK\' and  Service_User_Created__c=false and Infinity_Sale_Dataload__c=true and Account.Platinum_Sale_Count__c=0  limit 50'; 
        }else{
              taskQuery='select id, Name, CreatedBy.Name, Infinity_Memebership__c, Account.name, Sale_Campaign__c,Infinity_Sale_Dataload__c from opportunity where Infinity_Memebership__c=\'Free\' and RecordTypeID=\'0120B000000N8E5QAK\' and  Service_User_Created__c=false and Infinity_Sale_Dataload__c=true and Account.Platinum_Sale_Count__c=0 limit 50 ';
        }
          if(!Test.isRunningTest()){
          batchJobId1 = Database.executeBatch(new InfinityUserCreationBatch(taskQuery), 1);
         }else{
              batchJobId1 = Database.executeBatch(new InfinityUserCreationBatch(taskQuery), 200);
         }
    }
}