objects/Account.object
<CustomObject>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Infinity</fullName>
        <active>true</active>
        <label>Infinity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Infinity_Memebership__c</fullName>
        <label>Infinity Membership</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Free</fullName>
                </value>
                <value>
                    <fullName>Stock</fullName>
                    <label>Stock Pro</label>
                </value>
                <value>
                    <fullName>Real</fullName>
                    <label>Real Estate Pro</label>
                </value>
                <value>
                    <fullName>360</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Infinity_Sale_Dataload__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Infinity Sale Dataload</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_User_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service User Created</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Infinity</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Infinity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DigitalProdSaleWPusercreationBatchTest.cls
@isTest
public class DigitalProdSaleWPusercreationBatchTest {
@testSetup static void createTestData() {
   
      
    }
    @isTest
    public static void makeserviceUser() {
         Test.startTest();
              String CRON_EXP = '0 0 0 15 3 ? *';
         Account a = new Account();
        a.First_Name__c = 'Bob';
        a.Last_Name__c = 'Apples';
        a.Name = '123';
        a.E_Mail__c = 'bazam123@gmail.com';
        insert a;
        
        Contact c = new Contact();
        c.AccountId = a.id;
        c.FirstName = 'Bob';
        c.LastName = 'Apples';
        c.Email = 'bazam123@gmail.com';
        c.Account_Roles__c = 'Primary Contact';
        insert c;
        
        Opportunity o = new Opportunity();
        o.AccountId = a.Id;
        o.Name = 'Infinity Subscription';
        o.CloseDate = system.today();
        o.StageName = 'Closed Won';
    	o.Infinity_Memebership__c = '360';
    o.Service_User_Created__c=false;
    o.Infinity_Sale_Dataload__c=true;
        o.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Infinity Subscription').getRecordTypeId();
        insert o;
        
     String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new InfinityUserCreationBtachClassCall());
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(CRON_EXP, ct.CronExpression);
            System.assertEquals(0, ct.TimesTriggered);
test.stopTest();
        
    }
}