objects/Account.object
<CustomObject>
    <fields>
        <fullName>Base_Url__c</fullName>
        <formula>LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base Url</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Base_URL__c</fullName>
        <formula>IMAGE(&quot;https://andersonadvisors--c.na132.visual.force.com/&quot; + Processor_Signature_Field__c, &quot;Processor Signature&quot;, 75, 150)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consult_Scheduled__c</fullName>
        <label>Consult Scheduled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disregarded_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Disregarded To This Entity</description>
        <label>Disregarded To Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Entities (Disregarded To)</relationshipLabel>
        <relationshipName>Entities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EIN__c</fullName>
        <label>EIN #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Federal_Return__c</fullName>
        <formula>IF(
AND(ISPICKVAL(Tax_Form__c, &quot;1120&quot;), AND(MONTH(Year_End__c)=12, DAY(Year_End__c)=31)), &quot;April 15&quot;, 
IF(
AND(ISPICKVAL(Tax_Form__c, &quot;1120&quot;), AND(MONTH(Year_End__c)=10, DAY(Year_End__c)=31)), &quot;February 15&quot;,
IF(
AND(ISPICKVAL(Tax_Form__c, &quot;1120&quot;), AND(MONTH(Year_End__c)=9, DAY(Year_End__c)=30)), &quot;January 15&quot;,
IF(
AND(ISPICKVAL(Tax_Form__c, &quot;1120&quot;), AND(MONTH(Year_End__c)=6, DAY(Year_End__c)=30)), &quot;September 15&quot;,
IF(
AND(ISPICKVAL(Tax_Form__c, &quot;1120&quot;), AND(MONTH(Year_End__c)=3, DAY(Year_End__c)=31)), &quot;July 15&quot;,
IF(
AND(ISPICKVAL(Tax_Status__c, &quot;Partnership&quot;), ISPICKVAL(Tax_Form__c, &quot;1065&quot;)), &quot;March 15&quot;,
IF(
ISPICKVAL(Tax_Form__c, &quot;1120S&quot;), &quot;March 15&quot;,
IF(
AND(ISPICKVAL(Tax_Status__c, &quot;Disregarded Entity&quot;), NOT(ISBLANK(Disregarded_To_Personal__c))), &quot;April 15&quot;,
NULL))))))))</formula>
        <label>Federal Return Due Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Status__c</fullName>
        <label>Tax Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>C - Corporation</fullName>
                </value>
                <value>
                    <fullName>S - Corporation</fullName>
                </value>
                <value>
                    <fullName>Disregarded Entity</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>Pension</fullName>
                </value>
                <value>
                    <fullName>QSUB</fullName>
                </value>
                <value>
                    <fullName>Public Charity</fullName>
                </value>
                <value>
                    <fullName>Private Foundation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trust__c.object
<CustomObject>
    <description>Object to hold Trust information.</description>
    <fields>
        <fullName>Consult_Scheduled__c</fullName>
        <label>Consult Scheduled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EIN__c</fullName>
        <label>EIN#</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Filing State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trusts</relationshipLabel>
        <relationshipName>Trusts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Status__c</fullName>
        <label>Tax Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tax_Return_Required__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>C - Corporation</fullName>
                </value>
                <value>
                    <fullName>S - Corporation</fullName>
                </value>
                <value>
                    <fullName>Disregarded Entity</fullName>
                </value>
                <value>
                    <fullName>Foundation</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>Pension</fullName>
                </value>
                <value>
                    <fullName>QSUB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trust</label>
    <nameField>
        <label>Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EntitiesAndTrustTabctrl.cls
public class EntitiesAndTrustTabctrl {
@AuraEnabled
   public static List<Entities__c> getEntity(Id clientid) {

     
   return [SELECT Id,Primary_Client__c, Primary_Client__r.name,Primary_Client__r.Base_Url__c,Status__c,EIN__c,Tax_Status__c,Disregarded_To__r.Name,Disregarded_To__c,Federal_Return__c,Organization_State__c,Consult_Scheduled__c,RecordTypeId,LivingTrustAttorney__c,Assigned_Paralegal__c,Assigned_Paralegal__r.name,Documents_Complete__c,Date_Shipped__c,RecordType.name,Name,Case__c,Case__r.CaseNumber  FROM Entities__c where Primary_Client__c=:clientid ];
       
       
   }
    
  @AuraEnabled
   public static List<Trust__c> getTrust(Id clientid) {
   

     
   return [SELECT Id,Primary_Client__c, Primary_Client__r.name,Primary_Client__r.Base_Url__c,Consult_Scheduled__c,RecordTypeId,LivingTrustAttorney__c,Assigned_Paralegal__c,Assigned_Paralegal__r.name,Documents_Complete__c,Date_Shipped__c,RecordType.name,Name,Case__c,Case__r.CaseNumber  FROM Trust__c where Primary_Client__c=:clientid];
       
       
   }
     @AuraEnabled
    public static boolean insideCommunity(){
        Id siteId = Site.getSiteId();
        if(siteId != Null){
            return true;
        }
        return false;
    }
    
     @AuraEnabled
    public static List<Entities__c> findByEntityName(String searchKey, Id ClientId) {
      
   
        String name = '%' + searchKey + '%';
            
        if(searchKey!='' && searchKey!=null){
             return [SELECT Id,Primary_Client__c, Primary_Client__r.name,Primary_Client__r.Base_Url__c,Status__c,EIN__c,Tax_Status__c,Disregarded_To__r.Name,Disregarded_To__c,Federal_Return__c,Organization_State__c,Consult_Scheduled__c,RecordTypeId,LivingTrustAttorney__c,Assigned_Paralegal__c,Assigned_Paralegal__r.name,Documents_Complete__c,Date_Shipped__c,RecordType.name,Name,Case__c,Case__r.CaseNumber  FROM Entities__c where Primary_Client__c=:clientid  and  (name LIKE :name or Organization_State__c like :name or RecordType.Name Like :name)  LIMIT 1000];
        }else{
           
  return [SELECT Id,Primary_Client__c, Primary_Client__r.name,Primary_Client__r.Base_Url__c,Status__c,EIN__c,Tax_Status__c,Disregarded_To__r.Name,Disregarded_To__c,Federal_Return__c,Organization_State__c,Consult_Scheduled__c,RecordTypeId,LivingTrustAttorney__c,Assigned_Paralegal__c,Assigned_Paralegal__r.name,Documents_Complete__c,Date_Shipped__c,RecordType.name,Name,Case__c,Case__r.CaseNumber  FROM Entities__c where Primary_Client__c=:clientid ];
        }
        
    }
    
      
     @AuraEnabled
    public static List<Trust__c> findByTrustName(String searchKey, Id ClientId) {
      
       

        String name = '%' + searchKey + '%';
        if(searchKey!='' && searchKey!=null){
            return [SELECT Id,Primary_Client__c, Primary_Client__r.name,Primary_Client__r.Base_Url__c,Consult_Scheduled__c,RecordTypeId,LivingTrustAttorney__c,Assigned_Paralegal__c,Assigned_Paralegal__r.name,Documents_Complete__c,Date_Shipped__c,RecordType.name,Name,Case__c,Case__r.CaseNumber  FROM Trust__c where Primary_Client__c=:clientid  and  (name LIKE :name  or RecordType.Name Like :name)  LIMIT 1000];   
        }else{
            return [SELECT Id,Primary_Client__c, Primary_Client__r.name,Primary_Client__r.Base_Url__c,Consult_Scheduled__c,RecordTypeId,LivingTrustAttorney__c,Assigned_Paralegal__c,Assigned_Paralegal__r.name,Documents_Complete__c,Date_Shipped__c,RecordType.name,Name,Case__c,Case__r.CaseNumber  FROM Trust__c where Primary_Client__c=:clientid];
        }
       
        
    }
}