objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Primary Contact Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountPrimaryContactCountClass.cls
global class AccountPrimaryContactCountClass implements 
    Database.Batchable<sObject>, Database.Stateful {
            private String query; 
       
       
        global AccountPrimaryContactCountClass(string query){
            this.query = query;
           
        }
        global Database.QueryLocator start(Database.BatchableContext bc) { 
             
    
    

         return Database.getQueryLocator(this.query);
        }
        global void execute(Database.BatchableContext bc,List<Account> scope){
         Map<id,account> accmap=new Map<id,account>();
            set<ID> accid=new set<ID>();
            for(Account a:scope){
                 for(Contact con:a.contacts){
                     if(con.Account_Roles__c=='Primary Contact'){
                         accmap.put(a.id,a);
                         
                     }
                 }
            }
            for(Account a :accmap.values() ){
                a.Primary_Contact_Count__c=1;
                
            }
          
            update accmap.values();
          
            
        }
          global void finish(Database.BatchableContext bc){
          }
}