objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <description>Cam Assigned to the account</description>
        <label>Assigned CAM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CAM</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <label>Assigned Client Success Coordinator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CSR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original source of the client.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platinum_Client_View__c</fullName>
        <label>Platinum Client View</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Lifetime Platinum</fullName>
                </value>
                <value>
                    <fullName>Infinity Only</fullName>
                </value>
                <value>
                    <fullName>Infinity &amp; Platinum</fullName>
                </value>
                <value>
                    <fullName>Tax Team</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>NVREA Platinum</fullName>
                    <isActive>false</isActive>
                    <label>NVREA Platinum</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Infinity</fullName>
        <active>true</active>
        <label>Infinity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <formula>TEXT(Account.Assigned_CAM__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned CAM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <formula>TEXT(Account.Assigned_CSR__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original Campaign associated with the Contact when converted from a Lead.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Override_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To override the Closed Lost automation.</inlineHelpText>
        <label>Override Automation</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Infinity</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Infinity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/CAM.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alexandria Lessard</fullName>
    </customValue>
    <customValue>
        <fullName>Mary Borden</fullName>
    </customValue>
    <customValue>
        <fullName>Matthew Smidowicz</fullName>
    </customValue>
    <customValue>
        <fullName>Team Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 6</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 7</fullName>
    </customValue>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Brown</fullName>
        <isActive>false</isActive>
        <label>Christina Brown</label>
    </customValue>
    <customValue>
        <fullName>Danielle Blair</fullName>
        <isActive>false</isActive>
        <label>Danielle Blair</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <customValue>
        <fullName>Joseph Sacco</fullName>
        <isActive>false</isActive>
        <label>Joseph Sacco</label>
    </customValue>
    <customValue>
        <fullName>Erica Terrell</fullName>
        <isActive>false</isActive>
        <label>Erica Terrell</label>
    </customValue>
    <customValue>
        <fullName>Savannah Wallace</fullName>
        <isActive>false</isActive>
        <label>Savannah Wallace</label>
    </customValue>
    <customValue>
        <fullName>Crystal Smerdel</fullName>
        <isActive>false</isActive>
        <label>Crystal Smerdel</label>
    </customValue>
    <description>Cams assigned</description>
    <masterLabel>CAM</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/CSR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aaron Bernhardt</fullName>
    </customValue>
    <customValue>
        <fullName>Adrienne Harper</fullName>
    </customValue>
    <customValue>
        <fullName>Alexa Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Alyssa Hoopii</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Zipprich</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Yadao</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Seguin</fullName>
    </customValue>
    <customValue>
        <fullName>Branden Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Brittany Rains</fullName>
    </customValue>
    <customValue>
        <fullName>Carly Coons</fullName>
    </customValue>
    <customValue>
        <fullName>Carrie J. Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Channell Palmer</fullName>
    </customValue>
    <customValue>
        <fullName>Chase Foster</fullName>
    </customValue>
    <customValue>
        <fullName>Christian DeField</fullName>
    </customValue>
    <customValue>
        <fullName>Claire Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Colette Grier</fullName>
    </customValue>
    <customValue>
        <fullName>Dana Heckathorn</fullName>
    </customValue>
    <customValue>
        <fullName>Deborah Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Domanick Page-Whitaker</fullName>
    </customValue>
    <customValue>
        <fullName>Duncan Bjerke</fullName>
    </customValue>
    <customValue>
        <fullName>Gabby Esteban</fullName>
    </customValue>
    <customValue>
        <fullName>Hayley Karlson</fullName>
    </customValue>
    <customValue>
        <fullName>Jade Comer</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Lundquist</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Nelson</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Seibert</fullName>
    </customValue>
    <customValue>
        <fullName>Jessica Thornton</fullName>
    </customValue>
    <customValue>
        <fullName>Kaila Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Katherine Baez</fullName>
    </customValue>
    <customValue>
        <fullName>Kim Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Ambria Tibbs</fullName>
        <isActive>false</isActive>
        <label>Ambria Tibbs</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <description>Assigned CSR</description>
    <masterLabel>CSR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/DeactivatePlatinumUserTest.cls
@isTest(SeeAllData=false)
public class DeactivatePlatinumUserTest {
    @isTest
    public static void testUserMethod()
    {
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
       // User thisUser = [select Id, AccountId from User where UserRoleId = :portalRole.Id Limit 1];  
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'opportunity' and name = 'Platinum Subscription'].Id;
        // System.runAs ( thisUser ) {
        Test.StartTest(); 
        Integer cseLstSze = 10;
        Id p = [select id from profile where name='Partner Community User'].id;
        Campaign cmp = new Campaign();
        cmp.Name = 'Steve';
        insert cmp;        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        testAccount.First_Name__c='Edward';
        testAccount.Last_Name__c='Lee';
        testAccount.Campaign__c = cmp.Id;
       // testAccount.OwnerId = thisUser.Id;
       // testAccount.Assigned_CAM__c = 'Sara Winter';
        //testAccount.Assigned_CSR__c = 'Ambria Tibbs';
      //  testAccount.Bookkeeper__c = thisUser.Id;
        testAccount.phone='123456782';
        testAccount.Platinum_Client_View__c = 'Platinum';
        insert testAccount; 
        Contact cont = new Contact();
        cont.FirstName = 'FirstNames';
        cont.LastName = 'LastNames';
        cont.Email='email@email.coms';
        cont.phone='12345678';
        cont.AccountId=testAccount.Id;
        insert cont;
        User uzr = new User();
        uzr.FirstName='Steves';
        uzr.LastName='Marks';
        uzr.Email='stevemark@gmail.coms';
        uzr.Username='stevemark@gmail.coms';
        uzr.Alias='autocase';
        uzr.CommunityNickname='Partner_Panelsss';
        uzr.TimeZoneSidKey='GMT';
        uzr.LocaleSidKey='en_US';
        uzr.EmailEncodingKey='UTF-8';
        uzr.LanguageLocaleKey='en_US'; 
        uzr.IsActive =true;
        uzr.ProfileId = p;
        uzr.ContactId = cont.Id;
        insert uzr; 
        Set<Id> usr = new Set<Id>();
        usr.add(uzr.id);
        Opportunity opp = new Opportunity();
        opp.AccountId = testAccount.Id;
        opp.RecordTypeId = strRecordTypeId;
        opp.Name = 'Dummyy Opportunity';
        opp.CloseDate = Date.today();
        opp.StageName = 'Closed Lost';
        opp.Override_Automation__c = True;
        insert opp; 
        testAccount.Platinum_Client_View__c = '';
        update testAccount;
        DeactivateUser.UserInactiveMethod(usr);
        Test.stopTest();  
        // }
    }
    
    @isTest
    public static void testUserMethodTwo()
    {
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
      //  User thisUser = [select Id, AccountId from User where UserRoleId = :portalRole.Id Limit 1];  
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'opportunity' and name = 'Platinum Subscription'].Id;
        // System.runAs ( thisUser ) {
        Test.StartTest(); 
        Integer cseLstSze = 10;
        Id p = [select id from profile where name='Partner Community User'].id;
        Campaign cmp = new Campaign();
        cmp.Name = 'Steve';
        insert cmp;        
        Account testAccount = new Account();
        testAccount.Name='Test Accounts' ;
        testAccount.First_Name__c='Edwards';
        testAccount.Last_Name__c='Lees';
        testAccount.Campaign__c = cmp.Id;
       // testAccount.OwnerId = thisUser.Id;
      //  testAccount.Assigned_CAM__c = 'Sara Winter';
        //testAccount.Assigned_CSR__c = 'Ambria Tibbs';
      //  testAccount.Bookkeeper__c = thisUser.Id;
        testAccount.phone='1234567829';
        testAccount.Platinum_Client_View__c = 'Infinity Only';
        insert testAccount;    
        Contact cont = new Contact();
        cont.FirstName = 'FirstName';
        cont.LastName = 'LastName';
        cont.Email='email@email.com';
        cont.phone='12345678';
        cont.AccountId=testAccount.Id;
        insert cont;
        User uzr = new User();
        uzr.FirstName='Steve';
        uzr.LastName='Mark';
        uzr.Email='stevemark@gmail.com';
        uzr.Username='stevemark@gmail.com';
        uzr.Alias='autocase';
        uzr.CommunityNickname='Partner_Panelsss';
        uzr.TimeZoneSidKey='GMT';
        uzr.LocaleSidKey='en_US';
        uzr.EmailEncodingKey='UTF-8';
        uzr.LanguageLocaleKey='en_US'; 
        uzr.IsActive =true;
        uzr.ProfileId = p;
        uzr.ContactId = cont.Id;
        insert uzr; 
        Set<Id> usr = new Set<Id>();
        usr.add(uzr.id);
        Opportunity opp = new Opportunity();
        opp.AccountId = testAccount.Id;
        opp.RecordTypeId = strRecordTypeId;
        opp.Name = 'Dummy Opportunity';
        opp.CloseDate = Date.today();
        opp.StageName = 'Closed Won';            
        insert opp; 
        testAccount.Platinum_Client_View__c = 'Platinum Elite';
        update testAccount;
        DeactivateUser.UserActiveMethod(usr);
        Test.stopTest();  
        // }
    }
}