objects/Account.object
<CustomObject>
    <fields>
        <fullName>Teams__c</fullName>
        <description>Team Assigned to Client</description>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Teams</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Using_Teams__c</fullName>
        <label>Using Teams</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PlatinumTeamDetail__mdt.object
<CustomObject>
    <fields>
        <fullName>Team_Image__c</fullName>
        <label>Team Image</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Phone__c</fullName>
        <label>Team Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>PlatinumTeamDetail</label>
    <pluralLabel>PlatinumTeamDetails</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Image_URL__c</fullName>
        <description>Links to user&apos;s image on Bamboo in order to display in Saleforce.</description>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Team 1</fullName>
                </value>
                <value>
                    <fullName>Team 3</fullName>
                </value>
                <value>
                    <fullName>Team 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Team 1</fullName>
    </customValue>
    <customValue>
        <fullName>Team 2</fullName>
    </customValue>
    <customValue>
        <fullName>Team 3</fullName>
    </customValue>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Team Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>Team 4</fullName>
    </customValue>
    <customValue>
        <fullName>Team 5</fullName>
    </customValue>
    <customValue>
        <fullName>Team 6</fullName>
    </customValue>
    <customValue>
        <fullName>Team 7</fullName>
    </customValue>
    <customValue>
        <fullName>Temp Team</fullName>
        <isActive>false</isActive>
        <label>Temp Team</label>
    </customValue>
    <description>Teams</description>
    <masterLabel>Teams</masterLabel>
</GlobalValueSet>

classes/FetchPlatinumTeam.cls
@RestResource(urlMapping='/ClientTeam/*')
global class FetchPlatinumTeam {
    
    public static string teamNumber;
    public static string msg;
    public static Map<String,String> msgMap = new Map<String,String>();
    @HttpGet
    global static void getTeamDetails(){
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        res.addHeader('Content-Type', 'application/json');
        Id clientId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        system.debug('Client Id: ' + clientId);
        try{
            if(clientId != null){
                if(isUsingTeams(clientId)){
                    List<Map<String,String>> teamDetails = fetchTeamInfo(teamNumber);
                    if(teamDetails.size() > 0){
                    	res.responseBody = Blob.valueOf(JSON.serialize(teamDetails));
                    }
                    else{
                        msgMap.put('Message','No members found against ' + teamNumber);
                        res.responseBody = Blob.valueOf(JSON.serialize(msgMap));
                    }
                }
                else{
                    msgMap.put('Message','Client not set for using Teams yet!');
                    res.responseBody = Blob.valueOf(JSON.serialize(msgMap));
                }
            }
            else{
                msgMap.put('Message','Invalid Request');
            	res.responseBody = Blob.valueOf(JSON.serialize(msgMap));
            }
        }
        catch(Exception e){
            msgMap.put('Message','Exception Occurred, failed to process request: ' + e);
            res.responseBody = Blob.valueOf(JSON.serialize(msgMap));
        }
    }
    
    public static boolean isUsingTeams(Id clientId){
        Account acc = [select teams__c, using_Teams__c from account where id =: clientId limit 1];
        if(acc.using_Teams__c == 'Yes' && acc.teams__c != null){
            teamNumber = acc.teams__c;
            return true;
        }
        return false;
        
    }
    
    public static List<Map<String,String>> fetchTeamInfo(String teamNo){
        List<Map<String,String>> userMapList = new List<Map<String,String>>();
        Map<String, String> userMap = new Map<String,String>();
        try{
            PlatinumTeamDetail__mdt teamData = [select masterlabel, team_image__c, team_phone__c from PlatinumTeamDetail__mdt where masterlabel =: teamNo limit 1];
            for(User usr : [select id,name,team__c,title,image_URL__c from user where team__c =: teamNo and isActive = true limit 1000]){
                userMap.put('Name',usr.Name);
                String title = usr.title != null ? usr.title : 'N/A';
                userMap.put('Title', usr.title);
                String img = usr.image_URL__c != null ? usr.image_URL__c : 'https://drive.google.com/uc?&id=0B05cYQRrxSNYZHRNN2R3RUZQUE0';
                userMap.put('Image', img);
                userMap.put('Team Phone', String.valueOf(teamData.Team_Phone__c));
                userMap.put('Team Name', teamNo);
                userMapList.add(userMap);
                userMap = new Map<String,String>();
            }
        }
        catch(Exception e){
            userMapList = new List<Map<String,String>>();
        }
    
        return userMapList;
        
    }

}