objects/Account.object
<CustomObject>
    <fields>
        <fullName>BadgeServiceItems__c</fullName>
        <label>BadgeServiceItems</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Infinity</fullName>
        <active>true</active>
        <label>Infinity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <description>Used with LearnDash and the Platinum website to provide course access.</description>
        <inlineHelpText>Used with LearnDash and the Platinum website to provide course access.</inlineHelpText>
        <label>Service Item List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <label>Service Item List</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Infinity</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Infinity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/opportunityTriggerTest.cls
@isTest
public class opportunityTriggerTest {
   
    @isTest
    public static void createTestData() {
        
        Account a = new Account();
        a.First_Name__c = 'Bob';
        a.Last_Name__c = 'Apples';
        a.Name = '123';
        a.E_Mail__c = 'bazam123@gmail.com';
        a.BadgeServiceItems__c = 'A10101';
        insert a;
        
        Contact c = new Contact();
        c.AccountId = a.id;
        c.FirstName = 'Bob';
        c.LastName = 'Apples';
        c.Email = 'bazam123@gmail.com';
        c.Account_Roles__c = 'Primary Contact';
        insert c;
        
        Opportunity o = new Opportunity();
        o.AccountId = a.Id;
        o.Name = 'Platinum Subscription';
        o.CloseDate = system.today();
        o.StageName = 'Closed Won';
        o.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Platinum Subscription').getRecordTypeId();
        insert o;
         Opportunity oInfinity = new Opportunity();
        oInfinity.AccountId = a.Id;
        oInfinity.Name = 'Infinity Basic';
        oInfinity.CloseDate = system.today();
        oInfinity.StageName = 'Closed Won';
        oInfinity.Service_Item_List__c = 'A11774a;';
        oInfinity.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Entity Formation').getRecordTypeId();
        insert oInfinity;
        
         Opportunity oInfinityupd = new Opportunity();
        oInfinityupd.AccountId = a.Id;
        oInfinityupd.Name = 'Infinity Basic';
        oInfinityupd.CloseDate = system.today();
        oInfinityupd.StageName = 'Qualification';
        oInfinityupd.Service_Item_List__c = 'A11774a;';
        oInfinityupd.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Entity Formation').getRecordTypeId();
        
        try{
            insert oInfinityupd;
        }
        catch(dmlexception e){
            system.debug('exception line 47: '+ e.getMessage());
        }
        oInfinityupd.StageName='Closed Won';
        try{
        update oInfinityupd;
        }
        catch(dmlexception e){
            system.debug('Exception line 54: '+ e.getMessage());
        }
        List<id> saleIDs=new List<Id>();
        saleIDs.add(o.Id);
         DigitalProductsSaleWPuserCreation.prepareCallout(saleIDs);
        
        
        
    }
    
        
        
    }