objects/Account.object
<CustomObject>
    <fields>
        <fullName>Reason_for_Follow_Up__c</fullName>
        <label>Reason for Follow Up</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sell Pension</fullName>
                </value>
                <value>
                    <fullName>Sell Living Trust ?</fullName>
                </value>
                <value>
                    <fullName>Sell Corporation ?</fullName>
                </value>
                <value>
                    <fullName>Sell LLC ?</fullName>
                </value>
                <value>
                    <fullName>Sell LP ?</fullName>
                </value>
                <value>
                    <fullName>Transfer Entities into Living Trust ?</fullName>
                </value>
                <value>
                    <fullName>Transfer LLC Units to Holding LLC ?</fullName>
                </value>
                <value>
                    <fullName>Client Needs Land Trust ?</fullName>
                </value>
                <value>
                    <fullName>Client Needs a Deed ?</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Follow_Up__c</fullName>
        <label>Reason for Follow Up</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sell Pension</fullName>
                </value>
                <value>
                    <fullName>Sell Living Trust ?</fullName>
                </value>
                <value>
                    <fullName>Sell Corporation ?</fullName>
                </value>
                <value>
                    <fullName>Sell LLC ?</fullName>
                </value>
                <value>
                    <fullName>Sell LP ?</fullName>
                </value>
                <value>
                    <fullName>Transfer Entities into Living Trust ?</fullName>
                </value>
                <value>
                    <fullName>Transfer LLC Units to Holding LLC ?</fullName>
                </value>
                <value>
                    <fullName>Client Needs Land Trust ?</fullName>
                </value>
                <value>
                    <fullName>Client Needs a Deed ?</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/To_Do__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>To Do&apos;s</relationshipLabel>
        <relationshipName>To_Do_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>To Do</label>
    <nameField>
        <label>To Do</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Do&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TodoTest_TC.cls
public class TodoTest_TC
{
   
    static testMethod void myUnitTest() {
    user u = [select id from USer where ProfileId= : '00eU0000000nGPz' limit 1];
   // System.runas(u)
  
        Account a = new Account();
        a.Name = 'Test Account';
        a.BillingCity = 'Test City';
        a.BillingCountry = 'Test Country';
        a.Reason_for_Follow_Up__c = 'Sell Pension';
        a.RecordTypeId = '012U0000000D8qm';
        //insert a;
        a.Reason_for_Follow_Up__c = 'Sell Living Trust ?';
       // update a;
           RecordType RTypes = [select id from RecordType where name = 'Entity Formation' limit 1 ];
        Opportunity o = new Opportunity();
        if(RTypes!=null)
        {
            o.RecordTypeId = RTypes.id;
        }
        o.Name = 'Test Sales';
        o.StageName = 'Prospecting';
        o.CloseDate = System.today();
        o.AccountId = a.id;
        
        insert o;
   
    
    
    RecordType RTypes1 = [select id from RecordType where name = 'Charitable Remainder Trust' limit 1 ];
    Entities__c e = new Entities__c();
    if(RTypes!=null)
        {
           e.RecordTypeId = RTypes1.id;
        }
     
    e.Name = 'Test Entity';
    e.Primary_Client__c = a.id;
    
    insert e;
    
    To_Do__c t = new To_Do__c();
    
    t.Name= 'Test Todo';
    t.Entity__c = e.id;
    
    insert t;
    }
}