objects/Account.object
<CustomObject>
    <fields>
        <fullName>BadgeServiceItems__c</fullName>
        <label>BadgeServiceItems</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Lead Source used for the general area of where the client came from. The campaign shows specific area.</description>
        <inlineHelpText>2018 Lead Source Main</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>E_mail__c</fullName>
        <label>Case creator Email (If Sharing Login)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Bookkeeping</businessProcess>
        <description>Used for Bookkeeping Cases</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <businessProcess>Operation Help desk</businessProcess>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <businessProcess>Tax</businessProcess>
        <description>Used for Tax Cases</description>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ChargentBase__Gateway__c.object
<CustomObject>
    <description>Configuration object. The administrator should create ONE account for the appropriate payment gateway.</description>
    <fields>
        <fullName>ChargentBase__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Available_Payment_Methods__c</fullName>
        <inlineHelpText>In Payment Console this field controls which Payment Methods are available to users.</inlineHelpText>
        <label>Available Payment Methods</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>eCheck</fullName>
                </value>
                <value>
                    <fullName>Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>Cash Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentBase__Merchant_ID__c</fullName>
        <inlineHelpText>Also know as:
&quot;API Login&quot; on Authorize.net
&quot;Merchant Login&quot; on Payflow Pro
&quot;Name&quot; (Username) on ePDQ
&quot;Connection Username&quot; on Orbital</inlineHelpText>
        <label>Merchant ID</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Main Lead Source</description>
        <inlineHelpText>2018 Main Lead source - general</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Default Record Type for All users</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Will hold last name of an entity.</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <recordTypes>
        <fullName>Corporation</fullName>
        <active>true</active>
        <description>Corporation</description>
        <label>Corporation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>All_Services_Status__c</fullName>
        <label>Sale Audited</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                    <isActive>false</isActive>
                    <label>On Hold</label>
                </value>
                <value>
                    <fullName>Step 1 - Supervisor</fullName>
                    <isActive>false</isActive>
                    <label>Step 1 - Supervisor</label>
                </value>
                <value>
                    <fullName>Step 2 - Manager</fullName>
                    <isActive>false</isActive>
                    <label>Step 2 - Manager</label>
                </value>
                <value>
                    <fullName>Step 3 - CEO</fullName>
                    <isActive>false</isActive>
                    <label>Step 3 - CEO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Main Lead Source - general</description>
        <inlineHelpText>2018 Main Lead Source - general</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sale_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE(
CASE(StageName,
&quot;Closed Won&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Closed Lost&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;Declined-&quot;, &quot;https://andersonadvisors--c.na171.visual.force.com/resource/1473631501000/Exclamation&quot;,
&quot;Converted&quot;, &quot;/servlet/servlet.FileDownload?file=015U00000040BV4&quot;,
&quot;Refund Requested&quot;,&quot;https://andersonadvisors--c.na171.visual.force.com/resource/1593114668000/RefundRequest&quot;,
&quot;/img/samples/flag_yellow.gif&quot;),
&quot;Priority Flag&quot;, 15, 15)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Sales Team</businessProcess>
        <description>Used for Bookkeeping overages.</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent a Kit</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/Main_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adduco Media</fullName>
    </customValue>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson Event</fullName>
    </customValue>
    <customValue>
        <fullName>Big Dog-Love American Homes</fullName>
    </customValue>
    <customValue>
        <fullName>Calendly</fullName>
    </customValue>
    <customValue>
        <fullName>Dani Johnson</fullName>
    </customValue>
    <customValue>
        <fullName>Dave Lindahl</fullName>
    </customValue>
    <customValue>
        <fullName>Don Pendleton</fullName>
    </customValue>
    <customValue>
        <fullName>Elite Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>Gene Guarino</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Lending</fullName>
    </customValue>
    <customValue>
        <fullName>Nick Vertucci-NVREA</fullName>
    </customValue>
    <customValue>
        <fullName>Online Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Online Marketing</fullName>
        <label>Online Paid</label>
    </customValue>
    <customValue>
        <fullName>Pat James</fullName>
    </customValue>
    <customValue>
        <fullName>Real Wealth Network</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Royal Media</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
        <isActive>false</isActive>
        <label>Website</label>
    </customValue>
    <description>2018 lead sources</description>
    <masterLabel>Main Lead Source</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/TestDatafactoryBulk.cls
@isTest
public class TestDatafactoryBulk {
    public static  List<User> uList=new  List<User>();
   public static List<Account> accList=new  List<Account>();
     public static List<Contact> conList=new  List<Contact>();
     public static List<Case> caseList=new  List<Case>();
    public static List<opportunity> oppList=new  List<opportunity>();
    public static List<Product2> productList=new  List<Product2>();
     public static List<PricebookEntry> pricebookList=new  List<PricebookEntry>();
     public static List<OpportunityLineItem> oppLineItemList=new  List<OpportunityLineItem>();
      public static List<Entities__c> EnItemList=new  List<Entities__c>();
     public static ChargentBase__Gateway__c Gateway=new ChargentBase__Gateway__c();
    @testSetup
    public static void createTestData(){
        Id devBKCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Bookkeeping').getRecordTypeId();
           Id devoppBkRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Bookkeeping').getRecordTypeId();
         Id devoppAsRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Anderson System Case').getRecordTypeId();
          Id devoppEFRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Entity Formation').getRecordTypeId();
          Id devoppPlatinumRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Platinum Subscription').getRecordTypeId();
         Id devoppstateRRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('State Renewal').getRecordTypeId();
          Id devoppStdRRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Renewal').getRecordTypeId();
          Id devoppPenRRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pension Renewal').getRecordTypeId();
         Id devoppEntityFormRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Entity Formation').getRecordTypeId();
        Id devoppEFSalesRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Entity Formation').getRecordTypeId();
          Id devoppTaxRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Tax Compliance').getRecordTypeId();
        Id devoppEnLandTrustRecordTypeId = Schema.SObjectType.entities__c.getRecordTypeInfosByName().get('Land Trust').getRecordTypeId();
         Id devoppEnLLCTypeId = Schema.SObjectType.entities__c.getRecordTypeInfosByName().get('Limited Liability Company (LLC)').getRecordTypeId();
           Id devoppEnCorpTypeId = Schema.SObjectType.entities__c.getRecordTypeInfosByName().get('Corporation').getRecordTypeId();
          Id devoppEnGapLLcTypeId = Schema.SObjectType.entities__c.getRecordTypeInfosByName().get('GAP Fund LLC').getRecordTypeId();
        Id devoppEnLivingTrustRecordTypeId = Schema.SObjectType.entities__c.getRecordTypeInfosByName().get('Living Trust').getRecordTypeId();
        Id devoppcallRecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('Call').getRecordTypeId();

 Gateway=    (ChargentBase__Gateway__c)TestDataFactory.createSObject('ChargentBase__Gateway__c', new Map<String,Object>{
  'Name' => 'Test ',
  'ChargentBase__Active__c' => True,
      'ChargentBase__Merchant_ID__c'=>'12354',
      'ChargentBase__Available_Payment_Methods__c' => 'Credit Card'
     
});    
       
Campaign cam = (Campaign)TestDataFactory.createSObject('Campaign', new Map<String,Object>{
  'Name' => 'Test Campaign',
  'IsActive' => True
     
});  
     
       
        	accList = TestDataFactory.createSObjectList('Account', new Map<String,Object>{
                'First_Name__c'=>new List<String>{'Bobby1','Bobby2','Bobby3'},
  'Last_Name__c' => new List<String>{'Apples1','Apples2','Apples3'},
      'Name' => new List<String>{'ApplesTest','ApplesTest2','ApplesTest3'},
      'E_Mail__c'=>'abc@123.com',
 'Main_Lead_Source__c'=> 'Existing Client',
      'BadgeServiceItems__c'=>''
     
},3);
       conList = TestDataFactory.createSObjectList('Contact', new Map<String,Object>{
  'firstname' =>new List<String>{'Bobby1','Bobby2','Bobby3'},
       'Lastname' => new List<String>{'Apples1','Apples2','Apples3'},
           'Email'=>'abc@123.com',
          ' Account_Roles__c'=>'Primary Contact',
  'Account' =>accList
},3);
       caseList = TestDataFactory.createSObjectList('Case', new Map<String,Object>{
  'Account' => AccList,
      'Subject'=>new List<String>{'Test Case1','Test Case2'},
      
  'Status'=>'New'
},2);
        oppList = TestDataFactory.createSObjectList('opportunity', new Map<String,Object>{
  'CloseDate' =>  Date.Today(),
      'Sale_Campaign__c'=>cam.id,
      'Name'=>new List<String>{'Test Sale 1','Test Sale 2','Test Sale 3'},
      'All_Services_Status__c'=>'',
      'StageName' =>  'Qualification',
          'RecordTypeID'=>new List<Id>{devoppstateRRecordTypeId,devoppStdRRecordTypeId,devoppEntityFormRecordTypeId},
  'Account' =>  AccList
},3);
         EnItemList = TestDataFactory.createSObjectList('Entities__c', new Map<String,Object>{
  'Status__c' =>  'Active',
     
      'Name'=>new List<String>{'Test En 1','Test En 2'},
          
      'Organization_State__c' =>  'Wyoming',
          'RecordTypeID'=>new List<Id>{devoppEnLLCTypeId,devoppEnCorpTypeId},
  'Primary_Client__c' =>  AccList[0].id
},2);
        productList=TestDataFactory.createSObjectList('Product2', new Map<String,Object>{
 
      'Name'=>new List<String>{'Unlimited Nominee','Privacy Trust with LLC Truste','Anderson Tax Advantage PRogram','Corporate Assistance Program, 1 Year, Initial','Corporate Assistance Program Annual Renewal','Annual List','LLC Trustee','Registered Agent Annual Renewal'},
          'ProductCode' => new List<String>{'Pro-1','Pro-2','Pro-3','Pro-4','Pro-5','Pro-6','Pro-7','Pro-8'},
              'Family'=>new List<String>{'Entity Formation','Entity Formation','Entity Formation','Entity Formation','Entity Formation','Entity Formation','Entity Formation','Entity Formation'},
                  'Entity_Type__c'=>new List<String>{'Any','Any','Any','Any','Any','Any','Any','Any'},
              
              'isActive' => true
},8);
             pricebookList=TestDataFactory.createSObjectList('PricebookEntry', new Map<String,Object>{
 
      'Product2'=>productList,
          'unitprice' => 0.01,
          'Pricebook2Id'=>Test.getStandardPricebookId(),
          'isActive'=>True,
          'UseStandardPrice'=>false
       
},8);
     oppLineItemList=TestDataFactory.createSObjectList('OpportunityLineItem', new Map<String,Object>{
 
      'Quantity'=>1,
          'Opportunity' => oppList,
          'UnitPrice'=>0.01,
          'Product_Family__c'=>'Entity Formation',
          'Product_Entity_Type__c'=>'Any',
          'PriceBookEntry'=>pricebookList
    
},2);
        
        System.debug('accList--'+accList.size());
    }
     @isTest
    static void TestaccordionDisplay(){
        createTestData();
         System.debug('accList--'+accList.size());
         System.debug('oppList--'+oppList.size());
         System.debug('pricebookList--'+pricebookList.size());
           System.debug('productList--'+productList.size());
         System.debug('oppLineItemList--'+oppLineItemList.size());
          System.debug('uList--'+uList.size());
          System.debug('oppLineItemList--'+oppLineItemList.size());
    }
}