objects/Account.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Lead Source used for the general area of where the client came from. The campaign shows specific area.</description>
        <inlineHelpText>2018 Lead Source Main</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Campaign Source</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Accounts (Original Campaign Source)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Lead Source being used</description>
        <inlineHelpText>lead source for 2018 - general category of where the client came from. For specifics look at campaign.</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Campaign Source</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads (Original Campaign Source)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Main Lead Source - general</description>
        <inlineHelpText>2018 Main Lead Source - general</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <formula>Account.Original_Campaign_Source__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original Campaign Source</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Sales Team</businessProcess>
        <description>Used for Bookkeeping overages.</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Main_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adduco Media</fullName>
    </customValue>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson Event</fullName>
    </customValue>
    <customValue>
        <fullName>Big Dog-Love American Homes</fullName>
    </customValue>
    <customValue>
        <fullName>Calendly</fullName>
    </customValue>
    <customValue>
        <fullName>Dani Johnson</fullName>
    </customValue>
    <customValue>
        <fullName>Dave Lindahl</fullName>
    </customValue>
    <customValue>
        <fullName>Don Pendleton</fullName>
    </customValue>
    <customValue>
        <fullName>Elite Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>Gene Guarino</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Lending</fullName>
    </customValue>
    <customValue>
        <fullName>Nick Vertucci-NVREA</fullName>
    </customValue>
    <customValue>
        <fullName>Online Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Online Marketing</fullName>
        <label>Online Paid</label>
    </customValue>
    <customValue>
        <fullName>Pat James</fullName>
    </customValue>
    <customValue>
        <fullName>Real Wealth Network</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Royal Media</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
        <isActive>false</isActive>
        <label>Website</label>
    </customValue>
    <description>2018 lead sources</description>
    <masterLabel>Main Lead Source</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/TesttrgUpdateAccOppSourceType.cls
@isTest(SeeAllData=True)
private class TesttrgUpdateAccOppSourceType {
    private static Id leadId;

    static testMethod void TesttrgUpdateAccOppSourceType() {
        Campaign c= new Campaign ();
        c.Name= 'test Campaign';
        c.IsActive=true;
           Insert c;
         
        Lead ld = new Lead();
        ld.LastName = 'Test';
      ld.Status='New Lead';
        ld.Main_Lead_Source__c='Anderson Event';
        ld.Original_Campaign_Source__c=c.id;
        insert ld;
        Account acc =new Account();
        acc.Name='test Account';
        insert acc;
         String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Opportunity' and Name = 'Bookkeeping'].Id;
       Opportunity opp = new Opportunity();
        opp.AccountId = acc.id;
        opp.RecordTypeId = strRecordTypeId;
        opp.StageName ='Closed Won';
        opp.Name ='Bookkeeping';
        opp.CloseDate = Date.Today().addDays(1);
        insert opp;
       leadId=ld.id;
     test.startTest();
        checkRecursive.run3=true;
      	database.leadConvert lc = new database.leadConvert();
         lc.setLeadId(leadId);
 			leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
      		lc.setDoNotCreateOpportunity(false);
      		lc.setConvertedStatus(convertStatus.MasterLabel);
        	lc.setOpportunityName('test Enity');
 			Database.LeadConvertResult lcr = Database.convertLead(lc);
        Lead Convertedlead=[Select id, ConvertedAccountId , LastName from lead where IsConverted=true and LastName='Test' limit 1 ];
       		Convertedlead.LastName='Test 2';
        update Convertedlead;
               System.assert( lcr.isSuccess());
      
        test.stopTest();
    }
     
}