objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BatchRunning__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Batch_Name__c</fullName>
        <label>Batch Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Batch_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Batch Running</label>
        <type>Checkbox</type>
    </fields>
    <label>Batch Running</label>
</CustomObject>

objects/ChargentBase__Gateway__c.object
<CustomObject>
    <description>Configuration object. The administrator should create ONE account for the appropriate payment gateway.</description>
    <fields>
        <fullName>ChargentBase__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Merchant_ID__c</fullName>
        <inlineHelpText>Also know as:
&quot;API Login&quot; on Authorize.net
&quot;Merchant Login&quot; on Payflow Pro
&quot;Name&quot; (Username) on ePDQ
&quot;Connection Username&quot; on Orbital</inlineHelpText>
        <label>Merchant ID</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Security_Key__c</fullName>
        <inlineHelpText>Also known as:
&quot;Transaction Key&quot; on Authorize.net
&quot;Password&quot; on Cybersource
&quot;Connection Password&quot; on Orbital
&quot;Password&quot; on Payflow Pro
&quot;Password&quot; on ePDQ
&quot;API Key&quot; on AltCharge</inlineHelpText>
        <label>Merchant Security Key</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default should be &apos;LV&apos;.</inlineHelpText>
        <label>Gateway</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose an Active Gateway record</errorMessage>
            <filterItems>
                <field>ChargentBase__Gateway__c.ChargentBase__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ChargentBase__Gateway__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>C-Corporation</fullName>
                </value>
                <value>
                    <fullName>S-Corporation</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>CRT</fullName>
                </value>
                <value>
                    <fullName>GRT</fullName>
                </value>
                <value>
                    <fullName>QPRT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Effective_Date__c</fullName>
        <description>Date the renewal went into effect.</description>
        <inlineHelpText>Date the renewal went into effect.</inlineHelpText>
        <label>Renewal Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_State__c</fullName>
        <description>State in which State filing will be filed.</description>
        <label>Renewal State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sale_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>BOSS</fullName>
                </value>
                <value>
                    <fullName>Business Credit</fullName>
                </value>
                <value>
                    <fullName>C-Corp</fullName>
                </value>
                <value>
                    <fullName>Corp</fullName>
                </value>
                <value>
                    <fullName>Corp Headquarters</fullName>
                </value>
                <value>
                    <fullName>Deed Preparation</fullName>
                </value>
                <value>
                    <fullName>Document Drafting</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Irrevocable Trust</fullName>
                </value>
                <value>
                    <fullName>Joint Venture LLC</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>LIST00</fullName>
                </value>
                <value>
                    <fullName>Living Trust</fullName>
                </value>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>Mail Forwarding</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Pension</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Registered Agent Fee</fullName>
                </value>
                <value>
                    <fullName>Resident Agent</fullName>
                </value>
                <value>
                    <fullName>S-Corp</fullName>
                </value>
                <value>
                    <fullName>Series LLC</fullName>
                </value>
                <value>
                    <fullName>Titanium</fullName>
                </value>
                <value>
                    <fullName>Unlimited LLC</fullName>
                </value>
                <value>
                    <fullName>Unlimited LLC Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Valley</fullName>
                </value>
                <value>
                    <fullName>Vertucci Fulfillment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SaleEntity__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <formula>Entity__r.RecordType.Name</formula>
        <label>Entity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Entity__r.Primary_Client__r.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Entity__r.Primary_Client__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_State__c</fullName>
        <formula>TEXT(Opportunity__r.Renewal_State__c)</formula>
        <label>Renewal State</label>
        <type>Text</type>
    </fields>
    <label>Sale Entity</label>
    <nameField>
        <label>Sale Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityBatchTest.cls
@isTest 
public class OpportunityBatchTest 
{
   
    
    @isTest
    static void testInsertClosedWonOpp() 
    {
        List<Opportunity> opplist = new List<Opportunity>();
        List<SaleEntity__c> saleEnts = new List<SaleEntity__c>();
        Campaign camp = new Campaign(Name = 'BCP', IsActive = TRUE);
        ChargentBase__Gateway__c gateway = 
            new ChargentBase__Gateway__c(Name = 'LV', 
                                         ChargentBase__Merchant_ID__c ='12345617',
                                         ChargentBase__Active__c = TRUE,
                                         ChargentBase__Security_Key__c = '1234567',
                                         RecordTypeId = Schema.SObjectType.ChargentBase__Gateway__c.getRecordTypeInfosByName().get('Network Merchants (NMI)').getRecordTypeId()
                                        );
        insert gateway;
        insert camp;
        
        BatchRunning__c BatchRunningObj = new BatchRunning__c(Batch_Name__c = 'OpportunityBatch', Is_Batch_Running__c = false);
        INSERT BatchRunningObj;
        
        integer i;
        
        Account a = new Account(
            Name = 'Test',
            First_Name__c = 'Test', 
            Last_Name__c = 'AccountA');
        insert a;
        
        for(i=0;i<5;i++)
        {
            Opportunity opp=new Opportunity();
            opp.Name = 'oppIns' + i;
            opp.StageName = 'Closed Won';
            opp.Description = 'Opportunites whose stage name is Closed Won at time of insertion itself';
            opp.CloseDate = Date.today();
            opp.Amount = 0.01;
            opp.AccountId = a.Id;
            opp.Sale_Campaign__c = camp.Id;
            opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Renewal').getRecordTypeId();
            opp.Renewal_effective_Date__c = Date.today()-2;
            opp.Renewal_State__c = 'California';
            opp.ChargentSFA__Gateway__c = gateway.Id;
            opp.Entity_Type__c = 'LP';
            opp.Pricebook2Id = Test.getStandardPricebookId();
            opp.Renewal_End_Date__c = Date.today().addDays(7);
            opp.ChargentSFA__Payment_Start_Date__c = Date.today();
            opplist.add(opp);     
        }
        
        for(i=0;i<5;i++)
        {
            Opportunity opp2 = new Opportunity();
            opp2.Name = 'oppIns' + i;
            opp2.StageName = 'Closed Won';
            opp2.Description = 'Opportunites whose stage name is Closed Won at time of insertion itself';
            opp2.CloseDate = Date.today();
            opp2.Amount = 0.01;
            opp2.AccountId = a.Id;
            opp2.Sale_Campaign__c = camp.Id;
            opp2.Pricebook2Id = Test.getStandardPricebookId();
            opp2.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Renewal').getRecordTypeId();
            opp2.Renewal_effective_Date__c = Date.today()-2;
            opp2.Renewal_State__c = 'California';
            opp2.Entity_Type__c = NULL;
            opp2.Renewal_End_Date__c = Date.today().addDays(7);
            opp2.ChargentSFA__Payment_Start_Date__c = Date.today();
            opplist.add(opp2);     
        }
        
        for(i=0;i<5;i++)
        {
            Opportunity opp3 = new Opportunity();
            opp3.Name = 'oppIns' + i;
            opp3.StageName = 'Closed Won';
            opp3.Description = 'Opportunites whose stage name is Closed Won at time of insertion itself';
            opp3.CloseDate = Date.today();
            opp3.Amount = 0.01;
            opp3.Pricebook2Id = Test.getStandardPricebookId();
            opp3.AccountId = a.Id;
            opp3.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Renewal').getRecordTypeId();
            opp3.Renewal_effective_Date__c = Date.today()-2;
            opp3.Renewal_End_Date__c = Date.today().addDays(7);
            opp3.ChargentSFA__Payment_Start_Date__c = Date.today();
            opplist.add(opp3);     
        } 
        
        insert opplist;
        
        SaleEntity__c se = new SaleEntity__c(
            Opportunity__c = opplist[0].Id
        );
        insert se;
        
        Product2 p = new Product2(
            Name = 'Service Item',
            Service_Fulfillment_Weight__c = '1',
            Type__c = 'LAW',
            IsActive = TRUE,
            Subscription_Product__c = TRUE
        );
        insert p;
        
        PricebookEntry pe = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = p.Id,
            UnitPrice = 500,
            IsActive = TRUE);
        insert pe;
        
        OpportunityLineItem li = new OpportunityLineItem(
            OpportunityId = oppList[0].Id,
            Product2Id = p.Id,
            PricebookEntryId = pe.Id,
            UnitPrice = 500,
            Quantity = 1);
        insert li;
   
        Test.startTest();
        OpportunityBatch tb = new OpportunityBatch();
        Id batchId = Database.executeBatch(tb);
        Test.stopTest();
        List <Opportunity> clonedOppList = [select Id, Name, StageName, Description from Opportunity where StageName != 'Closed Won'  and  Name like 'oppIns%']; //field 'Description' can not be filtered in a query call
        
       //system.assertequals(clonedOppList.size() , 15, '15 Opportunites should be cloned');
  }
}