objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ChargentSFA__Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Gateway_Date__c</fullName>
        <label>Gateway Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Gateway_ID__c</fullName>
        <label>Gateway ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Client Referral Credit</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Credit to be used</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Wire Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Response_Status__c</fullName>
        <label>Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Charge</fullName>
                    <default>true</default>
                    <label>Charge</label>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>ChargentSFA__Opportunity__r.Account.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>ChargentSFA__Opportunity__r.Account.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                    <default>true</default>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sale_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FirstEntityFormationSaleTest.cls
@isTest
public class FirstEntityFormationSaleTest {
    
    public static String CRON_EXP = '0 0 0 1 1 ? 2024';
    static testmethod void testScheduledJob() {
        
        Test.startTest();
        
                List<Account> accs = new List<Account>();
        List<Opportunity> opps = new List<Opportunity>();
        List<ChargentSFA__Transaction__c> trans = new List<ChargentSFA__Transaction__c>();
        Campaign camp = new Campaign(Name = 'Test Campaign', IsActive = TRUE);
        Id EFtype = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Entity Formation').getRecordTypeId();
        Id clienttype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        
        Date date_today = Date.today(); 
        DateTime dt_today = DateTime.now();
        
        for (integer i = 0; i<10; i++){
            Account a = new Account(
                Name = 'Test',
                First_Name__c = 'Test', 
                Last_Name__c = 'Account' + i, 
                RecordTypeId = clienttype);
        accs.add(a);
        }
        insert accs;
        
        for (integer j = 0; j < 10; j++){
            Opportunity o = new Opportunity(
            Name = 'EF Sale' + j,
            CloseDate = date_today.addDays(-j),
            StageName = 'Qualification',
            Sale_Campaign__c = camp.Id,
            RecordTypeId = EFtype,
            Amount = 10000,
            AccountId = accs[j].Id);
            opps.add(o);
        }
        insert opps;
        
        for (integer k = 0; k < 10; k++){
            ChargentSFA__Transaction__c t = new ChargentSFA__Transaction__C(
                ChargentSFA__Gateway_Date__c = dt_today,
                ChargentSFA__Gateway_ID__c = '11111111111111111',
                ChargentSFA__Opportunity__c = opps[k].Id,
                ChargentSFA__Type__c = 'Charge',
                ChargentSFA__Response_Status__c = 'Approved',
                ChargentSFA__Amount__c = 1000,
                ChargentSFA__Payment_Method__c = 'Credit Card');
            trans.add(t);
        }
        insert trans;
        
        FirstEFSale_Scheduled sh1 = new FirstEFSale_Scheduled();
        String jobId = system.schedule('Test First EF Sale Scheduled', CRON_EXP, sh1);
        
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id =:jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        System.assertEquals('2024-01-01 00:00:00', string.valueof(ct.NextFireTime));
        
        Test.stopTest();

       
    }
}