objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platinum_Client_View__c</fullName>
        <label>Platinum Client View</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Lifetime Platinum</fullName>
                </value>
                <value>
                    <fullName>Infinity Only</fullName>
                </value>
                <value>
                    <fullName>Infinity &amp; Platinum</fullName>
                </value>
                <value>
                    <fullName>Tax Team</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>NVREA Platinum</fullName>
                    <isActive>false</isActive>
                    <label>NVREA Platinum</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RestrictPlatinumClientViewTest.cls
@isTest 
private class RestrictPlatinumClientViewTest {

    static testmethod void restrictPlatinumMethod(){
         Test.startTest();
         Account partnerAccount = new Account(Name = 'Test Partner Account',First_Name__c='Edward',Last_Name__c='Lee',Platinum_Client_View__c ='Platinum Elite');                                                                           
        insert partnerAccount; 
         Test.stopTest();  
    }
    
}