objects/Account.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original source of the client.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BatchRetryAttempts__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Create a separate record for your batch.</description>
    <fields>
        <fullName>Current_Iteration__c</fullName>
        <label>Current Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Iteration__c</fullName>
        <label>Maximum Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Retry Attempts</label>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</description>
        <inlineHelpText>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anderson</fullName>
                    <default>true</default>
                    <label>Anderson</label>
                </value>
                <value>
                    <fullName>Client Formed</fullName>
                </value>
                <value>
                    <fullName>Shelf</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PlanType__c</fullName>
        <label>Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Admin Not Paid</fullName>
                    <isActive>false</isActive>
                    <label>Admin Not Paid</label>
                </value>
                <value>
                    <fullName>Admin Paid</fullName>
                    <isActive>false</isActive>
                    <label>Admin Paid</label>
                </value>
                <value>
                    <fullName>Money Purchase Plan</fullName>
                </value>
                <value>
                    <fullName>Profit Sharing Plan</fullName>
                </value>
                <value>
                    <fullName>ROBS Profit Sharing</fullName>
                </value>
                <value>
                    <fullName>ROBS Solo 401(k)</fullName>
                </value>
                <value>
                    <fullName>Solo 401(k)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prepaid_SLA_Date__c</fullName>
        <label>Prepaid SLA End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Service</fullName>
                </value>
                <value>
                    <fullName>Admin Service</fullName>
                </value>
                <value>
                    <fullName>Prepaid Admin</fullName>
                </value>
                <value>
                    <fullName>Robs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_End__c</fullName>
        <label>First Tax Year End</label>
        <type>Date</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <formula>TEXT(Entity__r.SLA__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLA</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SLA__c.object
<CustomObject>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Service</fullName>
                </value>
                <value>
                    <fullName>Documents Only</fullName>
                </value>
                <value>
                    <fullName>3rd Party Admin</fullName>
                </value>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SLA</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>SLA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Pension1stOfMonthCloseOpenSalesTest.cls
@isTest
private class Pension1stOfMonthCloseOpenSalesTest 
{
    @testSetup
    static void setup()
    {
        insert new BatchRetryAttempts__c(Name='BatchableSaleStageUpdate',Current_Iteration__c=1,Maximum_Iteration__c=3);
        Account acc = new Account();
        acc.Name = 'Test Batch 3';
        insert acc;
        Campaign camp = new Campaign();
        camp.Name = 'Pension Renewals';
        camp.Status='planned';
        camp.IsActive=true;
        insert camp;
        Entities__c myEnt = new Entities__c();
        myEnt.Primary_Client__c = acc.id;    
        myEnt.Name = 'Pension - Annual Maintenance';
        myEnt.Origin__c = 'Anderson';
       // myEnt.Year_End__c = date.newInstance(2020, 03, 20);
        myEnt.Organization_State__c = 'Maine';
        myEnt.SLA__c ='Prepaid Admin';
        myEnt.PlanType__c = 'Money Purchase Plan';
        Date mydate = date.parse('4/24/2021');
        myEnt.Prepaid_SLA_Date__c = mydate;
        myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
        insert myEnt;
        List<Opportunity> lstOpp = new List<Opportunity>();
        for (Integer i = 0; i<10; i++)
        {
            Opportunity op = new Opportunity();
            op.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pension Renewal').getRecordTypeId();
            op.AccountId = acc.Id;
            op.Name ='Annual Plan Maintenance';
            op.CloseDate = Date.newInstance(Date.today().Year(), 08, 31);
            op.Entity__c = myEnt.Id;
            op.Campaign__c = camp.Id;
            op.StageName ='Qualification';
            lstOpp.add(op);
            
        }
        insert lstOpp;
        
        
        
    }
    static testMethod void testMethodJanuary()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 01, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 09, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
    static testMethod void testMethodFebruary()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 02, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 10, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
     static testMethod void testMethodMarch()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 03, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 11, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
      static testMethod void testMethodApril()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 04, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 12, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
     static testMethod void testMethodMay()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 05, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 01, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
     static testMethod void testMethodJune()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 06, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 02, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
    static testMethod void testMethodJuly()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 07, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 03, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
    static testMethod void testMethodAugust()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 08, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 04, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
      static testMethod void testMethodSeptember()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 09, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 05, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
    static testMethod void testMethodOctober()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 10, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 06, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
    static testMethod void testMethodNovember()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 11, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 07, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
    static testMethod void testMethodDecember()
    {
        Entities__c qEntity = [Select id from Entities__c where Name='Pension - Annual Maintenance' Limit 1];
        qEntity.Year_End__c = date.newInstance(2020, 12, 20);
        update qEntity;
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales(Date.newInstance(2021, 08, 01));  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity];
		System.debug('Opportunity'+query);  
       // System.assertEquals(query.size(),10);
        for(Opportunity opp:query)
        {
            System.assertEquals(opp.StageName,'Closed Lost');
        }
        
    }
    static testMethod void testMethodEmptyConstructor()
    {
        Test.startTest();
        Pension1stOfMonthCloseOpenSales createSale = new Pension1stOfMonthCloseOpenSales();  
        Id batchId = Database.executeBatch(createSale);
        Test.stopTest();
       
        
    }



}