objects/Account.object
<CustomObject>
    <fields>
        <fullName>Financial_Analyst__c</fullName>
        <label>Financial Analyst</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Anderson_Financial_Analyst</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASA__c.object
<CustomObject>
    <fields>
        <fullName>ASA_Stage__c</fullName>
        <label>ASA Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASA Scheduled</fullName>
                    <label>ASA Initial Call Scheduled</label>
                </value>
                <value>
                    <fullName>Review Call Scheduled</fullName>
                    <label>Prepare Plan</label>
                </value>
                <value>
                    <fullName>Plan Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Follow Up</fullName>
                </value>
                <value>
                    <fullName>Review Call Complete</fullName>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Plan Approved</fullName>
                </value>
                <value>
                    <fullName>Ready for ASP Call</fullName>
                </value>
                <value>
                    <fullName>1 Year Follow-up</fullName>
                </value>
                <value>
                    <fullName>Client Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Engagement Initiated</fullName>
                    <isActive>false</isActive>
                    <label>Engagement Initiated</label>
                </value>
                <value>
                    <fullName>Survey Sent</fullName>
                    <isActive>false</isActive>
                    <label>Survey Sent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Advanced Strategy Analyzers</relationshipLabel>
        <relationshipName>ASA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Analyst__c</fullName>
        <label>Financial Analyst</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Brandon Smith</fullName>
                </value>
                <value>
                    <fullName>Jason Kopp</fullName>
                </value>
                <value>
                    <fullName>Kenzie Connor</fullName>
                </value>
                <value>
                    <fullName>Pia Washington</fullName>
                </value>
                <value>
                    <fullName>Rene Barthe</fullName>
                </value>
                <value>
                    <fullName>Ronald Sucre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Yearly_Follow_up_Date__c</fullName>
        <inlineHelpText>The date the Financial Analyst should follow-up with the client.</inlineHelpText>
        <label>Yearly Follow-up Date</label>
        <type>Date</type>
    </fields>
    <label>ASA</label>
    <nameField>
        <label>ASA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Follow_up_task_owner__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <description>user record id</description>
        <label>Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Follow Up year</description>
        <label>Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Follow up Task owner</label>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>ASA</fullName>
        <active>true</active>
        <label>ASA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Call</fullName>
        <active>true</active>
        <description>Used for Calls.</description>
        <label>Call</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Anderson_Financial_Analyst.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Jason Kopp</fullName>
    </customValue>
    <customValue>
        <fullName>Kenzie Connor</fullName>
    </customValue>
    <customValue>
        <fullName>Pia Washington</fullName>
    </customValue>
    <customValue>
        <fullName>Tom Konkowski</fullName>
    </customValue>
    <customValue>
        <fullName>Tyler Rosch</fullName>
    </customValue>
    <customValue>
        <fullName>Jeremy Bavelok</fullName>
    </customValue>
    <customValue>
        <fullName>Kaimara Hatcher</fullName>
    </customValue>
    <customValue>
        <fullName>Valencia Campbell</fullName>
    </customValue>
    <customValue>
        <fullName>Brandon Smith</fullName>
    </customValue>
    <customValue>
        <fullName>Rene Barthe</fullName>
    </customValue>
    <customValue>
        <fullName>Ronald Sucre</fullName>
    </customValue>
    <masterLabel>Anderson Financial Analyst</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ASA_TriggerHandler_Test.cls
/***********************************
* Author : Ifrahim Afzal
* Description : Test class for ASA_AfterUpdateHelper
							   ASA_BeforeInsertHelper
* Class : ASA_TriggerHandler_Test
***********************************/

@isTest
public class ASA_TriggerHandler_Test {

    public static Id call = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Call').getRecordTypeId();
    public static Id client = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
   
    
    public static Final String  FOLLOW_UP_YEAR= '1 Year Follow-up';
    public static Final String ASA_YEAR_FOLLOW = 'ASA Yearly Follow-up';
    
    @testSetup
    public static void testData(){
        
        Follow_up_task_owner__c followUp = new Follow_up_task_owner__c();
        followUp.Name = 'Follow Up';
        followUp.Year__c = 1;
        followUp.Subject__c = '1 Year Follow-up';
        followUp.Id__c = UserInfo.getUserId();
        insert followUp;
        
        ASA__c asa = new ASA__c();
        asa.Name = 'Test ASA Record';
        asa.ASA_Stage__c = 'Review Call Scheduled';
        asa.Yearly_Follow_up_Date__c = Date.today();
        insert asa;
        
        ASA__c asaUpdate = new ASA__c();
        asaUpdate.Name = 'ASA Update';
        asaUpdate.ASA_Stage__c = 'ASA Scheduled';
        asaUpdate.Yearly_Follow_up_Date__c = Date.today();
        insert asaUpdate;
        
        Task task = new Task();
        task.RecordTypeId = call;
        task.OwnerId = Follow_up_task_owner__c.getValues('Follow Up').Id__c;
        task.Date_Due__c =  Date.TODAY().addYears(1);
        task.WhatId = asaUpdate.Id;
        task.Subject = ASA_YEAR_FOLLOW;
        insert task;
        
        Account acc = new Account();
        acc.Name = 'test Name';
        
        acc.Financial_Analyst__c = 'Jason Kopp';
        acc.RecordTypeId = client;
        insert acc;
       
    }
    
    
    @isTest
    public static void taskGenerationTest(){
        try{
            Test.startTest();
            
            ASA__c asa = [Select Id,Name,ASA_Stage__c,Yearly_Follow_up_Date__c from ASA__c Where ASA_Stage__c = 'Review Call Scheduled' Limit 1];
            System.debug('asa'+asa);
            asa.ASA_Stage__c = '1 Year Follow-up';
            update asa;
            Test.stopTest();
        }catch(DMLException e){
            System.debug('e'+e.getMessage());
        }
    }
    
    @isTest
    public static void taskUpdationTest(){
        try{
            Test.startTest();
            ASA__c asa = [Select Id,Name,ASA_Stage__c,Yearly_Follow_up_Date__c from ASA__c Where ASA_Stage__c = 'ASA Scheduled'];
            asa.ASA_Stage__c = '1 Year Follow-up';
            asa.Yearly_Follow_up_Date__c = null;
            update asa;
            Test.stopTest();
        }catch(DMLException e){
            System.debug('e'+e.getMessage());
        }
    }
    
    @isTest
    public static void taskPopulateValue(){
        try{
            Test.startTest();
            Account acc = [Select Id from Account Limit 1]; 
            ASA__c asa = new ASA__c();
            asa.Name = 'Test ASA Record';
            asa.ASA_Stage__c = 'Review Call Scheduled';
            asa.Yearly_Follow_up_Date__c = Date.today();
            asa.Client_Name__c = acc.Id;
            insert asa;
            
            Test.stopTest();
        } catch(DMLException e){
            System.debug('e'+e.getMessage());
        }
    }
        
}