objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Set_of_Books__c.object
<CustomObject>
    <fields>
        <fullName>April_Bookkeeping_Status__c</fullName>
        <label>April Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Aug_Bookkeeping_Status__c</fullName>
        <label>Aug Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Admin</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeping_Reviewer__c</fullName>
        <label>Bookkeeping Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Reviewer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeping_Status__c</fullName>
        <label>Jan Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dec_Bookkeeping_Status__c</fullName>
        <label>Dec Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feb_Bookkeeping_Status__c</fullName>
        <label>Feb Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>July_Bookkeeping_Status__c</fullName>
        <label>July Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>June_Bookkeeping_Status__c</fullName>
        <label>June Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mar_Bookkeeping_Status__c</fullName>
        <label>Mar Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>May_Bookkeeping_Status__c</fullName>
        <label>May Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nov_Bookkeeping_Status__c</fullName>
        <label>Nov Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oct_Bookkeeping_Status__c</fullName>
        <label>Oct Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sep_Bookkeeping_Status__c</fullName>
        <label>Sep Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Set of Books</label>
    <nameField>
        <label>Set of Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Set of Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Bookkeeping_Admin.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abdur Rehman</fullName>
    </customValue>
    <customValue>
        <fullName>Abraham Carrillo</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Hendershot</fullName>
    </customValue>
    <customValue>
        <fullName>Angela Berrow</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Langer</fullName>
    </customValue>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>awais khan</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Arnold</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Bobby Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Bruce Williams</fullName>
    </customValue>
    <customValue>
        <fullName>Carol Spagnoletta</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Conrad Gomez</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Dawson Phipps</fullName>
    </customValue>
    <customValue>
        <fullName>Doug Guard</fullName>
    </customValue>
    <customValue>
        <fullName>Hebert Romero</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Petrunyak</fullName>
    </customValue>
    <customValue>
        <fullName>Jerome Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Joel Evans</fullName>
    </customValue>
    <customValue>
        <fullName>John Doe</fullName>
    </customValue>
    <customValue>
        <fullName>Jonna States</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Fleming</fullName>
    </customValue>
    <customValue>
        <fullName>Kelly Van Middlesworth</fullName>
    </customValue>
    <customValue>
        <fullName>Kenneth Harrah</fullName>
    </customValue>
    <masterLabel>Bookkeeping Admin</masterLabel>
</GlobalValueSet>

globalValueSets/Bookkeeping_Reviewer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Kiera Dunphy</fullName>
    </customValue>
    <customValue>
        <fullName>Lanzi Reel</fullName>
    </customValue>
    <customValue>
        <fullName>Ryan On</fullName>
    </customValue>
    <customValue>
        <fullName>Trisha Cullinane</fullName>
    </customValue>
    <customValue>
        <fullName>Troy Butler</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Nancy Naraine</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Kevin Dennis</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Flemming</fullName>
    </customValue>
    <customValue>
        <fullName>Tesia Owen</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
        <isActive>false</isActive>
        <label>Bethany Castleberry</label>
    </customValue>
    <customValue>
        <fullName>Christine Zimmerman</fullName>
        <isActive>false</isActive>
        <label>Christine Zimmerman</label>
    </customValue>
    <customValue>
        <fullName>Rebecca Gallegos</fullName>
        <isActive>false</isActive>
        <label>Rebecca Gallegos</label>
    </customValue>
    <customValue>
        <fullName>Marie Pues</fullName>
        <isActive>false</isActive>
        <label>Marie Pues</label>
    </customValue>
    <customValue>
        <fullName>Maria Boone</fullName>
        <isActive>false</isActive>
        <label>Maria Boone</label>
    </customValue>
    <masterLabel>Bookkeeping Reviewer</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Bookkeeping_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Client</fullName>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Review Notes</fullName>
    </customValue>
    <customValue>
        <fullName>Send Financials</fullName>
    </customValue>
    <customValue>
        <fullName>Client Unresponsive</fullName>
    </customValue>
    <customValue>
        <fullName>Stopped Services</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Sent to Tax</fullName>
        <isActive>false</isActive>
        <label>Completed - Sent to Tax</label>
    </customValue>
    <customValue>
        <fullName>Completed - Moved to Ongoing</fullName>
        <isActive>false</isActive>
        <label>Completed - Moved to Ongoing</label>
    </customValue>
    <masterLabel>Bookkeeping Status</masterLabel>
</GlobalValueSet>

classes/SetOfBooksBeforeHandler.cls
public with sharing class SetOfBooksBeforeHandler {
    public static void insertHandler(List<Set_of_Books__c> newList, Map<Id,Set_Of_Books__c> newMap) {
        if( newList.size() > 0 ){
            List<Set_of_Books__c> updatedList = [Select Id, Client__r.Name From Set_of_Books__c Where Id in: newMap.keyset()];
            
            Integer i = 0;
            for( Set_of_Books__c sob : newList ){
                Map<String, String> params = new Map<String, String>();
                if( sob.Bookkeeper__c != null ){
                    params.put('Recipient', sob.Bookkeeper__c);
                    if( updatedList.get(i).Client__r.Name != '' ){
                        params.put('ClientName', updatedList.get(i).Client__r.Name);
                    }
                    params.put('setOfBooksId', sob.Id);
                    params.put('Entity', 'Bookkeeper');

                    flow.Interview.Bookkeeping_Notify_Bookkeeper_and_Supervisor StaterenewalFlow = new flow.Interview.Bookkeeping_Notify_Bookkeeper_and_Supervisor(params);
                    StaterenewalFlow.start();
                }
                else if( sob.Bookkeeper__c == null && sob.Bookkeeping_Reviewer__c != null ){
                    params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    if( updatedList.get(i).Client__r.Name != '' ){
                        params.put('ClientName', updatedList.get(i).Client__r.Name);
                    }
                    params.put('setOfBooksId', sob.Id);
                    params.put('Entity', 'Bookkeeper');
                    
                    flow.Interview.Bookkeeping_Notify_Bookkeeper_and_Supervisor StaterenewalFlow = new flow.Interview.Bookkeeping_Notify_Bookkeeper_and_Supervisor(params);
                    StaterenewalFlow.start();
                }

                i++;
            }
        }
    }
    public static void updateHandler(List<Set_of_Books__c> newList, Map<Id,Set_Of_Books__c> newMap, Map<Id,Set_Of_Books__c> oldMap) {
        if( newList.size() > 0 ){
            List<Set_of_Books__c> updatedList = [Select Id, Client__r.Name From Set_of_Books__c Where Id in: newMap.keyset()];
            
            Integer i = 0;
            for( Set_of_Books__c sob : newList ){
                /**
                 * Check for bookkeeper update
                 */
                if( sob.Bookkeeper__c != oldMap.get(sob.Id).Bookkeeper__c && sob.Bookkeeper__c != '' ){
                    
                    Map<String, String> params = new Map<String, String>();
                    
                    params.put('Recipient', sob.Bookkeeper__c);
                    params.put('ClientName', updatedList.get(i).Client__r.Name);
                    params.put('setOfBooksId', sob.Id);
                    params.put('Entity', 'Bookkeeper');
                    
                    flow.Interview.Bookkeeping_Notify_Bookkeeper_and_Supervisor StaterenewalFlow = new flow.Interview.Bookkeeping_Notify_Bookkeeper_and_Supervisor(params);
                    StaterenewalFlow.start();
                }
                else{
                    /**
                     * Check for month update and notify bookkeeper
                     */
                    //January
                    Map<String, String> params = new Map<String, String>();

                    if( sob.Bookkeeping_Status__c != oldMap.get(sob.Id).Bookkeeping_Status__c && 
                    ( sob.Bookkeeping_Status__c != '' && 
                    sob.Bookkeeping_Status__c == 'Review Notes' || sob.Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }
                        
                    //February
                    else if( sob.Feb_Bookkeeping_Status__c != oldMap.get(sob.Id).Feb_Bookkeeping_Status__c && 
                    ( sob.Feb_Bookkeeping_Status__c != '' &&
                    sob.Feb_Bookkeeping_Status__c == 'Review Notes' || sob.Feb_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.Feb_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }
    
                    //March
                    else if( sob.Mar_Bookkeeping_Status__c != oldMap.get(sob.Id).Mar_Bookkeeping_Status__c && 
                    ( sob.Mar_Bookkeeping_Status__c != '' &&
                    sob.Mar_Bookkeeping_Status__c == 'Review Notes' || sob.Mar_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.Mar_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }
    
                    //April
                    else if( sob.April_Bookkeeping_Status__c != oldMap.get(sob.Id).April_Bookkeeping_Status__c && 
                    ( sob.April_Bookkeeping_Status__c != '' &&
                    sob.April_Bookkeeping_Status__c == 'Review Notes' || sob.April_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.April_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }

                    //May
                    else if( sob.May_Bookkeeping_Status__c != oldMap.get(sob.Id).May_Bookkeeping_Status__c && 
                    ( sob.May_Bookkeeping_Status__c != '' &&
                    sob.May_Bookkeeping_Status__c == 'Review Notes' || sob.May_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.May_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }

                    //June
                    else if( sob.June_Bookkeeping_Status__c != oldMap.get(sob.Id).June_Bookkeeping_Status__c && 
                    ( sob.June_Bookkeeping_Status__c != '' &&
                    sob.June_Bookkeeping_Status__c == 'Review Notes' || sob.June_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.June_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }

                    //July
                    else if( sob.July_Bookkeeping_Status__c != oldMap.get(sob.Id).July_Bookkeeping_Status__c && 
                    ( sob.July_Bookkeeping_Status__c != '' &&
                    sob.July_Bookkeeping_Status__c == 'Review Notes' || sob.July_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.July_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }

                    //August
                    else if( sob.Aug_Bookkeeping_Status__c != oldMap.get(sob.Id).Aug_Bookkeeping_Status__c && 
                    ( sob.Aug_Bookkeeping_Status__c != '' &&
                    sob.Aug_Bookkeeping_Status__c == 'Review Notes' || sob.Aug_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.Aug_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }

                    //September
                    else if( sob.Sep_Bookkeeping_Status__c != oldMap.get(sob.Id).Sep_Bookkeeping_Status__c && 
                    ( sob.Sep_Bookkeeping_Status__c != '' &&
                    sob.Sep_Bookkeeping_Status__c == 'Review Notes' || sob.Sep_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.Sep_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }

                    //October
                    else if( sob.Oct_Bookkeeping_Status__c != oldMap.get(sob.Id).Oct_Bookkeeping_Status__c && 
                    ( sob.Oct_Bookkeeping_Status__c != '' &&
                    sob.Oct_Bookkeeping_Status__c == 'Review Notes' || sob.Oct_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.Oct_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }

                    //November
                    else if( sob.Nov_Bookkeeping_Status__c != oldMap.get(sob.Id).Nov_Bookkeeping_Status__c && 
                    ( sob.Nov_Bookkeeping_Status__c != '' &&
                    sob.Nov_Bookkeeping_Status__c == 'Review Notes' || sob.Nov_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.Nov_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }

                    //December
                    else if( sob.Dec_Bookkeeping_Status__c != oldMap.get(sob.Id).Dec_Bookkeeping_Status__c && 
                    ( sob.Dec_Bookkeeping_Status__c != '' &&
                    sob.Dec_Bookkeeping_Status__c == 'Review Notes' || sob.Dec_Bookkeeping_Status__c == 'Send Financials' ) ) {
                        params.put('BookkeepingStage', sob.Dec_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeper__c);
                    }

                    /**
                     * Check for month update and notify bookkeeping reviewer
                     */
                    //January
                    else if( sob.Bookkeeping_Status__c != oldMap.get(sob.Id).Bookkeeping_Status__c && 
                    ( sob.Bookkeeping_Status__c != '' && 
                    sob.Bookkeeping_Status__c == 'Review' || sob.Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    //February
                    else if( sob.Feb_Bookkeeping_Status__c != oldMap.get(sob.Id).Feb_Bookkeeping_Status__c && 
                    ( sob.Feb_Bookkeeping_Status__c != '' &&
                    sob.Feb_Bookkeeping_Status__c == 'Review' || sob.Feb_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.Feb_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }
    
                    //March
                    else if( sob.Mar_Bookkeeping_Status__c != oldMap.get(sob.Id).Mar_Bookkeeping_Status__c && 
                    ( sob.Mar_Bookkeeping_Status__c != '' &&
                    sob.Mar_Bookkeeping_Status__c == 'Review' || sob.Mar_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.Mar_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }
    
                    //April
                    else if( sob.April_Bookkeeping_Status__c != oldMap.get(sob.Id).April_Bookkeeping_Status__c && 
                    ( sob.April_Bookkeeping_Status__c != '' &&
                    sob.April_Bookkeeping_Status__c == 'Review' || sob.April_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.April_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    //May
                    else if( sob.May_Bookkeeping_Status__c != oldMap.get(sob.Id).May_Bookkeeping_Status__c && 
                    ( sob.May_Bookkeeping_Status__c != '' &&
                    sob.May_Bookkeeping_Status__c == 'Review' || sob.May_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.May_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    //June
                    else if( sob.June_Bookkeeping_Status__c != oldMap.get(sob.Id).June_Bookkeeping_Status__c && 
                    ( sob.June_Bookkeeping_Status__c != '' &&
                    sob.June_Bookkeeping_Status__c == 'Review' || sob.June_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.June_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    //July
                    else if( sob.July_Bookkeeping_Status__c != oldMap.get(sob.Id).July_Bookkeeping_Status__c && 
                    ( sob.July_Bookkeeping_Status__c != '' &&
                    sob.July_Bookkeeping_Status__c == 'Review' || sob.July_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.July_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    //August
                    else if( sob.Aug_Bookkeeping_Status__c != oldMap.get(sob.Id).Aug_Bookkeeping_Status__c && 
                    ( sob.Aug_Bookkeeping_Status__c != '' &&
                    sob.Aug_Bookkeeping_Status__c == 'Review' || sob.Aug_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.Aug_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    //September
                    else if( sob.Sep_Bookkeeping_Status__c != oldMap.get(sob.Id).Sep_Bookkeeping_Status__c && 
                    ( sob.Sep_Bookkeeping_Status__c != '' &&
                    sob.Sep_Bookkeeping_Status__c == 'Review' || sob.Sep_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.Sep_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    //October
                    else if( sob.Oct_Bookkeeping_Status__c != oldMap.get(sob.Id).Oct_Bookkeeping_Status__c && 
                    ( sob.Oct_Bookkeeping_Status__c != '' &&
                    sob.Oct_Bookkeeping_Status__c == 'Review' || sob.Oct_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.Oct_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    //November
                    else if( sob.Nov_Bookkeeping_Status__c != oldMap.get(sob.Id).Nov_Bookkeeping_Status__c && 
                    ( sob.Nov_Bookkeeping_Status__c != '' &&
                    sob.Nov_Bookkeeping_Status__c == 'Review' || sob.Nov_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.Nov_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    //December
                    else if( sob.Dec_Bookkeeping_Status__c != oldMap.get(sob.Id).Dec_Bookkeeping_Status__c && 
                    ( sob.Dec_Bookkeeping_Status__c != '' &&
                    sob.Dec_Bookkeeping_Status__c == 'Review' || sob.Dec_Bookkeeping_Status__c == 'Completed' ) ) {
                        params.put('BookkeepingStage', sob.Dec_Bookkeeping_Status__c );
                        params.put('Recipient', sob.Bookkeeping_Reviewer__c);
                    }

                    params.put('SOBName', sob.Name);
                    params.put('ClientName', updatedList.get(i).Client__r.Name);
                    params.put('setOfBooksId', sob.Id);
                    params.put('Entity', 'Status');
                    
                    system.debug('params-else:' + params);
                    flow.Interview.Bookkeeping_Notify_Bookkeeper_and_Supervisor StaterenewalFlow = new flow.Interview.Bookkeeping_Notify_Bookkeeper_and_Supervisor(params);
                    StaterenewalFlow.start();
                }

                i++;
            }
        }
    }
}