objects/Account.object
<CustomObject>
    <fields>
        <fullName>BadgeServiceItems__c</fullName>
        <label>BadgeServiceItems</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Admin_Portal_Sale__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin Portal Sale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To override the Closed Lost automation.</inlineHelpText>
        <label>Override Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <label>Service Item List</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Sales Team</businessProcess>
        <description>Used for Bookkeeping overages.</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BadgeHelperTest.cls
@isTest 
public class BadgeHelperTest {
    @isTest
    public static void BadgeHelperData(){
        
        Account a = new Account();
        a.First_Name__c = 'Bob';
        a.Last_Name__c = 'Apples';
        a.Name = '123';
        a.E_Mail__c = 'bazam123@gmail.com';
        a.BadgeServiceItems__c = 'A10101;A10102;';
        insert a;
  
        Opportunity Sale = new Opportunity();
        Sale.AccountId = a.Id;
        Sale.Name = 'Test Opp';
        Sale.CloseDate = system.today();
        Sale.StageName = 'Closed Won';
        Sale.Service_Item_List__c = 'A11001;A52211;';
        Sale.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Bookkeeping').getRecordTypeId();
        Sale.Admin_Portal_Sale__c = False;
        Sale.Override_Automation__c	= True;
        Test.startTest();
        insert Sale;
        
        delete Sale;
        Test.stopTest();
        
    }
    @isTest
    public static void checkElse() {
        Account a = new Account();
        a.First_Name__c = 'Bob';
        a.Last_Name__c = 'Apples';
        a.Name = '123';
        a.E_Mail__c = 'bazam123@gmail.com';
        insert a;
        
        Opportunity Sale = new Opportunity();
        Sale.AccountId = a.Id;
        Sale.Name = 'Test Opp';
        Sale.CloseDate = system.today();
        Sale.StageName = 'Closed Won';
        Sale.Service_Item_List__c = 'A11001;A52211;';
        Sale.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Bookkeeping').getRecordTypeId();
        Sale.Admin_Portal_Sale__c = False;
        Sale.Override_Automation__c	= True;
        insert Sale;
    }
}