objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Important_Notes__c</fullName>
        <inlineHelpText>Extremely important information regarding a client&apos;s account goes here.  Marriage, divorce, separation from business partner, deaths, etc.  Notes regarding renewals or general phone calls get logged in the activity history.</inlineHelpText>
        <label>Important Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/box__FRUP__c.object
<CustomObject>
    <fields>
        <fullName>box__Folder_ID__c</fullName>
        <externalId>true</externalId>
        <label>Folder ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>box__Record_ID__c</fullName>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>FRUP</label>
    <nameField>
        <displayFormat>FRUP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRUP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/boxforcommunitiesDesignTest.cls
@isTest(SeeAllData=true)

public class boxforcommunitiesDesignTest {
     static testmethod void boxforcommunitiesDesignTestClass(){
         Test.startTest();
          Account acc=new account();
        acc.Name='test name';
 		acc.First_Name__c='Bob Test acc';
        acc.Last_Name__c='Apples';
        acc.Important_Notes__c='test important notes';
        insert acc;
  
         
         ApexPages.currentPage().getParameters().put('Id',acc.id);
         boxforcommunitiesDesign.doinit();
          boxforcommunitiesDesign.createAttachmentinBox();
            boxforcommunitiesDesign.getthecreatedfolder();
         test.stopTest();
      
     }
     static testmethod void boxforcommunitiesDesignTestClass2(){
         Test.startTest();
          Account acc=new account();
        acc.Name='test name';
 		acc.First_Name__c='Bob Test acc';
        acc.Last_Name__c='Apples';
        acc.Important_Notes__c='test important notes';
        insert acc;
    box__FRUP__c bfL=new box__FRUP__c();
         bfL.box__Folder_ID__c='122457680707';
         bfL.box__Record_ID__c=acc.id;
         insert bfL;
         
         ApexPages.currentPage().getParameters().put('Id',acc.id);
         boxforcommunitiesDesign.doinit();
         test.stopTest();
      
     }

}