objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Set_of_Books__c.object
<CustomObject>
    <fields>
        <fullName>April_Bookkeeping_Status__c</fullName>
        <label>April Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Aug_Bookkeeping_Status__c</fullName>
        <label>Aug Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Admin</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeping_Reviewer__c</fullName>
        <label>Bookkeeping Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Reviewer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeping_Status__c</fullName>
        <label>Jan Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dec_Bookkeeping_Status__c</fullName>
        <label>Dec Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feb_Bookkeeping_Status__c</fullName>
        <label>Feb Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>July_Bookkeeping_Status__c</fullName>
        <label>July Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>June_Bookkeeping_Status__c</fullName>
        <label>June Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mar_Bookkeeping_Status__c</fullName>
        <label>Mar Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>May_Bookkeeping_Status__c</fullName>
        <label>May Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nov_Bookkeeping_Status__c</fullName>
        <label>Nov Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oct_Bookkeeping_Status__c</fullName>
        <label>Oct Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sep_Bookkeeping_Status__c</fullName>
        <label>Sep Bookkeeping Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Set of Books</label>
    <nameField>
        <label>Set of Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Set of Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Bookkeeping_Admin.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abdur Rehman</fullName>
    </customValue>
    <customValue>
        <fullName>Abraham Carrillo</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Hendershot</fullName>
    </customValue>
    <customValue>
        <fullName>Angela Berrow</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Langer</fullName>
    </customValue>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>awais khan</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Arnold</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Bobby Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Bruce Williams</fullName>
    </customValue>
    <customValue>
        <fullName>Carol Spagnoletta</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Conrad Gomez</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Dawson Phipps</fullName>
    </customValue>
    <customValue>
        <fullName>Doug Guard</fullName>
    </customValue>
    <customValue>
        <fullName>Hebert Romero</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Petrunyak</fullName>
    </customValue>
    <customValue>
        <fullName>Jerome Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Joel Evans</fullName>
    </customValue>
    <customValue>
        <fullName>John Doe</fullName>
    </customValue>
    <customValue>
        <fullName>Jonna States</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Fleming</fullName>
    </customValue>
    <customValue>
        <fullName>Kelly Van Middlesworth</fullName>
    </customValue>
    <customValue>
        <fullName>Kenneth Harrah</fullName>
    </customValue>
    <masterLabel>Bookkeeping Admin</masterLabel>
</GlobalValueSet>

globalValueSets/Bookkeeping_Reviewer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Kiera Dunphy</fullName>
    </customValue>
    <customValue>
        <fullName>Lanzi Reel</fullName>
    </customValue>
    <customValue>
        <fullName>Ryan On</fullName>
    </customValue>
    <customValue>
        <fullName>Trisha Cullinane</fullName>
    </customValue>
    <customValue>
        <fullName>Troy Butler</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Nancy Naraine</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Kevin Dennis</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Flemming</fullName>
    </customValue>
    <customValue>
        <fullName>Tesia Owen</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
        <isActive>false</isActive>
        <label>Bethany Castleberry</label>
    </customValue>
    <customValue>
        <fullName>Christine Zimmerman</fullName>
        <isActive>false</isActive>
        <label>Christine Zimmerman</label>
    </customValue>
    <customValue>
        <fullName>Rebecca Gallegos</fullName>
        <isActive>false</isActive>
        <label>Rebecca Gallegos</label>
    </customValue>
    <customValue>
        <fullName>Marie Pues</fullName>
        <isActive>false</isActive>
        <label>Marie Pues</label>
    </customValue>
    <customValue>
        <fullName>Maria Boone</fullName>
        <isActive>false</isActive>
        <label>Maria Boone</label>
    </customValue>
    <masterLabel>Bookkeeping Reviewer</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Bookkeeping_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Client</fullName>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Review Notes</fullName>
    </customValue>
    <customValue>
        <fullName>Send Financials</fullName>
    </customValue>
    <customValue>
        <fullName>Client Unresponsive</fullName>
    </customValue>
    <customValue>
        <fullName>Stopped Services</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Sent to Tax</fullName>
        <isActive>false</isActive>
        <label>Completed - Sent to Tax</label>
    </customValue>
    <customValue>
        <fullName>Completed - Moved to Ongoing</fullName>
        <isActive>false</isActive>
        <label>Completed - Moved to Ongoing</label>
    </customValue>
    <masterLabel>Bookkeeping Status</masterLabel>
</GlobalValueSet>

classes/SetOfBooksBeforeHandlerTest.cls
@istest
public with sharing class SetOfBooksBeforeHandlerTest {
    @testSetup
    public static void createData() {
        
        Account a = new Account();
        a.Name = 'Test Account';
        insert a;

        Set_of_Books__c bookset = new Set_Of_Books__c();
        bookset.Client__c = a.id;
        bookset.Name = 'Test Bookset';
        insert bookset;
    }

    @isTest
    public static void updateTestBookkeepingReviewer() {
        Set_of_Books__c sob = [Select Id, Name, Bookkeeper__c, Bookkeeping_Reviewer__c, Bookkeeping_Status__c, Feb_Bookkeeping_Status__c, Mar_Bookkeeping_Status__c, April_Bookkeeping_Status__c, May_Bookkeeping_Status__c, June_Bookkeeping_Status__c, July_Bookkeeping_Status__c, Aug_Bookkeeping_Status__c, Sep_Bookkeeping_Status__c, Oct_Bookkeeping_Status__c, Nov_Bookkeeping_Status__c, Dec_Bookkeeping_Status__c, Client__r.Name From Set_of_Books__c Limit 1];
        
        sob.Bookkeeper__c = 'Ashley Cloutier';
        sob.Bookkeeping_Reviewer__c = 'Ashley Cloutier';
        update sob;

        sob.Bookkeeping_Status__c = 'Review';
        update sob;

        sob.Feb_Bookkeeping_Status__c = 'Completed';
        update sob;

        sob.Mar_Bookkeeping_Status__c = 'Review';
        update sob;

        sob.April_Bookkeeping_Status__c = 'Completed';
        update sob;

        sob.May_Bookkeeping_Status__c = 'Review';
        update sob;

        sob.June_Bookkeeping_Status__c = 'Completed';
        update sob;

        sob.July_Bookkeeping_Status__c = 'Review';
        update sob;

        sob.Aug_Bookkeeping_Status__c = 'Completed';
        update sob;

        sob.Sep_Bookkeeping_Status__c = 'Review';
        update sob;

        sob.Oct_Bookkeeping_Status__c = 'Completed';
        update sob;

        sob.Nov_Bookkeeping_Status__c = 'Review';
        update sob;

        sob.Dec_Bookkeeping_Status__c = 'Completed';
        update sob;
    }

    @isTest
    public static void updateTestBookkeeper() {
        Set_of_Books__c sob = [Select Id, Name, Bookkeeper__c, Bookkeeping_Reviewer__c, Bookkeeping_Status__c, Feb_Bookkeeping_Status__c, Mar_Bookkeeping_Status__c, April_Bookkeeping_Status__c, May_Bookkeeping_Status__c, June_Bookkeeping_Status__c, July_Bookkeeping_Status__c, Aug_Bookkeeping_Status__c, Sep_Bookkeeping_Status__c, Oct_Bookkeeping_Status__c, Nov_Bookkeeping_Status__c, Dec_Bookkeeping_Status__c, Client__r.Name From Set_of_Books__c Limit 1];
        
        sob.Bookkeeper__c = 'Ashley Cloutier';
        sob.Bookkeeping_Reviewer__c = 'Ashley Cloutier';
        update sob;

        sob.Bookkeeping_Status__c = 'Review Notes';
        update sob;

        sob.Feb_Bookkeeping_Status__c = 'Send Financials';
        update sob;

        sob.Mar_Bookkeeping_Status__c = 'Review Notes';
        update sob;

        sob.April_Bookkeeping_Status__c = 'Send Financials';
        update sob;

        sob.May_Bookkeeping_Status__c = 'Review Notes';
        update sob;

        sob.June_Bookkeeping_Status__c = 'Send Financials';
        update sob;

        sob.July_Bookkeeping_Status__c = 'Review Notes';
        update sob;

        sob.Aug_Bookkeeping_Status__c = 'Send Financials';
        update sob;

        sob.Sep_Bookkeeping_Status__c = 'Review Notes';
        update sob;

        sob.Oct_Bookkeeping_Status__c = 'Send Financials';
        update sob;

        sob.Nov_Bookkeeping_Status__c = 'Review Notes';
        update sob;

        sob.Dec_Bookkeeping_Status__c = 'Send Financials';
        update sob;
    }

    @isTest
    public static void insertTest() {
        Account a = [Select Id from Account Limit 1];

        Set_of_Books__c bookset = new Set_Of_Books__c();
        bookset.Client__c = a.id;
        bookset.Name = 'Test Bookset1';
        bookset.Bookkeeper__c = 'Ashley Cloutier';
        insert bookset;

        Set_of_Books__c bookset2 = new Set_Of_Books__c();
        bookset2.Client__c = a.id;
        bookset2.Name = 'Test Bookset2';
        bookset2.Bookkeeping_Reviewer__c = 'Ashley Cloutier';
        insert bookset2;
    }
}