objects/Account.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The rep who Originally created the Blueprint</inlineHelpText>
        <label>Blueprint Created by:</label>
        <referenceTo>Sales_Rep__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>Sales_Rep__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>Sales_Rep__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Sales_rep__c</fullName>
        <formula>Opportunity.Sales_Rep__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Rep</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Rep__c.object
<CustomObject>
    <label>Sales Rep</label>
    <nameField>
        <label>Sales Rep&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/To_Do__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>To Do&apos;s</relationshipLabel>
        <relationshipName>To_Do_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>To Do&apos;s</relationshipLabel>
        <relationshipName>To_Do_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>To Do&apos;s</relationshipLabel>
        <relationshipName>To_Do_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>Sales_Rep__c</referenceTo>
        <relationshipLabel>To Do&apos;s</relationshipLabel>
        <relationshipName>To_Do_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>To Do&apos;s</relationshipLabel>
        <relationshipName>To_Do_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>To Do</label>
    <nameField>
        <label>To Do</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Do&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HomeToDos.cls
public with sharing class HomeToDos 
{
	
	private String sortDirection = 'ASC';
   	private String sortExp = 'name';
	 public String sortExpression
   {
	get
     {
        return sortExp;
     }
     set
     {
       //if the column is clicked on then switch between Ascending and Descending modes
       if (value == sortExp)
         sortDirection = (sortDirection == 'ASC')? 'DESC' : 'ASC';
       else
         sortDirection = 'ASC';
       sortExp = value;
     }
   }
public HomeToDos()
{
	for(Sales_Rep__c s : [select id from Sales_Rep__c])
	{
		TObject.Sales_Rep__c = s.id;
	}
	
}
 public String getSortDirection()
 {
    //if not column is selected 
    if (sortExpression == null || sortExpression == '')
      return 'ASC';
    else
     return sortDirection;
 }

 public void setSortDirection(String value)
 {  
   sortDirection = value;
 }
	public List<SelectOption> getCompleted()
	{
		List<SelectOption> OptionList = new List<SelectOption>();
		OptionList.add(new Selectoption('No','No'));
		OptionList.add(new Selectoption('Yes','Yes'));
		
		
		return OptionList;
	}
	
	public String OptionSelected{get;set;}
	
	public To_Do__c TObject = new To_Do__c();
	
	public To_Do__c getTodo()
	{
		return TObject;
	}
	boolean b = true;
	public void setTodo(String str)
	{
		TObject.Sales_Rep__c = str;
	}
	
	List<To_Do__c> ToDoList = new List<To_Do__c>();
	public List<To_Do__c> getTodoList()
	{
		ViewData();
		return ToDoList;
		
	}
	
	
	 public PageReference ViewData() {
	 	
	 	if(OptionSelected=='Yes')
		{
			b = true;
		}
		else
		b=false;
		
       //build the full sort expression
       string sortFullExp = sortExpression  + ' ' + sortDirection;
       String Query = '';
       if(TObject.Sales_Rep__c!=null)
       {
       		Query = 'select id, name, Date__c,Lead__r.Name,Lead__r.id,Sales_Rep__r.id, Entity__r.Name,Entity__r.id, Completed__c, Sales__r.Name,Sales__r.id, Sales_Rep__r.Name,Client__r.Name, Client__r.id from To_Do__c where Completed__c = '+ b+' and Sales_Rep__c =\''+TObject.Sales_Rep__c+'\'  order by ' + sortFullExp;
       }
       else
       {
       	Query = 'select id, name, Date__c,Lead__r.Name,Lead__r.id,Sales_Rep__r.id, Entity__r.Name,Entity__r.id, Completed__c, Sales__r.Name,Sales__r.id, Sales_Rep__r.Name,Client__r.Name, Client__r.id from To_Do__c where Completed__c = '+ b+' and Sales_Rep__c =null  order by ' + sortFullExp;
       }
     //[select id, name, Date__c,Lead__r.Name,Lead__r.id,Sales_Rep__r.id, Entity__r.Name,Entity__r.id, Completed__c, Sales__r.Name,Sales__r.id, Sales_Rep__r.Name,Client__r.Name, Client__r.id from To_Do__c where Completed__c =: b and Sales_Rep__c =: TObject.Sales_Rep__c];LIKE\'%'+fname+'%\'
       //query the database based on the sort expression
       System.debug('***********************'+sortFullExp);
       ToDoList = Database.query(Query);
     /*  for(To_Do__c t : Database.query(Query))
       {
       		if(t.Completed__c == b && t.Sales_Rep__c==TObject.Sales_Rep__c)
       		{
       			ToDoList.add(t);
       		}
       }
      */
       return null;
   }
   
   
   
}