objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <label>Assigned Client Success Coordinator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CSR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSR_Email__c</fullName>
        <formula>Assigned_Law_Coordinator_Email__c

/* changed by shobi -LC_email__c*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <businessProcess>Operation Help desk</businessProcess>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Mail</fullName>
        <active>true</active>
        <businessProcess>Feedback</businessProcess>
        <description>Used for Mail Forwarding Cases</description>
        <label>Mail</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Credit_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Detail</relationshipLabel>
        <relationshipName>Credit_Card_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>AMEX: first digit = 3, second digit = 4 or 7. Valid length: 15 digits.
VISA: first digit = 4. Valid length: 13 or 16 digits.
MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</description>
        <inlineHelpText>AMEX: first digit = 3, second digit = 4 or 7.  Valid length: 15 digits.

VISA: first digit = 4.  Valid length: 13 or 16 digits.

MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</inlineHelpText>
        <label>Card Number</label>
        <length>19</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Mail_Check__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Mail Check</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Platinum_Subscription_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if uses for platinum payment.</inlineHelpText>
        <label>Platinum Subscription Card</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card Detail</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>Used for Emails</description>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/CSR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aaron Bernhardt</fullName>
    </customValue>
    <customValue>
        <fullName>Adrienne Harper</fullName>
    </customValue>
    <customValue>
        <fullName>Alexa Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Alyssa Hoopii</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Zipprich</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Yadao</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Seguin</fullName>
    </customValue>
    <customValue>
        <fullName>Branden Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Brittany Rains</fullName>
    </customValue>
    <customValue>
        <fullName>Carly Coons</fullName>
    </customValue>
    <customValue>
        <fullName>Carrie J. Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Channell Palmer</fullName>
    </customValue>
    <customValue>
        <fullName>Chase Foster</fullName>
    </customValue>
    <customValue>
        <fullName>Christian DeField</fullName>
    </customValue>
    <customValue>
        <fullName>Claire Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Colette Grier</fullName>
    </customValue>
    <customValue>
        <fullName>Dana Heckathorn</fullName>
    </customValue>
    <customValue>
        <fullName>Deborah Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Domanick Page-Whitaker</fullName>
    </customValue>
    <customValue>
        <fullName>Duncan Bjerke</fullName>
    </customValue>
    <customValue>
        <fullName>Gabby Esteban</fullName>
    </customValue>
    <customValue>
        <fullName>Hayley Karlson</fullName>
    </customValue>
    <customValue>
        <fullName>Jade Comer</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Lundquist</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Nelson</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Seibert</fullName>
    </customValue>
    <customValue>
        <fullName>Jessica Thornton</fullName>
    </customValue>
    <customValue>
        <fullName>Kaila Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Katherine Baez</fullName>
    </customValue>
    <customValue>
        <fullName>Kim Austin</fullName>
    </customValue>
    <description>Assigned CSR</description>
    <masterLabel>CSR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/SendEmailToCSRTriggerHandler.cls
public class SendEmailToCSRTriggerHandler {
    
    public static boolean isRecurive = true;
    
    public static void getProcess(List<Credit_Card_Detail__c> newItem){
        system.debug('newItem == ' + newItem);
        if(isRecurive){
            List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();
            List<Account> accLst =  new List<Account>();
            List<Task> tasks = new List<Task>(); 
            map<Id,Credit_Card_Detail__c> accMap = new map<Id,Credit_Card_Detail__c>();
            map<Id,Decimal> mailMap = new map<Id,Decimal>();
            for(Credit_Card_Detail__c cc : newItem){  
                system.debug('Platinum_Subscription_Card__c == ' + cc.Platinum_Subscription_Card__c);
                accMap.put(cc.Account__c, cc);  
                system.debug('Mail_Check__c == ' + cc.Mail_Check__c);
                mailMap.put(cc.id, cc.Mail_Check__c);
            }
            map<String,Id> userMap = new map<String,Id>();
            for(User u :[SELECT Id, name from User]){
                userMap.put(u.name,u.id);
            }
            //User u = [SELECT Id, name from User where name Like '%Michael Preseren%' LIMIT 1];
            for(Account acc : [SELECT Id, Name, Assigned_CSR__c, LastName, FirstName, CSR_Email__c, First_Name__c, Last_Name__c FROM Account where id IN :accMap.keySet()] ){
                Credit_Card_Detail__c cardNumber = accMap.get(acc.Id);
                String evt = '';
                Integer mailVal = integer.valueOf(mailMap.get(cardNumber.id));
                system.debug('Mail Val = ' + mailVal);
                
                if(mailVal == 1){
                    
                    if(Trigger.isInsert) {
                        evt = 'inserted';
                    } 
                    if(Trigger.isUpdate) {
                        evt = 'updated';
                    }
                    
                    Task tsk = new Task();
                    tsk.Subject = 'Card '+ evt ;
                    tsk.whatID = acc.Id;
                    
                    if(acc.Assigned_CSR__c != null && userMap.get(acc.Assigned_CSR__c) != null){    
                        tsk.OwnerId = userMap.get(acc.Assigned_CSR__c);
                    }else{            
                        tsk.OwnerId = userMap.get('Michael Preseren');  
                    }
                    
                    Integer charLength = cardNumber.Card_Number__c.length();
                    
                    String res = cardNumber.Card_Number__c.right(charLength - (charLength-4));
                    String regExp = '[0-9]';
                    String dummyCsrName = ''; 
                    if(acc.Assigned_CSR__c != null && userMap.get(acc.Assigned_CSR__c) != null){ 
                        dummyCsrName = acc.Assigned_CSR__c; 
                    }else{
                        dummyCsrName = ''; 
                    }
                    
                    string dummyCardNo = cardNumber.Card_Number__c.replaceAll(regExp, '*').substring(0,charLength-4);
                    // String accountLinkUrl = 'https://andersonadvisors--comm--c.cs19.visual.force.com/'+acc.Id; // for sandbox
                    String accountLinkUrl = 'https://na48.salesforce.com/'+acc.Id; // for production 
                    String accountName = '<a href='+accountLinkUrl+'>'+acc.First_Name__c+' '+ acc.Last_Name__c +'</a></br>';
                    tsk.Description = 'Hi '+ dummyCsrName +', Client with name '+acc.First_Name__c+' '+ acc.Last_Name__c +' with card number '+ dummyCardNo +res +' has '+ evt +' their platinum payment card in community portal.'; 
                    tasks.add(tsk);
                    system.debug('Platinum_Subscription_Card__c = ' + cardNumber.Platinum_Subscription_Card__c);
                    if(cardNumber.Platinum_Subscription_Card__c == true){ 
                        if(acc.CSR_Email__c != null){
                            
                            Messaging.SingleEmailMessage mail =  new Messaging.SingleEmailMessage();            
                            //  list of people who should get the email            
                            List<String> sendTo = new List<String>();
                            sendTo.add(acc.CSR_Email__c);
                            mail.setToAddresses(sendTo);            
                            // Set email is sent from
                            mail.setReplyTo('noreply@andersonadvisors.com');
                            mail.setSenderDisplayName('Anderson Advisors');            
                            // Set email contents
                            mail.setSubject('Client Platinum Payment Card');
                            //String body = 'Dear ' + usr.FirstName +' '+ usr.LastName + ', ';
                            String body = 'Hi '+ dummyCsrName +', Client with name '+ accountName +' with card number '+ dummyCardNo +res +' has '+ evt +' their platinum payment card in community portal.';                 
                            mail.setHtmlBody(body);        
                            // Add your email to the master list
                            mails.add(mail);                
                        }
                    }
                }
                
                if(cardNumber.Platinum_Subscription_Card__c == true){
                   changeCardDetails(cardNumber.id,cardNumber.Account__c);
                }
                
            }
                //Shobi- Commenting based on Savannah's request Case : 00088853:Card Insterted/Updated Tasks
            /*if(tasks.size() > 0) {
            
              //  insert tasks;
                if(mails.size() > 0){
                    // Send all emails in the master list
                    if(!test.isRunningTest()){
                    //    Messaging.sendEmail(mails);
                    }
                    system.debug('=== Mail Sent ===');
                }
            }*/
            isRecurive = false;
        }
    }
    
    /**
* This method is used to udpate Mail Check Field on credit card object.
* 
* @author Prateeks
* @date Apr 24, 2019
*/
    public static void changeCardDetails(Id cardId, Id accId) {
       
            List<Credit_Card_Detail__c> CardListToUpd = new List<Credit_Card_Detail__c>();
            for (Credit_Card_Detail__c cardChk : [SELECT Id, Account__c, Platinum_Subscription_Card__c FROM Credit_Card_Detail__c where id != : cardId and Account__c = :accId and Platinum_Subscription_Card__c = true]){
                cardChk.Platinum_Subscription_Card__c = false;
                CardListToUpd.add(cardChk);
            }
            if(CardListToUpd.size()>0){
                update CardListToUpd;
                
            }
       
    }
    
}