objects/Account.object
<CustomObject>
    <fields>
        <fullName>BadgeServiceItems__c</fullName>
        <label>BadgeServiceItems</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unlimited_Nominee_Transaction_Date__c</fullName>
        <description>Used in Badge Formula. The Unlimited Nominee expiration is 365 days from this date.
SCH-0076</description>
        <inlineHelpText>Unlimited Nominee Expiration is 365 days from this date.</inlineHelpText>
        <label>Unlimited Nominee Transaction Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ChargentSFA__Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Gateway_ID__c</fullName>
        <label>Gateway ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gateway</label>
        <referenceTo>ChargentBase__Gateway__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Client Referral Credit</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Credit to be used</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Wire Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Response_Status__c</fullName>
        <label>Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default should be &apos;LV&apos;.</inlineHelpText>
        <label>Gateway</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose an Active Gateway record</errorMessage>
            <filterItems>
                <field>ChargentBase__Gateway__c.ChargentBase__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ChargentBase__Gateway__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                    <default>true</default>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Transaction__c</fullName>
        <description>Date of first approved transaction.</description>
        <inlineHelpText>Date of first approved transaction.</inlineHelpText>
        <label>First Transaction</label>
        <summarizedField>ChargentSFA__Transaction__c.ChargentSFA__Gateway_Date__c</summarizedField>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Response_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>ChargentSFA__Transaction__c.ChargentSFA__Type__c</field>
            <operation>equals</operation>
            <value>Charge</value>
        </summaryFilterItems>
        <summaryForeignKey>ChargentSFA__Transaction__c.ChargentSFA__Opportunity__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <label>Service Item List</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ASID__c</fullName>
        <formula>PricebookEntry.Product2.ASID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASID</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/OppserrviceItemRollupTest.cls
@isTest
public class OppserrviceItemRollupTest {
     
    @isTest
    public static void TestServiceItemRolluponOpportunity(){
        TestDatafactoryBulk.createTestData();
           OppServiceItemRollUp.oppLineitemRollupProcessed.clear();
        System.debug('TestDatafactoryBulk.oppLineItemList---'+TestDatafactoryBulk.oppLineItemList.size());
       update TestDatafactoryBulk.oppLineItemList;
        string productId;
        id opportunityID;
        for(OpportunityLineItem oPLI:[Select id,ASID__c,OpportunityId from OpportunityLineItem where id=: TestDatafactoryBulk.oppLineItemList[0].id]){
            productId=oPLI.ASID__c;
            opportunityID=oPLI.OpportunityId;
            break;
        }
        
        opportunity opp=[select id,Service_Item_List__c from opportunity where id=: opportunityID limit 1];
        System.assert(opp.Service_Item_List__c.contains(productId), 'Please check!');
      
    }
        @isTest
     public static void TestServiceItemRolluponAccount(){
        TestDatafactoryBulk.createTestData();
         
           OppServiceItemRollUp.oppLineitemRollupProcessed.clear();
       
      
        string productId;
        id opportunityID;
        for(OpportunityLineItem oPLI:[Select id,ASID__c,OpportunityId from OpportunityLineItem where id=: TestDatafactoryBulk.oppLineItemList[0].id]){
            productId=oPLI.ASID__c;
            opportunityID=oPLI.OpportunityId;
            break;
        }
        
        opportunity opp=[select id,Service_Item_List__c,stageName,Amount,AccountId,First_Transaction__c from opportunity where id=: opportunityID limit 1];
         
        
      
         
          ChargentSFA__Transaction__c Tranaction=    (ChargentSFA__Transaction__c)TestDataFactory.createSObject('ChargentSFA__Transaction__c', new Map<String,Object>{
  'ChargentSFA__Gateway_ID__c' => '1234 ',
  'ChargentSFA__Opportunity__c' =>opp.id,
      'ChargentSFA__Gateway__c'=>TestDatafactoryBulk.Gateway.id,
      'ChargentSFA__Amount__c'=>opp.Amount,
      'ChargentSFA__Payment_Method__c'=>'Credit Card',
      'ChargentSFA__Response_Status__c'=>'Approved'
     
}); 
            opportunity updatedopp=[select id,Service_Item_List__c,stageName,Amount,AccountId,First_Transaction__c from opportunity where id=: opportunityID limit 1];
         // Test.setCreatedDate(Tranaction.id, DateTime.now().addMinutes(-5));
            Test.startTest();
        // now = DateTime.now().addMinutes(5);
          System.debug('AccountID--'+opp.AccountId);
         Account Acc=[Select id,BadgeServiceItems__c from Account where id=:opp.AccountId limit 1];
     
    List<FlowInterview> flowInterviews = [SELECT Id FROM FlowInterview];
        System.assertEquals(1, flowInterviews.size());
           BadgesDisplayLogic.BadgesDisplayParameter bd=new  BadgesDisplayLogic.BadgesDisplayParameter();
         bd.accId=Acc.id;
           bd.ServiceItems=opp.Service_Item_List__c;
          List<BadgesDisplayLogic.BadgesDisplayParameter> Params=new List< BadgesDisplayLogic.BadgesDisplayParameter>();
           Params.add(bd);
        BadgesDisplayLogic.updateExpDateAndServiceListOnAcc(Params);
         Account Updatecheck=[Select id,Unlimited_Nominee_Transaction_Date__c from Account where id=: bd.accId limit 1];
         System.assertEquals(updatedopp.First_Transaction__c,Updatecheck.Unlimited_Nominee_Transaction_Date__c , 'Please check!');
         
           Test.stopTest();
        
    }
      @isTest
     public static void TestServiceItemDelete(){
        TestDatafactoryBulk.createTestData();
         
         
        System.debug('TestDatafactoryBulk.oppLineItemList---'+TestDatafactoryBulk.oppLineItemList.size());
      
        string productId;
        id opportunityID;
        for(OpportunityLineItem oPLI:[Select id,ASID__c,OpportunityId from OpportunityLineItem where id=: TestDatafactoryBulk.oppLineItemList[0].id]){
            productId=oPLI.ASID__c;
            opportunityID=oPLI.OpportunityId;
            break;
        }
        Test.startTest();
     
           OppServiceItemRollUp.oppLineitemRollupProcessed.clear();
         DeleteAccountBadgeService.DeleteoppLineitemRollupProcessed.clear();
         delete TestDatafactoryBulk.oppLineItemList[0];
            opportunity opp=[select id,Service_Item_List__c,stageName,Amount,AccountId,First_Transaction__c from opportunity where id=: opportunityID limit 1];
         
        System.debug('productId==='+productId);
          System.debug('opp.Service_Item_List__c==='+opp.Service_Item_List__c);
        String oppserviceitem=opp.Service_Item_List__c;
        System.assert(oppserviceitem!=productId, 'Please check!');
     
      
    
           Test.stopTest();
        
    }
}