objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ChargentBase__Gateway__c.object
<CustomObject>
    <description>Configuration object. The administrator should create ONE account for the appropriate payment gateway.</description>
    <fields>
        <fullName>ChargentBase__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Available_Payment_Methods__c</fullName>
        <inlineHelpText>In Payment Console this field controls which Payment Methods are available to users.</inlineHelpText>
        <label>Available Payment Methods</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>eCheck</fullName>
                </value>
                <value>
                    <fullName>Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>Cash Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platinum_Website_Gateway__c</fullName>
        <description>Controls which Gateway payments coming from the Platinum membership site are run through. Does not affect Platinum recurring billing sales.</description>
        <inlineHelpText>Mark this field yes if you want this Gateway to run all payments coming from the Platinum membership site. Triple-check that there is only one single Gateway in Salesforce with this field marked Yes.</inlineHelpText>
        <label>Platinum Website Gateway</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Credit_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Detail</relationshipLabel>
        <relationshipName>Credit_Card_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>AMEX: first digit = 3, second digit = 4 or 7. Valid length: 15 digits.
VISA: first digit = 4. Valid length: 13 or 16 digits.
MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</description>
        <inlineHelpText>AMEX: first digit = 3, second digit = 4 or 7.  Valid length: 15 digits.

VISA: first digit = 4.  Valid length: 13 or 16 digits.

MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</inlineHelpText>
        <label>Card Number</label>
        <length>19</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <description>American Express cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</description>
        <inlineHelpText>AMEX cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</inlineHelpText>
        <label>Card Security Code</label>
        <length>5</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Platinum_Subscription_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if uses for platinum payment.</inlineHelpText>
        <label>Platinum Subscription Card</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card Detail</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <label>Card Security</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Number__c</fullName>
        <inlineHelpText>Please enter the complete credit card number without spaces or dashes</inlineHelpText>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>QB_Invoice_Number__c</fullName>
        <displayFormat>{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </fields>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CustomPaymentApiTest.cls
@isTest
public class CustomPaymentApiTest {
    
    @testSetup
    static void dataSetup() {
        Account acctest = new Account(
            Name='Test Account1',
            First_Name__c='Edward',
            Last_Name__c='Lee'
           );
        insert acctest;
        Credit_Card_Detail__c  ccd = new Credit_Card_Detail__c ();
        ccd.Account__c = acctest.Id;
        ccd.Card_Month__c = '04';
        ccd.Card_Number__c = '1234567896541236';
        ccd.Card_Security__c = '777';
        ccd.Card_Type__c = 'visa';
        ccd.Card_Year__c = '2020'; 
        ccd.Platinum_Subscription_Card__c = true;
        insert ccd;
        ChargentBase__Gateway__c cb = new ChargentBase__Gateway__c ();
        cb.Name = 'AuthorizeNetTestPayment';
        cb.ChargentBase__Active__c = true;
        cb.ChargentBase__Available_Payment_Methods__c = 'Credit Card';
        insert cb;
        ChargentBase__Gateway__c cbb = new ChargentBase__Gateway__c ();
        cbb.Name = 'Platinum';
        cbb.ChargentBase__Active__c = true;
        cbb.Platinum_Website_Gateway__c = 'Yes';
        cbb.ChargentBase__Available_Payment_Methods__c = 'Credit Card';
        insert cbb;
        String cardnumberVal= '123456789654';
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Closed Won';
        opp.AccountId = acctest.Id;
        opp.CloseDate = Date.newInstance(2018, 09, 1);
        //opp.QB_Invoice_Number__c = '1234';
        opp.ChargentSFA__Card_Number__c = cardnumberVal;
        insert opp;
        
        Opportunity opp2 = new Opportunity();
        opp2.Name = 'Testing';
        opp2.StageName = 'Closed Won';
        opp2.AccountId = acctest.Id;
        opp2.CloseDate = Date.newInstance(2018, 09, 10);
        //opp.QB_Invoice_Number__c = '12345';
        opp.ChargentSFA__Card_Number__c = cardnumberVal;
        insert opp2;
        
    }
    static testMethod void testGet() {
        Account acc = [ SELECT Id FROM Account LIMIT 1 ];
        Opportunity opp=[select id from Opportunity LIMIT 1];
        Credit_Card_Detail__c cc=[select id from Credit_Card_Detail__c LIMIT 1];
        
        List<Opportunity> commaSepIds = [select Id from Opportunity LIMIT 10];
        String[] tmp1 = New String[]{};
            for(Opportunity op : commaSepIds){
                tmp1.add(op.id);
            }
        String idString = string.join(tmp1,',');
        system.debug(' == idString === ' + idString);
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
        req.requestURI = '/services/apexrest/CustomPayment/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response= res;
        string s=CustomPaymentApi.getOppId(idString,cc.id);        
    }
    static testMethod void testGet2() {
        Account acc1 = [ SELECT Id FROM Account LIMIT 1 ];
        Opportunity opp2=[select id from Opportunity LIMIT 1];
        Credit_Card_Detail__c cc=[select id from Credit_Card_Detail__c LIMIT 1];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
        req.requestURI = '/services/apexrest/CustomPayment/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response= res;
        string s=CustomPaymentApi.getOppId(opp2.id,cc.id);        
    }
}