objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <description>Cam Assigned to the account</description>
        <label>Assigned CAM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CAM</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <label>Assigned Client Success Coordinator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CSR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bookkeeper assigned.</inlineHelpText>
        <label>Bookkeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original source of the client.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_CAM__c</fullName>
        <formula>TEXT(Account.Assigned_CAM__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned CAM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_CSR__c</fullName>
        <formula>TEXT(Account.Assigned_CSR__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Success Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <inlineHelpText>The original Campaign associated with the Contact when converted from a Lead.</inlineHelpText>
        <label>Parent Client Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/CAM.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alexandria Lessard</fullName>
    </customValue>
    <customValue>
        <fullName>Mary Borden</fullName>
    </customValue>
    <customValue>
        <fullName>Matthew Smidowicz</fullName>
    </customValue>
    <customValue>
        <fullName>Team Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 6</fullName>
    </customValue>
    <customValue>
        <fullName>Temp CAM 7</fullName>
    </customValue>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Brown</fullName>
        <isActive>false</isActive>
        <label>Christina Brown</label>
    </customValue>
    <customValue>
        <fullName>Danielle Blair</fullName>
        <isActive>false</isActive>
        <label>Danielle Blair</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <customValue>
        <fullName>Joseph Sacco</fullName>
        <isActive>false</isActive>
        <label>Joseph Sacco</label>
    </customValue>
    <customValue>
        <fullName>Erica Terrell</fullName>
        <isActive>false</isActive>
        <label>Erica Terrell</label>
    </customValue>
    <customValue>
        <fullName>Savannah Wallace</fullName>
        <isActive>false</isActive>
        <label>Savannah Wallace</label>
    </customValue>
    <customValue>
        <fullName>Crystal Smerdel</fullName>
        <isActive>false</isActive>
        <label>Crystal Smerdel</label>
    </customValue>
    <description>Cams assigned</description>
    <masterLabel>CAM</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/CSR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aaron Bernhardt</fullName>
    </customValue>
    <customValue>
        <fullName>Adrienne Harper</fullName>
    </customValue>
    <customValue>
        <fullName>Alexa Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Alyssa Hoopii</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Zipprich</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Yadao</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Seguin</fullName>
    </customValue>
    <customValue>
        <fullName>Branden Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Brittany Rains</fullName>
    </customValue>
    <customValue>
        <fullName>Carly Coons</fullName>
    </customValue>
    <customValue>
        <fullName>Carrie J. Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Channell Palmer</fullName>
    </customValue>
    <customValue>
        <fullName>Chase Foster</fullName>
    </customValue>
    <customValue>
        <fullName>Christian DeField</fullName>
    </customValue>
    <customValue>
        <fullName>Claire Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Colette Grier</fullName>
    </customValue>
    <customValue>
        <fullName>Dana Heckathorn</fullName>
    </customValue>
    <customValue>
        <fullName>Deborah Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Domanick Page-Whitaker</fullName>
    </customValue>
    <customValue>
        <fullName>Duncan Bjerke</fullName>
    </customValue>
    <customValue>
        <fullName>Gabby Esteban</fullName>
    </customValue>
    <customValue>
        <fullName>Hayley Karlson</fullName>
    </customValue>
    <customValue>
        <fullName>Jade Comer</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Lundquist</fullName>
    </customValue>
    <customValue>
        <fullName>Jason Nelson</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Seibert</fullName>
    </customValue>
    <customValue>
        <fullName>Jessica Thornton</fullName>
    </customValue>
    <customValue>
        <fullName>Kaila Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Katherine Baez</fullName>
    </customValue>
    <customValue>
        <fullName>Kim Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Ambria Tibbs</fullName>
        <isActive>false</isActive>
        <label>Ambria Tibbs</label>
    </customValue>
    <customValue>
        <fullName>Sara Winter</fullName>
        <isActive>false</isActive>
        <label>Sara Winter</label>
    </customValue>
    <description>Assigned CSR</description>
    <masterLabel>CSR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ChangePasswordCalloutTest.cls
@isTest(seeAllData=false)
public class ChangePasswordCalloutTest {
    
    @isTest static void testChagepasswordCallout(){
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('staticChangePassword');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, mock);
        
        UserRole portalRole = [Select Id, PortalRole From UserRole Where Name = 'Platinum User' Limit 1];
        User thisUser = [select Id, AccountId,ContactId from User where UserRoleId = :portalRole.Id Limit 1]; 
        //Contact primaryCon = [SELECT Id From Contact WHERE Account_Roles__c = 'Primary Contact' Limit 1];
         
        Id pp = [select id from profile where name='Partner Community User'].id;
        Integer cseLstSze = 15;
        Id p = [select id from profile where name='Partner Community User'].id;
        Campaign cmp = new Campaign();
        cmp.Name = 'Steve';
        insert cmp;  
        
        Account testAccount = new Account();
        testAccount.Name='Test Account';
        testAccount.First_Name__c='Edward';
        testAccount.Last_Name__c='Lee';
        testAccount.Campaign__c = cmp.Id;
        testAccount.OwnerId = thisUser.Id;
        //testAccount.Assigned_CAM__c = 'Sara Winter';
        //testAccount.Assigned_CSR__c = 'Ambria Tibbs';
        testAccount.Bookkeeper__c = thisUser.Id;
        testAccount.phone='123456782';
        insert testAccount;
        
        Contact cont = new Contact();
        cont.FirstName = 'FirstName';
        cont.LastName = 'LastName';
        cont.Email='email@email.com';
        cont.phone='12345678';
        cont.AccountId=testAccount.Id;
        cont.Account_Roles__c = 'Primary Contact';
        
        insert cont;
       
        User uzr = new User();
        uzr.FirstName='Chistrian';
        uzr.LastName='Abraham';
        uzr.Email='Chistrian@gmail.com';
        uzr.Username='Chistrian@gmail.com';
        uzr.Alias='autocase';
        uzr.CommunityNickname='Partner_Panelsss';
        uzr.TimeZoneSidKey='GMT';
        uzr.LocaleSidKey='en_US';
        uzr.EmailEncodingKey='UTF-8';
        uzr.ProfileId=pp;
        uzr.LanguageLocaleKey='en_US';
        uzr.ContactId = cont.Id;
        uzr.ProfileId = pp;     
        uzr.IsActive =true;
        //uzr.AccountId = testAccount.Id;
        insert uzr; 
        
        Test.startTest();
        system.runAs(uzr) {
            ChangePasswordCallout.sendNewPwdToWordpress('kaushar@gmail.com', 'Chetu@1231');
            ChangePasswordCallout.preUsername();
        }
        
        Test.stopTest();
        
    }
}