objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Will hold last name of an entity.</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</description>
        <inlineHelpText>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anderson</fullName>
                    <default>true</default>
                    <label>Anderson</label>
                </value>
                <value>
                    <fullName>Client Formed</fullName>
                </value>
                <value>
                    <fullName>Shelf</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Related_Parties__c.object
<CustomObject>
    <fields>
        <fullName>Entities__c</fullName>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Related Parties</relationshipLabel>
        <relationshipName>Related_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_1st_Member_Name__c</fullName>
        <label>Other 1st Member Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_2nd_Member_Name__c</fullName>
        <label>Other 2nd Member Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Entity_Member_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other_Entity_Member_1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Entity_Member_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other Entity Member 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Entity_Member_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other Entity Member 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Entity_Member_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other Entity Member 4</label>
        <type>Checkbox</type>
    </fields>
    <label>Related Parties</label>
    <nameField>
        <label>Related Parties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Processing</fullName>
        <active>true</active>
        <description>Processing Task</description>
        <label>Processing</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateTaskTestClass.cls
@isTest(SeeAllData=false)
public class UpdateTaskTestClass {
    
    public static testmethod void testCreateRelatedListMethod()
    {
        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        testAccount.First_Name__c='Edward';
        testAccount.Last_Name__c='Lee';
        testAccount.phone='123456782';
        insert testAccount;
        Entities__c et = new Entities__c();
        et.RecordTypeId = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType WHERE Name = 'Limited Liability Company (LLC)' and SobjectType = 'Entities__c'].Id; 
        et.Name ='Test Dec Entity';
        et.Origin__c = 'Anderson';
        et.Primary_Client__c =testAccount.id;
        et.Organization_State__c = 'Wyoming';
        et.Status__c = 'Sent To Processing';
        insert et;
        Task t=new Task();
        t.Subject='testing task subject and';       
        t.Priority='Normal';
        t.Description='Testing description 111';
        insert t;
        test.startTest();
        List<Related_Parties__c> relatedPartyList = new List<Related_Parties__c>();
        for(Integer i = 0 ; i<10 ; i++){
            Related_Parties__c related = new Related_Parties__c();
            related.Name='Testing Related'+i;
            related.Entities__c=et.id;
            related.Other_Entity_Member_1__c=true;
            related.Other_Entity_Member_2__c=true;
            related.Other_Entity_Member_4__c=true;
            related.Other_Entity_Member_3__c=true;
            related.Other_1st_Member_Name__c='Testing 1';
            related.Other_2nd_Member_Name__c='Testing 2';
            insert related;
            relatedPartyList.add(related);
        }
        if(relatedPartyList != null){
            try{
                insert relatedPartyList;
            }
            catch(Exception e)
            {}
        }
        
        UpdateTaskforRelatedParties utr=new UpdateTaskforRelatedParties();
        utr.updateTaskCommentByRelOninsert(relatedPartyList); 
        utr.updateTaskCommentByRelOnUpdate(relatedPartyList,'update'); 
        test.stopTest();
        
        Related_Parties__c rel1=[select id,name,Other_Entity_Member_1__c,Other_1st_Member_Name__c from Related_Parties__c where id=:relatedPartyList[0].id];
        rel1.Name='Test 2';
        try{
            update rel1;
        }catch(Exception e)
        {}
    }
}