objects/Account.object
<CustomObject>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ChargentSFA__Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Billing_Address__c</fullName>
        <label>Billing Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Company__c</fullName>
        <label>Billing Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                    <default>true</default>
                    <label>United States</label>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Email__c</fullName>
        <label>Billing Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Fax__c</fullName>
        <label>Billing Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_First__c</fullName>
        <label>Billing First</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Last__c</fullName>
        <label>Billing Last</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Phone__c</fullName>
        <label>Billing Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_State__c</fullName>
        <label>Billing State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Client Referral Credit</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Credit to be used</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Wire Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Billing_Address__c</fullName>
        <label>Billing Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Company__c</fullName>
        <label>Billing Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Email__c</fullName>
        <label>Billing Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Fax__c</fullName>
        <label>Billing Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_First__c</fullName>
        <label>Billing First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Last__c</fullName>
        <label>Billing Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Phone__c</fullName>
        <label>Billing Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Postcode__c</fullName>
        <label>Deprecated (Billing Postcode)</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_State__c</fullName>
        <label>Billing State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ChargentSFA__Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Count__c</fullName>
        <inlineHelpText>If &quot;Payment Stop&quot; is set to &quot;Count&quot; please enter the number of total payments in the series</inlineHelpText>
        <label>Payment Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_End_Date__c</fullName>
        <label>Payment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                    <default>true</default>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Start_Date__c</fullName>
        <label>Payment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>C-Corporation</fullName>
                </value>
                <value>
                    <fullName>S-Corporation</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>CRT</fullName>
                </value>
                <value>
                    <fullName>GRT</fullName>
                </value>
                <value>
                    <fullName>QPRT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entrity_Name__c</fullName>
        <label>Entrity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/testeventSuccessExtension.cls
@isTest
private class testeventSuccessExtension
{
	@isTest
	static void itShould()
	{

                        account acc = new account();
                        acc.Name = 'test';
                        acc.E_Mail__c = 'test@test.com';
                        acc.RecordTypeId = '012U0000000D8qm';
                        insert acc;

                         Opportunity opp = new Opportunity();
                         opp.Name = 'test';
                         opp.AccountId = acc.Id;
                         opp.CloseDate = System.today();
                         opp.StageName = 'Prospecting';
                         opp.Amount = 1.90;
                         opp.Entity_Type__c = 'S-Corporation';
                         opp.Entrity_Name__c = 'Test';
                         opp.ChargentSFA__Billing_Address__c = 'Test';
                         opp.ChargentSFA__Billing_City__c = 'Test';
                         opp.ChargentSFA__Billing_Company__c = 'Test';
                         opp.ChargentSFA__Billing_Country__c = 'Test';
                         opp.ChargentSFA__Billing_State__c = 'test';
                         opp.ChargentSFA__Billing_Fax__c = '123456';
                         opp.ChargentSFA__Billing_First__c = 'test';
                         opp.ChargentSFA__Billing_Last__c = 'test';
                         opp.ChargentSFA__Billing_Phone__c = '1234567890';
                         opp.ChargentSFA__Billing_Postcode__c = '123456';
                         opp.ChargentSFA__Payment_Method__c = 'Credit Card';
                         opp.ChargentSFA__Card_Type__c = 'Visa';
                         opp.ChargentSFA__Billing_Email__c = 'test@test.com';
                         opp.ChargentSFA__Payment_Count__c = 25;
                         opp.ChargentSFA__Payment_Start_Date__c = system.today();
                         opp.ChargentSFA__Payment_End_Date__c = system.today().adddays(2);
                         opp.ChargentSFA__Payment_Stop__c = 'Count';
                         opp.ChargentSFA__Payment_Status__c = 'Partial';
                         opp.ChargentSFA__Payment_Frequency__c = 'Daily';
                         opp.ChargentSFA__Payment_Status__c = 'Recurring';
                         opp.ChargentSFA__Card_Number__c='1234567891234567';
                         insert opp;




                        //eventFormExtension efe=new eventFormExtension();
                        //ApexPages.StandardController sc = new ApexPages.StandardController(opp);
                        Test.setCurrentPageReference(new PageReference('Page.eventSuccess'));
                        System.currentPageReference().getParameters().put('id', opp.id);

                        eventSuccessExtension ese=new eventSuccessExtension();
                        ese.onLoad();

                        //List<Apexpages.Message> msgs1 = ApexPages.getMessages();

                        // boolean isErrorMessage1 = false;


                        // for(Apexpages.Message msg : msgs1) {
                        //          if (msg.getDetail().contains('Please fill Address'))
                        //           isErrorMessage1  = true;

                        //}


                         //system.assert(isErrorMessage1);

                        ese.redirectToEventForm();


                        eventSuccessExtension ese1=new eventSuccessExtension();

                         Opportunity opp1 = new Opportunity();
                         opp1.Name = 'test';
                         opp1.AccountId = acc.Id;
                         opp1.CloseDate = System.today();
                         opp1.StageName = 'Prospecting';
                         opp1.Amount = 1.90;
                         opp1.Entity_Type__c = 'S-Corporation';
                         opp1.Entrity_Name__c = 'Test';
                         opp1.ChargentSFA__Billing_Address__c = 'Test';
                         opp1.ChargentSFA__Billing_City__c = 'Test';
                         opp1.ChargentSFA__Billing_Company__c = 'Test';
                         opp1.ChargentSFA__Billing_Country__c = 'Test';
                         opp1.ChargentSFA__Billing_State__c = 'test';
                         opp1.ChargentSFA__Billing_Fax__c = '123456';
                         opp1.ChargentSFA__Billing_First__c = 'test';
                         opp1.ChargentSFA__Billing_Last__c = 'test';
                         opp1.ChargentSFA__Billing_Phone__c = '1234567890';
                         opp1.ChargentSFA__Billing_Postcode__c = '123456';
                         opp1.ChargentSFA__Payment_Method__c = 'Credit Card';
                         opp1.ChargentSFA__Card_Type__c = 'Visa';
                         opp1.ChargentSFA__Billing_Email__c = 'test@test.com';
                         opp1.ChargentSFA__Payment_Count__c = 25;
                         opp1.ChargentSFA__Payment_Start_Date__c = system.today();
                         opp1.ChargentSFA__Payment_End_Date__c = system.today().adddays(2);
                         opp1.ChargentSFA__Payment_Stop__c = 'Count';
                         opp1.ChargentSFA__Payment_Status__c = 'Partial';
                         opp1.ChargentSFA__Payment_Frequency__c = 'Daily';
                         opp1.ChargentSFA__Payment_Status__c = 'Recurring';
                         opp1.ChargentSFA__Card_Number__c='1234567891234567';
                         insert opp1;

                        ChargentSFA__Transaction__c ct=new ChargentSFA__Transaction__c();
                        ct.ChargentSFA__Gateway_Date__c=System.today();
                        ct.ChargentSFA__Gateway_ID__c='12123123';
                        ct.ChargentSFA__Opportunity__c=opp1.id;
                        ct.ChargentSFA__Amount__c=1;
                        ct.ChargentSFA__Type__c='Charge';
                        ct.ChargentSFA__Response_Status__c='Approved';
                        ct.ChargentSFA__Payment_Method__c='Credit Card';
                        insert ct;

                        Test.setCurrentPageReference(new PageReference('Page.eventSuccess'));
                        System.currentPageReference().getParameters().put('id', opp1.id);


                        ese1.redirectToEventForm();

                        ct.ChargentSFA__Response_Status__c='Error';
                        update ct;
                        ese1.redirectToEventForm();


	}
}