objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Info_Sent_to_ABA_By__c</fullName>
        <description>How the client gives us access to their documentation to do their books.</description>
        <inlineHelpText>How the client gives us access to their documentation to do their books.</inlineHelpText>
        <label>Info Sent to ABA By</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Box</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuickBooks_Version__c</fullName>
        <label>QuickBooks Version</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QB Desktop</fullName>
                </value>
                <value>
                    <fullName>QBO</fullName>
                </value>
                <value>
                    <fullName>QB Enterprise</fullName>
                </value>
                <value>
                    <fullName>Remote In</fullName>
                </value>
                <value>
                    <fullName>Portable Copy</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Bookkeeping</businessProcess>
        <description>Used for Bookkeeping Cases</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EntityRecordTypeSelectionCtrlTest.cls
@isTest
public class EntityRecordTypeSelectionCtrlTest {
    Public static Account a;
      Public static Case c;

 @testSetup
    public static void createTestData() {
          Id devBKCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Bookkeeping').getRecordTypeId();
        a=new Account();
        a.Name = 'Bob Apples';
        a.First_Name__c='Bob';
        a.Last_Name__c='Apples';
           insert a;
c=new Case();
        c.Subject='TEst BK Case';
        C.RecordTypeId=devBKCaseRecordTypeId;
        c.Info_Sent_to_ABA_By__c='Access';
        c.QuickBooks_Version__c='QBO';
        c.Account=a;
      c.Status='New';
        insert c;
     
    }
     @isTest
    static void TestNewEntity(){
         createTestData();
        test.startTest();
        EntityRecordTypeSelectionCtrl.fetchRecordTypeValues();
        EntityRecordTypeSelectionCtrl.getPrimaryClient(c.id);
        EntityRecordTypeSelectionCtrl.getRecTypeId('Limited Liability Company (LLC)');
        
        test.stopTest();
    }
}