objects/Account.object
<CustomObject>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Platinum_Membership__c</fullName>
        <description>Does the client currently have a Platinum Membership?</description>
        <inlineHelpText>Does the client currently have a Platinum Membership?</inlineHelpText>
        <label>Platinum Membership</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Platinum Elite</fullName>
                </value>
                <value>
                    <fullName>Lifetime Platinum</fullName>
                </value>
                <value>
                    <fullName>Dani Johnson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Platinum_Membership__c</fullName>
        <label>Platinum Membership</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Platinum Elite</fullName>
                </value>
                <value>
                    <fullName>Lifetime Platinum</fullName>
                </value>
                <value>
                    <fullName>Dani Johnson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Frequency__c</fullName>
        <label>Payment Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Once</fullName>
                    <default>true</default>
                    <label>Once</label>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Bimonthly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Start_Date__c</fullName>
        <label>Payment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Platinum_Membership__c</fullName>
        <formula>IF(
OR(
ISPICKVAL(Account.Platinum_Type__c, &quot;Platinum&quot;),
ISPICKVAL(Account.Platinum_Type__c, &quot;Platinum Elite&quot;),
ISPICKVAL(Account.Platinum_Type__c, &quot;Lifetime Platinum&quot;),
ISPICKVAL(Account.Platinum_Type__c, &quot;Dani Johnson&quot;),
ISPICKVAL(Account.Platinum_Type__c, &quot;Tax Team&quot;)
),
TRUE,
FALSE
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Platinum Membership</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CardExpiryBatchTestClass.cls
@isTest
private class CardExpiryBatchTestClass {

    private static void populateData()
     {
        Account acc = new Account();
        acc.Name = 'TestAcc';
        acc.Platinum_Membership__c = 'Platinum';
        acc.E_Mail__c = 'bahareh.hajiakbar@magentrix.com';
        
        Insert acc;
        
        Contact ct = new Contact();
        ct.LastName = 'Ha';
        ct.AccountId = acc.Id;
        ct.Email = 'bahareh.hajiakbar@magentrix.com';
        
        Insert ct;
        
        Opportunity op = new Opportunity();
        op.Name = 'Testing';
        op.CloseDate = Date.newInstance(2016,12,31);
        op.StageName = 'Presented';
        op.ChargentSFA__Payment_Frequency__c = 'Monthly';
        op.ChargentSFA__Card_Month__c = '06';
        op.ChargentSFA__Card_Year__c = '2016';
        op.ChargentSFA__Payment_Start_Date__c = Date.newInstance(2016,06,01);
        op.AccountId = acc.Id;
        
        Insert op;
        
 
     }
     
    static testMethod void validateCardExpiryBatch() {
        
        populateData();
        Test.startTest();
        CardExpiryBatch c = new CardExpiryBatch ();
        c.cDate = Date.newInstance(2016,05,22);
        Database.ExecuteBatch(c);

        Test.stopTest();
     
    }
    static testMethod void validateCardExpiryBatch2() {
    
        populateData();
        Test.startTest();
        CardExpiryBatch c = new CardExpiryBatch ();
        c.cDate = Date.newInstance(2016,05,31);
        Database.ExecuteBatch(c);

        Test.stopTest();
  
    }
    static testMethod void validateCardExpiryBatch3() {
    
        populateData();
        Test.startTest();
        CardExpiryBatch c = new CardExpiryBatch ();
        c.cDate = Date.newInstance(2016,06,02);
        Database.ExecuteBatch(c);

        Test.stopTest();
  
    }
}