objects/Account.object
<CustomObject>
    <fields>
        <fullName>E_Mail__c</fullName>
        <externalId>true</externalId>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ChargentSFA__Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Last_4__c</fullName>
        <label>Card Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Credit_Card_Name__c</fullName>
        <label>Credit Card Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Credit_Card_Number__c</fullName>
        <label>Credit Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Gateway_Date__c</fullName>
        <label>Gateway Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Client Referral Credit</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Credit to be used</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Wire Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Response_Status__c</fullName>
        <label>Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <formula>ChargentSFA__Opportunity__r.QB_Invoice_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Number</label>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Balance_Due__c</fullName>
        <formula>ChargentSFA__Total__c -  ChargentSFA__Transaction_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Last_4__c</fullName>
        <label>Card Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ChargentSFA__Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Charge_Amount__c</fullName>
        <inlineHelpText>The amount to be processed by the next transaction (authorize, charge or refund). If there are multiple charges, this field will automatically reflect the Amount of the order or opportunity minus the total amount of successful charges.</inlineHelpText>
        <label>Charge Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                    <default>true</default>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <formula>Opportunity.Entity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Entity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <formula>Opportunity.Text_Invoice_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <formula>PricebookEntry.Product2.Name</formula>
        <label>Service Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/AndersonReceit.cls
public with sharing class AndersonReceit 
{
Decimal TotalPrice=0.0, Balance = 0.0;
 public AndersonReceit(ApexPages.StandardController controller) {
 	
 	for(OpportunityLineItem o : [select ListPrice, UnitPrice, TotalPrice,ServiceDate,Quantity,Description from OpportunityLineItem where OpportunityId = :ClientId])
 	{
 		TotalPrice = TotalPrice + o.TotalPrice;
 	}
 	for(ChargentSFA__Transaction__c c : [select ChargentSFA__Amount__c, ChargentSFA__Gateway_Date__c, ChargentSFA__Credit_Card_Name__c, ChargentSFA__Credit_Card_Number__c, ChargentSFA__Card_Last_4__c from ChargentSFA__Transaction__c where ChargentSFA__Opportunity__c = : ClientId  and ChargentSFA__Response_Status__c = 'Approved'])
 	{
 		Balance = Balance + c.ChargentSFA__Amount__c;
 	}
 	if(Balance > TotalPrice)
     {        
        //TotalPrice  =  O.ChargentSFA__Charge_Amount__c;   
        Balance = -1;
     }
 	
 	Decimal tt =  TotalPrice - Balance;
		if(tt<0)
		{
			CheckVE = true;
		}
 }
	Id ClientId = System.currentPageReference().getParameters().get('Id');
	Opportunity opp = [select AccountID, ChargentSFA__Balance_Due__c,ChargentSFA__Charge_Amount__c,ChargentSFA__Payment_Method__c,ChargentSFA__Card_Type__c, ChargentSFA__Card_Last_4__c from Opportunity where id=:ClientId];
	Account ClientInfo = [select id,Name,BillingCity,BillingCountry,BillingPostalCode,Phone,E_Mail__c,BillingState,BillingStreet from Account where id = :opp.AccountId];
	
	public Account getClientInfo()
	{
		return ClientInfo;
	}
	public Opportunity getOpps()
	{
		return opp;
	}
	
	public String getDate()
	{
		return System.today().month()+'/'+System.today().day()+'/'+System.today().year();
	}
	
	public List<ChargentSFA__Transaction__c> getTransactions()
	{
		return [select ChargentSFA__Credit_Card_Type__c,ChargentSFA__Payment_Method__c,ChargentSFA__Amount__c, ChargentSFA__Gateway_Date__c, ChargentSFA__Credit_Card_Name__c, ChargentSFA__Credit_Card_Number__c, ChargentSFA__Card_Last_4__c from ChargentSFA__Transaction__c where ChargentSFA__Opportunity__c = : ClientId and ChargentSFA__Response_Status__c = 'Approved'];
	}
	
	public List<OpportunityLineItem> getProdInfo()
	{
		return [select ListPrice, Entity_Name__c, Service_Name__c, Invoice_Number__c, UnitPrice, TotalPrice,ServiceDate,Quantity,Description from OpportunityLineItem where OpportunityId = : ClientId];
	}
	
	public OpportunityLineItem getGrandTotal()
	{
		OL.TotalPrice = TotalPrice;
		return OL;
		
	} 
	OpportunityLineItem OL = new OpportunityLineItem();
	OpportunityLineItem OL1 = new OpportunityLineItem();
	 
	public Decimal bal = opp.ChargentSFA__Balance_Due__c;
	public Decimal getBal()
	{
		return bal;
	}
	public boolean CheckVE = false;
	public boolean getCheckVE()
	{
		return CheckVE;
	}
	public OpportunityLineItem getDueBalance()
	{
		Decimal t =0;
		if(Balance >= 0)
		  t = TotalPrice - Balance;
		 
		  
	    if(Balance ==-1)
	    	t = TotalPrice;
		//OL1.TotalPrice = Math.abs(bal);
		OL1.TotalPrice = Math.abs(t);
		/*if(t<0)
		{
			return '-'+('$'+t).split('-')[0]+''+('$'+t).split('-')[1];
		}
		else
		{
			return '$'+t;
		}*/
		return OL1;
	}
}