objects/Account.object
<CustomObject>
    <fields>
        <fullName>Base_Url__c</fullName>
        <formula>LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base Url</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assigned_Paralegal__c</fullName>
        <formula>Related_Entity__r.Processor__r.FirstName + &quot; &quot; + Related_Entity__r.Processor__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned Paralegal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trust__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Paralegal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned Paralegal for Living Trust.</description>
        <inlineHelpText>This is the Assigned Paralegal for the Living Trust.</inlineHelpText>
        <label>Assigned Paralegal</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Entities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_URL__c</fullName>
        <formula>IMAGE(&quot;https://andersonadvisors--c.na132.visual.force.com/&quot; + Processor_Signature_Field__c, &quot;Processor Signature&quot;, 75, 150)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Primary_Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consult_Scheduled__c</fullName>
        <label>Consult Scheduled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Shipped__c</fullName>
        <label>Date Shipped</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Documents_Complete__c</fullName>
        <label>Documents Complete</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LivingTrustAttorney__c</fullName>
        <label>LivingTrustAttorney</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aaron Rowland</fullName>
                </value>
                <value>
                    <fullName>Aaron Soffer</fullName>
                </value>
                <value>
                    <fullName>Amanda Wynalda</fullName>
                </value>
                <value>
                    <fullName>Carl Zoellner</fullName>
                </value>
                <value>
                    <fullName>Clint Coons</fullName>
                </value>
                <value>
                    <fullName>David Monsivais</fullName>
                </value>
                <value>
                    <fullName>Ghassan Jabali</fullName>
                </value>
                <value>
                    <fullName>Gwendolyn Wolfe</fullName>
                </value>
                <value>
                    <fullName>Isaac Noh</fullName>
                </value>
                <value>
                    <fullName>Jason Zundel</fullName>
                </value>
                <value>
                    <fullName>Jeff Cottle</fullName>
                </value>
                <value>
                    <fullName>John Anderson</fullName>
                </value>
                <value>
                    <fullName>Jonathon Evans</fullName>
                </value>
                <value>
                    <fullName>Joshua Robertson</fullName>
                </value>
                <value>
                    <fullName>Lauren Robins</fullName>
                </value>
                <value>
                    <fullName>Layla Azari</fullName>
                </value>
                <value>
                    <fullName>Michael Bowman</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Rose Moore</fullName>
                </value>
                <value>
                    <fullName>Ryan Coon</fullName>
                </value>
                <value>
                    <fullName>Sergey Garanyants</fullName>
                </value>
                <value>
                    <fullName>Toby Mathis</fullName>
                </value>
                <value>
                    <fullName>Tom Hata</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_Shipped__c</fullName>
        <label>Date Shipped</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE(
CASE(StageName,
&quot;Closed Won&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Closed Lost&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;Declined-&quot;, &quot;https://andersonadvisors--c.na171.visual.force.com/resource/1473631501000/Exclamation&quot;,
&quot;Converted&quot;, &quot;/servlet/servlet.FileDownload?file=015U00000040BV4&quot;,
&quot;Refund Requested&quot;,&quot;https://andersonadvisors--c.na171.visual.force.com/resource/1593114668000/RefundRequest&quot;,
&quot;/img/samples/flag_yellow.gif&quot;),
&quot;Priority Flag&quot;, 15, 15)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trust__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Sales</relationshipLabel>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pymt__Balance__c</fullName>
        <description>Total Amount - Payments Made</description>
        <formula>MAX(NULLVALUE(pymt__Total_Amount__c,0) - NULLVALUE(pymt__Payments_Made__c,0),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Amount - Payments Made</inlineHelpText>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pymt__Total_Amount__c</fullName>
        <formula>Amount +  pymt__Shipping__c +  pymt__Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>PaymentConnect total calculated amount (Opportunity amount + shipping + tax)</inlineHelpText>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trust__c.object
<CustomObject>
    <description>Object to hold Trust information.</description>
    <fields>
        <fullName>Assigned_Paralegal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Paralegal</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trusts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Primary_Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Trusts</relationshipLabel>
        <relationshipName>Trusts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consult_Scheduled__c</fullName>
        <label>Consult Scheduled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Shipped__c</fullName>
        <label>Date Shipped</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Documents_Complete__c</fullName>
        <label>Documents Complete</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LivingTrustAttorney__c</fullName>
        <label>LivingTrustAttorney</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aaron Soffer</fullName>
                </value>
                <value>
                    <fullName>Carl Zoellner</fullName>
                </value>
                <value>
                    <fullName>Clint Coons</fullName>
                </value>
                <value>
                    <fullName>Eliot Thomas</fullName>
                </value>
                <value>
                    <fullName>Jarom Hillery</fullName>
                </value>
                <value>
                    <fullName>John Anderson</fullName>
                </value>
                <value>
                    <fullName>Jonathon Evans</fullName>
                </value>
                <value>
                    <fullName>Joshua Robertson</fullName>
                </value>
                <value>
                    <fullName>Layla Azari</fullName>
                </value>
                <value>
                    <fullName>Lora Caindec</fullName>
                </value>
                <value>
                    <fullName>Michael Bowman</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Sergey Garanyants</fullName>
                </value>
                <value>
                    <fullName>Toby Mathis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trusts</relationshipLabel>
        <relationshipName>Trusts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trust__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Trusts</relationshipLabel>
        <relationshipName>Trusts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Trust</label>
    <nameField>
        <label>Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RelatedEstateplanningcommunitiesctrl.cls
public class RelatedEstateplanningcommunitiesctrl {
  @AuraEnabled
   public static List<Entities__c> getEntityObjectLivingTrust(Id clientid) {
       Id devoppLivingTrustRecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Living Trust').getRecordTypeId();
       Id devoppLivingTrustobjRecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Living Trust').getRecordTypeId();
     
   return [SELECT Id,Primary_Client__c, Primary_Client__r.name,Primary_Client__r.Base_Url__c,Consult_Scheduled__c,RecordTypeId,LivingTrustAttorney__c,Assigned_Paralegal__c,Assigned_Paralegal__r.name,Documents_Complete__c,Date_Shipped__c,RecordType.name,Name,Case__c,Case__r.CaseNumber  FROM Entities__c where Primary_Client__c=:clientid and RecordTypeId=:devoppLivingTrustRecordTypeId];
       
       
   }
    @AuraEnabled
   public static List<Trust__c> getTrust(Id clientid) {
   
       Id devoppLivingTrustobjRecordTypeId = Schema.SObjectType.Trust__c.getRecordTypeInfosByName().get('Living Trust').getRecordTypeId();
     
   return [SELECT Id,Primary_Client__c, Primary_Client__r.name,Primary_Client__r.Base_Url__c,Consult_Scheduled__c,RecordTypeId,LivingTrustAttorney__c,Assigned_Paralegal__c,Assigned_Paralegal__r.name,Documents_Complete__c,Date_Shipped__c,RecordType.name,Name,Case__c,Case__r.CaseNumber  FROM Trust__c where Primary_Client__c=:clientid and RecordTypeId=:devoppLivingTrustobjRecordTypeId];
       
       
   }
    
     @AuraEnabled
    public static List<Opportunity> getSalesRecord(Id accId) {
         
       
      
    
        return [Select id,Name,RecordType.Name,Status__c,StageName,Account.Base_Url__c,CloseDate,Probability,pymt__Total_Amount__c,pymt__Balance__c,Entity__c,Entity__r.Name,OwnerId,Owner.name,Sales_Rep__c,Sales_Rep__r.Name From Opportunity where AccountId=:accId and (name like '%Living Trust%' or name like 'Living Trust%' or  name like '%Living Trust' or name='Living Trust' ) ];
    }
              @AuraEnabled
    public static List<task> getlvtasks(Id accId) {
          Id devoppLivingTRecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('Living Trust').getRecordTypeId();
      set<id> cid= new set<id>();
        for(contact c: [Select id from contact where AccountId=:accId]){
            cid.add(c.id);
        }
         
        return [Select Id,Subject, OwnerId,Owner.Name,Priority,ActivityDate,WhoId,What.Name,LastModifiedDate,WhatId,Status,Client__r.Base_Url__c,Summary__c,Days_Since_Last_Modified__c,Living_Trust_Stages__c From task where WhoId=:cid  and (RecordTypeID=:devoppLivingTRecordTypeId OR  subject Like '%Living Trust%'  or subject like 'Living Trust%' or  subject like '%Living Trust'  or subject='Living Trust'  )  ];
    }
         
           @AuraEnabled
    public static List<Case> getlvcase(Id accId) {
    Id devoppLivingCRecordTypeId = Schema.SObjectType.case.getRecordTypeInfosByName().get('Living Trust').getRecordTypeId();
        return [Select Id, subject,status,CaseNumber,Account.Base_Url__c,RecordTypeId,RecordType.Name,LastmodifiedDate,CreatedDate,OwnerId,Owner.Name From Case where AccountId=:accId and (RecordTypeID=:devoppLivingCRecordTypeId OR  subject Like '%Living Trust%'  or subject like 'Living Trust%' or  subject like '%Living Trust'  or subject='Living Trust'  ) ];
    }
    
  
}