objects/ASA__c.object
<CustomObject>
    <fields>
        <fullName>ASA_Stage__c</fullName>
        <label>ASA Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASA Scheduled</fullName>
                    <label>ASA Initial Call Scheduled</label>
                </value>
                <value>
                    <fullName>Review Call Scheduled</fullName>
                    <label>Prepare Plan</label>
                </value>
                <value>
                    <fullName>Plan Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Follow Up</fullName>
                </value>
                <value>
                    <fullName>Review Call Complete</fullName>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Plan Approved</fullName>
                </value>
                <value>
                    <fullName>Ready for ASP Call</fullName>
                </value>
                <value>
                    <fullName>1 Year Follow-up</fullName>
                </value>
                <value>
                    <fullName>Client Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Engagement Initiated</fullName>
                    <isActive>false</isActive>
                    <label>Engagement Initiated</label>
                </value>
                <value>
                    <fullName>Survey Sent</fullName>
                    <isActive>false</isActive>
                    <label>Survey Sent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Advanced Strategy Analyzers</relationshipLabel>
        <relationshipName>ASA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ASAS</relationshipLabel>
        <relationshipName>ASAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Yearly_Follow_up_Date__c</fullName>
        <inlineHelpText>The date the Financial Analyst should follow-up with the client.</inlineHelpText>
        <label>Yearly Follow-up Date</label>
        <type>Date</type>
    </fields>
    <label>ASA</label>
    <nameField>
        <label>ASA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Follow_up_task_owner__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <description>user record id</description>
        <label>Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Follow up Task owner</label>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>ASA</fullName>
        <active>true</active>
        <label>ASA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Call</fullName>
        <active>true</active>
        <description>Used for Calls.</description>
        <label>Call</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASA_AfterUpdateHelper.cls
/***********************************
* Author : Ifrahim Afzal
* Description : Class is invoked on After update of the Trigger context
* Class : ASA_AfterUpdateHelper
***********************************/
public class ASA_AfterUpdateHelper {
    
    public static Final String  FOLLOW_UP_YEAR= '1 Year Follow-up';
    public static Final String ASA_YEAR_FOLLOW = 'ASA Yearly Follow-up';
    public static Id call = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Call').getRecordTypeId();
    public static Map<Id,ASA__c> asaGenMap = new Map<Id,ASA__c>();
    /***********************************
    * Author : Ifrahim Afzal
    * Method : critierataskGeneration
    * Description : Generate task on below condition 
    				ASA Stage changed(ASA_Stage__c)      : 1-year Follow-up
					Follow Up date changed(ASA_Stage__c)  
					Record Type : None
     ***********************************/
    public static void critierataskGeneration(List<ASA__c> asaList,Map<Id,ASA__c> newMap, Map<Id,ASA__c> oldMap){
        try{
            if(!asaList.isEmpty()){
                for(ASA__c asa : asaList){
                    if((asa.ASA_Stage__c == FOLLOW_UP_YEAR && asa.ASA_Stage__c != oldMap.get(asa.Id).ASA_Stage__c) 
                        || asa.Yearly_Follow_up_Date__c != oldMap.get(asa.Id).Yearly_Follow_up_Date__c){
                        asaGenMap.put(asa.Id,asa);
                    }
                }
            }
            
            if(!asaGenMap.isEmpty()){
                taskGeneration(asaGenMap);
            }
        }catch(Exception e){
            System.debug('e.getMessage'+e.getMessage());
        }
    }
    
    
    /***********************************
    * Author : Ifrahim Afzal
    * Method : taskCreation
    * Description : Create a call task on below condition 
    				RecordType= call
                    AssignedTo= Jaime Escandon
                    Due date = 1year from the date it was set to followup
                    Subject= ASA Yearly Follow-up
                    related to Id= The Asa record that triggered the Task
					Client field= Associated to the related client on ASA
					Contact Field = Associated to the related contact on ASA
     ***********************************/
    public static void taskGeneration(Map<Id,ASA__c> asaGenMap){
        try{
            
            Task task = new Task();
            List<Task> followUpList = new List<Task>();
            Map<Id,Task> asaToTask = new Map<Id,Task>();
            
            for(Task taskObj :[Select Id,Subject,WhatId from Task Where Subject =: ASA_YEAR_FOLLOW and WhatId IN : asaGenMap.keySet() Limit 50000]){
               	 asaToTask.put(taskObj.WhatId, taskObj);
            }
            
            
            for(Id asaId : asaGenMap.keySet()){
                task = new Task();  
                if(asaToTask.containsKey(asaId)){  /*Update the Existing Task*/
                    task = asaToTask.get(asaId);
                    task.ActivityDate = asaGenMap.get(asaId).Yearly_Follow_up_Date__c;
                    
                }else{ /*Create the Task*/
                    task.RecordTypeId = call;
                    task.OwnerId = Follow_up_task_owner__c.getValues('Follow Up').Id__c;
                    task.ActivityDate = asaGenMap.get(asaId).Yearly_Follow_up_Date__c;
                    task.WhatId = asaId;
                    task.Subject = Follow_up_task_owner__c.getValues('Follow Up').Subject__c;
                    task.Client__c = asaGenMap.get(asaId).Client_Name__c;
                    task.WhoId =  asaGenMap.get(asaId).Contact__c;
                }
                followUpList.add(task);
            }
            
            if(!followUpList.isEmpty()){
                Database.UpsertResult[] ResultList = Database.upsert(followUpList, false);
                for (Database.UpsertResult sr : ResultList) {
                    if (!sr.isSuccess()) {
                        System.debug('Follow up task get created/Updated' + sr.getId());
                    }
                    else {
                        for(Database.Error err : sr.getErrors()) {
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        }
                    }
                }
            }
        }catch(Exception e){
             System.debug('e.getMessage'+e.getMessage());
        }
    }
}