objects/ASA__c.object
<CustomObject>
    <fields>
        <fullName>ASA_Stage__c</fullName>
        <label>ASA Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASA Scheduled</fullName>
                    <label>ASA Initial Call Scheduled</label>
                </value>
                <value>
                    <fullName>Review Call Scheduled</fullName>
                    <label>Prepare Plan</label>
                </value>
                <value>
                    <fullName>Plan Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Follow Up</fullName>
                </value>
                <value>
                    <fullName>Review Call Complete</fullName>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Plan Approved</fullName>
                </value>
                <value>
                    <fullName>Ready for ASP Call</fullName>
                </value>
                <value>
                    <fullName>1 Year Follow-up</fullName>
                </value>
                <value>
                    <fullName>Client Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Engagement Initiated</fullName>
                    <isActive>false</isActive>
                    <label>Engagement Initiated</label>
                </value>
                <value>
                    <fullName>Survey Sent</fullName>
                    <isActive>false</isActive>
                    <label>Survey Sent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Yearly_Follow_up_Date__c</fullName>
        <inlineHelpText>The date the Financial Analyst should follow-up with the client.</inlineHelpText>
        <label>Yearly Follow-up Date</label>
        <type>Date</type>
    </fields>
    <label>ASA</label>
    <nameField>
        <label>ASA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Follow_up_task_owner__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Year__c</fullName>
        <description>Follow Up year</description>
        <label>Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Follow up Task owner</label>
</CustomObject>

classes/ASA_BeforeUpdatetHelper.cls
/***********************************
* Author : Ifrahim Afzal
* Description : Helper class of Trigger event Before Update for ASA Object
* Class : ASA_BeforeUpdatetHelper
***********************************/
public class ASA_BeforeUpdatetHelper {

    public static Final String  FOLLOW_UP_YEAR= '1 Year Follow-up';
    
    /***********************************
    * Author : Ifrahim Afzal
    * Description : ASA - Logic Holder (Process Builder) migration to APEX
    * 				Populate the Follow up Date if the date is not populated. 
    * 				Stage is changed to FollowUp
    * Method : populateFollowUp
    ***********************************/
    public static void populateFollowUp(List<ASA__C> asaList, Map<Id,ASA__c> oldMap){
        try{
            for(ASA__C asa : asaList){
                if(asa.ASA_Stage__c == FOLLOW_UP_YEAR && asa.ASA_Stage__c != oldMap.get(asa.Id).ASA_Stage__c
                    && asa.Yearly_Follow_up_Date__c == null){
                	asa.Yearly_Follow_up_Date__c = Date.today().addyears(Integer.valueOf(Follow_up_task_owner__c.getValues('Follow Up').year__c));
                        //New follow up date is one year from today
                }
            }
        }catch(Exception e){
             System.debug('e.getMessage'+e.getMessage());
        }
    }
   
}