objects/BatchRetryAttempts__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Create a separate record for your batch.</description>
    <fields>
        <fullName>Current_Iteration__c</fullName>
        <label>Current Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Iteration__c</fullName>
        <label>Maximum Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Retry Attempts</label>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Current_Plan_Year_End__c</fullName>
        <label>Current Plan Year End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Adoption_Date__c</fullName>
        <label>Plan Adoption Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recap_End_Date__c</fullName>
        <formula>IF(  NOT(ISBLANK(Current_Plan_Year_End__c)),

Current_Plan_Year_End__c,


IF( Plan_Adoption_Year__c  &gt;= YEAR(TODAY()),
CASE( MONTH( Year_End__c ),
1,  DATE(Plan_Adoption_Year__c + 1,1,31),
2,  DATE(Plan_Adoption_Year__c + 1,2,28),
3,  DATE(Plan_Adoption_Year__c + 1,3,31),
4,  DATE(Plan_Adoption_Year__c + 1,4,30),
5,  DATE(Plan_Adoption_Year__c + 1,5,31),
6,  DATE(Plan_Adoption_Year__c + 1,6,30),
7,  DATE(Plan_Adoption_Year__c + 1,7,31),
8,  DATE(Plan_Adoption_Year__c + 1,8,31),
9,  DATE(Plan_Adoption_Year__c + 1,9,30),
10, DATE(Plan_Adoption_Year__c + 1,10,31),
11, DATE(Plan_Adoption_Year__c + 1,11,30),
12, DATE(Plan_Adoption_Year__c,12,31),
null),

CASE( MONTH( Year_End__c ),
1,  DATE(IF(MONTH(TODAY()) =1,  YEAR(TODAY()), YEAR(TODAY()) + 1),1,31),
2,  DATE(IF(MONTH(TODAY())&lt;=2,  YEAR(TODAY()), YEAR(TODAY()) + 1),2,28),
3,  DATE(IF(MONTH(TODAY())&lt;=3,  YEAR(TODAY()), YEAR(TODAY()) + 1),3,31),
4,  DATE(IF(MONTH(TODAY())&lt;=4,  YEAR(TODAY()), YEAR(TODAY()) + 1),4,30),
5,  DATE(IF(MONTH(TODAY())&lt;=5,  YEAR(TODAY()), YEAR(TODAY()) + 1),5,31),
6,  DATE(IF(MONTH(TODAY())&lt;=6,  YEAR(TODAY()), YEAR(TODAY()) + 1),6,30),
7,  DATE(IF(MONTH(TODAY())&lt;=7,  YEAR(TODAY()), YEAR(TODAY()) + 1),7,31),
8,  DATE(IF(MONTH(TODAY())&lt;=8,  YEAR(TODAY()), YEAR(TODAY()) + 1),8,31),
9,  DATE(IF(MONTH(TODAY())&lt;=9,  YEAR(TODAY()), YEAR(TODAY()) + 1),9,30),
10, DATE(IF(MONTH(TODAY())&lt;=10, YEAR(TODAY()), YEAR(TODAY()) + 1),10,31),
11, DATE(IF(MONTH(TODAY())&lt;=11, YEAR(TODAY()), YEAR(TODAY()) + 1),11,30),
12, DATE(YEAR(TODAY()),12,31),
null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recap End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recap_Start_Date__c</fullName>
        <formula>IF( NOT(ISBLANK(Current_Plan_Year_End__c)),

IF(
	AND(
		DAY(Current_Plan_Year_End__c) = 29 ,
		OR( 
		  MOD( YEAR( Current_Plan_Year_End__c ), 400 ) = 0, 
		  AND( 
		   MOD( YEAR( Current_Plan_Year_End__c ), 4 ) = 0,
			MOD( YEAR( Current_Plan_Year_End__c ), 100 ) != 0
		  )
		)
	),
	DATE(YEAR(Current_Plan_Year_End__c)-1,MONTH(Current_Plan_Year_End__c),DAY(Current_Plan_Year_End__c)-1)+1,
	DATE(YEAR(Current_Plan_Year_End__c)-1,MONTH(Current_Plan_Year_End__c),DAY(Current_Plan_Year_End__c))+1
),

IF( Plan_Adoption_Year__c &gt;= YEAR(TODAY()),
CASE( MONTH( Year_End__c ),
1, DATE(Plan_Adoption_Year__c,2,1),
2, DATE(Plan_Adoption_Year__c,3,1),
3, DATE(Plan_Adoption_Year__c,4,1),
4, DATE(Plan_Adoption_Year__c,5,1),
5, DATE(Plan_Adoption_Year__c,6,1),
6, DATE(Plan_Adoption_Year__c,7,1),
7, DATE(Plan_Adoption_Year__c,8,1),
8, DATE(Plan_Adoption_Year__c,9,1),
9, DATE(Plan_Adoption_Year__c,10,1),
10, DATE(Plan_Adoption_Year__c,11,1),
11, DATE(Plan_Adoption_Year__c,12,1),
12, DATE(Plan_Adoption_Year__c,1,1),
null),


CASE( MONTH( Year_End__c ),
1, DATE(IF(MONTH(TODAY()) =1, YEAR(TODAY()) - 1, YEAR(TODAY())),2,1),
2, DATE(IF(	MONTH(TODAY())&lt;=2, YEAR(TODAY()) - 1, YEAR(TODAY())),3,1),
3, DATE(IF(MONTH(TODAY())&lt;=3, YEAR(TODAY()) - 1, YEAR(TODAY())),4,1),
4, DATE(IF(MONTH(TODAY())&lt;=4, YEAR(TODAY()) - 1, YEAR(TODAY())),5,1),
5, DATE(IF(MONTH(TODAY())&lt;=5, YEAR(TODAY()) - 1, YEAR(TODAY())),6,1),
6, DATE(IF(MONTH(TODAY())&lt;=6, YEAR(TODAY()) - 1, YEAR(TODAY())),7,1),
7, DATE(IF(MONTH(TODAY())&lt;=7, YEAR(TODAY()) - 1, YEAR(TODAY())),8,1),
8, DATE(IF(MONTH(TODAY())&lt;=8, YEAR(TODAY()) - 1, YEAR(TODAY())),9,1),
9, DATE(IF(MONTH(TODAY())&lt;=9, YEAR(TODAY()) - 1, YEAR(TODAY())),10,1),
10, DATE(IF(MONTH(TODAY())&lt;=10, YEAR(TODAY()) - 1, YEAR(TODAY())),11,1),
11, DATE(IF(MONTH(TODAY())&lt;=11, YEAR(TODAY()) - 1, YEAR(TODAY())),12,1),
12, DATE(YEAR(TODAY()),1,1),
null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recap Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Service</fullName>
                </value>
                <value>
                    <fullName>Admin Service</fullName>
                </value>
                <value>
                    <fullName>Prepaid Admin</fullName>
                </value>
                <value>
                    <fullName>Robs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_End_Month__c</fullName>
        <description>Vertiba OnDemand, 7/3/2014, SR-00001758</description>
        <formula>IF(ISBLANK(Updated_Tax_Year_End__c),
CASE(MONTH( Year_End__c ),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;&quot;
),
CASE(MONTH( Updated_Tax_Year_End__c),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;&quot;
))</formula>
        <label>Year End Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_End__c</fullName>
        <label>First Tax Year End</label>
        <type>Date</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <recordTypes>
        <fullName>Pension_Plan</fullName>
        <active>true</active>
        <description>Pension Plan</description>
        <label>Pension Plan</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SLA__c.object
<CustomObject>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Service</fullName>
                </value>
                <value>
                    <fullName>Documents Only</fullName>
                </value>
                <value>
                    <fullName>3rd Party Admin</fullName>
                </value>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SLA</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>SLA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchableBLogicEntity.cls
global class BatchableBLogicEntity implements Database.Batchable<sObject>,System.Schedulable, Database.Stateful {
    Exception[] errors = new Exception[0];
    Set<String> setErrorIds = new Set<String>();
    Set<String> setFailedIds = new Set<String>();
    
    Integer currentYear;
    Integer currentMonth;
    Date selectedDate; //Give your date

    BatchRetryAttempts__c cs = BatchRetryAttempts__c.getInstance('BatchableBLogicEntity');
    public BatchableBLogicEntity()
    {
        
    }
    public BatchableBLogicEntity(Set<String> setIds, Integer cy, Integer cm, Date sd){
        if (test.isRunningTest() && cy != null && cm != null && sd != null) {
            currentYear = cy;
            currentMonth = cm;
            selectedDate = sd;
        } else {
            currentYear = Date.Today().Year();
            currentMonth = Date.Today().Month();
            selectedDate = Date.Today();
        }
        
        try {
            if (!setIds.isEmpty())
            {
                
                setErrorIds = setIds;
            }
        } catch (Exception e) {
            system.debug('Continue');
        }
        
    } 
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // collect the batches of records or objects to be passed to execute
        //SLA not equal NO Service
        //SLA Month should be equal to the conditions
        
        String query;
        
       if (!setErrorIds.isEmpty())
        {
            query = 'SELECT Id,Name,SLA__c,Current_Plan_Year_End__c,Plan_Adoption_Date__c,Year_End__c,Year_End_Month__c,Recap_Start_Date__c,Recap_End_Date__c FROM Entities__c WHERE Id IN: setErrorIds' ;
            cs.Current_Iteration__c= cs.Current_Iteration__c+1;
            update cs;
            system.debug('Failed Batch===>>>>');
            
        }
        else
        {
            query = 'SELECT Id,Name,SLA__c,Plan_Adoption_Date__c,Current_Plan_Year_End__c,Year_End__c,Year_End_Month__c,Recap_Start_Date__c,Recap_End_Date__c FROM Entities__c WHERE RecordType.DeveloperName = \'Pension_Plan\' ';
            cs.Current_Iteration__c = 1;
            update cs;
            system.debug('Success Batch===>>>');
        }
        // query = 'SELECT Id,Name,SLA__c,Plan_Adoption_Date__c,Year_End__c,Year_End_Month__c,Recap_Start_Date__c,Recap_End_Date__c FROM Entities__c WHERE Id IN: setErrorIds ';
        
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Entities__c> entityList)
    {
        List<Entities__c> lstEntities = new List<Entities__c>();
        
        Date firstDate = selectedDate.toStartOfMonth();
        Date lastDate = firstDate.addDays(date.daysInMonth(selectedDate.year() , selectedDate.month())  - 1);
        system.debug(firstDate  + ' **** ' +lastDate );
        Boolean isCurrentAndLastDateSame = selectedDate.isSameDay(lastDate);
        Boolean currentYearIsLeapYear = Date.isLeapYear(currentYear);
        Integer nextYear = Date.Today().Year()+1;
        Boolean nextYearIsLeapYear = Date.isLeapYear(nextYear);
        // Date nextLeapFebruaryDte = Date.newInstance(nextYear,2, 29);
        //Date notNextLeapFebruaryDte = Date.newInstance(nextYear, 2, 28);
        
        //  Map<String,List<Entities__c>> mapOfEntitiesId = new Map<String,List<Entities__c>>();
        if(entityList.size()>0)
        {
            
            for(Entities__c entity: entityList)
            {
                //Uncomment the slaMonths line of code and put the if condition again
                //String slaMonths = entity.Year_End_Month__c;
                Date firstTaxYearEndDate = entity.Year_End__c;
                Date dtUpdateCurrentPlanYear= Date.newInstance(firstTaxYearEndDate.year()+1, firstTaxYearEndDate.month(), firstTaxYearEndDate.Day());
                system.debug('entity =====>>> '+ entity);
               // system.debug('SLAMonth =====>>> '+ slaMonths);
                system.debug('isCurrentAndLastDateSame =====>>> '+ isCurrentAndLastDateSame);
                system.debug('CurrentMonth =====>>> '+ currentMonth);
                system.debug('selectedDate =====>>> '+ selectedDate);
                system.debug('lastDate =====>>> '+ lastDate);
                // system.debug('nextLeapFebruaryDte =====>>> '+ nextLeapFebruaryDte);
                //system.debug('notNextLeapFebruaryDte =====>>> '+ notNextLeapFebruaryDte);
                
                If(isCurrentAndLastDateSame==true && currentMonth==3)
                {
                    //Put this in the if condition if SLA logic is implemented
                    //slaMonths == 'January' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==4)
                {
                    //slaMonths == 'February' && 
                    //entity.SLA__c = 'No Service';
                    if(nextYearIsLeapYear==true)
                    {
                        entity.Current_Plan_Year_End__c = Date.newInstance(firstTaxYearEndDate.year()+1,2, 29);
                    }
                    else if(nextYearIsLeapYear==false)
                    {
                        entity.Current_Plan_Year_End__c = Date.newInstance(firstTaxYearEndDate.year()+1, 2, 28);
                    }
                    
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==5)
                {
                    //slaMonths == 'March' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==6)
                {
                    //slaMonths == 'April' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==7)
                {
                    //slaMonths == 'May' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==8)
                {
                    //slaMonths == 'June' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==9)
                {
                    //slaMonths == 'July' && 
                   // entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==10)
                {
                    //slaMonths == 'August' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==11)
                {
                    //slaMonths == 'September' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==12)
                {
                    //slaMonths == 'October' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==1)
                {
                    //slaMonths == 'November' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                else if(isCurrentAndLastDateSame==true && currentMonth==2)
                {
                    //slaMonths == 'December' && 
                    //entity.SLA__c = 'No Service';
                    entity.Current_Plan_Year_End__c = dtUpdateCurrentPlanYear;
                    lstEntities.add(entity);
                }
                
                
            }
            
            if (lstEntities.size() > 0) {
                
                Database.SaveResult[] updateResult = Database.update(lstEntities,false);
                
                for (Integer i = 0; i < updateResult.size(); i++) {
                    if (!updateResult.get(i).isSuccess()) {
                        setFailedIds.add(lstEntities.get(i).Id);
                    }
                   
                }
                
            }
                 //     setFailedIds.add('a0I7c000004KG4BEAW');

            
            
        }
        
        
    }
    global void finish(Database.BatchableContext BC) 
    {
        system.debug('Set Failed Ids >>>>>>>>>>>>>>>>>>>>>>>>>>> ' + setFailedIds);
        
        if(!setFailedIds.isEmpty() && cs.Current_Iteration__c <= cs.Maximum_Iteration__c)
        {
            database.executebatch(new BatchableBLogicEntity(setFailedIds, null, null, null),10);
        }
       /*else if(cs.Current_Iteration__c > cs.Maximum_Iteration__c)
        {
            cs.Current_Iteration__c = 0;
            System.debug('Check Custom Setting Value===>>>'+cs.Current_Iteration__c);
        }*/
        // execute any post-processing operations
    }
    global void execute(SchedulableContext SC) {
        database.executebatch(new BatchableBLogicEntity(null, null, null, null),10);
    }
}