objects/BatchRetryAttempts__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Create a separate record for your batch.</description>
    <fields>
        <fullName>Current_Iteration__c</fullName>
        <label>Current Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Iteration__c</fullName>
        <label>Maximum Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Retry Attempts</label>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Current_Plan_Year_End__c</fullName>
        <label>Current Plan Year End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</description>
        <inlineHelpText>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anderson</fullName>
                    <default>true</default>
                    <label>Anderson</label>
                </value>
                <value>
                    <fullName>Client Formed</fullName>
                </value>
                <value>
                    <fullName>Shelf</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year_End__c</fullName>
        <label>First Tax Year End</label>
        <type>Date</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchableBLogicEntityTest.cls
@isTest
private class BatchableBLogicEntityTest {
    /*@TestVisible static Integer currentMonth = Date.today().month();
    @TestVisible static Integer currentYear = Date.today().Year();
    @TestVisible static Date SelectedDate = Date.today();*/
    
    
    @testSetup
    static void setup() {
        insert new BatchRetryAttempts__c(Name='BatchableBLogicEntity',Current_Iteration__c=1,Maximum_Iteration__c=3);
        //List<Account> accounts = new List<Account>();
        Account acc = new Account();
        acc.Name = 'sfdcpoint';
        insert acc;
        //List<Entities__c> ent = new List<Entities__c>();
        List<Entities__c> updateList = new List<Entities__c>(); 
        
        for (Integer i = 0; i<20; i++){
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Entity_'+i;
            myEnt.Origin__c = 'Anderson';
            myEnt.Organization_State__c = 'Maine';
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();


            updateList.add(myEnt);
        }
        
        insert updateList;
        
    }
    static testMethod void testMethod1() 
    {
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().Year();
        Date SelectedDate = Date.today();
        currentMonth = 1;
        currentYear = 2021;
        SelectedDate = Date.newInstance(2021, 1, 31);
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select id,Year_End__c,  Current_Plan_Year_End__c from Entities__c])
        {
            
            date mydate = date.parse('11/30/2020');
            e.Year_End__c = mydate;
            updateList.add(e);
            
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntity updateEntity = new BatchableBLogicEntity(null,null,null,null);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();

        
    }
    static testMethod void testMethod2() 
    {
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().Year();
        Date SelectedDate = Date.today();
        currentMonth = 10;
        currentYear = 2021;
        SelectedDate = Date.newInstance(2021, 10, 31);
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select id,Year_End__c,  Current_Plan_Year_End__c from Entities__c])
        {
            
            date mydate = date.parse('10/31/2020');
            e.Year_End__c = mydate;
            updateList.add(e);
            
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntity updateEntity = new BatchableBLogicEntity(null,currentYear,currentMonth,SelectedDate);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();

        
    }
     static testMethod void testMethod3() 
    {
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().Year();
        Date SelectedDate = Date.today();
        currentMonth = 3;
        currentYear = 2021;
        SelectedDate = Date.newInstance(2021, 3, 31);
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select id,Year_End__c,  Current_Plan_Year_End__c from Entities__c])
        {
            
            date mydate = date.parse('3/31/2020');
            e.Year_End__c = mydate;
            updateList.add(e);
            
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntity updateEntity = new BatchableBLogicEntity(null,currentYear,currentMonth,SelectedDate);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();

        
    }
     static testMethod void testMethod4() 
    {
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().Year();
        Date SelectedDate = Date.today();
        currentMonth = 4;
        currentYear = 2021;
        SelectedDate = Date.newInstance(2021, 4, 30);
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select id,Year_End__c,  Current_Plan_Year_End__c from Entities__c])
        {
            
            date mydate = date.parse('2/29/2020');
            e.Year_End__c = mydate;
            updateList.add(e);
            
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntity updateEntity = new BatchableBLogicEntity(null,currentYear,currentMonth,SelectedDate);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();

        
    }
      static testMethod void testMethod5() 
    {
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().Year();
        Date SelectedDate = Date.today();
        currentMonth = 4;
        currentYear = 2020;
        SelectedDate = Date.newInstance(2020, 4, 30);
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select id,Year_End__c,  Current_Plan_Year_End__c from Entities__c])
        {
            
            date mydate = date.parse('2/28/2019');
            e.Year_End__c = mydate;
            updateList.add(e);
            
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntity updateEntity = new BatchableBLogicEntity(null,currentYear,currentMonth,SelectedDate);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();

        
    }
   
      static testMethod void testMethod6() 
    {
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().Year();
        Date SelectedDate = Date.today();
        currentMonth = 8;
        currentYear = 2021;
        SelectedDate = Date.newInstance(2020, 8, 31);
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select id,Year_End__c,  Current_Plan_Year_End__c from Entities__c])
        {
            
            date mydate = date.parse('8/31/2020');
            e.Year_End__c = mydate;
            updateList.add(e);
            
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntity updateEntity = new BatchableBLogicEntity(null,currentYear,currentMonth,SelectedDate);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();

        
    }
      static testMethod void testMethod7() 
    {
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().Year();
        Date SelectedDate = Date.today();
        currentMonth = 6;
        currentYear = 2021;
        SelectedDate = Date.newInstance(2020, 6, 30);
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select id,Year_End__c,  Current_Plan_Year_End__c from Entities__c])
        {
            
            date mydate = date.parse('6/30/2020');
            e.Year_End__c = mydate;
            updateList.add(e);
            
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntity updateEntity = new BatchableBLogicEntity(null,currentYear,currentMonth,SelectedDate);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();

        
    }
      static testMethod void testMethod8() 
    {
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().Year();
        Date SelectedDate = Date.today();
        currentMonth = 5;
        currentYear = 2020;
        SelectedDate = Date.newInstance(2020, 5, 31);
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select id,Year_End__c,  Current_Plan_Year_End__c from Entities__c])
        {
            
            date mydate = date.parse('5/31/2020');
            e.Year_End__c = mydate;
            updateList.add(e);
            
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntity updateEntity = new BatchableBLogicEntity(null,currentYear,currentMonth,SelectedDate);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();

        
    }
     static testMethod void testMethod9() 
    {
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().Year();
        Date SelectedDate = Date.today();
        currentMonth = 9;
        currentYear = 2021;
        SelectedDate = Date.newInstance(2020, 9, 30);
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select id,Year_End__c,  Current_Plan_Year_End__c from Entities__c])
        {
            
            date mydate = date.parse('9/30/2020');
            e.Year_End__c = mydate;
            updateList.add(e);
            
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntity updateEntity = new BatchableBLogicEntity(null,currentYear,currentMonth,SelectedDate);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();

        
    }
    
}