objects/BatchRetryAttempts__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Create a separate record for your batch.</description>
    <fields>
        <fullName>Current_Iteration__c</fullName>
        <label>Current Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Iteration__c</fullName>
        <label>Maximum Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Retry Attempts</label>
</CustomObject>

objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Bookkeeping</businessProcess>
        <description>Used for Bookkeeping Cases</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</description>
        <inlineHelpText>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anderson</fullName>
                    <default>true</default>
                    <label>Anderson</label>
                </value>
                <value>
                    <fullName>Client Formed</fullName>
                </value>
                <value>
                    <fullName>Shelf</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prepaid_SLA_Date__c</fullName>
        <label>Prepaid SLA End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Service</fullName>
                </value>
                <value>
                    <fullName>Admin Service</fullName>
                </value>
                <value>
                    <fullName>Prepaid Admin</fullName>
                </value>
                <value>
                    <fullName>Robs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SLA__c.object
<CustomObject>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Service</fullName>
                </value>
                <value>
                    <fullName>Documents Only</fullName>
                </value>
                <value>
                    <fullName>3rd Party Admin</fullName>
                </value>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SLA</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>SLA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchableBLogicEntityForPensionSLATest.cls
@isTest
private class BatchableBLogicEntityForPensionSLATest {
    @testSetup
    static void setup() {
        insert new BatchRetryAttempts__c(Name='BatchableBLogicEntityForPensionSLA',Current_Iteration__c=1,Maximum_Iteration__c=3);
        //List<Account> accounts = new List<Account>();
        Account acc = new Account();
        acc.Name = 'sfdcpoint';
        insert acc;
        //List<Entities__c> ent = new List<Entities__c>();
        List<Entities__c> updateList = new List<Entities__c>(); 
        
        for (Integer i = 0; i<20; i++){
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Entity_'+i;
            myEnt.Origin__c = 'Anderson';
            myEnt.Organization_State__c = 'Maine';
            myEnt.SLA__c ='Prepaid Admin';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            
            
            updateList.add(myEnt);
        }
        
        insert updateList;
        
    }
    static testMethod void test1() {
        Test.StartTest();
        BatchableBLogicEntityForPensionSLA emt = new  BatchableBLogicEntityForPensionSLA();
        Id batchId = Database.executeBatch(emt);
        Test.StopTest();        
    }
    static testMethod void positiveTestCase() 
    {
        insert new BatchRetryAttempts__c(Name='BatchableBLogicEntityForPensionSLA',Current_Iteration__c=1,Maximum_Iteration__c=3);
        
        List<Entities__c> updateList = new List<Entities__c>();
        List<Entities__c> flipSLA = new List<Entities__c>();
        for(Entities__c e: [Select Id,Name,SLA__c,Prepaid_SLA_Date__c from Entities__c])
        {
           // Date SelectedDate = Date.today();
           // Date SelectedDate = Date.newInstance(2021, 7, 31);
            //date mydate = date.parse('7/31/2021');
            e.Prepaid_SLA_Date__c = Date.newInstance(2021, 7, 31);
            e.SLA__c = 'No Service';
            updateList.add(e);          
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntityForPensionSLA updateEntity = new BatchableBLogicEntityForPensionSLA(null);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();
        
    }
  /*  static testMethod void negativeTestCaseForDatabase() 
    {
        Account acc = new Account();
        acc.Name = 'sfdcpoint2';
        insert acc;
        List<Entities__c> updateList = new List<Entities__c>(); 
         for (Integer i = 0; i<5; i++)
         {
        Entities__c myEnt = new Entities__c();
        myEnt.Primary_Client__c = acc.id;    
        myEnt.Name = 'Entity_Testing'+i;
        myEnt.Origin__c = 'Anderson';
        myEnt.Organization_State__c = 'Maine';
        myEnt.SLA__c =' ';
        Date mydate = date.parse('4/24/2021');
        myEnt.Prepaid_SLA_Date__c = mydate;
        //myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Bookkeeping').getRecordTypeId();
         updateList.add(myEnt);
         }
             insert updateList;
        Test.startTest();
        BatchableBLogicEntityForPensionSLA myEnt = new BatchableBLogicEntityForPensionSLA(null);
        Id batchId = Database.executeBatch(myEnt);
        Test.stopTest();
        
    }*/
    static testMethod void negativeTestCase() 
    {
        insert new BatchRetryAttempts__c(Name='BatchableBLogicEntityForPensionSLA',Current_Iteration__c=1,Maximum_Iteration__c=3);
        
        List<Entities__c> updateList = new List<Entities__c>();
        for(Entities__c e: [Select Id,Name,SLA__c,Prepaid_SLA_Date__c from Entities__c])
        {
            date mydate = date.parse('8/31/2021');
            e.Prepaid_SLA_Date__c = mydate;
            e.SLA__c = 'Negative Case Value';
            updateList.add(e);
            
        }
        update updateList;
        Test.startTest();
        BatchableBLogicEntityForPensionSLA updateEntity = new BatchableBLogicEntityForPensionSLA(null);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();
        
    }
    private static void testClass()
    {
        Test.startTest();
        BatchableBLogicEntityForPensionSLA controller = new BatchableBLogicEntityForPensionSLA();
        BatchableBLogicEntityForPensionSLA updateEntity = new BatchableBLogicEntityForPensionSLA(null);
        Id batchId = Database.executeBatch(updateEntity);
        Test.stopTest();
        
        
    }
    
    
}