objects/BatchRunning__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Is_Batch_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Batch Running</label>
        <type>Checkbox</type>
    </fields>
    <label>Batch Running</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default should be &apos;LV&apos;.</inlineHelpText>
        <label>Gateway</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose an Active Gateway record</errorMessage>
            <filterItems>
                <field>ChargentBase__Gateway__c.ChargentBase__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ChargentBase__Gateway__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Manual_Charge__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box when you want to authorize or charge an amount different than the amount due on the opportunity or order. This will prevent the &quot;Charge Amount&quot; from being automatically calculated and updated.</inlineHelpText>
        <label>Manual Charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Start_Date__c</fullName>
        <label>Payment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>DATETIMEVALUE (Renewal_Effective_Date__c) - 21</formula>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>C-Corporation</fullName>
                </value>
                <value>
                    <fullName>S-Corporation</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>CRT</fullName>
                </value>
                <value>
                    <fullName>GRT</fullName>
                </value>
                <value>
                    <fullName>QPRT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Override_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To override the Closed Lost automation.</inlineHelpText>
        <label>Override Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Effective_Date__c</fullName>
        <description>Date the renewal went into effect.</description>
        <inlineHelpText>Date the renewal went into effect.</inlineHelpText>
        <label>Renewal Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_End_Date__c</fullName>
        <inlineHelpText>Date renewal ends.</inlineHelpText>
        <label>Renewal End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_State__c</fullName>
        <description>State in which State filing will be filed.</description>
        <label>Renewal State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sale_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OpportunityBatch.cls
global class OpportunityBatch  implements Database.Batchable<sObject>, Database.Stateful  {
    
    id standardRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Renewal').getRecordTypeId();
    id stateRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('State Renewal').getRecordTypeId();
    global Integer recordsProcessed = 0;
    
    global database.QueryLocator start(Database.BatchableContext BC) 
    {
        List <Opportunity> oppIdsToClone = new List<Opportunity>();
        
        // WHEN "Is_Batch_Running__c = true", IT WILL BLOCK THE PROCESS BUILDER(Populate the Entity lookup field) CONDITON AND WILL NOT EXECUTE THE FLOW(Populate the Entity lookup field) FOR BATCH RECORDS
        // ADDED BY "Umer Amjad" ON "23-Nov-2021"
        BatchRunning__c runningBatch = BatchRunning__c.getOrgDefaults();
        runningBatch.Is_Batch_Running__c = true;
        UPDATE runningBatch;
        
        if(Test.isRunningTest()){
            oppIdsToClone = [select Id, Name,Createddate, StageName, AccountId,Sale_Campaign__c from Opportunity where StageName= 'Closed Won'  and Closedate =: Date.today()];    
        }
        else{
            oppIdsToClone = [select Id, Name,Createddate, StageName, AccountId,Sale_Campaign__c from Opportunity where StageName= 'Closed Won'  and Closedate =: Date.today()-1];
        }
        System.debug('Size==='+oppIdsToClone.size());
      
        
        return Database.getQueryLocator('select id,name,RecordTypeId,stageName,Due_Date__c,Entity_Type__c,Renewal_effective_Date__c,Renewal_End_Date__c,Renewal_State__c,ChargentSFA__Payment_Start_Date__c,CloseDate,AccountId,Sale_Campaign__c,ChargentSFA__Gateway__c,Override_Automation__c,ChargentSFA__Manual_Charge__c   from Opportunity where id IN:oppIdsToClone');        
    }  
    global void execute(Database.BatchableContext bc,List<Opportunity> scope){
        List <opportunity> opplist = New List <opportunity>();
        map<id,Opportunity> oppsToProcess = new map<id,Opportunity>();
        set<id> oppProcessed = new set<id>();
        set<id> oppids=new set<id>();
        system.debug('scope=='+scope);
        for(opportunity opp : scope)
        {
            system.debug('opp.stageName=='+opp.stageName);
            system.debug('opp.recordTypeId'+opp.recordTypeId);
            if(opp.stageName == 'Closed Won' &&
               (opp.recordTypeId == stateRecordTypeId ||
                opp.recordTypeId == standardRecordTypeId)
              )
                if(!OpportunityTriggerHandler.oppProcessed.contains(opp.id)){ // !OpportunityTriggerHandler.oppProcessed.contains //!oppProcessed.contains
                    oppsToProcess.put(opp.id, opp);
                    oppProcessed.add(opp.id);
                }
            system.debug(' === oppsToProcess === ' + oppsToProcess);
            system.debug(' === oppProcessed === ' + oppProcessed);
        } 
        OpportunityTriggerHandler.OpportunityRenewal(oppsToProcess);
    }
    global void finish(Database.BatchableContext BC){
        
        // WHEN "Is_Batch_Running__c = false", IT WILL ALLOW THE PROCESS BUILDER(Populate the Entity lookup field) CONDITON AND WILL EXECUTE THE FLOW(Populate the Entity lookup field) FOR INDIVIDUAL RECORDS
        // ADDED BY "Umer Amjad" ON "23-Nov-2021"
        BatchRunning__c runningBatchObj = BatchRunning__c.getOrgDefaults();
        runningBatchObj.Is_Batch_Running__c = false;
        UPDATE runningBatchObj;
        
        system.debug('Batch execution completed.');
    }                                            
}