objects/BatchRetryAttempts__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Create a separate record for your batch.</description>
    <fields>
        <fullName>Current_Iteration__c</fullName>
        <label>Current Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Iteration__c</fullName>
        <label>Maximum Iteration</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Retry Attempts</label>
</CustomObject>

objects/DebugInfo__c.object
<CustomObject>
    <fields>
        <fullName>DebugData__c</fullName>
        <label>DebugData</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>DebugInfo</label>
    <nameField>
        <displayFormat>DBI-{00000}</displayFormat>
        <label>DebugInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DebugInfo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dissolving</fullName>
                </value>
                <value>
                    <fullName>Inactive - SOS</fullName>
                </value>
                <value>
                    <fullName>Non Payment</fullName>
                </value>
                <value>
                    <fullName>Not Utilizing</fullName>
                </value>
                <value>
                    <fullName>Other (Explain in Notes)</fullName>
                    <default>true</default>
                    <label>Other (Explain in Notes)</label>
                </value>
                <value>
                    <fullName>RA Change</fullName>
                </value>
                <value>
                    <fullName>Renewal cost too high</fullName>
                </value>
                <value>
                    <fullName>Service Complaint</fullName>
                </value>
                <value>
                    <fullName>Client filing on their own.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <label>Service Item List</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>pymt__Total_Amount__c</fullName>
        <formula>Amount +  pymt__Shipping__c +  pymt__Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>PaymentConnect total calculated amount (Opportunity amount + shipping + tax)</inlineHelpText>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Pension901ClsAnnMaintSale.cls
/*
This batch will close lost renemal sales that were created from CreateSalesEntity batch
Schedule Date: 9/1
Developer: Rabeea Aqil
Final touch date: 6/28/2021

*/

global class Pension901ClsAnnMaintSale implements Database.Batchable<sObject>,System.Schedulable, Database.Stateful
{
    global   DebugInfo__c Dinfo=new DebugInfo__c();
    /* Exception[] errors = new Exception[0];
Set<String> setErrorIds = new Set<String>();
Set<String> setFailedIds = new Set<String>();
BatchRetryAttempts__c cs = BatchRetryAttempts__c.getInstance('BatchableFlipSaleStagePensionRenewals');
public BatchableFlipSaleStagePensionRenewals()
{

}
public BatchableFlipSaleStagePensionRenewals(Set<String> setIds)
{
try {
if (!setIds.isEmpty())
{

setErrorIds = setIds;
}
} catch (Exception e) {
system.debug('Continue');
}

}*/
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        Integer currentYear = Date.Today().Year();
        Date checkOppDte = Date.newInstance(currentYear, 08, 31);
        String query;
        /*   if(!setErrorIds.isEmpty())
{
query = 'SELECT Id,Name,StageName,Closed_Lost_Reason__c,Service_Item_List__c FROM Opportunity WHERE d IN: setErrorIds' ;
cs.Current_Iteration__c= cs.Current_Iteration__c+1;
update cs;
system.debug('Failed Batch===>>>>');
}
else
{
//query = 'SELECT Id,Name,StageName,Closed_Lost_Reason__c,Service_Item_List__c FROM Opportunity WHERE RecordType.Name = \'Pension Renewal\' AND Name=\'Annual Plan Maintenance\' AND CloseDate=:checkOppDte AND pymt__Total_Amount__c=350.00 AND StageName=\'Qualification\'';
query = 'SELECT Id,Name,StageName,Closed_Lost_Reason__c FROM Opportunity WHERE RecordType.Name = \'Pension Renewal\' AND Name=\'Annual Plan Maintenance\' AND CloseDate=:checkOppDte AND Service_Item_List__c=\'A00373;\' AND pymt__Total_Amount__c=350.00 AND StageName=\'Qualification\'';
cs.Current_Iteration__c = 1;
update cs;
system.debug('Success Batch===>>>');

}*/		
        if(Test.isRunningTest())
        {
            query = 'SELECT Id,Name,StageName,Closed_Lost_Reason__c FROM Opportunity WHERE RecordType.Name = \'Pension Renewal\' AND Name=\'Annual Plan Maintenance\' AND CloseDate=:checkOppDte AND Service_Item_List__c=\'A00373;\' AND Amount=350.00 AND StageName=\'Qualification\' LIMIT 200';
            
            
        }
        else
        {
            query = 'SELECT Id,Name,StageName,Closed_Lost_Reason__c FROM Opportunity WHERE RecordType.Name = \'Pension Renewal\' AND Name=\'Annual Plan Maintenance\' AND CloseDate=:checkOppDte AND Service_Item_List__c=\'A00373;\' AND Amount=350.00 AND StageName=\'Qualification\'';
        }
        
        
        
        return Database.getQueryLocator(query);
        
    }
    global void execute(Database.BatchableContext BC, List<Opportunity> scopeListOpp)
    {
        //list<OpportunityLineItem> tprod=[SELECT Name,Quantity, UnitPrice, TotalPrice,PricebookEntry.Name, PricebookEntry.Product2.Family FROM OpportunityLineItem WHERE OpportunityId IN:scopeListOpp AND Product2.Name='Pension - Annual Maintenance'];
        Product2[] pd = [Select id from Product2 where name='Pension - Annual Maintenance' ];
        Integer currentYear = Date.Today().Year();
        Date selectedDate =Date.today();
        Integer currentMonth = Date.Today().Month();
        Date firstDate = selectedDate.toStartOfMonth();
        Date oppCloseDte = Date.newInstance(currentYear, 08, 31);
        Date lastDate = firstDate.addDays(date.daysInMonth(selectedDate.year() , selectedDate.month())  - 1);
        system.debug(firstDate  + ' **** ' +lastDate );
        Boolean isCurrentAndLastDateSame = selectedDate.isSameDay(lastDate);
        List<Opportunity> updateOpp = new List<Opportunity>();
        if(scopeListOpp.size()>0)
        {
            if((currentMonth==9 && selectedDate.day()==1) || Test.isRunningTest())
            {
                for(Opportunity o: scopeListOpp)
                {
                    
                    o.Closed_Lost_Reason__c = 'Non Payment';
                    o.StageName = 'Closed Lost';
                    // o.CloseDate = Date.newInstance(currentYear, 09, 01);
                    updateOpp.add(o);
                    
                }
                try
                {
                    if(updateOpp.size()>0)
                    {
                        update updateOpp;
                    }
                    
                    
                }
                catch (Exception ex)
                {
                    System.Debug('Update failed ' + ex);
                    /*  for (Integer i = 0; i < updateOpp.size(); i++)
{
Dinfo.DebugData__c=ex.getMessage()+updateOpp.get(i).Id;
}*/
                    Dinfo.DebugData__c=ex.getMessage();
                    upsert Dinfo;
                    
                }
                //insert Dinfo;
                /* if(updateOpp.size()>0)
{
Database.SaveResult[] updateResult = Database.update(updateOpp,false);
for (Integer i = 0; i < updateResult.size(); i++) {
if (!updateResult.get(i).isSuccess()) {
setFailedIds.add(updateOpp.get(i).Id);
//Dinfo.DebugData__c ='Failed Record IDs: '+string.valueOf(setFailedIds);
Dinfo.DebugData__c ='Failed Record IDs: '+string.valueOf(updateOpp.get(i).Id)+',';
}

}
insert Dinfo;

}*/
            }
            
        }
        
    }
    global void finish(Database.BatchableContext BC)
    {
        /*   if(!setFailedIds.isEmpty() && cs.Current_Iteration__c <= cs.Maximum_Iteration__c)
{
database.executebatch(new BatchableFlipSaleStagePensionRenewals(setFailedIds),10);
}*/
        
    }
    global void execute(SchedulableContext SC) 
    {
        // database.executebatch(new BatchableFlipSaleStagePensionRenewals(null),10);
        database.executebatch(new Pension901ClsAnnMaintSale(),80);
    }
    
}