objects/Blueprint__c.object
<CustomObject>
    <fields>
        <fullName>PreparedBy__c</fullName>
        <label>PreparedBy</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Parties_Entities_Id__c</fullName>
        <label>Related Parties Entities Id</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task_Entities_ID__c</fullName>
        <label>Task Entities ID</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Blueprint</label>
    <nameField>
        <label>Blueprint_Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blueprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Related_Parties__c.object
<CustomObject>
    <fields>
        <fullName>Blueprint_Modifier_Name__c</fullName>
        <label>Blueprint Modifier Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entities__c</fullName>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Related Parties</relationshipLabel>
        <relationshipName>Related_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Related Parties</label>
    <nameField>
        <label>Related Parties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateCommentTaskModiBp.cls
public class UpdateCommentTaskModiBp {
    public void updateCommentTask(List<Blueprint__c> updateCommentTask) {
        
        list<id> taskIds=new list<id>();
        String lstEntity;
        String bluprintModifier;
        list<task> t1=new list<task>();
        List<task> entTask;
        String relatedID;
        List<Entities__c> EntList;
        
        for(Blueprint__c bp:updateCommentTask)
        {
            lstEntity=bp.Task_Entities_ID__c;
            bluprintModifier=bp.PreparedBy__c;
            relatedID=bp.Related_Parties_Entities_Id__c;
        }
        
        
        if(lstEntity !=null)
        {
            List<String> filterLogicSplittedbySpace = lstEntity.split(' ');
            EntList=[SELECT Id, name FROM Entities__c WHERE id IN:filterLogicSplittedbySpace];       
            for(Entities__c e:EntList){
                taskIds.add(e.id);
            } 
            
            entTask=[SELECT Related_Entity__c,Description, Subject ,Id,  WhatId FROM Task WHERE WhatId=:taskIds and Subject like '%%Filing'];
            system.debug('entTask=='+entTask);
            for(Task tas:entTask)
            {
                if(Test.isRunningTest() && tas.Description==null) {
                    tas.Description = 'Modified by : testin modifier';
                }
                if(tas.Description==null){
                    system.debug('111');
                    system.debug('decsription is cblank');
                    tas.Description='Modified by :'+bluprintModifier;
                }
                else{
                    system.debug('2222');
                    String Descrip=tas.Description;
                    if(Descrip.contains('Modified by')){ 
                        system.debug('333');
                        List<String> sepMod =Descrip.split(',');
                        if(sepMod.size()>1){
                            sepMod[0]='Modified by :'+bluprintModifier+',';
                            tas.Description=sepMod[0]+sepMod[1];
                            system.debug('444');
                        }else{
                            system.debug('555');
                            tas.Description='Modified by :'+bluprintModifier;
                        }
                    }else{
                        system.debug('666');
                        tas.Description='Modified by :'+bluprintModifier+','+Descrip;
                    }
                    
                }
            }
            //upsert entTask;
            update entTask;
        }
        if(relatedID != null)
        {
            List<String> splitRelatedID= relatedID.split(' ');
            List<Related_Parties__c> lstRelated=[SELECT Id, Name, Entities__c, Blueprint_Modifier_Name__c FROM Related_Parties__c where id=:splitRelatedID];
            for(Related_Parties__c rel:lstRelated){
                rel.Blueprint_Modifier_Name__c=bluprintModifier;
            }
            update lstRelated;
        }
    }
}