objects/Blueprint__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreparedBy__c</fullName>
        <label>PreparedBy</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Blueprint_Id__c</fullName>
        <label>Unique_Blueprint_Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Blueprint</label>
    <nameField>
        <label>Blueprint_Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blueprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Strategy_Session_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Account_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Lookup</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategy Session Questionnaires</relationshipLabel>
        <relationshipName>Strategy_Session_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Strategy Session Questionnaire</label>
    <nameField>
        <label>Strategy Session Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy Session Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountImageController.cls
/**
* A controller class to used to show Blueprint image on account page layout.
* 
* @author prateeks
* @version 1.0 - Aug 03, 2018
*/
Public Class AccountImageController {
    
    Public String recId{get; set;}  
    Public String fullFileURL{get; set;}
    Public List<Attachment> att{get; set;}
    public AccountImageController(ApexPages.StandardController controller) {
        
        fullFileURL = 'https://' + URL.getSalesforceBaseUrl().getHost();
        if(!test.isRunningTest()){
            recId = apexpages.currentpage().getparameters().get('id');
        }else{
            recId = controller.getId();
        }
        Id MyId = id.valueOf(recId);
        String sObjName = MyId.getSObjectType().getDescribe().getName();

        system.debug('curr page == ' + sObjName);
        if(sObjName == 'Strategy_Session_Questionnaire__c'){
         Strategy_Session_Questionnaire__c sId = [SELECT Id, Name, Account_Lookup__c FROM Strategy_Session_Questionnaire__c where id = :MyId LIMIT 1];
            system.debug('*******sId'+sId);
            recId = sId.Account_Lookup__c;
            system.debug('*******recId'+recId);
        }
        Account acc = new Account(id = recId);
        
        try {
            Blueprint__c uId = [SELECT AttachmentId__c,Unique_Blueprint_Id__c FROM Blueprint__c WHERE AccountId__c =:acc.Id ORDER By CreatedDate DESC LIMIT 1];
            system.debug('Unique id is = ' + uId.Unique_Blueprint_Id__c);
            List<Blueprint__c> attachmentId = [SELECT AttachmentId__c,Unique_Blueprint_Id__c,PreparedBy__c FROM Blueprint__c WHERE Unique_Blueprint_Id__c = :uId.Unique_Blueprint_Id__c ORDER By CreatedDate ASC];
            Set<String> attSet = new Set<String>();
            for(Blueprint__c bp : attachmentId){
                attSet.add(bp.AttachmentId__c);
            }       
            att= [select Id, Name, Description from Attachment where Id in :attSet ORDER By CreatedDate DESC];
        } catch (QueryException e) {
            ApexPages.addMessages(e); 
        }   
    }
}