objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Apr_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Apr Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Aug_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Aug Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Bookkeeping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bookkeepings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dec_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Dec Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Feb_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Feb Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Jan_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Jan Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Jul_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Jul Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Jun_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Jun Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mar_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Mar Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>May_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>May Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Nov_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Nov Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Oct_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Oct Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sep_Called_Client_On__c</fullName>
        <inlineHelpText>Please call the client at least once a month and record when you did so here.</inlineHelpText>
        <label>Sep Called Client On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Set_of_Books__c</fullName>
        <label>Set of Books</label>
        <referenceTo>Set_of_Books__c</referenceTo>
        <relationshipLabel>Entity Bookkeeping Records</relationshipLabel>
        <relationshipName>Bookkeeping_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Bookkeeping</businessProcess>
        <description>Used for Bookkeeping Cases</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Set_of_Books__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeping_Reviewer__c</fullName>
        <label>Bookkeeping Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Reviewer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Set of Books</label>
    <nameField>
        <label>Set of Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Set of Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <description>Task For Bookkeeping</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Call</fullName>
        <active>true</active>
        <description>Used for Calls.</description>
        <label>Call</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Bookkeeping_Reviewer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Kiera Dunphy</fullName>
    </customValue>
    <customValue>
        <fullName>Lanzi Reel</fullName>
    </customValue>
    <customValue>
        <fullName>Ryan On</fullName>
    </customValue>
    <customValue>
        <fullName>Trisha Cullinane</fullName>
    </customValue>
    <customValue>
        <fullName>Troy Butler</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Nancy Naraine</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Kevin Dennis</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Flemming</fullName>
    </customValue>
    <customValue>
        <fullName>Tesia Owen</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
        <isActive>false</isActive>
        <label>Bethany Castleberry</label>
    </customValue>
    <customValue>
        <fullName>Christine Zimmerman</fullName>
        <isActive>false</isActive>
        <label>Christine Zimmerman</label>
    </customValue>
    <customValue>
        <fullName>Rebecca Gallegos</fullName>
        <isActive>false</isActive>
        <label>Rebecca Gallegos</label>
    </customValue>
    <customValue>
        <fullName>Marie Pues</fullName>
        <isActive>false</isActive>
        <label>Marie Pues</label>
    </customValue>
    <customValue>
        <fullName>Maria Boone</fullName>
        <isActive>false</isActive>
        <label>Maria Boone</label>
    </customValue>
    <masterLabel>Bookkeeping Reviewer</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/BKLoggedCallHandler.cls
public class BKLoggedCallHandler {
    
    public static boolean alreadyProcessed;
    
    public void taskDuplication(List<Task> newList) {
        
        if(alreadyProcessed == true) return;
        alreadyProcessed = true;
        List<Task> taskList = new List<Task>();
        List<Bookkeeping__c> bkUpdateList = new List<Bookkeeping__c>();
        
        for (Task t:newList) {
            // If a completed call is logged in a case
            if (t.RecordTypeId == '012U0000000g5s9' && 
                t.Status == 'Completed' && 
                t.WhatId != null &&
                String.valueOf(t.WhatId).StartsWith('500')){
                    // Duplicate the call on related bookkeeping records
                    for(Bookkeeping__c BK:[SELECT Id, Set_Of_Books__c, Client_Name__c FROM Bookkeeping__c Where (Case__c = :t.WhatId)]) {
                        task newTask = new task();
                        newTask.Subject = t.Subject;
                        newTask.ActivityDate = t.ActivityDate;
                        newTask.Status = t.Status;
                        newTask.OwnerId = t.OwnerId;
                        newTask.RecordTypeId = t.RecordTypeId;
                        newTask.WhatId = BK.Id;
                        newTask.Client__c = bk.Client_Name__c;
                        newTask.Summary__c = t.Summary__c;
                        newTask.Call_Outcome__c = t.Call_Outcome__c;
                        newTask.Type = t.Type;
                        newTask.Priority = t.Priority;
                        newTask.Description = t.Description;
                        newTask.Bookkeeping_Reviewer__c = t.Bookkeeping_Reviewer__c;
                        taskList.add(newTask);
                        
                            switch on (test.isRunningTest() ? Integer.valueOf(t.Fee_Quote__c) : system.today().month()) {
                                
                                When 1 {
                                    bk.Jan_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                When 2 {
                                    bk.Feb_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                When 3 {
                                    bk.Mar_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                when 4 {
                                    bk.Apr_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                when 5 {
                                    bk.May_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                when 6 {
                                    bk.Jun_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                when 7 {
                                    bk.Jul_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                when 8 {
                                    bk.Aug_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                when 9 {
                                    bk.Sep_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                when 10 {
                                    bk.Oct_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                when 11 {
                                    bk.Nov_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                }
                                when 12{
                                    bk.Dec_Called_Client_On__c = system.now();
                                    bkUpdateList.add(bk);
                                } 
                        }

                        
                    } 
  
                    insert taskList;
                    update bkUpdateList;    
                    
                }
        }
    }
}