objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeping_IC__c</fullName>
        <label>Bookkeeping IC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bookkeeper 1</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 2</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 3</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 4</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 5</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 6</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 7</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 8</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 9</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 10</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 11</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 12</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 13</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 14</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 15</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 16</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 17</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 18</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 19</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 20</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 21</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 22</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 23</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 24</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 25</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 26</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 27</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 28</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 29</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Bookkeeping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Lead__c</fullName>
        <label>Team Lead</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Nancy Naraine</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Mandrell Hahn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Bookkeeping_Task</fullName>
        <active>true</active>
        <description>Task for Bookkeeper</description>
        <label>Bookkeeping Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/bookkeepingFieldsFromTasks.cls
public class bookkeepingFieldsFromTasks {
    
    public static boolean firstRun;
    public static boolean stopRun;
    
    public void passUpdateFields(List<Task> newList, Map<Id,Task> oldMap) {
        
        if (firstRun == true) return;
        firstRun = true;
        
        Id bookkeepingTaskid = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Bookkeeping_Task').getRecordTypeId();
        
        List<Bookkeeping__c> updateList = new List<Bookkeeping__c>();
        
        for (Task t : newList) {
            
            if (t.RecordTypeId == bookkeepingTaskid && string.valueOf(t.whatId).startsWith('500')) {
                
                if(t.Team_Lead__c != oldMap.get(t.id).Team_Lead__c ||
                   t.Bookkeeping_IC__c != oldMap.get(t.id).Bookkeeping_IC__c) {
                       
                       for (Bookkeeping__c bk : [SELECT Id 
                                                 FROM Bookkeeping__c
                                                 WHERE Case__c = :t.WhatId]) {
                                                     
                                                     bk.Team_Lead__c = t.Team_Lead__c;
                                                     bk.Bookkeeping_IC__c = t.Bookkeeping_IC__c;
                                                     updateList.add(bk);
                                                     
                                                 }
                       
                       
                   } 
                
            }
        }
        
        update updateList;        
    }
    
    public void passInsertFields(List<Task> newList) {
        
        if (stopRun == true) return;
        stopRun = true;
        
        Id bookkeepingTaskid = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Bookkeeping_Task').getRecordTypeId();
        
        List<Bookkeeping__c> updateList = new List<Bookkeeping__c>();
        
        for (Task t : newList) {
            
            if (t.RecordTypeId == bookkeepingTaskid && string.valueOf(t.whatId).startsWith('500')) {
                
                if(t.Team_Lead__c != null ||
                   t.Bookkeeping_IC__c != null) {
                       
                       for (Bookkeeping__c bk : [SELECT Id 
                                                 FROM Bookkeeping__c
                                                 WHERE Case__c = :t.WhatId]) {
                                                     
                                                     bk.Team_Lead__c = t.Team_Lead__c;
                                                     bk.Bookkeeping_IC__c = t.Bookkeeping_IC__c;
                                                     updateList.add(bk);
                                                     
                                                 }
                       
                   }
                
            }
            
            
        }
        update updateList;
    }
    
}