objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abraham Carrillo</fullName>
                </value>
                <value>
                    <fullName>Alishia Greene-Jenkins</fullName>
                </value>
                <value>
                    <fullName>Antoinette Reid</fullName>
                </value>
                <value>
                    <fullName>Ashley Cloutier</fullName>
                </value>
                <value>
                    <fullName>Austin Stephens</fullName>
                </value>
                <value>
                    <fullName>Becky Arnold</fullName>
                </value>
                <value>
                    <fullName>Blanca Lemus</fullName>
                </value>
                <value>
                    <fullName>Brenda Guzman</fullName>
                </value>
                <value>
                    <fullName>Brenda Navarrette</fullName>
                </value>
                <value>
                    <fullName>Christina Chavez</fullName>
                </value>
                <value>
                    <fullName>Cindy Mejorado</fullName>
                </value>
                <value>
                    <fullName>Crystal Moyer</fullName>
                </value>
                <value>
                    <fullName>Danny On</fullName>
                </value>
                <value>
                    <fullName>Dawn Popa</fullName>
                </value>
                <value>
                    <fullName>Imelda Hilario</fullName>
                </value>
                <value>
                    <fullName>Jacquie Wallace-Small</fullName>
                </value>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Jennifer Soikowski</fullName>
                </value>
                <value>
                    <fullName>Jessica Turner</fullName>
                </value>
                <value>
                    <fullName>Jonathan Salyer</fullName>
                </value>
                <value>
                    <fullName>Kayla Fleming</fullName>
                </value>
                <value>
                    <fullName>Keanu Rhodes</fullName>
                </value>
                <value>
                    <fullName>Kenneth Harrah</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Kimberly Smiley</fullName>
                </value>
                <value>
                    <fullName>Kingstone Mashingaidze</fullName>
                </value>
                <value>
                    <fullName>Lanzi Reel</fullName>
                </value>
                <value>
                    <fullName>Mandrell Hahn</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Melissa McBride</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <description>Task For Bookkeeping</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>Used for Emails</description>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <description>Tax Task</description>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Job_Role__c</fullName>
        <label>Job Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Job_Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LoginHistoryCount__c</fullName>
        <label>LoginHistoryCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UpdateLoginCount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UpdateLoginCount</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Job_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accounting Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Bookkeeping</fullName>
    </customValue>
    <customValue>
        <fullName>Estate Planning</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>QA</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal Advisor - BCP</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Tax</fullName>
    </customValue>
    <customValue>
        <fullName>External User</fullName>
    </customValue>
    <masterLabel>Job Roles</masterLabel>
</GlobalValueSet>

classes/RoleAutomationServiceTest.cls
/*****************************************************************************************************************************
@ Class Name:    RoleAutomationServiceTest
@ Version:       1.0
@ Author:        Sadia Asif
@ Description:   Test Class of RoleAutomationService 
*****************************************************************************************************************************/
@isTest
public  with sharing class RoleAutomationServiceTest {
    public static user USER =[select Id,name from user where id=:userinfo.getuserid() limit 1];
    public static Set<Id> userIds = new Set<Id>();
    public static String name;
    public static boolean deactivate = true;
    
    private static testmethod void userLicenseAssignmentTest(){
        
        String creatRequestResponse = '{"Metadata":{"active":true,"label":"Tax","fullName":"Task.Tax","picklistValues":[{"picklist":"Bookkeeping_Admin__c","values":[{"color":null,"default":false,"description":null,"isActive":true,"urls":null,"valueName":"Abraham Carrillo"}]}],"urls":null}}';      
        Profile p = [select id from profile where name='System Administrator'];
        User usr1= new User();
        usr1.Username = 'testyzk@test.com';
        usr1.LastName= 'User1';
        usr1.Alias='Testa';
        usr1.Email='testuser1@gmail.com';
        usr1.Job_Role__c='Bookkeeping';
        usr1.ProfileId= p.id;
        usr1.TimeZoneSidKey = 'GMT';
        usr1.LocaleSidKey ='en_US';
        usr1.EmailEncodingKey ='ISO-8859-1';
        usr1.LanguageLocaleKey ='en_US';
        usr1.isActive = true;
        
        usr1.UpdateLoginCount__c = false;
        userIds.add(usr1.Id);
        database.insert(usr1);
        
        Test.setMock(HttpCalloutMock.class, new Mock());
        Test.startTest();
        RoleAutomationService construct = new RoleAutomationService(userIds,deactivate);
        deactivate=true;
        System.enqueueJob(new RoleAutomationRecordType());
        Test.stopTest();
        
        Test.setMock(HttpCalloutMock.class, new MockGenerator());
        
        System.enqueueJob(new RoleAutomationBookRecType());
        //  Test.setMock(HttpCalloutMock.class, new MockGeneratorforRec());
    }
    private static testMethod void setPermissionSet(){
        
        RoleAutomationService.setPermissionSet(userIds);
    }
    private static testmethod void userTrigger(){
        try{
            User usr= new User();
            usr.LoginHistoryCount__c = 29;
            usr.Id= USER.Id ;
            usr.UpdateLoginCount__c= true;
            database.update(usr);
            RoleAutomationService.customPicklistValuesSet('def');
        }
        catch(Exception e){}
    }
    
    Private class Mock implements HttpCalloutMock{
        
        
        public  HTTPResponse respond(HTTPRequest req) {
            
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            String creatRequestResponse = '{"Metadata":{"customValue":[{"color":null,"default":false,"description":null,"isActive":true,"label":"Abraham Carrillo","urls":null,"valueName":"Abraham Carrillo"}],"description":null,"masterLabel":"Bookkeeping Admin","sorted":true,"urls":null},"FullName":"Bookkeeping_Admin"}';
            res.setBody(creatRequestResponse);
            res.setStatusCode(201);
            res.setStatus('CREATED');
            return res;
        } 
    }
    
    Private class MockGenerator implements HttpCalloutMock{
        
        public  HTTPResponse respond(HTTPRequest req) {
            
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            String creatRequestResponse = '{"Metadata":{"label":"Bookkeeper","required":false,"type":"Picklist","valueSet":{"valueSetDefinition":{"sorted":true,"value":[{"color":null,"default":false,"description":null,"isActive":true,"label":"Hi","urls":null,"valueName":"Hi"}]}}},"FullName":"Bookkeeping__c.Bookkeeper__c"}';
            res.setBody(creatRequestResponse);
            res.setStatusCode(201);
            res.setStatus('CREATED');
            return res;
        } 
    }
    
    @isTest
    public static void myUnitTest(){
        
        PicklistValueWrapper wrapper= new PicklistValueWrapper ();
        
        wrapper.color=null;
        wrapper.description=null;
        wrapper.urls=null;
        
    }
    
    
    Private class MockGeneratorforRec implements HttpCalloutMock{
        
        
        public  HTTPResponse respond(HTTPRequest req) {
            
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            String creatRequestResponse = '{"Metadata":{"active":true,"label":"Tax","fullName":"Task.Tax","picklistValues":[{"picklist":"Bookkeeping_Admin__c","values":[{"color":null,"default":false,"description":null,"isActive":true,"urls":null,"valueName":"Abraham Carrillo"}]}],"urls":null}}';
            res.setBody(creatRequestResponse);
            res.setStatusCode(201);
            res.setStatus('CREATED');
            return res;
        } 
    }
    
}