objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bookkeepings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Wide_Comments__c</fullName>
        <inlineHelpText>Putting comments in this box will put the same comments in this box on every bookkeeping record that belongs to this client.</inlineHelpText>
        <label>Client-Wide Comments</label>
        <length>35000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Set_of_Books__c</fullName>
        <label>Set of Books</label>
        <referenceTo>Set_of_Books__c</referenceTo>
        <relationshipLabel>Entity Bookkeeping Records</relationshipLabel>
        <relationshipName>Bookkeeping_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Set_of_Books__c.object
<CustomObject>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Wide_Comments__c</fullName>
        <label>Client Wide Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Set of Books</label>
    <nameField>
        <label>Set of Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Set of Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/bookkeepingClientWideComments.cls
public class bookkeepingClientWideComments {
    
    public static boolean alreadyProcessed;
    
    public static void ClientWideComments(List<Bookkeeping__c> newList, Map<Id,Bookkeeping__c> oldMap){
        
        if (alreadyProcessed == true) return;
        alreadyProcessed = true;
        
        List<Bookkeeping__c> updateList = new List<Bookkeeping__c>();

		for (Bookkeeping__c bk : newList) {
        
            if (bk.Client_Wide_Comments__c != OldMap.get(bk.Id).Client_Wide_Comments__c && bk.Set_of_Books__c == null) {
            
        		for (Bookkeeping__c allBk : [SELECT Id,Client_Wide_Comments__c 
                                             From Bookkeeping__c 
                                             WHERE Client_Name__c = :bk.Client_Name__c 
                                             AND Id != :bk.id AND Set_of_Books__c = null]) {
   
                    allBk.Client_Wide_Comments__c = bk.Client_Wide_Comments__c;
                	updateList.add(allBk);
                    
                }
                                   
            }
        }
        
      update updateList;  
  
    }
    
}