objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeping_IC__c</fullName>
        <label>Bookkeeping IC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bookkeeper 1</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 2</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 3</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 4</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 5</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 6</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 7</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 8</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 9</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 10</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 11</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 12</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 13</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 14</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 15</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 16</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 17</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 18</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 19</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 20</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 21</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 22</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 23</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 24</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 25</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 26</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 27</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 28</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 29</fullName>
                </value>
                <value>
                    <fullName>Bookkeeper 30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Bookkeeping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bookkeepings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Lead__c</fullName>
        <label>Team Lead</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Nancy Naraine</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Mandrell Hahn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <businessProcess>Bookkeeping</businessProcess>
        <description>Used for Bookkeeping Cases</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <description>Task For Bookkeeping</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Bookkeeping_Task</fullName>
        <active>true</active>
        <description>Task for Bookkeeper</description>
        <label>Bookkeeping Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/bookkeepingFieldsFromTasksTest.cls
@isTest
public class bookkeepingFieldsFromTasksTest {
    
    @testSetup static void createData() {
        
        Account a = new account();
        a.Name = '123';
        insert a;
        
        Case c = new Case();
        c.Subject = 'Test Case';
        C.AccountId = a.id;
        c.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Bookkeeping').getRecordTypeId();
        insert c;
        
        Bookkeeping__c bk = new Bookkeeping__c();
        bk.Name = 'Bk 123';
        bk.Client_Name__c = a.id;
        bk.Case__c = c.id;
        insert bk;
        
        Contact ct = new Contact();
        ct.LastName = 'todd';
        ct.AccountId = a.id;
        insert ct;
        
        Id bookkeepingTaskid = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Bookkeeping_Task').getRecordTypeId();
        
		Task t = new Task();
        t.Subject = 'Test Task 2';
        t.RecordTypeId = bookkeepingTaskid;
        t.WhatId = c.id;
        t.WhoId = ct.id;
        t.Bookkeeping_Admin__c = 'Ashley Cloutier';
        t.Status = 'Not Started';
        t.Priority = 'Normal';
        t.OwnerId = [SELECT Id FROM User WHERE Name = 'Anderson Advisors'].id;
        t.Team_Lead__c = 'Jasmine Licitra';
        t.Bookkeeping_IC__c = 'Bookkeeper 1';
        insert t;        
        
    }
    
    @isTest
    public static void createTasks() {
        
        Case c = [SELECT Id FROM Case];
        Contact ct = [SELECT Id FROM Contact];
        
        Id bookkeepingTaskid = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Bookkeeping_Task').getRecordTypeId();
        
        Task t = new Task();
        t.Subject = 'Test Task 1';
        t.RecordTypeId = bookkeepingTaskid;
        t.WhatId = c.id;
        t.WhoId = ct.id;
        t.Bookkeeping_Admin__c = 'Ashley Cloutier';
        t.Status = 'Not Started';
        t.Priority = 'Normal';
        t.OwnerId = [SELECT Id FROM User WHERE Name = 'Anderson Advisors'].id;
        t.Team_Lead__c = 'Jasmine Licitra';
        t.Bookkeeping_IC__c = 'Bookkeeper 1';
        insert t;
        
        Bookkeeping__c bk = [SELECT Id, Team_Lead__c, Bookkeeping_IC__c FROM Bookkeeping__c];
        
        System.assertEquals('Jasmine Licitra', bk.Team_Lead__c);
        System.assertEquals('Bookkeeper 1', bk.Bookkeeping_IC__c);
    
    }
    
    @isTest
    public static void updateTasks() {
        
		Task t2 = [SELECT Id From Task WHERE Subject = 'Test Task 2']; 
        t2.Team_Lead__c = 'Maria Boone';
        t2.Bookkeeping_IC__c = 'Bookkeeper 2';
        
        update t2;
        
        Bookkeeping__c bk2 = [SELECT Id, Team_Lead__c, Bookkeeping_IC__c FROM Bookkeeping__c];
        
        System.assertEquals('Maria Boone', bk2.Team_Lead__c);
        System.assertEquals('Bookkeeper 2', bk2.Bookkeeping_IC__c);
   
    }

}