objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Apr_Bookkeeping_Stages__c</fullName>
        <label>Apr Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Aug_Bookkeeping_Stages__c</fullName>
        <label>Aug Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper_Reviewer__c</fullName>
        <label>Bookkeeper Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Ashley Cloutier</fullName>
                </value>
                <value>
                    <fullName>Blanca Lemus</fullName>
                </value>
                <value>
                    <fullName>Christina Chavez</fullName>
                </value>
                <value>
                    <fullName>Crystal Moyer</fullName>
                </value>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Lanzi Reel</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Rebecca Gallegos</fullName>
                </value>
                <value>
                    <fullName>Tracy Cooklin</fullName>
                </value>
                <value>
                    <fullName>Trisha Cullinane</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abraham Carrillo</fullName>
                </value>
                <value>
                    <fullName>Alishia Greene-Jenkins</fullName>
                </value>
                <value>
                    <fullName>Antoinette Reid</fullName>
                </value>
                <value>
                    <fullName>Ashley Cloutier</fullName>
                </value>
                <value>
                    <fullName>Austin Stephens</fullName>
                </value>
                <value>
                    <fullName>Becky Arnold</fullName>
                </value>
                <value>
                    <fullName>Blanca Lemus</fullName>
                </value>
                <value>
                    <fullName>Brenda Guzman</fullName>
                </value>
                <value>
                    <fullName>Brenda Navarrette</fullName>
                </value>
                <value>
                    <fullName>Christina Chavez</fullName>
                </value>
                <value>
                    <fullName>Cindy Mejorado</fullName>
                </value>
                <value>
                    <fullName>Crystal Moyer</fullName>
                </value>
                <value>
                    <fullName>Danny On</fullName>
                </value>
                <value>
                    <fullName>Dawn Popa</fullName>
                </value>
                <value>
                    <fullName>Imelda Hilario</fullName>
                </value>
                <value>
                    <fullName>Jacquie Wallace-Small</fullName>
                </value>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Jennifer Soikowski</fullName>
                </value>
                <value>
                    <fullName>Jessica Turner</fullName>
                </value>
                <value>
                    <fullName>Jonathan Salyer</fullName>
                </value>
                <value>
                    <fullName>Kayla Fleming</fullName>
                </value>
                <value>
                    <fullName>Keanu Rhodes</fullName>
                </value>
                <value>
                    <fullName>Kenneth Harrah</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Kimberly Smiley</fullName>
                </value>
                <value>
                    <fullName>Kingstone Mashingaidze</fullName>
                </value>
                <value>
                    <fullName>Lanzi Reel</fullName>
                </value>
                <value>
                    <fullName>Mandrell Hahn</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Melissa McBride</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Box_Viewable_Folder__c</fullName>
        <inlineHelpText>Please enter the client&apos;s Box Viewable Folder URL here. This link will be used when emails are sent to the client.</inlineHelpText>
        <label>Box Viewable Folder</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Bookkeeping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bookkeepings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dec_Bookkeeping_Stages__c</fullName>
        <label>Dec Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feb_Bookkeeping_Stages__c</fullName>
        <label>Feb Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Jan_Bookkeeping_Stages__c</fullName>
        <label>Jan Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Jul_Bookkeeping_Stages__c</fullName>
        <label>Jul Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Jun_Bookkeeping_Stages__c</fullName>
        <label>Jun Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mar_Bookkeeping_Stages__c</fullName>
        <label>Mar Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>May_Bookkeeping_Stages__c</fullName>
        <label>May Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nov_Bookkeeping_Stages__c</fullName>
        <label>Nov Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oct_Bookkeeping_Stages__c</fullName>
        <label>Oct Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quickbooks_Record_URL__c</fullName>
        <label>Quickbooks Record URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sep_Bookkeeping_Stages__c</fullName>
        <label>Sep Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Set_of_Books__c</fullName>
        <label>Set of Books</label>
        <referenceTo>Set_of_Books__c</referenceTo>
        <relationshipLabel>Entity Bookkeeping Records</relationshipLabel>
        <relationshipName>Bookkeeping_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Set_of_Books__c.object
<CustomObject>
    <fields>
        <fullName>Apr_Bookkeeping_Stages__c</fullName>
        <label>Apr Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Aug_Bookkeeping_Stages__c</fullName>
        <label>Aug Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Admin</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bookkeeping_Reviewer__c</fullName>
        <label>Bookkeeping Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Reviewer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Box_Viewable_Folder__c</fullName>
        <label>Box Viewable Folder</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Set of Books</relationshipLabel>
        <relationshipName>Set_of_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feb_Bookkeeping_Stages__c</fullName>
        <label>Feb Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Jan_Bookkeeping_Stages__c</fullName>
        <label>Jan Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Jul_Bookkeeping_Stages__c</fullName>
        <label>Jul Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Jun_Bookkeeping_Stages__c</fullName>
        <label>Jun Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mar_Bookkeeping_Stages__c</fullName>
        <label>Mar Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>May_Bookkeeping_Stages__c</fullName>
        <label>May Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nov_Bookkeeping_Stages__c</fullName>
        <label>Nov Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oct_Bookkeeping_Stages__c</fullName>
        <label>Oct Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quickbooks_Record_URL__c</fullName>
        <label>Quickbooks Record URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sep_Bookkeeping_Stages__c</fullName>
        <label>Sep Bookkeeping Stages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bookkeeping_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Set of Books</label>
    <nameField>
        <label>Set of Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Set of Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Bookkeeping_Admin.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abdur Rehman</fullName>
    </customValue>
    <customValue>
        <fullName>Abraham Carrillo</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Hendershot</fullName>
    </customValue>
    <customValue>
        <fullName>Angela Berrow</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Langer</fullName>
    </customValue>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>awais khan</fullName>
    </customValue>
    <customValue>
        <fullName>Becky Arnold</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Bobby Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Bruce Williams</fullName>
    </customValue>
    <customValue>
        <fullName>Carol Spagnoletta</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Conrad Gomez</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Dawson Phipps</fullName>
    </customValue>
    <customValue>
        <fullName>Doug Guard</fullName>
    </customValue>
    <customValue>
        <fullName>Hebert Romero</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Jennifer Petrunyak</fullName>
    </customValue>
    <customValue>
        <fullName>Jerome Apples</fullName>
    </customValue>
    <customValue>
        <fullName>Joel Evans</fullName>
    </customValue>
    <customValue>
        <fullName>John Doe</fullName>
    </customValue>
    <customValue>
        <fullName>Jonna States</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Fleming</fullName>
    </customValue>
    <customValue>
        <fullName>Kelly Van Middlesworth</fullName>
    </customValue>
    <customValue>
        <fullName>Kenneth Harrah</fullName>
    </customValue>
    <masterLabel>Bookkeeping Admin</masterLabel>
</GlobalValueSet>

globalValueSets/Bookkeeping_Reviewer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ashley Cloutier</fullName>
    </customValue>
    <customValue>
        <fullName>Blanca Lemus</fullName>
    </customValue>
    <customValue>
        <fullName>Christina Chavez</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Licitra</fullName>
    </customValue>
    <customValue>
        <fullName>Kiera Dunphy</fullName>
    </customValue>
    <customValue>
        <fullName>Lanzi Reel</fullName>
    </customValue>
    <customValue>
        <fullName>Ryan On</fullName>
    </customValue>
    <customValue>
        <fullName>Trisha Cullinane</fullName>
    </customValue>
    <customValue>
        <fullName>Troy Butler</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal Martinez</fullName>
    </customValue>
    <customValue>
        <fullName>Nancy Naraine</fullName>
    </customValue>
    <customValue>
        <fullName>Cindy Mejorado</fullName>
    </customValue>
    <customValue>
        <fullName>Kevin Dennis</fullName>
    </customValue>
    <customValue>
        <fullName>Kayla Flemming</fullName>
    </customValue>
    <customValue>
        <fullName>Tesia Owen</fullName>
    </customValue>
    <customValue>
        <fullName>Bethany Castleberry</fullName>
        <isActive>false</isActive>
        <label>Bethany Castleberry</label>
    </customValue>
    <customValue>
        <fullName>Christine Zimmerman</fullName>
        <isActive>false</isActive>
        <label>Christine Zimmerman</label>
    </customValue>
    <customValue>
        <fullName>Rebecca Gallegos</fullName>
        <isActive>false</isActive>
        <label>Rebecca Gallegos</label>
    </customValue>
    <customValue>
        <fullName>Marie Pues</fullName>
        <isActive>false</isActive>
        <label>Marie Pues</label>
    </customValue>
    <customValue>
        <fullName>Maria Boone</fullName>
        <isActive>false</isActive>
        <label>Maria Boone</label>
    </customValue>
    <masterLabel>Bookkeeping Reviewer</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Bookkeeping_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No Books This Month</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>Client Unresponsive</fullName>
    </customValue>
    <customValue>
        <fullName>Supporting Documents Received</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Client</fullName>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Review Notes</fullName>
    </customValue>
    <customValue>
        <fullName>Review Notes - Waiting on Client</fullName>
    </customValue>
    <customValue>
        <fullName>Send Financials</fullName>
    </customValue>
    <customValue>
        <fullName>Send Financials - Waiting on Client</fullName>
    </customValue>
    <customValue>
        <fullName>Stopped_Services</fullName>
        <label>Stopped Services</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Needs Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Missing Information</fullName>
        <isActive>false</isActive>
        <label>Missing Information</label>
    </customValue>
    <masterLabel>Bookkeeping Stages</masterLabel>
</GlobalValueSet>

classes/setOfBooksHandler.cls
public class setOfBooksHandler {
    
    public static void bkChange(List<Set_of_Books__c> newList, Map<Id,Set_Of_Books__c> newMap, Map<Id,Set_Of_Books__c> oldMap) {
        
        List<Bookkeeping__c> updateList = new List<Bookkeeping__c>();
                
        for (Set_of_Books__c bookset : newList) {
            
            system.debug(bookset.id);
            
            // SCH-0048
            if(!newMap.equals(oldMap)) {
                system.debug('cond chk: '+ ( !newMap.equals(oldMap) ) );
                for (Bookkeeping__c bk : [SELECT Id,Name, Bookkeeper__c FROM Bookkeeping__c WHERE Set_Of_Books__c = :bookset.id]) {
                    
                    system.debug('bk.Name: '+bk.Name);
                    
                    //Record Details
                    bk.Bookkeeper__c 		    = bookset.Bookkeeper__c;
                    bk.Bookkeeper_Reviewer__c   = bookset.Bookkeeping_Reviewer__c;
                    bk.Client_Name__c		    = bookset.Client__c;
                    bk.Case__c  			    = bookset.Case__c;
                    bk.Quickbooks_Record_URL__c = bookset.Quickbooks_Record_URL__c;
                    bk.Box_Viewable_Folder__c   = bookset.Box_Viewable_Folder__c;
                    
                    //Stage info
                    bk.Jan_Bookkeeping_Stages__c = bookset.Jan_Bookkeeping_Stages__c;
                    bk.Feb_Bookkeeping_Stages__c = bookset.Feb_Bookkeeping_Stages__c;
                    bk.Mar_Bookkeeping_Stages__c = bookset.Mar_Bookkeeping_Stages__c;
                    bk.Apr_Bookkeeping_Stages__c = bookset.Apr_Bookkeeping_Stages__c;
                    bk.May_Bookkeeping_Stages__c = bookset.May_Bookkeeping_Stages__c;
                    bk.Jun_Bookkeeping_Stages__c = bookset.Jun_Bookkeeping_Stages__c;
                    bk.Jul_Bookkeeping_Stages__c = bookset.Jul_Bookkeeping_Stages__c;
                    bk.Aug_Bookkeeping_Stages__c = bookset.Aug_Bookkeeping_Stages__c;
                    bk.Sep_Bookkeeping_Stages__c = bookset.Sep_Bookkeeping_Stages__c;
                    bk.Oct_Bookkeeping_Stages__c = bookset.Oct_Bookkeeping_Stages__c;
                    bk.Nov_Bookkeeping_Stages__c = bookset.Nov_Bookkeeping_Stages__c;
                    bk.Dec_Bookkeeping_Stages__c = bookset.Dec_Bookkeeping_Stages__c;
                    
                    //Draft Financial Info
                    bk.Jan_Draft_Financial_Sent_to_Client_On__c = bookset.Jan_Draft_Financial_Sent_to_Client_On__c;
                    bk.Feb_Draft_Financial_Sent_to_Client_On__c = bookset.Feb_Draft_Financial_Sent_to_Client_On__c;
                    bk.Mar_Draft_Financial_Sent_to_Client_On__c = bookset.Mar_Draft_Financial_Sent_to_Client_On__c;
                    bk.Apr_Draft_Financial_Sent_to_Client_On__c = bookset.Apr_Draft_Financial_Sent_to_Client_On__c;
                    bk.May_Draft_Financial_Sent_to_Client_On__c = bookset.May_Draft_Financial_Sent_to_Client_On__c;
                    bk.Jun_Draft_Financial_Sent_to_Client_On__c = bookset.Jun_Draft_Financial_Sent_to_Client_On__c;
                    bk.Jul_Draft_Financial_Sent_to_Client_On__c = bookset.Jul_Draft_Financial_Sent_to_Client_On__c;
                    bk.Aug_Draft_Financial_Sent_to_Client_On__c = bookset.Aug_Draft_Financial_Sent_to_Client_On__c;
                    bk.Sep_Draft_Financial_Sent_to_Client_On__c = bookset.Sep_Draft_Financial_Sent_to_Client_On__c;
                    bk.Oct_Draft_Financial_Sent_to_Client_On__c = bookset.Oct_Draft_Financial_Sent_to_Client_On__c;
                    bk.Nov_Draft_Financial_Sent_to_Client_On__c = bookset.Nov_Draft_Financial_Sent_to_Client_On__c;
                    bk.Dec_Draft_Financial_Sent_to_Client_On__c = bookset.Dec_Draft_Financial_Sent_to_Client_On__c;
                    
                    //Tax Info
                    bk.Fiscal_Year_End__c 					= bookset.Fiscal_Year_End__c;
                    bk.Completing_Books_for_Tax_Year__c     = bookset.Completing_Books_for_Tax_Year__c;
                    bk.Sent_to_Tax__c						= bookset.Sent_To_Tax__c;
                    bk.Extension_Filed__c					= bookset.Extension_Filed__c;
                    bk.Return_Filed__c						= bookset.Return_Filed__c;
                    bk.X1099_Info__c						= bookset.X1099_Info__c;
                    
                    
                    updateList.add(bk);
                }
                
            }
            
        }
        
        update updateList;
        
    }
}