objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abraham Carrillo</fullName>
                </value>
                <value>
                    <fullName>Alishia Greene-Jenkins</fullName>
                </value>
                <value>
                    <fullName>Antoinette Reid</fullName>
                </value>
                <value>
                    <fullName>Ashley Cloutier</fullName>
                </value>
                <value>
                    <fullName>Austin Stephens</fullName>
                </value>
                <value>
                    <fullName>Becky Arnold</fullName>
                </value>
                <value>
                    <fullName>Blanca Lemus</fullName>
                </value>
                <value>
                    <fullName>Brenda Guzman</fullName>
                </value>
                <value>
                    <fullName>Brenda Navarrette</fullName>
                </value>
                <value>
                    <fullName>Christina Chavez</fullName>
                </value>
                <value>
                    <fullName>Cindy Mejorado</fullName>
                </value>
                <value>
                    <fullName>Crystal Moyer</fullName>
                </value>
                <value>
                    <fullName>Danny On</fullName>
                </value>
                <value>
                    <fullName>Dawn Popa</fullName>
                </value>
                <value>
                    <fullName>Imelda Hilario</fullName>
                </value>
                <value>
                    <fullName>Jacquie Wallace-Small</fullName>
                </value>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Jennifer Soikowski</fullName>
                </value>
                <value>
                    <fullName>Jessica Turner</fullName>
                </value>
                <value>
                    <fullName>Jonathan Salyer</fullName>
                </value>
                <value>
                    <fullName>Kayla Fleming</fullName>
                </value>
                <value>
                    <fullName>Keanu Rhodes</fullName>
                </value>
                <value>
                    <fullName>Kenneth Harrah</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Kimberly Smiley</fullName>
                </value>
                <value>
                    <fullName>Kingstone Mashingaidze</fullName>
                </value>
                <value>
                    <fullName>Lanzi Reel</fullName>
                </value>
                <value>
                    <fullName>Mandrell Hahn</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Melissa McBride</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <recordTypes>
        <fullName>Annual</fullName>
        <active>true</active>
        <description>Used for annual records</description>
        <label>Annual</label>
    </recordTypes>
    <recordTypes>
        <fullName>As_Needed</fullName>
        <active>true</active>
        <label>As Needed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Role_Automation_Setting__mdt.object
<CustomObject>
    <description>This Setting will be used to assign licenses based on the job role field in the user profile.</description>
    <fields>
        <fullName>Global_ValueSet_ID__c</fullName>
        <label>Global ValueSet ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_ValueSet_Name__c</fullName>
        <label>Global ValueSet Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licences__c</fullName>
        <label>Licences</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Local_Picklist_ID__c</fullName>
        <label>Local Picklist ID</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Role Automation Setting</label>
    <pluralLabel>Role Automation Settings</pluralLabel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <description>Task For Bookkeeping</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Bookkeeping_Task</fullName>
        <active>true</active>
        <description>Task for Bookkeeper</description>
        <label>Bookkeeping Task</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <description>Tax Task</description>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Job_Role__c</fullName>
        <label>Job Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Job_Roles</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Job_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accounting Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Bookkeeping</fullName>
    </customValue>
    <customValue>
        <fullName>Estate Planning</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>QA</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal Advisor - BCP</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Tax</fullName>
    </customValue>
    <customValue>
        <fullName>External User</fullName>
    </customValue>
    <masterLabel>Job Roles</masterLabel>
</GlobalValueSet>

classes/RoleAutomationService.cls
/*****************************************************************************************************************************
@ Class Name:    RoleAutomationService
@ Version:       1.0
@ Author:        Sadia Asif
@ Description:   This service is used to assign license based on the job role field in the user profile.    
*****************************************************************************************************************************/
public class RoleAutomationService implements Queueable, Database.AllowsCallouts {
    
    private static final string GET= 'GET';
    private static final string PATCH = 'PATCH';
    private static final string label='Bookkeeping';
    public static Id taxRecord = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Tax').getRecordTypeId(); 
    public static Id bookkeepingRec = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Bookkeeping').getRecordTypeId();
    public static Id bookTaskRec = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Bookkeeping_Task').getRecordTypeId();
    public static Id annualRec = Schema.SObjectType.Bookkeeping__c.getRecordTypeInfosByDeveloperName().get('Annual').getRecordTypeId();
    public static Id asNeededRec = Schema.SObjectType.Bookkeeping__c.getRecordTypeInfosByDeveloperName().get('As_Needed').getRecordTypeId();
    private static string BASEURL = URL.getSalesforceBaseUrl().toExternalForm()+ '/services/data/v48.0/tooling/';
    public static Role_Automation_Setting__mdt record = Role_Automation_Setting__mdt.getInstance(label);
    public static string globalPicklistVal = record.Global_ValueSet_ID__c;
    public static string localPicklistVal= record.Local_Picklist_ID__c;
    public static string license= record.Licences__c;
    public static string globalValSetName= record.Global_ValueSet_Name__c;
    public static string localPicklistName= record.Global_ValueSet_Name__c;
    public Set<Id> setofUser = new Set<Id>();
   
    Boolean deactivate = false;
    public RoleAutomationService (Set<Id> usersId,Boolean deactivate){
        setofUser= usersId;
        this.deactivate=deactivate;
        System.debug('@@+Id'+setofUser);
        
    }
    public void execute(QueueableContext context){
        try{
            List<UserPackageLicense> listofUserLicense = new List<UserPackageLicense>();
            List<PackageLicense> lstPackageLicense  = [SELECT Id, NamespacePrefix, AllowedLicenses, UsedLicenses, CreatedDate, ExpirationDate, Status 
                                                       FROM PackageLicense WHERE NamespacePrefix =: license LIMIT 1];
            for (User usr : [Select Id, Name,Job_Role__c FROM User Where Id =: setofUser LIMIT 1]){ 
                getGlobalPicklistValues(usr.Name,deactivate);
                getcustomPicklistValues(usr.Name,deactivate);
                if(!deactivate){
                    System.enqueueJob(new RoleAutomationRecordType()); 
                    setPermissionSet(setofUser);
                }
            }
        } Catch(Exception ex){
            System.debug('ERROR:' + ex.getmessage());
        }
    }

    @testVisible
    private static void setPermissionSet(Set<Id> userId){
        List<PermissionSetAssignment> permissionSetList = new List<PermissionSetAssignment>();
        List<String> PermissionSetIds = new List<String> { '0PS6f000000Y5qr', '0PS6f0000001MRX', '0PS0B0000005T5a'};
        for(Id userIdFromSet : userId){
            for (String permissionSetId : PermissionSetIds){
            PermissionSetAssignment psa = new PermissionSetAssignment (PermissionSetId = permissionSetId,AssigneeId = userIdFromSet);
            permissionSetList.add(psa);
            }
        }
try{
    upsert permissionSetList;
}catch(exception e){
    system.debug('exception caught' + e);
}
    }

    public static void getGlobalPicklistValues(String username, Boolean deactivate) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/GlobalValueSet/'+globalPicklistVal,'GET');
        
        HttpResponse res = Callout.buildHttpResponse(req);
        
        /*Data mapping for insert string creation  */
        Map<String, Object> resultData = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
        Map<String, Object> Metadata =  (Map<String, Object>)resultData.get('Metadata');
        List<PicklistValueWrapper> customValue = (List<PicklistValueWrapper>) JSON.deserialize(JSON.serialize(Metadata.get('customValue')),List<PicklistValueWrapper>.class);

        System.debug('@@ res.getBody()'+ res.getBody());
        String dataString = valueCompilation(customValue, true, username, deactivate);
        
        String fieldDef = '{"Metadata":{"customValue":'+dataString+',"description":null,"masterLabel":"Bookkeeping Admin","sorted":true,"urls":null},"FullName":"Bookkeeping_Admin"}';
        system.debug('@@fieldDef '+ fieldDef);
        globalPicklistSet(fieldDef);
        
    }
    public static void globalPicklistSet(String fieldDef) {           
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/GlobalValueSet/'+globalPicklistVal+'?_HttpMethod=PATCH','PATCH');
        req.setBody(fieldDef);
        HttpResponse res = Callout.buildHttpResponse(req);
        
    }   
    public static void getcustomPicklistValues(String username,Boolean deactivate) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/CustomField/'+localPicklistVal,'GET');
        
        HttpResponse res = Callout.buildHttpResponse(req);
        
        Map<String, Object> resultData = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
        Map<String, Object> Metadata =  (Map<String, Object>)resultData.get('Metadata');
        Map<String, Object> valueSet =  (Map<String, Object>)Metadata.get('valueSet');
        Map<String, Object> valueSetDefinition =  (Map<String, Object>)valueSet.get('valueSetDefinition');
        List<PicklistValueWrapper> value = (List<PicklistValueWrapper>) JSON.deserialize(JSON.serialize(valueSetDefinition.get('value')),List<PicklistValueWrapper>.class);
        String dataString = valueCompilation(value, true, username,deactivate);
        String fieldDef = '{"Metadata":{"label":"Bookkeeper","required":false,"type":"Picklist","valueSet":{"valueSetDefinition":{"sorted":true,"value":'+dataString+'}}},"FullName":"Bookkeeping__c.Bookkeeper__c"}';
        System.debug('fieldDef for custom '+fieldDef);
        customPicklistValuesSet(fieldDef);
        
    }
    public static void customPicklistValuesSet(String fieldDef) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/CustomField/'+localPicklistVal+'?_HttpMethod=PATCH','PATCH');
        req.setBody(fieldDef);
        HttpResponse res = Callout.buildHttpResponse(req);
        
    }  
    public static String valueCompilation(List<PicklistValueWrapper> values, Boolean customPicklist, String username, Boolean deactivate) {
        String dataString = '';
        List<PicklistValueWrapper> newValues = new List<PicklistValueWrapper>();
        Boolean userNameAlreadyExists = false;
        System.debug('@@+Deactivate'+deactivate);
        //if(!deactivate)
        if(!deactivate){
            for(PicklistValueWrapper val:values){
                if(val.isActive == null || (!val.isActive && val.valueName == username)){
                    val.isActive = true;
                    if(val.valueName == username){
                        userNameAlreadyExists=true;
                    }
                }
                newValues.add(val); 
            }
            if(!userNameAlreadyExists){
                //add a new picklist value in newValues
                PicklistValueWrapper npv = new PicklistValueWrapper();
                npv.isActive=true;
                npv.label=username;
                npv.valueName=username;
                newValues.add(npv);
            }
        }
       else{
         
            for(PicklistValueWrapper val:values){
                if(val.isActive == null){
                    val.isActive = true;
                }
                if(val.valueName == username){
                    val.isActive = false;
                   
                }
                newValues.add(val); 
            }
        }
        return JSON.serialize(newValues);
    }
   
}