objects/Bookkeeping__c.object
<CustomObject>
    <fields>
        <fullName>Bookkeeper__c</fullName>
        <label>Bookkeeper</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abraham Carrillo</fullName>
                </value>
                <value>
                    <fullName>Alishia Greene-Jenkins</fullName>
                </value>
                <value>
                    <fullName>Antoinette Reid</fullName>
                </value>
                <value>
                    <fullName>Ashley Cloutier</fullName>
                </value>
                <value>
                    <fullName>Austin Stephens</fullName>
                </value>
                <value>
                    <fullName>Becky Arnold</fullName>
                </value>
                <value>
                    <fullName>Blanca Lemus</fullName>
                </value>
                <value>
                    <fullName>Brenda Guzman</fullName>
                </value>
                <value>
                    <fullName>Brenda Navarrette</fullName>
                </value>
                <value>
                    <fullName>Christina Chavez</fullName>
                </value>
                <value>
                    <fullName>Cindy Mejorado</fullName>
                </value>
                <value>
                    <fullName>Crystal Moyer</fullName>
                </value>
                <value>
                    <fullName>Danny On</fullName>
                </value>
                <value>
                    <fullName>Dawn Popa</fullName>
                </value>
                <value>
                    <fullName>Imelda Hilario</fullName>
                </value>
                <value>
                    <fullName>Jacquie Wallace-Small</fullName>
                </value>
                <value>
                    <fullName>Jasmine Licitra</fullName>
                </value>
                <value>
                    <fullName>Jennifer Soikowski</fullName>
                </value>
                <value>
                    <fullName>Jessica Turner</fullName>
                </value>
                <value>
                    <fullName>Jonathan Salyer</fullName>
                </value>
                <value>
                    <fullName>Kayla Fleming</fullName>
                </value>
                <value>
                    <fullName>Keanu Rhodes</fullName>
                </value>
                <value>
                    <fullName>Kenneth Harrah</fullName>
                </value>
                <value>
                    <fullName>Kiera Dunphy</fullName>
                </value>
                <value>
                    <fullName>Kimberly Smiley</fullName>
                </value>
                <value>
                    <fullName>Kingstone Mashingaidze</fullName>
                </value>
                <value>
                    <fullName>Lanzi Reel</fullName>
                </value>
                <value>
                    <fullName>Mandrell Hahn</fullName>
                </value>
                <value>
                    <fullName>Maria Boone</fullName>
                </value>
                <value>
                    <fullName>Melissa McBride</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bookkeeping Record</label>
    <nameField>
        <label>Bookkeeping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookkeeping Records</pluralLabel>
    <recordTypes>
        <fullName>As_Needed</fullName>
        <active>true</active>
        <label>As Needed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Bookkeeping_Monthly_Recurring</fullName>
        <active>true</active>
        <label>Bookkeeping Monthly Recurring</label>
    </recordTypes>
    <recordTypes>
        <fullName>Cleanup</fullName>
        <active>true</active>
        <description>Used for cleanup records.</description>
        <label>Cleanup</label>
    </recordTypes>
    <recordTypes>
        <fullName>Inactive</fullName>
        <active>true</active>
        <description>Used to indicate if a record is inactive.</description>
        <label>Inactive</label>
    </recordTypes>
    <recordTypes>
        <fullName>Monthly</fullName>
        <active>true</active>
        <description>Used for monthly records.</description>
        <label>Monthly</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quarterly</fullName>
        <active>true</active>
        <description>Used for quarterly records.</description>
        <label>Quarterly</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rollover</fullName>
        <active>true</active>
        <label>Rollover</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Role_Automation_Setting__mdt.object
<CustomObject>
    <description>This Setting will be used to assign licenses based on the job role field in the user profile.</description>
    <fields>
        <fullName>Global_ValueSet_ID__c</fullName>
        <label>Global ValueSet ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_ValueSet_Name__c</fullName>
        <label>Global ValueSet Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licences__c</fullName>
        <label>Licences</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Local_Picklist_ID__c</fullName>
        <label>Local Picklist ID</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Role Automation Setting</label>
    <pluralLabel>Role Automation Settings</pluralLabel>
</CustomObject>

classes/RoleAutomationBookRecType.cls
/*****************************************************************************************************************************
@ Class Name:    RoleAutomationBookRecType
@ Version:       1.0
@ Author:        Sadia Asif
@ Description:   This service is used to assign license based on the job role field in the user profile.    
*****************************************************************************************************************************/
public class RoleAutomationBookRecType implements Queueable, Database.AllowsCallouts {
    
    private static final string GET= 'GET';
    private static final string PATCH = 'PATCH';
    private static final string label='Bookkeeping';
    public static Id bookMonthlyRec = Schema.SObjectType.Bookkeeping__c.getRecordTypeInfosByDeveloperName().get('Bookkeeping_Monthly_Recurring').getRecordTypeId();
    public static Id cleanupRec = Schema.SObjectType.Bookkeeping__c.getRecordTypeInfosByDeveloperName().get('Cleanup').getRecordTypeId();
    public static Id asNeededRec = Schema.SObjectType.Bookkeeping__c.getRecordTypeInfosByDeveloperName().get('As_Needed').getRecordTypeId();
    public static Id InactiveRec = Schema.SObjectType.Bookkeeping__c.getRecordTypeInfosByDeveloperName().get('Inactive').getRecordTypeId();
    public static Id monthlyRec = Schema.SObjectType.Bookkeeping__c.getRecordTypeInfosByDeveloperName().get('Monthly').getRecordTypeId();
    public static Id quarterlyRec = Schema.SObjectType.Bookkeeping__c.getRecordTypeInfosByDeveloperName().get('Quarterly').getRecordTypeId();
    public static Id rolloverRec = Schema.SObjectType.Bookkeeping__c.getRecordTypeInfosByDeveloperName().get('Rollover').getRecordTypeId();
    private static string BASEURL = URL.getSalesforceBaseUrl().toExternalForm()+ '/services/data/v48.0/tooling/';
    public static Role_Automation_Setting__mdt record = Role_Automation_Setting__mdt.getInstance(label);
    public static string globalPicklistVal = record.Global_ValueSet_ID__c;
    public static string localPicklistVal= record.Local_Picklist_ID__c;
    public static string license= record.Licences__c;
    public static string globalValSetName= record.Global_ValueSet_Name__c;
    public static string localPicklistName= record.Global_ValueSet_Name__c;
    public static List<Role_Automation_Setting__mdt> rec= Role_Automation_Setting__mdt.getall().values();
    public static Set<Id> setofUser = new Set<Id>();
    
    
    public void execute(QueueableContext qc){
        try{
            
            getAsNeededRecTypeVal();
            getbookMonthlyRecTypeVal();
            getCleanUpRecTypeVal();
            getInactiveRecTypeVal();
            getmonthlyRecTypeVal();
            getquarterlyRecTypeVal();
            getRolloverRecTypeVal() ;     
            
        } Catch(Exception ex){
            System.debug('ERROR:' + ex.getmessage());
        }
    }
    
     public static void getAsNeededRecTypeVal() {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/CustomField/00N0B000006Ivqm','GET');
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response1: ' + res.getBody());
        
        
        Map<String, Object> resultData = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
        Map<String, Object> Metadata =  (Map<String, Object>)resultData.get('Metadata');
        Map<String, Object> valueSet =  (Map<String, Object>)Metadata.get('valueSet');
        Map<String, Object> valueSetDefinition =  (Map<String, Object>)valueSet.get('valueSetDefinition');
        List<Object> value =  (List<Object>)valueSetDefinition.get('value');
        
        String dataString = valueCompilationforRecType(value, false);
        
        String fieldDef = '{"Metadata":{"active":true,"label":"As Needed","fullName":"Bookkeeping__c.As_Needed","picklistValues":[{"picklist":"Bookkeeper__c","values":'+dataString+'}],"urls":null}}';
        System.debug('dataString: '+dataString);
        AsNeededRecTypeValSet (fieldDef);
        
    }
    public static void AsNeededRecTypeValSet(String fieldDef) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/RecordType/'+asNeededRec+'','PATCH');
        req.setBody(fieldDef);
        
        HttpResponse res = Callout.buildHttpResponse(req);
        
    }   
    public static void getbookMonthlyRecTypeVal() {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/CustomField/00N0B000006Ivqm','GET');
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response1: ' + res.getBody());
        
        Map<String, Object> resultData = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
        Map<String, Object> Metadata =  (Map<String, Object>)resultData.get('Metadata');
        Map<String, Object> valueSet =  (Map<String, Object>)Metadata.get('valueSet');
        Map<String, Object> valueSetDefinition =  (Map<String, Object>)valueSet.get('valueSetDefinition');
        List<Object> value =  (List<Object>)valueSetDefinition.get('value');
        
        String dataString = valueCompilationforRecType(value, false);
        
        String fieldDef = '{"Metadata":{"active":true,"label":"Bookkeeping Monthly Recurring","fullName":"Bookkeeping__c.Bookkeeping_Monthly_Recurring","picklistValues":[{"picklist":"Bookkeeper__c","values":'+dataString+'}],"urls":null}}';
        
        bookMonthlyRecTypeValSet (fieldDef);
        
    }
    public static void bookMonthlyRecTypeValSet(String fieldDef) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/RecordType/'+bookMonthlyRec+'','PATCH');
        req.setBody(fieldDef);
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response: ' + res.getBody());
        
        
    }
    public static void getCleanUpRecTypeVal() {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/CustomField/00N0B000006Ivqm','GET');
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response1: ' + res.getBody());
        
        Map<String, Object> resultData = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
        Map<String, Object> Metadata =  (Map<String, Object>)resultData.get('Metadata');
        Map<String, Object> valueSet =  (Map<String, Object>)Metadata.get('valueSet');
        Map<String, Object> valueSetDefinition =  (Map<String, Object>)valueSet.get('valueSetDefinition');
        List<Object> value =  (List<Object>)valueSetDefinition.get('value');
        
        String dataString = valueCompilationforRecType(value, false);
        
        String fieldDef = '{"Metadata":{"active":true,"label":"Cleanup","fullName":"Bookkeeping__c.Cleanup","picklistValues":[{"picklist":"Bookkeeper__c","values":'+dataString+'}],"urls":null}}';
        System.debug('dataString: '+dataString);
        cleanupRecTypeValSet (fieldDef);
        
    }
    public static void cleanupRecTypeValSet(String fieldDef) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/RecordType/'+cleanupRec+'','PATCH');
        req.setBody(fieldDef);
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response: ' + res.getBody());
        
        
    }
    public static void getInactiveRecTypeVal() {       
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/CustomField/00N0B000006Ivqm','GET');
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response1: ' + res.getBody());
        
        Map<String, Object> resultData = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
        Map<String, Object> Metadata =  (Map<String, Object>)resultData.get('Metadata');
        Map<String, Object> valueSet =  (Map<String, Object>)Metadata.get('valueSet');
        Map<String, Object> valueSetDefinition =  (Map<String, Object>)valueSet.get('valueSetDefinition');
        List<Object> value =  (List<Object>)valueSetDefinition.get('value');
        
        String dataString = valueCompilationforRecType(value, false);
        
        String fieldDef = '{"Metadata":{"active":true,"label":"Inactive","fullName":"Bookkeeping__c.Inactive","picklistValues":[{"picklist":"Bookkeeper__c","values":'+dataString+'}],"urls":null}}';
        
        InactiveRecTypeValSet(fieldDef);
        
    }
    public static void InactiveRecTypeValSet(String fieldDef) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/RecordType/'+InactiveRec+'','PATCH');
        req.setBody(fieldDef);
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response: ' + res.getBody());
        
        
    }
    public static void getmonthlyRecTypeVal() {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/CustomField/00N0B000006Ivqm','GET');
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response1: ' + res.getBody());
        
        Map<String, Object> resultData = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
        Map<String, Object> Metadata =  (Map<String, Object>)resultData.get('Metadata');
        Map<String, Object> valueSet =  (Map<String, Object>)Metadata.get('valueSet');
        Map<String, Object> valueSetDefinition =  (Map<String, Object>)valueSet.get('valueSetDefinition');
        List<Object> value =  (List<Object>)valueSetDefinition.get('value');
        
        String dataString = valueCompilationforRecType(value, false);
        
        String fieldDef = '{"Metadata":{"active":true,"label":"Monthly","fullName":"Bookkeeping__c.Monthly","picklistValues":[{"picklist":"Bookkeeper__c","values":'+dataString+'}],"urls":null}}';
        
        monthlyRecTypeValuesSet (fieldDef);
        
    }
    public static void monthlyRecTypeValuesSet(String fieldDef) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/RecordType/'+monthlyRec+'','PATCH');
        req.setBody(fieldDef);
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response: ' + res.getBody());
        
        
    }
    public static void getquarterlyRecTypeVal() {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/CustomField/00N0B000006Ivqm','GET');
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response1: ' + res.getBody());
        
        Map<String, Object> resultData = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
        Map<String, Object> Metadata =  (Map<String, Object>)resultData.get('Metadata');
        Map<String, Object> valueSet =  (Map<String, Object>)Metadata.get('valueSet');
        Map<String, Object> valueSetDefinition =  (Map<String, Object>)valueSet.get('valueSetDefinition');
        List<Object> value =  (List<Object>)valueSetDefinition.get('value');
        
        String dataString = valueCompilationforRecType(value, false);
        
        String fieldDef = '{"Metadata":{"active":true,"label":"Quarterly","fullName":"Bookkeeping__c.Quarterly","picklistValues":[{"picklist":"Bookkeeper__c","values":'+dataString+'}],"urls":null}}';
        quarterlyRecTypeValSet(fieldDef);
        
    }
    public static void quarterlyRecTypeValSet(String fieldDef) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/RecordType/'+quarterlyRec+'','PATCH');
        req.setBody(fieldDef);
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response: ' + res.getBody());    
    }
    public static void getRolloverRecTypeVal() {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/CustomField/00N0B000006Ivqm','GET');
        
        HttpResponse res = Callout.buildHttpResponse(req);
        System.Debug('**** ApexClass Response1: ' + res.getBody());
        
        
        Map<String, Object> resultData = (Map<String, Object>)JSON.deserializeUntyped( res.getBody() );
        Map<String, Object> Metadata =  (Map<String, Object>)resultData.get('Metadata');
        Map<String, Object> valueSet =  (Map<String, Object>)Metadata.get('valueSet');
        Map<String, Object> valueSetDefinition =  (Map<String, Object>)valueSet.get('valueSetDefinition');
        List<Object> value =  (List<Object>)valueSetDefinition.get('value');
        
        String dataString = valueCompilationforRecType(value, false);
        
        String fieldDef = '{"Metadata":{"active":true,"label":"Rollover","fullName":"Bookkeeping__c.Rollover","picklistValues":[{"picklist":"Bookkeeper__c","values":'+dataString+'}],"urls":null}}';
        rolloverRecTypeValSet (fieldDef);
        
    }
    public static void rolloverRecTypeValSet(String fieldDef) {
        
        HttpRequest req = Callout.buildHttpRequest(BASEURL+'sobjects/RecordType/'+rolloverRec+'','PATCH');
        req.setBody(fieldDef);
        
        HttpResponse res = Callout.buildHttpResponse(req);    
    }
    
    public static String valueCompilationforRecType(List<Object> value, Boolean customPicklist) {
        String dataString = '[';
        integer i = 0;
        List<String> vals = new List<String>();
        String localString;
        
        for( Object m : value ) {
            
            vals.clear();
            String strLis = String.valueOf(m);
            for( String st : strLis.split(',') ){
                
                List<String> innerVal = st.split('=');
                vals.add(innerVal[1].replace('}',''));
            }
            localString = '';
            if(vals.get(3) != 'false'){
                
                localString += '{';
                localString += ( vals.get(0) != 'null' ) ? '"color":"'+vals.get(0)+'",' : '"color":null,';  
                localString += ( vals.get(1) == 'false' || vals.get(1) == 'true' ) ? '"default":'+vals.get(1)+',' : '"default":false,';  
                localString += ( vals.get(2) != 'null' ) ? '"description":"'+vals.get(2)+'",' : '"description":null,'; 
                localString += ( vals.get(3) == 'true' ) ? '"isActive":'+vals.get(3)+',' : '"isActive":true,'; 
                localString += ( vals.get(5) != 'null' ) ? '"urls":"'+vals.get(5)+'",' : '"urls":null,';
                localString += '"valueName":"'+vals.get(6)+'"';
                localString += '},';    
            }
            if( localString != '' )
            {
                dataString += localString;   
            }                
        }
        
        dataString = dataString.Substring(0, dataString.length()-1);
        
        dataString += ']';
        
        return dataString;
    }
    
    
}