objects/Box_Listener__c.object
<CustomObject>
    <fields>
        <fullName>Base_Folder_Name__c</fullName>
        <label>Base Folder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Created_By_Email_Address__c</fullName>
        <label>File Created By Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>File_Created_By__c</fullName>
        <label>File Created By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Id__c</fullName>
        <label>File Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Modified_Date_and_time__c</fullName>
        <label>File Modified Date and time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_created_Date_and_Time__c</fullName>
        <label>File created Date and Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Name__c</fullName>
        <label>Folder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_User_Email__c</fullName>
        <label>Login User Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Login_User_name__c</fullName>
        <label>Login User name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Folder_ID__c</fullName>
        <label>Parent Folder ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uploaded_File_Name__c</fullName>
        <label>Uploaded File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Listener</label>
    <nameField>
        <displayFormat>BLA-{0}</displayFormat>
        <label>Box Listener Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Box Listeners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BoxUploadBatchClasscall.cls
global class BoxUploadBatchClasscall implements Schedulable {
    global void execute(SchedulableContext sc) {
     
        string taskQuery='';
        if(!Test.isRunningTest()){
            taskQuery='select id, File_Id__c, Uploaded_File_Name__c, File_Created_Date_and_time__c, File_Modified_Date_and_time__c,Base_Folder_Name__c,File_Created_By__c,File_Created_By_Email_Address__c,Folder_Name__c,Parent_Folder_ID__c,Login_User_name__c,Login_User_Email__c from Box_Listener__c where CreatedDate=Today and Processed__c=false '; 
        }else{
            taskQuery='select id, File_Id__c, Uploaded_File_Name__c, File_Created_Date_and_time__c, File_Modified_Date_and_time__c,Base_Folder_Name__c,File_Created_By__c,File_Created_By_Email_Address__c,Folder_Name__c,Parent_Folder_ID__c,Login_User_name__c,Login_User_Email__c from Box_Listener__c where CreatedDate=Today and Processed__c=false limit 1';
        }
        
         
         Id batchJobId1;
          if(!Test.isRunningTest()){
          batchJobId1 = Database.executeBatch(new BoxUploadBatchClasscallCreatecase(taskQuery), 5);
         }else{
             batchJobId1 = Database.executeBatch(new BoxUploadBatchClasscallCreatecase(taskQuery), 200);
         }
      
    }
}