objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <description>Total number of workshop attendees</description>
        <label>Number of Attendees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Primary_Campaign_Dummy__c</fullName>
        <label>Primary Campaign Dummy</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pi__utm_campaign__c</fullName>
        <label>Google Analytics Campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestcopyCampaign.cls
@isTest
private class TestcopyCampaign
{
	@isTest
	static void itShould()
	{

                  Campaign cam=new Campaign();
                  cam.Name='test cam';
                  cam.Number_of_Attendees__c=10;
                   insert cam;

                  Lead ld = new Lead();
                  ld.FirstName = 'testFirstName';
                  ld.LastName = 'testLastName';
                  ld.Primary_Campaign_Dummy__c='test cam';
                  ld.pi__utm_campaign__c='test cam';
                  insert ld;
                  update ld;

	}
}