objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ClientReferralCampaign</relationshipLabel>
        <relationshipName>ClientReferralCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities (Account)</relationshipLabel>
        <relationshipName>Entities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dissolution_Date__c</fullName>
        <label>Dissolution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organizational_Date__c</fullName>
        <label>Organizational Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DeleteCampBatchActiveNonprofitClients.cls
/* 
* Author: Muhammad Awais Khan
* Date: 11/Feb/22
* Purpose: Delete Members from "Active Nonprofit Clients" Campaign based on criteria specified in the report "Active Non Profit Entities" 
*/
global class DeleteCampBatchActiveNonprofitClients implements Database.Batchable<sObject>, Database.Stateful, System.Schedulable {
    private String query;
    private Campaign cmpT;
    public Set<CampaignMember> deleteMembers;
    public List<Entities__c> allEntities;

    global DeleteCampBatchActiveNonprofitClients() {
        this.cmpT = ( [Select Id, Name From Campaign Where Name = 'Active Nonprofit Clients' AND IsActive = true Limit 1].size() > 0 ) ?
        [Select Id From Campaign Where Name = 'Active Nonprofit Clients' AND IsActive = true Limit 1] : 
        null;
        this.query = 'Select Id, Name, Account__c From CampaignMember Where CampaignId = \'' + cmpT.Id+'\'';
        deleteMembers = new Set<CampaignMember>(); 
    }

    global DeleteCampBatchActiveNonprofitClients(String query) {
        this.query = query;
        deleteMembers = new Set<CampaignMember>(); 
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        this.allEntities = [ SELECT Primary_Client__c FROM Entities__c WHERE Organizational_Date__c != null AND Organization_State__c != null AND Dissolution_Date__c = null AND RecordType.name ='Non-Profit Entity' AND Status__c !='Inactive' AND Status__c !='Terminated' AND Status__c !='Future Planned' AND Status__c !='Missing Information' AND Status__c !='Expedited' AND Status__c !='Sent To Processing' ];
        return Database.getQueryLocator( this.query );
    }
    
    global void execute(Database.BatchableContext BC, List<CampaignMember> mainList){
        Map<Id, Entities__c> allEntitiesMap = new Map<Id, Entities__c>();
        for( Entities__c  ents : this.allEntities ) {
            allEntitiesMap.put( ents.Primary_Client__c, ents ); 
        }

        if( mainList.size() > 0 ) {
            for( CampaignMember allExistingMembersList : mainList ) {
                /**
                 * If condition is not met for any of current query, delete this record
                 */
                if( !( allEntitiesMap.containsKey( allExistingMembersList.Account__c ) ) ) {
                    deleteMembers.add( allExistingMembersList );
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC){
        System.debug('deleteMembers size: ' + deleteMembers.size() );
        if( deleteMembers.size() > 0 ) {
            List<CampaignMember> deleteMembersList = new List<CampaignMember>(deleteMembers); 
            delete deleteMembersList;
        }

        List<CronTrigger> ct = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name = 'DeleteCampBatchActiveNonprofitClients One Time'];
        if( ct.size() > 0 ) {
            System.abortJob(ct.get(0).Id);
        }
    }

    global void execute(SchedulableContext SC) {
        database.executebatch(new DeleteCampBatchActiveNonprofitClients(),200);
    }
}