objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <description>Total number of workshop attendees</description>
        <label>Number of Attendees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>evt__Attendee__c</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/evt__Attendee__c.object
<CustomObject>
    <customHelpPage>evt__EventManagementHelp</customHelpPage>
    <description>Event attendees</description>
    <fields>
        <fullName>evt__Event__c</fullName>
        <label>Event</label>
        <referenceTo>evt__Special_Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>evt__Invitation_Status__c</fullName>
        <label>Invitation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Payment Pending</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Wait Listed</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>No-Show</fullName>
                </value>
                <value>
                    <fullName>Hard Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>evt__Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Attendee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/evt__Special_Event__c.object
<CustomObject>
    <customHelpPage>evt__EventManagementHelp</customHelpPage>
    <description>Primary event management object for Linvio Events.</description>
    <label>Special Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testCampaignMember.cls
@isTest
private class testCampaignMember
{
   @isTest
   static void itShould()
   {

      evt__Special_Event__c evnt=new evt__Special_Event__c();
      evnt.Name='test event';
      insert evnt;
      evt__Attendee__c attende=new evt__Attendee__c();
      attende.evt__Event__c=evnt.id;
      attende.evt__Invitation_Status__c='Cancelled';
      attende.evt__Is_Primary__c=true;
      insert attende;
      update attende;

      Campaign cam=new Campaign();
      cam.Name='test campaign';
      cam.Number_of_Attendees__c=10;
      insert cam;

      Contact con=new Contact(FirstName='first test name',LastName='last test name',Email='test@yahoo.com');
      insert con;

      CampaignMember camMember=new CampaignMember();
      camMember.campaignid  =cam.id;
      camMember.Attendee__c=attende.id;
      camMember.ContactId =con.id;
      camMember.status='Cancelled';
      insert camMember;
      camMember.Status='Attended';
      update camMember;

      attende.evt__Invitation_Status__c='Attended';
      update attende;
   }
}