objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Total_Collected__c</fullName>
        <inlineHelpText>Net transactions, net of fees, for this child campaign.</inlineHelpText>
        <label>Total Collected</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Collected_for_Hierarchy__c</fullName>
        <inlineHelpText>Net transactions, net of fees, for all campaigns in the hierarchy.</inlineHelpText>
        <label>Total Collected for Hierarchy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Net_Transactions_net_of_Fees__c</fullName>
        <description>If &apos;Net Transactions&apos; - &apos;Total Filing Fees&apos; is less than or equal to zero then return $0.00, Else return &apos;Net Transactions&apos; - &apos;Total Filing Fees&apos;.  This will prevent returning a negative value for this field.</description>
        <formula>IF(Net_Transactions__c - Total_Filing_Fees__c &lt;= 0, 0, Net_Transactions__c - Total_Filing_Fees__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If &apos;Net Transactions&apos; - &apos;Total Filing Fees&apos; is less than or equal to zero then return $0.00, Else return &apos;Net Transactions&apos; - &apos;Total Filing Fees&apos;.  This will prevent returning a negative value for this field.</inlineHelpText>
        <label>Net Transactions (net of fees)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sale_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CampaignBatch.cls
global class CampaignBatch implements Database.Batchable<sObject>, Database.Stateful {
    global Integer recordsProcessed = 0;
    global database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('Start called');
        return Database.getQueryLocator('select id,name,Total_Collected_for_Hierarchy__c,Total_Collected__c from Campaign where IsActive=True');
    }
    global void execute(Database.BatchableContext bc,List<Campaign> scope){
        system.debug('Entered in Execute');
        List <Campaign> campaigns = new List<Campaign>();
        List <opportunity> oppList = New List <opportunity>();
        List<Campaign> lstAcc = new List<Campaign>();
        List<Campaign> lstcampToupdate = new List<Campaign>();
        Boolean updateTotalColected=false;
        set<id> camids=new set<id>();
        for(Campaign cam : scope)
        {
            system.debug('cam id=='+cam.id);
            camids.add(cam.id);
        }
        if(camids.size() > 0){
            lstAcc = [Select id,Total_Collected__c,(Select id,Net_Transactions_net_of_Fees__c,Amount  from opportunities where amount != 0 AND sale_campaign__c != '7014P000001BSSuQAO' AND campaignid != null) from Campaign where id IN : camids];
        }
        for(Campaign cmp : lstAcc){
            Decimal val = 0;
            for(opportunity opp : cmp.opportunities){
                
                val += opp.Net_Transactions_net_of_Fees__c;
                
            }
            if(cmp.Total_Collected__c!=val){
                  cmp.Total_Collected__c = val;
                lstcampToupdate.add(cmp);
                
            }
          
        }
      
        update lstcampToupdate;
    }
    global void finish(Database.BatchableContext BC){
        system.debug('Batch execution completed.');
        
    }
}