objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce Error</fullName>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Web Page Error</fullName>
                    <label>Website</label>
                </value>
                <value>
                    <fullName>Blueprint / LucidChart</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Reports/Dashboards/Export</fullName>
                </value>
                <value>
                    <fullName>Conga</fullName>
                </value>
                <value>
                    <fullName>8x8</fullName>
                </value>
                <value>
                    <fullName>Box</fullName>
                </value>
                <value>
                    <fullName>DocuSign</fullName>
                </value>
                <value>
                    <fullName>Google</fullName>
                </value>
                <value>
                    <fullName>Groove</fullName>
                </value>
                <value>
                    <fullName>Lenovo/Windows</fullName>
                </value>
                <value>
                    <fullName>Windows</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Onboarding/Offboarding</fullName>
                </value>
                <value>
                    <fullName>Phone Line Ticket</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                    <isActive>false</isActive>
                    <label>--None--</label>
                </value>
                <value>
                    <fullName>Blueprint Software</fullName>
                    <isActive>false</isActive>
                    <label>Blueprint Software</label>
                </value>
                <value>
                    <fullName>Field Update</fullName>
                    <isActive>false</isActive>
                    <label>Field Update</label>
                </value>
                <value>
                    <fullName>Form Request</fullName>
                    <isActive>false</isActive>
                    <label>Form Request</label>
                </value>
                <value>
                    <fullName>Lead Upload</fullName>
                    <isActive>false</isActive>
                    <label>Lead Upload</label>
                </value>
                <value>
                    <fullName>List Views</fullName>
                    <isActive>false</isActive>
                    <label>List Views</label>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                    <isActive>false</isActive>
                    <label>Maintenance</label>
                </value>
                <value>
                    <fullName>Operations Other</fullName>
                    <isActive>false</isActive>
                    <label>Operations Other</label>
                </value>
                <value>
                    <fullName>Page Layout Change</fullName>
                    <isActive>false</isActive>
                    <label>Page Layout Change</label>
                </value>
                <value>
                    <fullName>Purchase Request</fullName>
                    <isActive>false</isActive>
                    <label>Purchase Request</label>
                </value>
                <value>
                    <fullName>Salesforce Other</fullName>
                    <isActive>false</isActive>
                    <label>Salesforce Other</label>
                </value>
                <value>
                    <fullName>Technical Support</fullName>
                    <isActive>false</isActive>
                    <label>Technical Support</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_many_users_are_impacted__c</fullName>
        <label>How many users are impacted?</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_there_currently_a_workaround__c</fullName>
        <label>Is there currently a workaround?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Campaign Source</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>LeadCampaignSource</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Due_Date__c</fullName>
        <label>Requested Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Severity_Level__c</fullName>
        <label>Priority Internal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Level 1 - Critical</fullName>
                </value>
                <value>
                    <fullName>Level 2 - Urgent</fullName>
                </value>
                <value>
                    <fullName>Level 3 - High</fullName>
                </value>
                <value>
                    <fullName>Level 4 - Medium</fullName>
                </value>
                <value>
                    <fullName>Level 5 - New Idea</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Web_Error_URL_if_applicable__c</fullName>
        <label>Web Error URL (if applicable)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Events</fullName>
        <active>true</active>
        <businessProcess>Feedback</businessProcess>
        <description>Event Request Form Case</description>
        <label>Events</label>
    </recordTypes>
    <recordTypes>
        <fullName>Marketing</fullName>
        <active>true</active>
        <businessProcess>Feedback</businessProcess>
        <description>Marketing Related Cases</description>
        <label>Marketing</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <businessProcess>Tax</businessProcess>
        <description>Used for Tax Cases</description>
        <label>Tax</label>
    </recordTypes>
    <recordTypes>
        <fullName>Webinar</fullName>
        <active>true</active>
        <businessProcess>Feedback</businessProcess>
        <description>Webinar Request</description>
        <label>Webinar</label>
    </recordTypes>
    <recordTypes>
        <fullName>Website</fullName>
        <active>true</active>
        <businessProcess>Feedback</businessProcess>
        <label>Website</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Meeting</fullName>
        <active>true</active>
        <description>For general use.</description>
        <label>Meeting</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Main_Lead_Source__c</fullName>
        <description>2018 Lead Source being used</description>
        <inlineHelpText>lead source for 2018 - general category of where the client came from. For specifics look at campaign.</inlineHelpText>
        <label>Main Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Main_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Campaign_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Campaign Source</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads (Original Campaign Source)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Main_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adduco Media</fullName>
    </customValue>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson Event</fullName>
    </customValue>
    <customValue>
        <fullName>Big Dog-Love American Homes</fullName>
    </customValue>
    <customValue>
        <fullName>Calendly</fullName>
    </customValue>
    <customValue>
        <fullName>Dani Johnson</fullName>
    </customValue>
    <customValue>
        <fullName>Dave Lindahl</fullName>
    </customValue>
    <customValue>
        <fullName>Don Pendleton</fullName>
    </customValue>
    <customValue>
        <fullName>Elite Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>Gene Guarino</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Lending</fullName>
    </customValue>
    <customValue>
        <fullName>Nick Vertucci-NVREA</fullName>
    </customValue>
    <customValue>
        <fullName>Online Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Online Marketing</fullName>
        <label>Online Paid</label>
    </customValue>
    <customValue>
        <fullName>Pat James</fullName>
    </customValue>
    <customValue>
        <fullName>Real Wealth Network</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Royal Media</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
        <isActive>false</isActive>
        <label>Website</label>
    </customValue>
    <description>2018 lead sources</description>
    <masterLabel>Main Lead Source</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/HelpDeskClassTestClass.cls
@isTest
public class HelpDeskClassTestClass {
      //Events
    static testmethod void CaseinserstEventsTEstClass(){
        List <Case> Cases=New List<Case>();
        
        Case ca=new Case();
  
        Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
        //insert Cases;
        //Events
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Events'; 
        testHelpDesk.onChangeDepartment();
        testHelpDesk.getMeetingTypes();
        testHelpDesk.meetingType='Client Meeting(1:1)';
        testHelpDesk.OrganiztionName='TEst Event';
        testHelpDesk.getEventTypesList();
        testHelpDesk.eventType='In-House (Staff,Workshop,etc)';
        testHelpDesk.getVenueAddresses();
        testHelpDesk.eventVenueAddress='Event Center (Summerlin)';
        testHelpDesk.eventcontactPerson='Test Name';
        testHelpDesk.contactEmailAddress='test@test.com';
        testHelpDesk.contactPhoneNumber='123456789';
         testHelpDesk.meetingDesc='This is a test';
        testHelpDesk.getroomSetups();
        testHelpDesk.roomSetup='Classroom';
          testHelpDesk.getAvneedsList();
        testHelpDesk.aVNeeds='Laptop / Surface or Tablet';
           testHelpDesk.getFoodneedList();
        testHelpDesk.foodBeverageNeeds='Dry Snacks and Fruit';
         testHelpDesk.getstaffneedList();
        testHelpDesk.staffNeeds='Staff Attendant Only';
        testHelpDesk.getregistrationReqList();
        testHelpDesk.registrationRequirements='No registration';
         testHelpDesk.getSuppliesList();
        testHelpDesk.Supplies='Sales Flyers - Tax Package, Platinum';
        testHelpDesk.comments='Testing---';
          testHelpDesk.fileName='Unit Test Attachment';
        testHelpDesk.fileBody=Blob.valueOf('Unit Test Attachment Body');
      
        testHelpDesk.save();
        
     
        Test.stopTest();
    }
      //Marketing
        
     static testmethod void CaseinserstMarketingTEstClass(){
        List <Case> Cases=New List<Case>();
        
        Case ca=new Case();
      
        Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
        //insert Cases;
      
      
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Marketing'; 
         testHelpDesk.onChangeDepartment();
        testHelpDesk.projectName='Test Project';
        testHelpDesk.getProjectType();
      testHelpDesk.projectTypes='Print (brochures, packets, postcards)';
        
        testHelpDesk.deptPaying='Sales';
        testHelpDesk.projectDesc='Promotion Test';
        testHelpDesk.projectAudience='Clients';
        testHelpDesk.projectValue='1000';
        testHelpDesk.projectInfo='Test info';
       
          testHelpDesk.fileName='Unit Test Attachment';
        testHelpDesk.fileBody=Blob.valueOf('Unit Test Attachment Body');
      
        testHelpDesk.save();
        
        Test.stopTest();
    }
     //training
  static testmethod void CaseinsersttrainingTEstClass(){
        List <Case> Cases=New List<Case>();
        
        Case ca=new Case();
     
        Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
        //insert Cases;
	 testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Training'; 
      testHelpDesk.onChangeDepartment();
        testHelpDesk.webinarTitle='Test Project';
      testHelpDesk.webinarSpeaker='TEst Speaker';
        testHelpDesk.getwebinarAudiencelist();
      testHelpDesk.webinarAudience='General Public';
        
        testHelpDesk.getplatformTypelist();
        testHelpDesk.platformType='Webinar';
        testHelpDesk.getintendedAudiencelist();
        testHelpDesk.webinarAudience='Tax';
       
       
          testHelpDesk.fileName='Unit Test Attachment';
        testHelpDesk.fileBody=Blob.valueOf('Unit Test Attachment Body');
      
        testHelpDesk.save();
        
        Test.stopTest();
    }
    
     //Affiliate Onboarding

    
     static testmethod void CaseinserstAffiliateTEstClass(){
        List <Case> Cases=New List<Case>();
        
        Case ca=new Case();
     
        Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
        //insert Cases;
      
               
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='New Affiliate On-boarding'; 
         testHelpDesk.onChangeDepartment();
        testHelpDesk.affiliateName='Test Affiliate';
      testHelpDesk.getcitylist();
        testHelpDesk.billingAffstate='Missouri';
      testHelpDesk.getmarketingTypesList();
        
        testHelpDesk.marketingTypes='No Marketing Allow';
      
          testHelpDesk.fileName='Unit Test Attachment';
        testHelpDesk.fileBody=Blob.valueOf('Unit Test Attachment Body');
         testHelpDesk.fileName1='Unit Test Attachment1';
        testHelpDesk.fileBody1=Blob.valueOf('Unit Test Attachment Body1');
         testHelpDesk.fileName2='Unit Test Attachment1';
        testHelpDesk.fileBody2=Blob.valueOf('Unit Test Attachment Body2');
      
        testHelpDesk.save();
        
        Test.stopTest();
    }
  
     // Salesforce Support
    static testmethod void CaseinserstSalesforceTEstClass(){
        List <Case> Cases=New List<Case>();
        
        Case ca=new Case();
       
        
       
        
       
        Test.startTest();
        
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk  = new HelpDeskClass(sc);
        //insert Cases;
      
      
        
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Salesforce Support Request'; 
        testHelpDesk.onChangeDepartment();
        testHelpDesk.getcategorylist();
        testHelpDesk.categoryChoice='Field Update';
         testHelpDesk.onChangecategory();
     
     
          testHelpDesk.fileName='Unit Test Attachment';
        testHelpDesk.fileBody=Blob.valueOf('Unit Test Attachment Body');
        
        testHelpDesk.save();
        
        Test.stopTest();
    }
    
    //file upload
    
      static testmethod void CaseinserstSalesforcefileuploadcateTEstClass(){
        List <Case> Cases=New List<Case>();
        
        Case ca=new Case();
       
       
       
        
       
        Test.startTest();
        
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk  = new HelpDeskClass(sc);
        //insert Cases;
      
      
        
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Salesforce Support Request'; 
        testHelpDesk.onChangeDepartment();
        testHelpDesk.getcategorylist();
        testHelpDesk.categoryChoice='Lead Upload';
          testHelpDesk.onChangecategory();
           testHelpDesk.objcase.Severity_Level__c='Level 3 - High';
       
          testHelpDesk.objcase.Requested_Due_Date__c=system.today();
         testHelpDesk.objcase.Is_there_currently_a_workaround__c='Yes';
         testHelpDesk.objcase.How_many_users_are_impacted__c=2;
         testHelpDesk.objcase.Category__c='Field Update';
         testHelpDesk.objcase.Web_Error_URL_if_applicable__c='Test Salesforce Support';
         testHelpDesk.objcase.Subject='Test Salesforce Support';
       
     
          testHelpDesk.fileName='Unit Test Attachment';
        testHelpDesk.fileBody=Blob.valueOf('Unit Test Attachment Body');
        
        testHelpDesk.save();
        
        Test.stopTest();
    }
    
    
     static testmethod void CaseinserstSalesforcecaseownerTEstClass(){
        List <Case> Cases=New List<Case>();
        
        Case ca=new Case();
     
        Test.startTest();
        
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk  = new HelpDeskClass(sc);
     
        
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Salesforce Support Request'; 
        testHelpDesk.onChangeDepartment();
        testHelpDesk.getcategorylist();
           testHelpDesk.objcase.Severity_Level__c='Level 3 - High';
        testHelpDesk.categoryChoice='Form Request';
         testHelpDesk.onChangecategory();
        
       testHelpDesk.objcase.Requested_Due_Date__c=System.today();
          testHelpDesk.objcase.How_many_users_are_impacted__c=3;
      testHelpDesk.objcase.Is_there_currently_a_workaround__c='Yes';
         testHelpDesk.objcase.Subject='Test Salesforce Support';
         
        
        testHelpDesk.save();
        
        Test.stopTest();
    }
    
     //Blueprint Support
     static testmethod void CaseinserstBlueprintTEstClass(){
        List <Case> Cases=New List<Case>();
        
        Case ca=new Case();
       
        


        //Cases.add(ca);
        
    
        Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
        //insert Cases;
    
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Blueprint Software'; 
         testHelpDesk.onChangeDepartment();
                testHelpDesk.objcase.Severity_Level__c='Level 3 - High';
      
        testHelpDesk.objcase.Is_there_currently_a_workaround__c='Yes';
        testHelpDesk.objcase.How_many_users_are_impacted__c=3;
        testHelpDesk.objcase.Category__c='Blueprint Software';
        testHelpDesk.objcase.Web_Error_URL_if_applicable__c='Test Website Support';
        testHelpDesk.objcase.Subject='Test Website Support';
       testHelpDesk.objcase.Requested_Due_Date__c=System.today();
          testHelpDesk.fileName='Unit Test Attachment';
        testHelpDesk.fileBody=Blob.valueOf('Unit Test Attachment Body');
         testHelpDesk.fileName1='Unit Test Attachment1';
        testHelpDesk.fileBody1=Blob.valueOf('Unit Test Attachment Body1');
         testHelpDesk.fileName2='Unit Test Attachment1';
        testHelpDesk.fileBody2=Blob.valueOf('Unit Test Attachment Body2');
         
      
        testHelpDesk.save();
      
         testHelpDesk.Department='Blueprint Software'; 
            testHelpDesk.onChangeDepartment();
                testHelpDesk.objcase.Severity_Level__c=null;
      
        testHelpDesk.objcase.Is_there_currently_a_workaround__c=null;
        testHelpDesk.objcase.How_many_users_are_impacted__c=3;
        testHelpDesk.objcase.Category__c='Blueprint Software';
        testHelpDesk.objcase.Web_Error_URL_if_applicable__c='Test Website Support';
        testHelpDesk.objcase.Subject='Test Website Support';
          testHelpDesk.save();
        Test.stopTest();
    }
    
     //Website Support
       static testmethod void CaseinserstWebsiteTEstClass(){
        List <Case> Cases=New List<Case>();
          
        
        Case ca=new Case();
       ID Caseid;
        String Recordtype;
    
         Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
        //insert Cases;
      testHelpDesk.getcategoryweblist();
          
      
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Websites (Anderson, Intranet, Affiliate)'; 
           testHelpDesk.onChangeDepartment();
    	testHelpDesk.getcategorylist();
     	testHelpDesk.objcase.Severity_Level__c='Level 3 - High';
       	testHelpDesk.objcase.Is_there_currently_a_workaround__c='Yes';
         testHelpDesk.objcase.How_many_users_are_impacted__c=3;
       testHelpDesk.objcase.Requested_Due_Date__c=System.today();
        testHelpDesk.objcase.Web_Error_URL_if_applicable__c='Test Website Support';
         testHelpDesk.objcase.Subject='Test Website Support';
       testHelpDesk.categoryChoiceweb='Web Page Error'; 
          testHelpDesk.fileName='Unit Test Attachment';
        testHelpDesk.fileBody=Blob.valueOf('Unit Test Attachment Body');
        
        testHelpDesk.save();
           for(Case c:[select id,RecordTypeId from case ]){
               Caseid=c.id;
              Recordtype=c.RecordTypeId;
            Cases.add(c);
            }
         
System.assertEquals('0120B000000NAE1QAO', Recordtype, 'Not Updated!!!Please check!!!') ;
             PageReference pageRef = new PageReference('/apex/HelpdeskthankyouPage');
          
  pageRef.getParameters().put('Caseid', String.valueOf(Caseid));
  Test.setCurrentPage(pageRef);
ApexPages.StandardController sc1 = new ApexPages.StandardController(ca);
              HelpDeskClass testHelpDesk2 = new HelpDeskClass(sc1);

            testHelpDesk.getdynamiclist();
        testHelpDesk.Department=''; 
           testHelpDesk.onChangeDepartment();
          // testHelpDesk.redirecttohomepage();
        Test.stopTest();
    }
    
    static testmethod void CaseinserstLeadupload(){
        List <Case> Cases=New List<Case>();
            ID caseid;
        
        Case ca=new Case();
       
        
     Campaign cam=new campaign();
           cam.Name='Elite Legacy - February 2019 Leads';
           insert cam;
      
           
        Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
              
       
        //insert Cases;
     
      
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Salesforce Support Request'; 
           testHelpDesk.onChangeDepartment();
    testHelpDesk.getcategorylist();
       
       
         testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Salesforce Support Request'; 
           testHelpDesk.onChangeDepartment();
    testHelpDesk.getcategorylist();
         testHelpDesk.objcase.Severity_Level__c='Level 2 - Urgent';
      
       
        testHelpDesk.objcase.Description='Test';
        testHelpDesk.objcase.Main_Lead_Source__c='Affiliate';
        testHelpDesk.objcase.Original_Campaign_Source__c=cam.Id;
        testHelpDesk.objcase.Requested_Due_Date__c=System.today();
          testHelpDesk.getcategorylist();
         testHelpDesk.categoryChoice='Lead Upload'; 
                  testHelpDesk.fileName3='Test';
        testHelpDesk.fileBody3=Blob.valueOf('Test');
         
        testHelpDesk.save();
          

        Test.stopTest();
    }
    
    // Error Message
    
        static testmethod void CaseinserstErrorMessage(){
        List <Case> Cases=New List<Case>();
            ID caseid;
        
        Case ca=new Case();
       
        
    
      
           
        Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
              
         testHelpDesk.objcase.Severity_Level__c='Level 3 - High';
      
        testHelpDesk.objcase.Is_there_currently_a_workaround__c='Yes';
        testHelpDesk.objcase.How_many_users_are_impacted__c=3;
        testHelpDesk.objcase.Category__c='Platinum';
        testHelpDesk.objcase.Web_Error_URL_if_applicable__c='Test Website Support';
        testHelpDesk.objcase.Subject='Test Website Support';
        
        //insert Cases;
      testHelpDesk.getcategoryweblist();
         testHelpDesk.categoryChoiceweb='Web Page Error';  
      
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Websites (Anderson, Intranet, Affiliate)'; 
           testHelpDesk.onChangeDepartment();
    testHelpDesk.getcategorylist();
        testHelpDesk.categoryChoice='Field Update';
       
        testHelpDesk.save();
        

                   

        Test.stopTest();
    }
          static testmethod void CaseinserstErrorMessageDML(){
        List <Case> Cases=New List<Case>();
            ID caseid;
        
        Case ca=new Case();
       
        
    
      
           
        Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
              
       
        //insert Cases;
     
      
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Websites (Anderson, Intranet, Affiliate)'; 
           testHelpDesk.onChangeDepartment();
    testHelpDesk.getcategorylist();
         testHelpDesk.objcase.Severity_Level__c='Level 3 - High';
      
        testHelpDesk.objcase.Is_there_currently_a_workaround__c='Yes';
        testHelpDesk.objcase.How_many_users_are_impacted__c=3;
      
                testHelpDesk.objcase.Requested_Due_Date__c=System.today();
        testHelpDesk.objcase.Web_Error_URL_if_applicable__c='Test Website Support';
        testHelpDesk.objcase.Subject='Test Website Support';
          testHelpDesk.getcategoryweblist();
         testHelpDesk.categoryChoiceweb='Web123'; 
                 testHelpDesk.fileName='';
        testHelpDesk.fileBody=Blob.valueOf('');
         testHelpDesk.fileName1='';
        testHelpDesk.fileBody1=Blob.valueOf('');
         testHelpDesk.fileName2='';
        testHelpDesk.fileBody2=Blob.valueOf('');
        testHelpDesk.save();
       
      
          

        Test.stopTest();
    }
      static testmethod void CaseinserstErrorMessagefieldsDML(){
        List <Case> Cases=New List<Case>();
            ID caseid;
        
        Case ca=new Case();
       
        
    
      
           
        Test.startTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        HelpDeskClass testHelpDesk = new HelpDeskClass(sc);
              
       
        //insert Cases;
     
      
        testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Salesforce Support Request'; 
           testHelpDesk.onChangeDepartment();
    testHelpDesk.getcategorylist();
         testHelpDesk.objcase.Severity_Level__c=null;
      
        testHelpDesk.objcase.Is_there_currently_a_workaround__c=null;
        testHelpDesk.objcase.How_many_users_are_impacted__c=3;
        testHelpDesk.objcase.Category__c='Platinum';
        testHelpDesk.objcase.Web_Error_URL_if_applicable__c='Test salesforce Support';
        testHelpDesk.objcase.Subject='Test salesforce Support';
          testHelpDesk.getcategorylist();
         testHelpDesk.categoryChoice='Salesforce Error'; 
                 
        testHelpDesk.save();
       
         testHelpDesk.getdynamiclist();
        testHelpDesk.Department='Salesforce Support Request'; 
           testHelpDesk.onChangeDepartment();
    testHelpDesk.getcategorylist();
         testHelpDesk.objcase.Severity_Level__c=null;
      
        testHelpDesk.objcase.Severity_Level__c=null;
        testHelpDesk.objcase.Description=null;
        testHelpDesk.objcase.Main_Lead_Source__c=null;
        testHelpDesk.objcase.Original_Campaign_Source__c=null;
        testHelpDesk.objcase.Requested_Due_Date__c=null;
          testHelpDesk.getcategorylist();
         testHelpDesk.categoryChoice='Lead Upload'; 
                  testHelpDesk.fileName3='';
        testHelpDesk.fileBody3=Blob.valueOf('');
         
        testHelpDesk.save();
          

        Test.stopTest();
    }
}