objects/Case.object
<CustomObject>
    <fields>
        <fullName>Sale2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>2nd Related Sale to Case</inlineHelpText>
        <label>2nd Sale</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases (2nd Sale)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>3rd Sale</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases (3rd Sale)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>4th Sale</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases (4th Sale)</relationshipLabel>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>5th Sale</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases (5th Sale)</relationshipLabel>
        <relationshipName>Cases4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>6th Sale</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases (6th Sale)</relationshipLabel>
        <relationshipName>Cases5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Vertiba OnDemand, 9/18/2014, SR-00002279</description>
        <inlineHelpText>Related Sale</inlineHelpText>
        <label>Sales</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE(
CASE(StageName,
&quot;Closed Won&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Closed Lost&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;Declined-&quot;, &quot;https://andersonadvisors--c.na171.visual.force.com/resource/1473631501000/Exclamation&quot;,
&quot;Converted&quot;, &quot;/servlet/servlet.FileDownload?file=015U00000040BV4&quot;,
&quot;Refund Requested&quot;,&quot;https://andersonadvisors--c.na171.visual.force.com/resource/1593114668000/RefundRequest&quot;,
&quot;/img/samples/flag_yellow.gif&quot;),
&quot;Priority Flag&quot;, 15, 15)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent a Kit</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/consolidatedServiceItemsCtrl.cls
public class consolidatedServiceItemsCtrl {
    @AuraEnabled
    public static List<OpportunityLineItem> getseviceItems(Id CaseId) {
        List<id> saleid=new List<id>();
        List<Case> SelectedCase=[Select id,Sales__c,Sale2__c,Sale3__c,Sale4__c,Sale5__c,Sale6__c from case where id=:CaseId ];
        for(case c:SelectedCase){
            saleid.add(c.Sales__c);
             saleid.add(c.Sale2__c);
             saleid.add(c.Sale3__c);
             saleid.add(c.Sale4__c);
             saleid.add(c.Sale5__c);
             saleid.add(c.Sale6__c);
            
        }
       return[select id,OpportunityId,Opportunity.Name,Product2Id,Product2.Name,Status__c from OpportunityLineItem where OpportunityId in:saleid ];
    }
              @AuraEnabled
    public static  List < String > getseviceItemsStatuspicklist(sObject objObject, string fld) {
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);
        List < String > allOpts = new list < String > ();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        system.debug('allOpts ---->' + allOpts);
        allOpts.sort();
        return allOpts;
    }
     @AuraEnabled
   public static List < OpportunityLineItem > saveoplt(List<OpportunityLineItem> lstoplt) {
        update lstoplt;
        return lstoplt;
    }
}