objects/Case.object
<CustomObject>
    <fields>
        <fullName>Critical_Cases__c</fullName>
        <label>Critical Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>High_Cases__c</fullName>
        <label>High Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Medium_Cases__c</fullName>
        <label>Medium Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Ideas__c</fullName>
        <label>New Ideas</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queue_Length__c</fullName>
        <label>Queue Length</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity_Level__c</fullName>
        <label>Priority Internal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Level 1 - Critical</fullName>
                </value>
                <value>
                    <fullName>Level 2 - Urgent</fullName>
                </value>
                <value>
                    <fullName>Level 3 - High</fullName>
                </value>
                <value>
                    <fullName>Level 4 - Medium</fullName>
                </value>
                <value>
                    <fullName>Level 5 - New Idea</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Urgent_Cases__c</fullName>
        <label>Urgent Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/getHelpDeskInfo.cls
public class getHelpDeskInfo {
          
    public static boolean alreadyProcessed;
    
    public static void insertQueueLength(List<Case> newList) {
        
        if (alreadyProcessed == true) return;
        alreadyProcessed = true;
        
        Integer criticalCases = 0;
        Integer urgentCases = 0;
        Integer highCases = 0;
        Integer mediumCases = 0;
        Integer newIdeas = 0;
        
        List<Case> helpDeskCases = [SELECT Id, Status, Severity_Level__c  From Case Where Status != 'Closed'
                                   AND RecordTypeId = '0120B000000NAE1'
                                   AND OwnerId != '005U0000003rcF8'];

        Integer totalCases = helpDeskCases.size() + 1;
                
        for (Case c : helpDeskCases)
        {
            Switch on c.Severity_Level__c {
                when 'Level 1 - Critical' {
                    criticalCases += 1;
                }
                when 'Level 2 - Urgent' {
                    urgentCases += 1;
                }
                when 'Level 3 - High' {
                    highCases += 1;
                }
                when 'Level 4 - Medium' {
                    mediumCases += 1;
                }
                when 'Level 5 - New Idea' {
                    newIdeas += 1;
                }
            }
            
        }
               
        for(Case c : newList) {
            
            if(c.RecordTypeId == '0120B000000NAE1') {
              
                Switch on c.Severity_Level__c {
                when 'Level 1 - Critical' {
                    criticalCases += 1;
                }
                when 'Level 2 - Urgent' {
                    urgentCases += 1;
                }
                when 'Level 3 - High' {
                    highCases += 1;
                }
                when 'Level 4 - Medium' {
                    mediumCases += 1;
                }
                when 'Level 5 - New Idea' {
                    newIdeas += 1;
                }
            }
                                
              c.Queue_Length__c = string.valueOf(totalCases);
              c.Critical_Cases__c = criticalCases;
              c.Urgent_Cases__c = urgentCases;
              c.High_Cases__c = highCases;
              c.Medium_Cases__c = mediumCases;
              c.New_Ideas__c = newIdeas;
                
            } 
        }
                
    }

}