objects/ChargentBase__Gateway__c.object
<CustomObject>
    <description>Configuration object. The administrator should create ONE account for the appropriate payment gateway.</description>
    <fields>
        <fullName>ChargentBase__Accounting_Seed_Integration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Turn on for use Integration with Accounting Seed package.</description>
        <inlineHelpText>Accounting Seed customers can integrate Chargent and Accounting Seed by checking this field.</inlineHelpText>
        <label>Accounting Seed Integration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Available_Card_Types__c</fullName>
        <inlineHelpText>Select the values in this field that represent the card types you want to accept in the Payment Request and the Payment Console features. When a card type is not selected on this list, users will get an error when attempting to use it on PC or PR.</inlineHelpText>
        <label>Available Card Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>American Express</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Diners Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentBase__Charge_Amount_Behavior__c</fullName>
        <inlineHelpText>In Payment Console you can control how the Charge Amount field is populated.</inlineHelpText>
        <label>Charge Amount Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Use Opportunity/Order/Case Charge Amount</fullName>
                </value>
                <value>
                    <fullName>Use Gateway Charge    Amount (Fixed)</fullName>
                </value>
                <value>
                    <fullName>Allow User to Edit in Console</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentBase__Debug__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Merchant_ID__c</fullName>
        <inlineHelpText>Also know as:
&quot;API Login&quot; on Authorize.net
&quot;Merchant Login&quot; on Payflow Pro
&quot;Name&quot; (Username) on ePDQ
&quot;Connection Username&quot; on Orbital</inlineHelpText>
        <label>Merchant ID</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Merchant_Reference__c</fullName>
        <inlineHelpText>Not used by Authorize.net
&quot;User Name&quot; in Cybersource
&quot;Partner&quot; in Payflow/Paypal
&quot;Client ID&quot; on Barclays ePDQ
&quot;Merchant Number&quot; on Orbital
&quot;Restrict Key&quot; for eProcessingNetwork</inlineHelpText>
        <label>Merchant Reference</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Require_AVS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Require AVS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Require_CCV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Require Card Security Code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Security_Key__c</fullName>
        <inlineHelpText>Also known as:
&quot;Transaction Key&quot; on Authorize.net
&quot;Password&quot; on Cybersource
&quot;Connection Password&quot; on Orbital
&quot;Password&quot; on Payflow Pro
&quot;Password&quot; on ePDQ
&quot;API Key&quot; on AltCharge</inlineHelpText>
        <label>Merchant Security Key</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Test_Mode__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Test Endpoint</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentBase__Use_Tokenization__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tokenization is a feature that helps lower your PCI scope.  Tokenization works on a number of our gateways, check AppFrontier.com for a complete list.</inlineHelpText>
        <label>Use Tokenization</label>
        <type>Checkbox</type>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Chargent_Single_Scope_Batch_Test.cls
/**
 * @author ericalexander
 * @date 11/29/16
 * @group Tests
 * @description Tests the Chargent Single Scope Batch Scheduler
 */
@isTest
private class Chargent_Single_Scope_Batch_Test {

    private static testmethod void testSchedule() {
        Test.startTest();

        // Schedule the test job
        String jobId = System.schedule('testChargentSingleScopeSchedule',
                Chargent_Single_Scope_Batch.CRON_EXP,
                new Chargent_Single_Scope_Batch());
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,
                NextFireTime
        FROM CronTrigger WHERE id = :jobId];

        // Verify the expressions are the same

        System.assertEquals(Chargent_Single_Scope_Batch.CRON_EXP,
                ct.CronExpression);

        // Verify the job has not run

        System.assertEquals(0, ct.TimesTriggered);

        // Verify the next time the job will run

        System.assertEquals(date.today().addYears(1).year() + '-09-03 00:00:00',
                String.valueOf(ct.NextFireTime));


        Test.stopTest();

    }

    @TestSetup private static void setupData(){
        
        ChargentBase__Gateway__c testGateway = new ChargentBase__Gateway__c(
                Name = 'TestGateway',
                ChargentBase__Active__c = TRUE,
                ChargentBase__Merchant_ID__c = '111111111111111',
                ChargentBase__Security_Key__c = '222222222222222',
                ChargentBase__Merchant_Reference__c = '123123123',
                ChargentBase__Test_Mode__c = TRUE,
                ChargentBase__Require_AVS__c = TRUE,
                ChargentBase__Require_CCV__c = TRUE,
                ChargentBase__Debug__c = TRUE,
                ChargentBase__Use_Tokenization__c = TRUE,
                ChargentBase__Accounting_Seed_Integration__c = false,
                ChargentBase__Available_Card_Types__c = 'Visa;Mastercard;Discover;American Express',
                ChargentBase__Charge_Amount_Behavior__c = 'Use Opportunity/Order/Case Charge Amount'
        );

        insert testGateway;

    }

}