objects/ChargentBase__Gateway__c.object
<CustomObject>
    <description>Configuration object. The administrator should create ONE account for the appropriate payment gateway.</description>
    <fields>
        <fullName>ChargentBase__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Platinum_Website_Gateway__c</fullName>
        <description>Controls which Gateway payments coming from the Platinum membership site are run through. Does not affect Platinum recurring billing sales.</description>
        <inlineHelpText>Mark this field yes if you want this Gateway to run all payments coming from the Platinum membership site. Triple-check that there is only one single Gateway in Salesforce with this field marked Yes.</inlineHelpText>
        <label>Platinum Website Gateway</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Credit_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Detail</relationshipLabel>
        <relationshipName>Credit_Card_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>AMEX: first digit = 3, second digit = 4 or 7. Valid length: 15 digits.
VISA: first digit = 4. Valid length: 13 or 16 digits.
MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</description>
        <inlineHelpText>AMEX: first digit = 3, second digit = 4 or 7.  Valid length: 15 digits.

VISA: first digit = 4.  Valid length: 13 or 16 digits.

MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</inlineHelpText>
        <label>Card Number</label>
        <length>19</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <description>American Express cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</description>
        <inlineHelpText>AMEX cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</inlineHelpText>
        <label>Card Security Code</label>
        <length>5</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Notes__c</fullName>
        <description>Notes regarding what this credit card should be used for.</description>
        <inlineHelpText>Notes regarding what this credit card should be used for.</inlineHelpText>
        <label>Credit Card Notes</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Credit Card Detail</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <label>Card Security</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Name__c</fullName>
        <inlineHelpText>Name on the card to be charged - will default to Client First and Last</inlineHelpText>
        <label>Card Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Number__c</fullName>
        <inlineHelpText>Please enter the complete credit card number without spaces or dashes</inlineHelpText>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ChargentSFA__Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default should be &apos;LV&apos;.</inlineHelpText>
        <label>Gateway</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose an Active Gateway record</errorMessage>
            <filterItems>
                <field>ChargentBase__Gateway__c.ChargentBase__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ChargentBase__Gateway__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CustomPaymentApi.cls
/** A Rest webservice class is used to get the opportunity for payment.
* @author Sharukh khan
* @version 1.0 - apr 23, 2020
*/

@RestResource(urlmapping='/CustomPayment/*')
global class CustomPaymentApi {
    
    @HttpPost
    global static String getOppId(String opportunityid,String creditId)
    {
        String myString=opportunityid;
        String creditCardId=creditId;
        Id cardId = Id.valueOf(creditCardId);
        system.debug(cardId);
        Credit_Card_Detail__c cardDetails = [SELECT Id, Name, Card_Month__c, Card_Year__c, Card_Number__c, Card_Security__c, Card_Type__c, Account__c, Credit_Card_Notes__c FROM Credit_Card_Detail__c where Id = :cardId LIMIT 1];
        system.debug('cardDetails::'+cardDetails);
        String allOppId = '';
        //Id gatewayId = [SELECT Id, Name FROM ChargentBase__Gateway__c WHERE Name = :'AuthorizeNetTestPayment' and ChargentBase__Active__c = true].Id; //For Sandbox
        Id websitegatewayId = [SELECT Id, Name FROM ChargentBase__Gateway__c WHERE Platinum_Website_Gateway__c = 'Yes' and ChargentBase__Active__c = true Limit 1]?.Id; //For Production
        Id platinumgatewayId = [SELECT Id, Name FROM ChargentBase__Gateway__c WHERE Name=:'Platinum' and ChargentBase__Active__c = true Limit 1]?.Id;
		Id gatewayId = String.isBlank(String.valueOf(websitegatewayId)) ? platinumgatewayId : websitegatewayId;
        
        if(myString.contains(',')){ 
            String[] commaSeperatedOppId = New String[]{};
                List<String> myArray = myString.split(',');
            for (String o : myArray) {
                Id oppId = Id.valueOf(o);  
                Opportunity op = new Opportunity(Id = oppId);
                op.ChargentSFA__Card_Type__c = cardDetails.Card_Type__c;
                op.ChargentSFA__Card_Year__c = cardDetails.Card_Year__c;
                op.ChargentSFA__Card_Month__c = cardDetails.Card_Month__c;
                op.ChargentSFA__Card_Name__c = cardDetails.Name;
                op.ChargentSFA__Card_Number__c = cardDetails.Card_Number__c;
                op.ChargentSFA__Gateway__c = gatewayId;
                try{
                    update op;
                    commaSeperatedOppId.add(oppId);
                }catch(exception e) {
                    system.debug('Chargent Exception === ' + e);
                }
            }
            allOppId = string.join(commaSeperatedOppId,',');
        } else {
            Id myArray = Id.valueOf(myString);
            Opportunity op = new Opportunity(Id = myArray);
            op.ChargentSFA__Card_Month__c = cardDetails.Card_Month__c;
            op.ChargentSFA__Card_Name__c = cardDetails.Name;
            op.ChargentSFA__Card_Number__c = cardDetails.Card_Number__c;
            op.ChargentSFA__Card_Type__c = cardDetails.Card_Type__c;
            op.ChargentSFA__Card_Year__c = cardDetails.Card_Year__c;
            op.ChargentSFA__Gateway__c = gatewayId;
            try{
                update op;
            }catch(exception e) {
                system.debug('Chargent Exception === ' + e);
            }
            allOppId = myArray;
        }
        return allOppId;
       /* //String oId=PlatinumInvoiceController.MyOpportunities(myString,creditCardId);
        String response=PlatinumInvoiceController.Charge(allOppId);
        system.debug('response=='+response);
        //PlatinumInvoiceController.MyOpportunities(oppotunityId,creditCardId);
        return response; */
    }
    
}