objects/ChargentBase__Gateway__c.object
<CustomObject>
    <description>Configuration object. The administrator should create ONE account for the appropriate payment gateway.</description>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Default_Renewal_Oppty_Fields__mdt.object
<CustomObject>
    <description>Custom metadata to default fields on renewal opportunities</description>
    <fields>
        <fullName>Add_Year__c</fullName>
        <description>field to store number of years to be added to end date</description>
        <label>Add Year</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <description>Entity type of opportunity getting renewed</description>
        <label>Entity Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_State__c</fullName>
        <description>State for renewal opportunities</description>
        <label>Renewal State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Default Renewal Oppty Fields</label>
    <pluralLabel>Default Renewal Oppty Fields</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default should be &apos;LV&apos;.</inlineHelpText>
        <label>Gateway</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose an Active Gateway record</errorMessage>
            <filterItems>
                <field>ChargentBase__Gateway__c.ChargentBase__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ChargentBase__Gateway__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Manual_Charge__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box when you want to authorize or charge an amount different than the amount due on the opportunity or order. This will prevent the &quot;Charge Amount&quot; from being automatically calculated and updated.</inlineHelpText>
        <label>Manual Charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Payment_Start_Date__c</fullName>
        <label>Payment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>DATETIMEVALUE (Renewal_Effective_Date__c) - 21</formula>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>C-Corporation</fullName>
                </value>
                <value>
                    <fullName>S-Corporation</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>CRT</fullName>
                </value>
                <value>
                    <fullName>GRT</fullName>
                </value>
                <value>
                    <fullName>QPRT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To override the Closed Lost automation.</inlineHelpText>
        <label>Override Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Populate_the_Entity_lookup_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Populate the Entity lookup Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Effective_Date__c</fullName>
        <description>Date the renewal went into effect.</description>
        <inlineHelpText>Date the renewal went into effect.</inlineHelpText>
        <label>Renewal Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_End_Date__c</fullName>
        <inlineHelpText>Date renewal ends.</inlineHelpText>
        <label>Renewal End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_State__c</fullName>
        <description>State in which State filing will be filed.</description>
        <label>Renewal State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sale_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>BOSS</fullName>
                </value>
                <value>
                    <fullName>Business Credit</fullName>
                </value>
                <value>
                    <fullName>C-Corp</fullName>
                </value>
                <value>
                    <fullName>Corp</fullName>
                </value>
                <value>
                    <fullName>Corp Headquarters</fullName>
                </value>
                <value>
                    <fullName>Deed Preparation</fullName>
                </value>
                <value>
                    <fullName>Document Drafting</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Irrevocable Trust</fullName>
                </value>
                <value>
                    <fullName>Joint Venture LLC</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>LIST00</fullName>
                </value>
                <value>
                    <fullName>Living Trust</fullName>
                </value>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>Mail Forwarding</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Pension</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Registered Agent Fee</fullName>
                </value>
                <value>
                    <fullName>Resident Agent</fullName>
                </value>
                <value>
                    <fullName>S-Corp</fullName>
                </value>
                <value>
                    <fullName>Series LLC</fullName>
                </value>
                <value>
                    <fullName>Titanium</fullName>
                </value>
                <value>
                    <fullName>Unlimited LLC</fullName>
                </value>
                <value>
                    <fullName>Unlimited LLC Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Valley</fullName>
                </value>
                <value>
                    <fullName>Vertucci Fulfillment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SaleEntity__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <formula>Entity__r.RecordType.Name</formula>
        <label>Entity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Sale Entities</relationshipLabel>
        <relationshipName>Sale_Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sale Entities</relationshipLabel>
        <relationshipName>Sale_Entities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Renewal_State__c</fullName>
        <formula>TEXT(Opportunity__r.Renewal_State__c)</formula>
        <label>Renewal State</label>
        <type>Text</type>
    </fields>
    <label>Sale Entity</label>
    <nameField>
        <label>Sale Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityTriggerHandler.cls
public with sharing class OpportunityTriggerHandler {
    public static boolean OpportunityTriggerIsRunning = false;
    public static set<id> oppProcessed = new set<id>();
    
    public static void OpportunityRenewal(map<id,Opportunity>  oppIdToOpps){
        
        if(OpportunityTriggerIsRunning == true) return;
        OpportunityTriggerIsRunning = true;
        
        map<id,Opportunity> oppToClone = new map<id,Opportunity>();
        
        List<ChargentBase__Gateway__c> gateway = new List<ChargentBase__Gateway__c>([SELECT Id FROM ChargentBase__Gateway__c WHERE Name = 'LV' LIMIT 1]);
        List<Campaign> campaign = new List<Campaign>([SELECT Id FROM Campaign WHERE Name = 'BCP' LIMIT 1]);
        
        Map<string,List<Default_Renewal_Oppty_Fields__mdt>> renewalStateDefaultMap = new Map<string,List<Default_Renewal_Oppty_Fields__mdt>>();
        for(Default_Renewal_Oppty_Fields__mdt drof : [select Id,Renewal_State__c,Entity_Type__c,Add_Year__c from Default_Renewal_Oppty_Fields__mdt]){
            if(renewalStateDefaultMap.containskey(drof.Renewal_State__c))
                renewalStateDefaultMap.get(drof.Renewal_State__c).add(drof);
            else
                renewalStateDefaultMap.put(drof.Renewal_State__c, new list<Default_Renewal_Oppty_Fields__mdt>{drof});
        }
        for(Opportunity each : oppIdToOpps.values()){
            Opportunity o = each.clone(false,true);
            system.debug('CloseDate%%%'+o.CloseDate);
            // set fields for clone
            o.StageName = 'Qualification';
            o.ChargentSFA__Manual_Charge__c = FALSE;
            o.Override_Automation__c = FALSE;
            o.ChargentSFA__Gateway__c = gateway[0].Id;
            
            if(each.Sale_Campaign__c == NULL){
                o.Sale_Campaign__c = campaign[0].Id;}
            
            if(each.Renewal_effective_Date__c != null){
                if(each.Renewal_State__c != null && renewalStateDefaultMap.containskey(each.Renewal_State__c)){
                    Boolean matchFound = false; 
                    for(Default_Renewal_Oppty_Fields__mdt dfSet : renewalStateDefaultMap.get(each.Renewal_State__c)){
                        
                        if(dfSet.Entity_Type__c != null){
                            if(dfSet.Entity_Type__c == each.Entity_Type__c){                      
                                o.Renewal_effective_Date__c = each.Renewal_effective_Date__c.addYears(Integer.valueOf(dfSet.Add_Year__c));
                                if(each.Renewal_End_Date__c != null)
                                    o.Renewal_End_Date__c = o.Renewal_End_Date__c.addYears(Integer.valueOf(dfSet.Add_Year__c));
                                if(each.ChargentSFA__Payment_Start_Date__c != null)
                                    o.ChargentSFA__Payment_Start_Date__c = each.Due_Date__c.addYears(Integer.valueOf(dfSet.Add_Year__c));
                                matchFound = true;
                                if(each.RecordTypeId == Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Renewal').getRecordTypeId()){matchFound = false;}
                            }
                        }else{
                            o.Renewal_effective_Date__c = each.Renewal_effective_Date__c.addYears(Integer.valueOf(dfSet.Add_Year__c));
                            if(each.Renewal_End_Date__c != null)
                                o.Renewal_End_Date__c = o.Renewal_End_Date__c.addYears(Integer.valueOf(dfSet.Add_Year__c));
                            if(each.ChargentSFA__Payment_Start_Date__c != null)
                                o.ChargentSFA__Payment_Start_Date__c = each.Due_Date__c.addYears(Integer.valueOf(dfSet.Add_Year__c));
                            matchFound = true;
                            if(each.RecordTypeId == Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Renewal').getRecordTypeId()){matchFound = false;}
                        }
                    }
                    if(!matchFound){
                        o.Renewal_effective_Date__c = each.Renewal_effective_Date__c.addYears(1);
                        if(each.Renewal_End_Date__c != null)
                            o.Renewal_End_Date__c = each.Renewal_End_Date__c.addYears(1);
                        if(each.ChargentSFA__Payment_Start_Date__c != null)
                            o.ChargentSFA__Payment_Start_Date__c = each.Due_Date__c.addYears(1);
                    }   
                }else{
                    o.Renewal_effective_Date__c = each.Renewal_effective_Date__c.addYears(1);
                    if(each.Renewal_End_Date__c != null)
                        o.Renewal_End_Date__c = each.Renewal_End_Date__c.addYears(1);
                    if(each.ChargentSFA__Payment_Start_Date__c != null)
                        o.ChargentSFA__Payment_Start_Date__c = each.Due_Date__c.addYears(1);
                    
                }             
            }
            system.debug('CloseDateAfter%%%'+o.CloseDate); 
            if(each.Name.contains('**')){
                o.Name=each.Name.left(each.Name.length()-2)+each.Name.right(0);
            }
            oppToClone.put(each.id, o);
        }
        set<id> oppToCloneKeys = oppToClone.keyset();
        
        // insert clones
        if(!oppToClone.values().isEmpty())
            insert oppToClone.values();
        
        List<Opportunity> updateOppWithEntityID = new List<Opportunity>();
        Map<Id, Opportunity> updateOppWithEntityIDMap = new Map<Id, Opportunity>();
        
        list<SaleEntity__c> saleEntities = new list<SaleEntity__c>();
        string SEQ = cloneQuery('SaleEntity__c') +' WHERE Opportunity__c IN  :oppToCloneKeys';
        system.debug(seq);
        for(SaleEntity__c each : database.query(SEQ))
        {
            SaleEntity__c s = each.clone(false,true);
            s.Opportunity__c = oppToClone.get(each.Opportunity__c).id;
            saleEntities.add(s);
            
            // "updateOppWithEntityID" ADDED BY "Umer Amjad" ON "19-Nov-2021"
            if(oppToClone.get(each.Opportunity__c) != null && 
               oppToClone.get(each.Opportunity__c).Name != 'Corporate Headquarters Renewal' && 
               oppToClone.get(each.Opportunity__c).Name != 'Corporate Assistance Program Renewal' )
            {
                Opportunity oppObj = new Opportunity();
                oppObj.Id = oppToClone.get(each.Opportunity__c).id;
                oppObj.Entity__c = s.Entity__c;
                oppObj.Populate_the_Entity_lookup_Processed__c = true;
                
                //updateOppWithEntityID.add(oppObj);
                updateOppWithEntityIDMap.put(oppObj.Id, oppObj);
                                
            }
            // "updateOppWithEntityID" ADDED BY "Umer Amjad" ON "19-Nov-2021"
        }
        
        list<OpportunityLineItem> products = new list<OpportunityLineItem>();
        string pq = cloneQuery('OpportunityLineItem') +' WHERE Product2.Subscription_Product__c = true AND OpportunityId IN :oppToCloneKeys'; 
        for(OpportunityLineItem each : database.Query(pq))
        {
            OpportunityLineItem op = each.clone(false,true);
            op.OpportunityId = oppToClone.get(each.OpportunityId).id;
            op.TotalPrice = null;
            products.add(op);
        }
        
        if(!saleEntities.isEmpty())
        {
            updateOppWithEntityID = updateOppWithEntityIDMap.Values();
            
            insert saleEntities;
        	UPDATE updateOppWithEntityID; // ADDED BY "Umer Amjad" ON "19-Nov-2021"
        }
            
        
        if(!products.isEmpty())
            insert products;
    }
    
    public static string cloneQuery(string objectName){
        string q = 'SELECT ';
        for(string each :  Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().keySet())
            q += each +',';
        q = q.removeEnd(',');
        q += ' FROM '+objectName + ' ';
        return q;
    }
    
    
}