objects/Client_Statement__c.object
<CustomObject>
    <fields>
        <fullName>All_1099_Tax_Forms__c</fullName>
        <label>All 1099 Tax Forms</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>All_Bookkeeping_Completed_By__c</fullName>
        <label>All Bookkeeping Completed By</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>All_Entities__c</fullName>
        <label>All Entities</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>All_Entity_Extensions__c</fullName>
        <label>All Entity Extensions</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>All_Tax_Return_Filings__c</fullName>
        <label>All Tax Return Filings</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Entity_11__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity 11</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Client Statements11</relationshipLabel>
        <relationshipName>Client_Statements11</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity 6</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Client Statements6</relationshipLabel>
        <relationshipName>Client_Statements6</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Statement</label>
    <nameField>
        <label>Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</description>
        <inlineHelpText>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anderson</fullName>
                    <default>true</default>
                    <label>Anderson</label>
                </value>
                <value>
                    <fullName>Client Formed</fullName>
                </value>
                <value>
                    <fullName>Shelf</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testFormatStatement.cls
@isTest
public class testFormatStatement {
    
    @testSetup static void createEntities() {
        
        List<Entities__c> updateList = new List<Entities__c>();
        
        for (Integer i = 0; i<20; i++){
            Entities__c myEnt = new Entities__c();
            myEnt.Name = 'Entity_'+i;
            myEnt.Origin__c = 'Anderson';
            myEnt.Organization_State__c = 'Maine';
            updateList.add(myEnt);
            
        }
        
        insert updateList;
    }
    
    @isTest static void createClientStatement() {
        
        List<Entities__c> entList = [SELECT Id FROM Entities__c];
        String[] idList = new String[]{};
            
            
        for (Entities__c ents : entList) {
                idList.add(ents.id);
            }   
        String commaList = string.join(idList,',');
        
        List<Entities__c> ent7List = [SELECT Id FROM Entities__c LIMIT 7];
        String[] id7List = new String[]{};
            
            
        for (Entities__c ents : ent7List) {
                id7List.add(ents.id);
            }   
        String comma7List = string.join(id7List,',');
 
        Client_Statement__c cs = new Client_Statement__c();
        cs.Name = 'Test CS';
        cs.All_Entities__c = commaList;
        cs.All_Entity_Extensions__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        cs.All_Tax_Return_Filings__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        cs.All_Bookkeeping_Completed_By__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        cs.All_1099_Tax_Forms__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        insert CS;
        
        cs.Name = 'Test CS - Update';
        update cs;
        
        cs.All_Entities__c = null;
        update cs;
        
        cs.Entity_11__c = null;
        update cs;
        
   		cs.Entity_6__c = null;
        update cs;
        
        Client_Statement__c cs1 = new Client_Statement__c();
        cs1.Name = 'Test CS 1';
        cs1.All_Entities__c = comma7List;
        cs1.All_Entity_Extensions__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        cs1.All_Tax_Return_Filings__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        cs1.All_Bookkeeping_Completed_By__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        cs1.All_1099_Tax_Forms__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        insert CS1;
        
        Client_Statement__c cs2 = new Client_Statement__c();
        cs2.Name = 'Test CS 2';
        cs2.All_Entity_Extensions__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        cs2.All_Tax_Return_Filings__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        cs2.All_Bookkeeping_Completed_By__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        cs2.All_1099_Tax_Forms__c = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V';
        insert CS2;
      
    }

}