objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platinum_Email__c</fullName>
        <label>Platinum Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platinum_Wordpress_Id__c</fullName>
        <label>Platinum Wordpress Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PlatinumCreationHandler.cls
public class PlatinumCreationHandler {
    
    
    public static void updatePrimaryContact(string accountId, String responseBody,string contactID) {
        
        PlatinumUser.newUser brandNewUser = (PlatinumUser.newUser)JSON.deserialize(responseBody, PlatinumUser.newUser.class);
        String wordPressId = brandNewUser.Id;
        
        updateContact(accountId, wordPressId,contactID);
        
    }
    
 
    public static void updateContact(String accountId, String wordPressId,string contactID){
        Contact c=[select Id, Email, Account_Roles__c, Platinum_Email__c, Platinum_Wordpress_Id__c FROM Contact WHERE AccountId = :accountId and id=:contactID limit 1 ];
        if(c!=null){
          c.Platinum_Wordpress_Id__c = wordPressId;
        if(c.Platinum_Email__c == null) c.Platinum_Email__c = c.Email; 
               update c;
        }
       // Contact c = getPrimaryOrOldestContact(accountId,contactID);
       
     
        
    }

   /* private static Contact getPrimaryOrOldestContact(Id accountId) {
        
        List<Contact> conList = new List<Contact>();
        
        for (Contact con : [SELECT Id, Email, Account_Roles__c, Platinum_Email__c, Platinum_Wordpress_Id__c FROM Contact WHERE AccountId = :accountId ORDER BY CreatedDate ASC]) {
            
            if (con.Account_Roles__c == 'Primary Contact') {
                conList.add(con);
            } 
            
            if (conList.size() == 0) {
                conList.add(con);
            }
            
        }
        
        return conList[0];
        
    }*/
    
}