objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Platinum_Email__c</fullName>
        <label>Platinum Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platinum_Password__c</fullName>
        <label>Platinum Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platinum_Wordpress_Id__c</fullName>
        <label>Platinum Wordpress Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/updateWordpress.cls
public class updateWordpress {
    
    @AuraEnabled
    public static void sendUpdate(Id conId){
        
        List<Contact> conList = [SELECT Platinum_Wordpress_Id__c, Platinum_Password__c, FirstName, LastName, Platinum_Email__c FROM Contact WHERE Id = :conId];
        
        wordpressUpdatePlatinumUser.processContacts(conList);
    }

    @AuraEnabled
    public static void resetPassword (Id conId){
        
        List<Contact> conList = [SELECT Platinum_Wordpress_Id__c, Platinum_Password__c, FirstName, LastName, Platinum_Email__c FROM Contact WHERE Id = :conId];
        
        wordpressUpdatePlatinumUser.processContactsforreset(conList);
    }
}