objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <inlineHelpText>How each contact relates to the entire account.</inlineHelpText>
        <label>Account Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Child</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Father</fullName>
                </value>
                <value>
                    <fullName>Primary Contact Mother</fullName>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                </value>
                <value>
                    <fullName>Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner</fullName>
                </value>
                <value>
                    <fullName>Second Business Partner Spouse</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Outside Attorney</fullName>
                </value>
                <value>
                    <fullName>Outside Accountant</fullName>
                </value>
                <value>
                    <fullName>Outside Bookkeeper</fullName>
                </value>
                <value>
                    <fullName>Event Guest</fullName>
                </value>
                <value>
                    <fullName>Contact Spouse</fullName>
                </value>
                <value>
                    <fullName>Anderson Employee</fullName>
                </value>
                <value>
                    <fullName>DO NOT CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign2ID__c</fullName>
        <label>Campaign2ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignID__c</fullName>
        <label>CampaignID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PlatinumOnboadingBatchCall.cls
global class PlatinumOnboadingBatchCall implements Schedulable {
     global void execute(SchedulableContext sc) {
      Id batchJobId1 = Database.executeBatch(new PlatinumOnboardingBatch('Select id, Name,CampaignID__c,Campaign2ID__c from Contact where AccountId IN:NewoppIDlawsale and Account_Roles__c=\'Primary Contact\'','New Client Law Sale'), 200);
System.debug('Batch1--'+batchJobId1);
    
Id batchJobId2 = Database.executeBatch(new PlatinumOnboardingBatch('Select id, Name,CampaignID__c,Campaign2ID__c from Contact where AccountId IN:NewoppIDtaxsale and Account_Roles__c=\'Primary Contact\'','New Client Tax Sale'), 200);
System.debug('Batch2--'+batchJobId2);
            
Id batchJobId3 = Database.executeBatch(new PlatinumOnboardingBatch('Select id, Name,CampaignID__c,Campaign2ID__c from Contact where AccountId IN:NewoppIDlawandtaxsale and Account_Roles__c=\'Primary Contact\'','New Client Law and Tax Sale'), 200);
             System.debug('Batch3--'+batchJobId3);
         


     /*     Id batchJobId4 = Database.executeBatch(new PlatinumOnboardingBatch('Select id, Name,CampaignID__c,Campaign2ID__c from Contact where AccountId IN:ExistingppIDlawsalewelcomecall and Account_Roles__c=\'Primary Contact\'','Existing Client Law Sale'), 200);
System.debug('Batch4--'+batchJobId4);
Id batchJobId5 = Database.executeBatch(new PlatinumOnboardingBatch('Select id, Name,CampaignID__c,Campaign2ID__c from Contact where AccountId IN:ExistingppIDtaxsalewelcomecall and Account_Roles__c=\'Primary Contact\'','Existing Client Tax Sale'), 200);
System.debug('Batch5--'+batchJobId5);
Id batchJobId6 = Database.executeBatch(new PlatinumOnboardingBatch('Select id, Name,CampaignID__c,Campaign2ID__c from Contact where AccountId IN:ExistingppIDlawandtaxpandwelcomecall and Account_Roles__c=\'Primary Contact\'','Existing Client Tax and Law Sale'), 200);
System.debug('Batch6--'+batchJobId6);*/
    
    }

}