objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Platinum_Wordpress_Id__c</fullName>
        <label>Platinum Wordpress Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <description>Used with LearnDash and the Platinum website to provide course access.</description>
        <inlineHelpText>Used with LearnDash and the Platinum website to provide course access.</inlineHelpText>
        <label>Service Item List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DebugInfo__c.object
<CustomObject>
    <fields>
        <fullName>DebugData__c</fullName>
        <label>DebugData</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>DebugInfo</label>
    <nameField>
        <displayFormat>DBI-{00000}</displayFormat>
        <label>DebugInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DebugInfo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Infinity_Memebership__c</fullName>
        <label>Infinity Membership</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Free</fullName>
                </value>
                <value>
                    <fullName>Stock</fullName>
                    <label>Stock Pro</label>
                </value>
                <value>
                    <fullName>Real</fullName>
                    <label>Real Estate Pro</label>
                </value>
                <value>
                    <fullName>360</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Item_List__c</fullName>
        <label>Service Item List</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_User_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service User Created</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>Used for Emails</description>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InfinityUserCreationBatch.cls
global class InfinityUserCreationBatch implements 
    Database.Batchable<sObject>,Database.AllowsCallouts, Database.Stateful {
      private String query; 
           List<Opportunity> OppUpdate=new List<Opportunity>();
        public Integer recordsProcessed = 0;
      
       global   DebugInfo__c Dinfo=new DebugInfo__c();

        List<task> taskList=new List<task>();
        global InfinityUserCreationBatch(string query){
            this.query = query;
            
        }
        global Database.QueryLocator start(Database.BatchableContext bc) {
                   
         return Database.getQueryLocator(this.query);
        }
      global void execute(Database.BatchableContext bc, List<opportunity> saledatalist){
          List<contact> conList=new List<contact>();
          List<Id> accountIDs= new List<Id>();
       contact con=new contact(); 
          for(opportunity opp : saledatalist){
              accountIDs.add(opp.AccountId);
         
          DigitalProductsSaleWPusercreationBatch.wrapConatct wcreturned=DigitalProductsSaleWPusercreationBatch.getPrimaryOrOldestContact(opp.AccountId);
              if(wcreturned.ContactID!=null){
                   conList=[Select id,Service_Item_List__c from contact where id=: wcreturned.ContactID limit 1];
              if(conList.size()>0){
                  if(string.isBlank(conList[0].Service_Item_List__c) && conList[0].Service_Item_List__c==null ){
                      conList[0].Service_Item_List__c=opp.Infinity_Memebership__c+',';
                 
                  }else if( ((!string.isBlank(conList[0].Service_Item_List__c)&&conList[0].Service_Item_List__c!=null) ?!conList[0].Service_Item_List__c.contains(opp.Infinity_Memebership__c):false)){
                  conList[0].Service_Item_List__c=conList[0].Service_Item_List__c+opp.Infinity_Memebership__c+',';
                  
              }
              conList.add(con);
              } 
              }
            
            
             
             OppUpdate.add(opp);
          }
DigitalProductsSaleWPusercreationBatch.prepareCallout(accountIDs);
           try{ 
               update conList;
        		
            } catch (Exception e) {
            debugInfo.createDebugLog(e);
            }
        
         
   
        }
        global void finish(Database.BatchableContext bc){
            List<Opportunity> oppList=new  List<Opportunity>();
            Contact Updatecon=new contact();
            for(opportunity oppu:OppUpdate ){
                 DigitalProductsSaleWPusercreationBatch.wrapConatct wcreturned=DigitalProductsSaleWPusercreationBatch.getPrimaryOrOldestContact(oppu.AccountId);
                if(wcreturned.ContactID!=null){
                   Updatecon=[Select id,Service_Item_List__c,Platinum_Wordpress_Id__c from contact where id=: wcreturned.ContactID limit 1];
                    if(Updatecon!=null){
                        if(Updatecon.Platinum_Wordpress_Id__c!='' && Updatecon.Platinum_Wordpress_Id__c!=null){
                            oppu.Service_User_Created__c=true;
                        }
                    }
                    }
                
                oppList.add(oppu);
            }
                       try{ 
               update oppList;
        		
            } catch (Exception e) {
            debugInfo.createDebugLog(e);
            }
          
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
         integer cpuTime = Limits.getCpuTime();
            integer Queries = Limits.getQueries();
         
            Dinfo.DebugData__c='Job Name:SFFBuploadBatchClass; Records deleted:'+recordsProcessed;
            insert Dinfo;
        }
    
}