objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SSN_Text__c</fullName>
        <description>SCH-0034</description>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>SSN</label>
        <length>9</length>
        <maskChar>X</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>UpdateSSN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SCH-0034</description>
        <label>UpdateSSN</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SyncSSNTest.cls
//SCH-0036
@iStest
public class SyncSSNTest {
    
    
    @testSetup
    public static void createData() {
        
        Contact c = new contact();
        c.FirstName = 'Ted';
        c.LastName = 'Excellent Adventure';
        c.SSN__c = '123456789';
        insert c;
        
    }
    
    @isTest
    public static void SyncEncryptToTextSSN() {
        
        Contact c = [SELECT Id, UpdateSSN__c, SSN__c, LastName FROM Contact WHERE LastName = 'Excellent Adventure'];
        
        c.SSN__c = '448559667';
        update c;
        
        Contact con = [SELECT Id, SSN_Text__c, UpdateSSN__c, LastName FROM Contact WHERE LastName = 'Excellent Adventure'];
        system.assertEquals('448559667', con.SSN_Text__c);
        
    }
    
    @isTest
    public static void SyncTextToEncryptSSN() {
        
        Contact c = [SELECT Id, UpdateSSN__c, SSN__c, SSN_Text__c, LastName FROM Contact WHERE LastName = 'Excellent Adventure'];
        
        c.SSN_Text__c = '221133448';
        update c;
        
        Contact con = [SELECT Id, SSN_Text__c, UpdateSSN__c, SSN__c, LastName FROM Contact WHERE LastName = 'Excellent Adventure'];
        system.assertEquals('221133448', con.SSN__c);
        
    }

}