objects/Credit_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Detail</relationshipLabel>
        <relationshipName>Credit_Card_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Zip_Postal__c</fullName>
        <label>Billing Zip / Postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>AMEX: first digit = 3, second digit = 4 or 7. Valid length: 15 digits.
VISA: first digit = 4. Valid length: 13 or 16 digits.
MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</description>
        <inlineHelpText>AMEX: first digit = 3, second digit = 4 or 7.  Valid length: 15 digits.

VISA: first digit = 4.  Valid length: 13 or 16 digits.

MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</inlineHelpText>
        <label>Card Number</label>
        <length>19</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <description>American Express cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</description>
        <inlineHelpText>AMEX cards have a four-digit code printed on the front side of the card above the number.  All others have a three-digit code located on the back.</inlineHelpText>
        <label>Card Security Code</label>
        <length>5</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Credit Card Detail</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Security__c</fullName>
        <label>Card Security</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_Zip__c</fullName>
        <label>Billing Zip/Postal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Name__c</fullName>
        <inlineHelpText>Name on the card to be charged - will default to Client First and Last</inlineHelpText>
        <label>Card Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Number__c</fullName>
        <inlineHelpText>Please enter the complete credit card number without spaces or dashes</inlineHelpText>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ChargentSFA__Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AddCardinfoComponenentCtrl.cls
//Last Updated 3/28/2021
//Reason: Exception Handling and Aura Update for the same
//Developer: Rabeea Aqil
public class AddCardinfoComponenentCtrl {
    @AuraEnabled
    public static List<SelectOptionAuraEnabled> cardinformation(id opperunityid)
    {
        String Selectedid;
        String Selectcard;
        list<SelectOptionAuraEnabled> option;
        list<Credit_Card_Detail__c> lstcardDetail;
        list<Opportunity> getopprtunityid;
        
        
        string getaccountid;
        option=new list<SelectOptionAuraEnabled>();
        getopprtunityid=new list<Opportunity>();
        getopprtunityid=[Select id,AccountId from Opportunity where id=:opperunityid];
        getaccountid= getopprtunityid[0].AccountId ;
        
        lstcardDetail=[Select id,Name,Card_Type__c,Card_Number__c from Credit_Card_Detail__c where Account__c=:getaccountid ];
        for(Credit_Card_Detail__c ccd:lstcardDetail){
            if(ccd.Card_Number__c!=null && ccd.Card_Number__c!='' ){
                
                integer result = ccd.Card_Number__c.length();
                ccd.Card_Number__c= ccd.Card_Number__c.SubString(result -4,result); 
                Selectcard=ccd.Name +'-'+ccd.Card_Number__c;
                Selectedid=ccd.id;
                
                option.add(new SelectOptionAuraEnabled(Selectedid,Selectcard));
            }
            else
            {
                Selectcard=ccd.Name; 
                Selectedid=ccd.id;
                option.add(new SelectOptionAuraEnabled(Selectedid,Selectcard));
            }
        }
        return option;
    }
    @AuraEnabled
    
    public static string Updateinformationcard(id opperunityid,id SelectedId){
        string returnMsg;
        try{
            // Boolean CardType;
            
            
            list<Credit_Card_Detail__c> lstcardDetail;
            
            list<Opportunity> lstoppertunity=new list<Opportunity>();
            lstcardDetail=[Select id,Name,Card_Type__c,Card_Month__c,Card_Year__c,Card_Number__c,Card_Security__c,Billing_Zip_Postal__c from Credit_Card_Detail__c where id=:Selectedid ];
            lstoppertunity=[Select id,ChargentSFA__Card_Name__c,ChargentSFA__Card_Type__c,ChargentSFA__Card_Month__c,ChargentSFA__Billing_Zip__c,ChargentSFA__Card_Year__c,ChargentSFA__Card_Number__c from Opportunity where id=:opperunityid];
            if(lstcardDetail.size()>0){
                lstoppertunity[0].ChargentSFA__Card_Type__c=lstcardDetail[0].Card_Type__c;
                lstoppertunity[0].ChargentSFA__Card_Month__c=lstcardDetail[0].Card_Month__c;    
                lstoppertunity[0].ChargentSFA__Card_Year__c=lstcardDetail[0].Card_Year__c;    
                lstoppertunity[0].ChargentSFA__Card_Number__c=lstcardDetail[0].Card_Number__c; 
                lstoppertunity[0].ChargentSFA__Card_Name__c=lstcardDetail[0].Name;  
                If(lstcardDetail[0].Billing_Zip_Postal__c !=Null && lstcardDetail[0].Billing_Zip_Postal__c!='') 
                {
                    lstoppertunity[0].ChargentSFA__Billing_Zip__c=lstcardDetail[0].Billing_Zip_Postal__c;
                    
                }
                //CardType=True;
                update lstoppertunity; 
                returnMsg = 'Success';
                return returnMsg;
                
            } 
        }
        catch(Exception e)
        { 
            System.debug('UpdateCardError :: ' + e.getMessage() ); 
            returnMsg = e.getMessage();
            return returnMsg;
        }
        return returnMsg;
        
    }
}