objects/Credit_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Detail</relationshipLabel>
        <relationshipName>Credit_Card_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>AMEX: first digit = 3, second digit = 4 or 7. Valid length: 15 digits.
VISA: first digit = 4. Valid length: 13 or 16 digits.
MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</description>
        <inlineHelpText>AMEX: first digit = 3, second digit = 4 or 7.  Valid length: 15 digits.

VISA: first digit = 4.  Valid length: 13 or 16 digits.

MC: first digit: 5, second digit = 1-5.  Valid length: 16 digits.</inlineHelpText>
        <label>Card Number</label>
        <length>19</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Platinum_Subscription_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if uses for platinum payment.</inlineHelpText>
        <label>Platinum Subscription Card</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card Detail</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Name__c</fullName>
        <inlineHelpText>Name on the card to be charged - will default to Client First and Last</inlineHelpText>
        <label>Card Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Number__c</fullName>
        <inlineHelpText>Please enter the complete credit card number without spaces or dashes</inlineHelpText>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ChargentSFA__Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>MC Eurocard</fullName>
                </value>
                <value>
                    <fullName>UK Maestro</fullName>
                </value>
                <value>
                    <fullName>JCB Card</fullName>
                </value>
                <value>
                    <fullName>Solo</fullName>
                </value>
                <value>
                    <fullName>Electron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UpdatePlatinumSale.cls
public class UpdatePlatinumSale {
    
    public static boolean alreadyProcessed = false;

    public static void insertCard(List<Credit_Card_Detail__c> ccList) {
     
        if (alreadyProcessed == true) return;
        alreadyProcessed = true;
        
        List<Opportunity> updateOppList = new List<Opportunity>();
        List<Credit_Card_Detail__c> falseCardList = new List<Credit_Card_Detail__c>();
        
        	for (Credit_Card_Detail__c c : ccList) {
  
            	if (c.Platinum_Subscription_Card__c == TRUE) {

            		for (Opportunity opp : [SELECT Id,ChargentSFA__Card_Type__c,ChargentSFA__Card_Month__c,ChargentSFA__Card_Year__c,ChargentSFA__Card_Number__c,ChargentSFA__Card_Name__c FROM Opportunity WHERE AccountId = :c.Account__c AND Name LIKE 'Platinum Subscription' LIMIT 1]) {
                                       
            		opp.ChargentSFA__Card_Type__c     = c.Card_Type__c;
            		opp.ChargentSFA__Card_Month__c    = c.Card_Month__c;
            		opp.ChargentSFA__Card_Year__c     = c.Card_Year__c;
            		opp.ChargentSFA__Card_Number__c   = c.Card_Number__c;
            		opp.ChargentSFA__Card_Name__c     = c.Name;
            		updateOppList.add(opp);
                    
                    }
                
 
                	for (Credit_Card_Detail__c card : [SELECT Id from Credit_Card_Detail__c WHERE Account__c = :c.Account__c AND Platinum_Subscription_Card__c = TRUE AND id != :c.id]) {
                    
                    card.Platinum_Subscription_Card__c = FALSE;
                    falseCardList.add(card);               
        			} 
                }    
            }

        update updateOppList;
        update falseCardList;

    }
    
    public static void updateCard(List<Credit_Card_Detail__c> ccList, Map<Id,Credit_Card_Detail__c> oldMap) {
     
        if (alreadyProcessed == true) return;
        alreadyProcessed = true;
        
        List<Opportunity> updateOppList = new List<Opportunity>();
        List<Credit_Card_Detail__c> falseCardList = new List<Credit_Card_Detail__c>();
        
        	for (Credit_Card_Detail__c c : ccList) {
  				if (c.Platinum_Subscription_Card__c == TRUE && c.Platinum_Subscription_Card__c != oldMap.get(c.Id).Platinum_Subscription_Card__c) {

            		for (Opportunity opp : [SELECT Id,ChargentSFA__Card_Type__c,ChargentSFA__Card_Month__c,ChargentSFA__Card_Year__c,ChargentSFA__Card_Number__c,ChargentSFA__Card_Name__c FROM Opportunity WHERE AccountId = :c.Account__c AND Name LIKE 'Platinum Subscription' LIMIT 1]) {
                                       
            		opp.ChargentSFA__Card_Type__c     = c.Card_Type__c;
            		opp.ChargentSFA__Card_Month__c    = c.Card_Month__c;
            		opp.ChargentSFA__Card_Year__c     = c.Card_Year__c;
            		opp.ChargentSFA__Card_Number__c   = c.Card_Number__c;
            		opp.ChargentSFA__Card_Name__c     = c.Name;
            		updateOppList.add(opp);
                    
                    }
                
 
                	for (Credit_Card_Detail__c card : [SELECT Id from Credit_Card_Detail__c WHERE Account__c = :c.Account__c AND Platinum_Subscription_Card__c = TRUE AND id != :c.id]) {
                    
                    card.Platinum_Subscription_Card__c = FALSE;
                    falseCardList.add(card);               
        			} 
                }    
            }

        update updateOppList;
        update falseCardList;

    }
}