objects/DebugInfo__c.object
<CustomObject>
    <fields>
        <fullName>DebugData__c</fullName>
        <label>DebugData</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>DebugInfo</label>
    <nameField>
        <displayFormat>DBI-{00000}</displayFormat>
        <label>DebugInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DebugInfo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>Used for Emails</description>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SFFBuploadBatchClass.cls
global class SFFBuploadBatchClass implements 
    Database.Batchable<sObject> {
         private String query; 
        global Integer recordsProcessed = 0;
       global   DebugInfo__c Dinfo=new DebugInfo__c();

        List<task> taskList=new List<task>();
        global SFFBuploadBatchClass(string query){
            this.query = query;
            
        }
        global Database.QueryLocator start(Database.BatchableContext bc) {
                   
         return Database.getQueryLocator(this.query);
        }
        global void execute(Database.BatchableContext bc, List<opportunity> opportunitytobeprocessed){
            SySTem.debug('oppid==');
            
           
            List<Attachment> attList=new List<Attachment>();
            List<opportunity> updateOpp=new List<opportunity>();
        
           List<String> AccountList=new List<String>();
              List<String> oppList=new List<String>();
            for(opportunity opp:opportunitytobeprocessed){
             SySTem.debug('oppid=='+opp.Id);
                AccountList.add(opp.AccountID);
                oppList.add(opp.id);
            }
             Map<String, Object> inputs = new Map<String, Object>();
 			 inputs.put('AccountIDS', AccountList);
            inputs.put('Saleids', oppList);
           
                Flow.Interview.Test_Uploading_to_csv myFlow = 
    		new Flow.Interview.Test_Uploading_to_csv(inputs);
  			myFlow.start();
          
  			
           
            
     
        }
        global void finish(Database.BatchableContext bc){
              
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
         integer cpuTime = Limits.getCpuTime();
            integer Queries = Limits.getQueries();
         
            Dinfo.DebugData__c='Job Name:SFFBuploadBatchClass; Records deleted:'+recordsProcessed;
            insert Dinfo;
        }
}