objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Processor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Processor assigned to form the entity.</inlineHelpText>
        <label>Processor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Entities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Action_Alert__c</fullName>
        <formula>IF(OR( ISPICKVAL( Processing_Stage__c , &apos;Completed&apos;),ISPICKVAL( Processing_Stage__c , &apos;Refunded&apos;),ISPICKVAL( Processing_Stage__c , &apos;N/A&apos;),ISPICKVAL( Processing_Stage__c , &apos;Kitted&apos;),ISPICKVAL( Processing_Stage__c , &apos;Exchanged for Other Services&apos;) ),IMAGE(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;,$Api.Partner_Server_URL_260))+&quot;resource/greenIndicator&quot;, &apos;image&apos;, 20,20),IF(Due_Date__c - TODAY() &gt;= 14, IMAGE(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;,$Api.Partner_Server_URL_260))+&quot;resource/greenIndicator&quot;, &apos;image&apos;, 20,20),  IF(AND(Due_Date__c - TODAY() &lt; 14, Due_Date__c - TODAY() &gt; 0), IMAGE(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;,$Api.Partner_Server_URL_260))+&quot;resource/yellowIndicator&quot;, &apos;image&apos;, 20,20), 
IMAGE(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;,$Api.Partner_Server_URL_260))+&quot;resource/redIndicator&quot;, &apos;image&apos;, 20,20)
) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Action Alert</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Audit_Completed__c</fullName>
        <label>Last QA Audit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity_Organization_State__c</fullName>
        <description>Captures the organization state from entity</description>
        <label>Entity Organization State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Processing_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processor__c</fullName>
        <label>Processor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processors</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <formula>Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Anderson Services</fullName>
                </value>
                <value>
                    <fullName>Annual List</fullName>
                </value>
                <value>
                    <fullName>BK Consult</fullName>
                </value>
                <value>
                    <fullName>Book</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping - Misc</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Tax Form</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Virtual</fullName>
                </value>
                <value>
                    <fullName>Certified Copy</fullName>
                </value>
                <value>
                    <fullName>Change Filings</fullName>
                </value>
                <value>
                    <fullName>Charitable Registration</fullName>
                </value>
                <value>
                    <fullName>Deed</fullName>
                </value>
                <value>
                    <fullName>Dissolution</fullName>
                </value>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Foreign Filings</fullName>
                </value>
                <value>
                    <fullName>Formation</fullName>
                </value>
                <value>
                    <fullName>Informational Only</fullName>
                </value>
                <value>
                    <fullName>IRS Form</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>Pensions</fullName>
                </value>
                <value>
                    <fullName>Pension Termination</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>RA Change</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Strategy Session</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Tax Review</fullName>
                </value>
                <value>
                    <fullName>WPB</fullName>
                    <label>Welcome Phase</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Update_Comments_Utility__c</fullName>
        <label>Update Comments Utility</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Update_Comments__c</fullName>
        <label>Update Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

globalValueSets/Processing_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1023 Consult Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>1023 Drafting</fullName>
    </customValue>
    <customValue>
        <fullName>1023 In Review</fullName>
    </customValue>
    <customValue>
        <fullName>1023 Ready for Review</fullName>
    </customValue>
    <customValue>
        <fullName>1023 - Review Comments</fullName>
    </customValue>
    <customValue>
        <fullName>Admin Dissolved</fullName>
    </customValue>
    <customValue>
        <fullName>Agreement Received</fullName>
    </customValue>
    <customValue>
        <fullName>Agreement Sent</fullName>
    </customValue>
    <customValue>
        <fullName>All Tax Years Not Filed, Please Call</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Assigned</fullName>
    </customValue>
    <customValue>
        <fullName>Assigned to Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Assigned to Tax Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Attempted to Schedule Tax Review</fullName>
    </customValue>
    <customValue>
        <fullName>Attorney Consult Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Audit in Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Back to BCP/Renewal Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Back to CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Back to Formation Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Back to LC</fullName>
    </customValue>
    <customValue>
        <fullName>Back to Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Back to Renewal Advisors/CSC</fullName>
    </customValue>
    <customValue>
        <fullName>Back to VIP Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Back to WPB Team</fullName>
    </customValue>
    <customValue>
        <fullName>BCP Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>BD Complete, awaiting FA &amp; EIN</fullName>
    </customValue>
    <customValue>
        <fullName>Binder Shipped- Back to Processor</fullName>
    </customValue>
    <customValue>
        <fullName>BKG Consult Completed</fullName>
    </customValue>
    <customValue>
        <fullName>BKG Consult Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Bookkeeper Assigned</fullName>
    </customValue>
    <masterLabel>Processing Stages</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Processors.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adrienne Moyte (Community Test)</fullName>
    </customValue>
    <customValue>
        <fullName>Alan Lam</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Phillips</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Phillips (Community Test)</fullName>
    </customValue>
    <customValue>
        <fullName>Amanda Wynalda</fullName>
    </customValue>
    <customValue>
        <fullName>Amina Barraj</fullName>
    </customValue>
    <customValue>
        <fullName>Andrew Nguyen</fullName>
    </customValue>
    <customValue>
        <fullName>Andrew Nguyen (Community Test)</fullName>
    </customValue>
    <customValue>
        <fullName>Ari Vogan</fullName>
    </customValue>
    <customValue>
        <fullName>Benjamin Sacco</fullName>
    </customValue>
    <customValue>
        <fullName>Brittany Rains</fullName>
    </customValue>
    <customValue>
        <fullName>Caleb Nichols</fullName>
    </customValue>
    <customValue>
        <fullName>Carly Coons</fullName>
    </customValue>
    <customValue>
        <fullName>Catherine Hernandez</fullName>
    </customValue>
    <customValue>
        <fullName>Chase Caindec</fullName>
    </customValue>
    <customValue>
        <fullName>Chase Caindec (Community Test)</fullName>
    </customValue>
    <customValue>
        <fullName>Christian Abraham</fullName>
    </customValue>
    <customValue>
        <fullName>Christian Abraham (Community Test)</fullName>
    </customValue>
    <customValue>
        <fullName>Claudette Pendleton</fullName>
    </customValue>
    <customValue>
        <fullName>Crayton Olivieri</fullName>
    </customValue>
    <customValue>
        <fullName>Dalton Luong</fullName>
    </customValue>
    <customValue>
        <fullName>Danielle Dennie</fullName>
    </customValue>
    <customValue>
        <fullName>Deborah Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Deborah Lewis (Community Test)</fullName>
    </customValue>
    <customValue>
        <fullName>Dominique McGhee</fullName>
    </customValue>
    <customValue>
        <fullName>James Morris</fullName>
    </customValue>
    <customValue>
        <fullName>James Morris (Community Test)</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Barkum</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Barkum (Community Test)</fullName>
    </customValue>
    <customValue>
        <fullName>Jasmine Grayson</fullName>
    </customValue>
    <masterLabel>Processors</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/RowController.cls
public class RowController {
    
    @Auraenabled
    public static list<orderItem> fetchOrderItems(Id odrId){
        List<OrderItem> orderItems = [SELECT Id, Audit_Completed__c,action_alert__c,type__c,Entity_Organization_State__c,Processor__c,toLabel(Processing_Stage__c),Service_Name__c,UnitPrice, Quantity,Entity__c,Entity__r.Name,Due_Date__c,Comments__c,Update_Comments__c,Update_Comments_Utility__c FROM OrderItem where orderid =: odrId];
        system.debug('orders: ' + orderItems);
        Schema.DescribeFieldResult F = OrderItem.Processing_Stage__c.getDescribe();
		List<Schema.PicklistEntry> P = F.getPicklistValues();
        for ( Schema.PicklistEntry obj : P ) {
            system.debug('stage label =  '+ obj.getLabel());
        }
        
        for (OrderItem inst : orderItems )
        {
            system.debug('stage =  '+ inst.Processing_Stage__c);
        }
        return orderItems;
    }
    
    @AuraEnabled
    public static List < OrderItem > saveServiceItems(List<OrderItem> serviceItems) {
        system.debug('service items: ' + serviceItems);
        
        Map<String,String> picklistValues = new Map<String,String>();
        Schema.DescribeFieldResult F = OrderItem.Processing_Stage__c.getDescribe();
		List<Schema.PicklistEntry> P = F.getPicklistValues();
        for ( Schema.PicklistEntry obj : P ) {
            picklistValues.put(obj.getLabel(), obj.getValue());
        }
        
        for(OrderItem item : serviceItems){
            item.Update_Comments__c = item.Update_Comments_Utility__c;
            item.Update_Comments_Utility__c = '';
            item.Processing_Stage__c = picklistValues.get( item.Processing_Stage__c );
        }
        try{
            update serviceItems;
        }
        catch(Exception e){
            system.debug(e);
            return null;
        }
        return serviceItems;
    }
    
    @AuraEnabled
    public static boolean insideCommunity(){
        Id siteId = Site.getSiteId();
        if(siteId != Null){
            return true;
        }
        return false;
    }
    
    @AuraEnabled
    public static List < String > getselectOptions(sObject objObject, string fld) {
        List < String > allOpts = new list < String > ();
        Schema.sObjectType objType = objObject.getSObjectType();
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
        
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        allOpts.sort();
        return allOpts;
    }
    
    @AuraEnabled
    public static Map<String,List<String>> getDependentPicklistValues(String typeValue){
         Schema.DescribeFieldResult typeApivalue = OrderItem.Type__c.getDescribe();
        String ApiValofType='';
        for(Schema.PicklistEntry TypeApi : typeApivalue.getPicklistValues()){
            if(TypeApi.getValue()==typeValue){
                ApiValofType=TypeApi.getValue();
                break;
            }
            
        }
        System.debug('ApiValofType'+ApiValofType);
        
        Schema.DescribeFieldResult depend = OrderItem.Processing_Stage__c.getDescribe();
        Schema.sObjectField controlToken = depend.getController();
        
        Schema.DescribeFieldResult control = controlToken.getDescribe();
        List<Schema.PicklistEntry> controlEntries = control.getPicklistValues();
        
        integer valueIndex;
        for(Schema.PicklistEntry centry : controlEntries){
            if(centry.getValue() == ApiValofType){
                System.debug('Reached');
                valueIndex = controlEntries.indexOf(centry);
                break;
            }
        }
        
        String base64map = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
        Map<String,List<String>> dependentPicklistValues = new Map<String,List<String>>();
        
        for (Schema.PicklistEntry entry : depend.getPicklistValues()){ 
            if(entry.isActive() ){
                try{
                    system.debug('entry:' + entry.getLabel());
                    List<String> base64chars = String.valueOf(((Map<String,Object>) JSON.deserializeUntyped( JSON.serialize( entry ) )).get( 'validFor' )).split( '' );
                    system.debug(base64chars.size());
                    system.debug('base: ' + base64chars);
                    String controlValue = controlEntries[ valueIndex ].isActive() ? controlEntries[ valueIndex ].getValue() : null;
                    system.debug('controlValue:' + controlValue );
                    Integer bitIndex = valueIndex / 6, bitShift = 5 - Math.mod( valueIndex, 6 );
                    system.debug('index: ' + bitIndex);
                    if  (controlValue == null || (base64map.indexOf( base64chars[ bitIndex ] ) & (1 << bitShift)) == 0){ 
                        continue;
                    }
                    if ( !dependentPicklistValues.containsKey( controlValue ) )
                    {
                        dependentPicklistValues.put( controlValue, new List<String>() );
                    }
                    dependentPicklistValues.get( controlValue ).add( entry.getLabel() );
                }
                catch(Exception e){
                    system.debug(e);
                }
            }
        }
        
        system.debug('Mapp: ' + dependentPicklistValues);
        return dependentPicklistValues;
    }
}