objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Business_Address__c</fullName>
        <label>Business Address</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Corp HQ</fullName>
                    <label>CAP</label>
                </value>
                <value>
                    <fullName>Client Address</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>RA Address</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_City__c</fullName>
        <label>Business City</label>
        <length>152</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Location__c</fullName>
        <label>Business Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Picklist__c</fullName>
        <label>Mailing Address</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client Address</fullName>
                </value>
                <value>
                    <fullName>Corp HQ</fullName>
                    <default>true</default>
                    <label>CAP</label>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>RA Address</fullName>
                    <isActive>false</isActive>
                    <label>RA Address</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_Address__c</fullName>
        <label>Mailing Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</description>
        <inlineHelpText>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anderson</fullName>
                    <default>true</default>
                    <label>Anderson</label>
                </value>
                <value>
                    <fullName>Client Formed</fullName>
                </value>
                <value>
                    <fullName>Shelf</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registered_Agent_Address__c</fullName>
        <label>Registered Agent Address</label>
        <type>TextArea</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testtrgInsertAddressinEntity.cls
@isTest
private class testtrgInsertAddressinEntity{
 
    @testSetup static void createTestAccount() {
        
        Account acc = new account();
        Acc.name = 'Bobby Apples';
        acc.BillingStreet = '500 Commodore Way';
        acc.BillingCity = 'Las Vegas';
        acc.Billingstate = 'NV';
        acc.BillingPostalCode = '89135';
        insert acc;
        
    }
    
    @isTest public static void createEntityAndTestIt() {
        
        Entities__c ent = new Entities__c();
        ent.Name = 'Address Test Entity';
        ent.Primary_Client__c = [SELECT Id from Account LIMIT 1].id;
        ent.Origin__c = 'Anderson';
        ent.Organization_State__c = 'Alaska';
        ent.Business_Address__c = 'Boss Address';
        ent.Mailing_Address_Picklist__c = 'Boss Address';
        insert ent;
   
        Entities__c entCheck = [SELECT Id, Business_Location__c, Business_City__c,Mailing_Address__c FROM Entities__c];
        
        System.assertEquals('3225 McLeod Dr, Suite 100 Las Vegas, NV 89121', entCheck.Business_Location__c);
        System.assertEquals('Las Vegas',entCheck.Business_City__c);
        System.assertEquals('3225 McLeod Dr, Suite 100 Las Vegas, NV 89121',entCheck.Mailing_Address__c);
        
        ent.Business_Address__c = 'Wyoming';
        ent.Mailing_Address_Picklist__c = 'Wyoming';
        update ent;
        
        Entities__c entCheck2 = [SELECT Id, Business_Location__c, Business_City__c,Mailing_Address__c FROM Entities__c];
        
        System.assertEquals('1718 Capitol Ave. Cheyenne, WY 82001', entCheck2.Business_Location__c);
        System.assertEquals('Cheyenne',entCheck2.Business_City__c);
        System.assertEquals('1718 Capitol Ave. Cheyenne, WY 82001', entCheck2.Mailing_Address__c);
        
        ent.Business_Address__c = 'Client Address';
        ent.Mailing_Address_Picklist__c  = 'Client Address';
        update ent;
        
        Entities__c entCheck3 = [SELECT Id, Business_Location__c, Business_City__c,Mailing_Address__c FROM Entities__c];
        
        System.assertEquals('500 Commodore Way Las Vegas NV 89135', entCheck3.Business_Location__c);
        System.assertEquals('Las Vegas',entCheck3.Business_City__c);
        System.assertEquals('500 Commodore Way Las Vegas NV 89135', entCheck3.Mailing_Address__c);
        
        ent.Mailing_Address_Picklist__c = 'RA Address';
        update ent;
        
        Entities__c entCheck4 = [SELECT Id,Mailing_Address__c,Registered_Agent_Address__c FROM Entities__c];
        System.assertEquals(entcheck4.Registered_Agent_Address__c, entCheck4.Mailing_Address__c);
        
     
    }

}