objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Mailing_Services__c</fullName>
        <description>This field is used to inform users if the client&apos;s entity has mailing services.</description>
        <inlineHelpText>Use this field to select if the client has mail forwarding services!</inlineHelpText>
        <label>Mailing Services</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Assistance Program</fullName>
                    <label>Company Assistance Program</label>
                </value>
                <value>
                    <fullName>Corporate Headquarters</fullName>
                    <label>CAP</label>
                </value>
                <value>
                    <fullName>Mail Forwarding</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nominee_Services__c</fullName>
        <description>This field is for users to select what nominee service this entity is using.</description>
        <inlineHelpText>If you&apos;d like, please select if this entity is using Anderson&apos;s Nominee service!</inlineHelpText>
        <label>Nominee Services</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nominee</fullName>
                </value>
                <value>
                    <fullName>Corp Nom</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organizational_Date__c</fullName>
        <label>Organizational Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registered_Agent_Services__c</fullName>
        <description>To tell us if this entity has registered agent services.</description>
        <inlineHelpText>Please select if this entity is using our registered agent services!</inlineHelpText>
        <label>Registered Agent Services</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>True</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
                <value>
                    <fullName>NWRA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reminder_Email_10__c</fullName>
        <label>Client Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <recordTypes>
        <fullName>Corporation</fullName>
        <active>true</active>
        <description>Corporation</description>
        <label>Corporation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organizational_Date__c</fullName>
        <label>Organizational Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE(
CASE(StageName,
&quot;Closed Won&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Closed Lost&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;Declined-&quot;, &quot;https://andersonadvisors--c.na171.visual.force.com/resource/1473631501000/Exclamation&quot;,
&quot;Converted&quot;, &quot;/servlet/servlet.FileDownload?file=015U00000040BV4&quot;,
&quot;Refund Requested&quot;,&quot;https://andersonadvisors--c.na171.visual.force.com/resource/1593114668000/RefundRequest&quot;,
&quot;/img/samples/flag_yellow.gif&quot;),
&quot;Priority Flag&quot;, 15, 15)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RenewalSaleProcessTest.cls
@isTest
public class RenewalSaleProcessTest {
    Public static List<Entities__c>  updateLLcEnList=new List<Entities__c>();
     Public static List<Entities__c>  updateCorpEnListMailSCAP=new List<Entities__c>();
     Public static List<Entities__c>  updateCorpEnListMailSMailF=new List<Entities__c>();
     Public static Id clientIdLLC;
     Public static Id clientIdCorp;
    public static void getEntities(){
                 TestDatafactoryBulk.createTestData();
        
        for(Entities__c en:TestDatafactoryBulk.EnItemList){
            System.debug('en.RecordType.Name==='+en.RecordTypeId);
            if(en.RecordTypeId=='012U0000000DE8SIAW'){
                 en.Organizational_Date__c=system.today();
            clientIdCorp=en.Primary_Client__c;
            en.Registered_Agent_Services__c='True';
            en.Nominee_Services__c='Nominee';
            en.Mailing_Services__c='Corporate Assistance Program';
            updateCorpEnListMailSCAP.add(en);
            }
           
               if(en.RecordTypeId=='012U0000000DE8mIAG'){
                 en.Organizational_Date__c=system.today();
            clientIdLLC=en.Primary_Client__c;
            en.Registered_Agent_Services__c='True';
            en.Nominee_Services__c='Nominee';
            en.Mailing_Services__c='Corporate Assistance Program';
            updateLLcEnList.add(en);
            }
        }
        
           
    }
        
  @isTest
    public static void TestCorpFlowOrgDateisChangedMailServiceCAP(){
getEntities();
        Test.startTest();
       
        System.debug('updateEn=='+updateCorpEnListMailSCAP.size());
        update updateCorpEnListMailSCAP;
        
      List<opportunity> oplist=[select id,name from opportunity where AccountId=:clientIdCorp and (name ='WY Annual List, Nom' or name ='Corporate Assistance Program Renewal')];
        
       
    System.assertEquals(2, oplist.size(), 'Please check!');
    Test.stopTest();
    }
    @isTest
    public static void TestCorpFlowOrgDateisChangedMailServiceMailForwarding(){

        Test.startTest();
       Id devoppEnCorpTypeId = Schema.SObjectType.entities__c.getRecordTypeInfosByName().get('Corporation').getRecordTypeId();
        Entities__c En = (Entities__c)TestDataFactory.createSObject('Entities__c', new Map<String,Object>{
  'Status__c' =>  'Active',
     'Registered_Agent_Services__c'=>'True',
      'Nominee_Services__c'=>'Nominee',
      'Name'=>'Test En LLC Mail Forwarding',
          'Mailing_Services__c'=>'Mail Forwarding',
          'Reminder_Email_10__c'=>'abc@123.com',
      'Organization_State__c' =>  'Wyoming',
          'RecordTypeID'=>devoppEnCorpTypeId,
  'Primary_Client__c' =>  clientIdCorp      
});
        en.Organizational_Date__c=system.today();
      
       update en;
        
      List<opportunity> oplist=[select id,name from opportunity where AccountId=:clientIdCorp and name ='Mail Forwarding Renewal'];
        
       
    System.assertEquals(1, oplist.size(), 'Please check!');
    Test.stopTest();
    }
      @isTest
    public static void TestLLcFlowOrgDateisChangedMailServiceCAP(){
         Test.startTest();
   getEntities();
    
        update updateLLcEnList;
      List<opportunity> oplist=[select id,name from opportunity where AccountId=:clientIdLLC and name ='WY Annual List, Nom'];
       
    System.assertEquals(1, oplist.size(), 'Please check!');
        Test.stopTest();
    
    }
        @isTest
    public static void TestLLcFlowOrgDateisChangedMailServiceForwarding(){

        Test.startTest();
       Id devoppEnLLCTypeId = Schema.SObjectType.entities__c.getRecordTypeInfosByName().get('Limited Liability Company (LLC)').getRecordTypeId();
        Entities__c En = (Entities__c)TestDataFactory.createSObject('Entities__c', new Map<String,Object>{
  'Status__c' =>  'Active',
     'Registered_Agent_Services__c'=>'True',
      'Nominee_Services__c'=>'Nominee',
      'Name'=>'Test En LLC Mail Forwarding',
          'Mailing_Services__c'=>'Mail Forwarding',
          'Reminder_Email_10__c'=>'abc@123.com',
      'Organization_State__c' =>  'Wyoming',
          'RecordTypeID'=>devoppEnLLCTypeId,
  'Primary_Client__c' =>  clientIdCorp      
});
        en.Organizational_Date__c=system.today();
      
       update en;
        
      List<opportunity> oplist=[select id,name from opportunity where AccountId=:clientIdCorp and name ='Mail Forwarding Renewal'];
        
       
    System.assertEquals(1, oplist.size(), 'Please check!');
    Test.stopTest();
    }
    @isTest
    public static void TestLPFlowOrgDateisChangedMailServiceForwarding(){

        Test.startTest();
       Id devoppEnLPTypeId = Schema.SObjectType.entities__c.getRecordTypeInfosByName().get('Limited Partnership (LP)').getRecordTypeId();
        Entities__c En = (Entities__c)TestDataFactory.createSObject('Entities__c', new Map<String,Object>{
  'Status__c' =>  'Active',
     'Registered_Agent_Services__c'=>'True',
      'Nominee_Services__c'=>'Nominee',
      'Name'=>'Test En LLC Mail Forwarding',
          'Mailing_Services__c'=>'Mail Forwarding',
          'Reminder_Email_10__c'=>'abc@123.com',
      'Organization_State__c' =>  'Wyoming',
          'RecordTypeID'=>devoppEnLPTypeId,
  'Primary_Client__c' =>  clientIdCorp      
});
        en.Organizational_Date__c=system.today();
      
       update en;
        
      List<opportunity> oplist=[select id,name from opportunity where AccountId=:clientIdCorp and name ='Mail Forwarding Renewal'];
        
       
    System.assertEquals(1, oplist.size(), 'Please check!');
    Test.stopTest();
    }
    @isTest
    public static void TestLPFlowOrgDateisChangedMailServiceCap(){

        Test.startTest();
       Id devoppEnLPTypeId = Schema.SObjectType.entities__c.getRecordTypeInfosByName().get('Limited Partnership (LP)').getRecordTypeId();
        Entities__c En = (Entities__c)TestDataFactory.createSObject('Entities__c', new Map<String,Object>{
  'Status__c' =>  'Active',
     'Registered_Agent_Services__c'=>'True',
      'Nominee_Services__c'=>'Nominee',
      'Name'=>'Test En LLC Mail Forwarding',
          'Mailing_Services__c'=>'Corporate Assistance Program',
          'Reminder_Email_10__c'=>'abc@123.com',
      'Organization_State__c' =>  'Wyoming',
          'RecordTypeID'=>devoppEnLPTypeId,
  'Primary_Client__c' =>  clientIdCorp      
});
        en.Organizational_Date__c=system.today();
      
       update en;
        
      List<opportunity> oplist=[select id,name from opportunity where AccountId=:clientIdCorp and  (name ='WY Annual List, Nom' or name ='Corporate Assistance Program Renewal')];
        
       
    System.assertEquals(2, oplist.size(), 'Please check!');
    Test.stopTest();
    }
}