objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Organization_State_1__c</fullName>
        <label>Organization State 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State_2__c</fullName>
        <label>Organization State 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State_3__c</fullName>
        <label>Organization State 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State_4__c</fullName>
        <label>Organization State 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signor_Title_1__c</fullName>
        <label>Signor Title 1</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Signor_Title_2__c</fullName>
        <label>Signor Title 2</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Signor_Title_3__c</fullName>
        <label>Signor Title 3</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Signor_Title_4__c</fullName>
        <label>Signor Title 4</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Signor_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signor Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Signor_of_Entity_Member_1__c</fullName>
        <label>Signor of Entity/Trust Member 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signor_of_Entity_Member_2__c</fullName>
        <label>Signor of Entity/Trust Member 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signor_of_Entity_Member_3__c</fullName>
        <label>Signor of Entity/Trust Member 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signor_of_Entity_Member_4__c</fullName>
        <label>Signor of Entity/Trust Member 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trust_Member_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust Member 1</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Entities (Trust Member 1)</relationshipLabel>
        <relationshipName>Entities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trust_Member_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust Member 2</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Entities (Trust Member 2)</relationshipLabel>
        <relationshipName>Entities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trust_Member_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust Member 3</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Entities (Trust Member 3)</relationshipLabel>
        <relationshipName>Entities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trust_Member_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trust Member 4</label>
        <referenceTo>Trust__c</referenceTo>
        <relationshipLabel>Entities (Trust Member 4)</relationshipLabel>
        <relationshipName>Entities5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trust__c.object
<CustomObject>
    <description>Object to hold Trust information.</description>
    <fields>
        <fullName>First_Trustee_Name__c</fullName>
        <label>First Trustee Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trust</label>
    <nameField>
        <label>Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TrustBinder.cls
public class TrustBinder {
    
    public static void updateTrustMember(List<Entities__c>  listOfEnty,Map<id,Entities__c> listOfoldEntymap) {
              list<Entities__c> LlcInput = new list<Entities__c> ();
        Map <Id,Entities__c> LlcBinderMap;
   
        For(Entities__c Ent :[Select id,Name,Trust_Member_1__c ,Organization_State_1__c,Organization_State_2__c,Organization_State_3__c,Organization_State_4__c,Signor_Update__c ,Trust_Member_1__r.First_Trustee_Name__c,Trust_Member_2__r.First_Trustee_Name__c,Trust_Member_3__r.First_Trustee_Name__c,Trust_Member_4__r.First_Trustee_Name__c,Trust_Member_2__c,Trust_Member_3__c,Trust_Member_4__c,
                              Signor_of_Entity_Member_1__c , Signor_of_Entity_Member_2__c,Signor_of_Entity_Member_3__c,Signor_of_Entity_Member_4__c,
                              Signor_Title_1__c,Signor_Title_2__c,Signor_Title_3__c,Signor_Title_4__c from Entities__c where Id IN :listOfEnty ]){  
   
                                  if(Ent.Signor_Update__c !=listOfoldEntymap.get(Ent.id).Signor_Update__c && Ent.Signor_Update__c == true  ){ 
                                      system.debug('Ent.Signor_Update__c'+ Ent.Signor_Update__c);
                                      system.debug('listOfoldEntymap.get(Ent.id).Signor_Update__c'+ listOfoldEntymap.get(Ent.id).Signor_Update__c);
                                  LlcInput.add(Ent); }
                                    
                                  if (LlcInput.size()>0){
                                      
                                      
        LlcBinderMap = LLcBinderOnEntity.updateEntityLLcBinder(LlcInput);
                                       system.debug('>>>LlcBinderMap'+LlcBinderMap);
                                    Entities__c Enttemp;                                                                                                 
                                  if(!LlcBinderMap.Isempty() && LlcBinderMap.containskey(Ent.id) )
                                  {
                                      system.debug('>>>1st if for LlcBinderMap');
                                   Enttemp =LlcBinderMap.get(Ent.id);
                                  }
                                  else   Enttemp =new Entities__c(id=Ent.id);
                                  
                                      if(Ent.Trust_Member_1__c != listOfoldEntymap.get(Ent.id).Trust_Member_1__c &&  Ent.Trust_Member_1__c != null  ){
                                      Enttemp.Signor_of_Entity_Member_1__c= Ent.Trust_Member_1__r.First_Trustee_Name__c;
                                      Enttemp.Signor_Title_1__c = 'Trustee';
                                             If(Ent.Organization_State_1__c!=null){
                                        
                                              Enttemp.Organization_State_1__c = '';
                                          }
                      
                         }     
                                  
                                  if(Ent.Trust_Member_2__c != listOfoldEntymap.get(Ent.id).Trust_Member_2__c && Ent.Trust_Member_2__c != null ){
                                      Enttemp.Signor_of_Entity_Member_2__c= Ent.Trust_Member_2__r.First_Trustee_Name__c;
                                      Enttemp.Signor_Title_2__c = 'Trustee'; 
                                        If(Ent.Organization_State_2__c!=null){
                                              
                                              Enttemp.Organization_State_2__c = '';
                                          }

                                                                      }  
                                  
                                  if(Ent.Trust_Member_3__c != listOfoldEntymap.get(Ent.id).Trust_Member_3__c && Ent.Trust_Member_3__c != null ){
                                      Enttemp.Signor_of_Entity_Member_3__c= Ent.Trust_Member_3__r.First_Trustee_Name__c;
                                      Enttemp.Signor_Title_3__c = 'Trustee';
                                       If(Ent.Organization_State_3__c!=null){
                                             
                                              Enttemp.Organization_State_3__c = '';
                                          }
                                         
                                  }  
                                  
                                  if(Ent.Trust_Member_4__c != listOfoldEntymap.get(Ent.id).Trust_Member_4__c  && Ent.Trust_Member_4__c != null ){
                                      
                                      Enttemp.Signor_of_Entity_Member_4__c= Ent.Trust_Member_4__r.First_Trustee_Name__c;
                                      Enttemp.Signor_Title_4__c = 'Trustee';
                                       If(Ent.Organization_State_4__c!=null){
                                              
                                              Enttemp.Organization_State_4__c = '';
                                          }
                                       }  
                            
                              LlcBinderMap.put(Ent.id,Enttemp);
                                      system.debug('>>>>LlcBinderMap at last'+LlcBinderMap);
                                                                 
  }
                          
                                  
}
         if(!LlcBinderMap.Isempty()){
           
update LlcBinderMap.values();
            } 
}
}