objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Current_Plan_Year_End__c</fullName>
        <label>Current Plan Year End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pension_Due_Date__c</fullName>
        <label>Pension Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recap_End_Date__c</fullName>
        <formula>IF(  NOT(ISBLANK(Current_Plan_Year_End__c)),

Current_Plan_Year_End__c,


IF( Plan_Adoption_Year__c  &gt;= YEAR(TODAY()),
CASE( MONTH( Year_End__c ),
1,  DATE(Plan_Adoption_Year__c + 1,1,31),
2,  DATE(Plan_Adoption_Year__c + 1,2,28),
3,  DATE(Plan_Adoption_Year__c + 1,3,31),
4,  DATE(Plan_Adoption_Year__c + 1,4,30),
5,  DATE(Plan_Adoption_Year__c + 1,5,31),
6,  DATE(Plan_Adoption_Year__c + 1,6,30),
7,  DATE(Plan_Adoption_Year__c + 1,7,31),
8,  DATE(Plan_Adoption_Year__c + 1,8,31),
9,  DATE(Plan_Adoption_Year__c + 1,9,30),
10, DATE(Plan_Adoption_Year__c + 1,10,31),
11, DATE(Plan_Adoption_Year__c + 1,11,30),
12, DATE(Plan_Adoption_Year__c,12,31),
null),

CASE( MONTH( Year_End__c ),
1,  DATE(IF(MONTH(TODAY()) =1,  YEAR(TODAY()), YEAR(TODAY()) + 1),1,31),
2,  DATE(IF(MONTH(TODAY())&lt;=2,  YEAR(TODAY()), YEAR(TODAY()) + 1),2,28),
3,  DATE(IF(MONTH(TODAY())&lt;=3,  YEAR(TODAY()), YEAR(TODAY()) + 1),3,31),
4,  DATE(IF(MONTH(TODAY())&lt;=4,  YEAR(TODAY()), YEAR(TODAY()) + 1),4,30),
5,  DATE(IF(MONTH(TODAY())&lt;=5,  YEAR(TODAY()), YEAR(TODAY()) + 1),5,31),
6,  DATE(IF(MONTH(TODAY())&lt;=6,  YEAR(TODAY()), YEAR(TODAY()) + 1),6,30),
7,  DATE(IF(MONTH(TODAY())&lt;=7,  YEAR(TODAY()), YEAR(TODAY()) + 1),7,31),
8,  DATE(IF(MONTH(TODAY())&lt;=8,  YEAR(TODAY()), YEAR(TODAY()) + 1),8,31),
9,  DATE(IF(MONTH(TODAY())&lt;=9,  YEAR(TODAY()), YEAR(TODAY()) + 1),9,30),
10, DATE(IF(MONTH(TODAY())&lt;=10, YEAR(TODAY()), YEAR(TODAY()) + 1),10,31),
11, DATE(IF(MONTH(TODAY())&lt;=11, YEAR(TODAY()), YEAR(TODAY()) + 1),11,30),
12, DATE(YEAR(TODAY()),12,31),
null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recap End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Updated_Tax_Year_End__c</fullName>
        <description>A new date Field on Entity for Pension RecordType get the Updated Tax Year-End. It is updated manually</description>
        <label>Updated Tax Year-End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X5500_Due_Date__c</fullName>
        <label>5500 Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year_End_Month__c</fullName>
        <description>Vertiba OnDemand, 7/3/2014, SR-00001758</description>
        <formula>IF(ISBLANK(Updated_Tax_Year_End__c),
CASE(MONTH( Year_End__c ),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;&quot;
),
CASE(MONTH( Updated_Tax_Year_End__c),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;&quot;
))</formula>
        <label>Year End Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_End__c</fullName>
        <label>First Tax Year End</label>
        <type>Date</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EntityTriggerHelper5500Update.cls
/* 
* Author: Muhammad Awais Khan
* Date: 12/Jan/22
* Purpose: Update "Current Plan Year End" field based on "Updated Tax Year-End" when it is changed, 
			and also calculate and update "5500 Due Date"
Change History: Ali Hamza Added check based on trigger context and record type.
*/
public with sharing class EntityTriggerHelper5500Update {
    
    public static boolean helper5500Update(List<Entities__c> newData,Map<Id,Entities__c> oldMap, Boolean insertTrigger,Boolean updateTrigger){
        Boolean ret = true;
        Integer intCurrentYear = date.Today().year() ;
        String currentYear = String.valueOf( intCurrentYear );
        String nextYear = String.valueOf( intCurrentYear + 1 );
        Boolean isLeapYear = Date.isLeapYear( intCurrentYear + 1 );
        Id recordTypeIdPensionPlan =Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
        //context is update and current plan year end change
        //context is update and Tax year end changed is updated
        //Record type check
        for (Entities__c Ent : newData) {
            if(Ent.RecordTypeId == recordTypeIdPensionPlan && 
               ((updateTrigger && oldMap!=null &&( Ent.Current_Plan_Year_End__c != oldMap.get(Ent.Id).Current_Plan_Year_End__c  || Ent.Updated_Tax_Year_End__c != oldMap.get(Ent.Id).Updated_Tax_Year_End__c) )
               || (insertTrigger && (Ent.Year_End__c != null || Ent.Current_Plan_Year_End__c != null || Ent.Updated_Tax_Year_End__c != null) ))
              )
            {
                if( insertTrigger && Ent.Year_End__c == null) { return false; }//First Tax Year End is null
                if(Ent.Year_End_Month__c != null ) {
                    MONTHS selectedMonths = getSelectedMonth(Ent.Year_End_Month__c);
                    system.debug('selectedMonths>'+selectedMonths);
                    Date PensionDueDate= getFormattedPensionDueDate(Ent.Recap_End_Date__c);
                    switch on selectedMonths {
                        when January {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '8/31/'+currentYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = ( Date.isLeapYear( Ent.Recap_End_Date__c.year() ) == true ) ? 
                                    PensionDueDate.addDays(122) : PensionDueDate.addDays(121);
                            }
                        }
                        when February {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '9/30/'+currentYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = PensionDueDate.addDays(123);
                            }
                        }
                        when March {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '10/31/'+currentYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = PensionDueDate.addDays(123);
                             }
                        }
                        when April {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '11/30/'+currentYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = PensionDueDate.addDays(124);
                            }
                        }
                        when May {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '12/31/'+currentYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = PensionDueDate.addDays(123);
                            }
                        }
                        when June {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '1/31/'+nextYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = PensionDueDate.addDays(124);
                            }                    
                        }
                        when July {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  ( isLeapYear == true ) ? date.parse( '02/29/'+nextYear ) : date.parse( '02/28/'+nextYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = PensionDueDate.addDays(123);
                             }
                        }
                        when August {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '3/31/'+nextYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = PensionDueDate.addDays(123);
                            }
                        }
                        when September {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '4/30/'+nextYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = PensionDueDate.addDays(124);
                            }
                        }
                        when October {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '5/31/'+nextYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = ( Date.isLeapYear( Ent.Recap_End_Date__c.year() + 1 ) == true ) ? 
                                    PensionDueDate.addDays(122) : PensionDueDate.addDays(121);
                            }
                        }
                        when November {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '6/30/'+nextYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = ( Date.isLeapYear( Ent.Recap_End_Date__c.year() + 1 ) == true ) ? 
                                    PensionDueDate.addDays(123) : PensionDueDate.addDays(122);
                            }
                        }
                        when December {
                            Ent.X5500_Due_Date__c = (Ent.Current_Plan_Year_End__c == null) ? null :  date.parse( '7/31/'+nextYear );
                            if(Ent.Recap_End_Date__c != null){
                                Ent.Pension_Due_Date__c = ( Date.isLeapYear( Ent.Recap_End_Date__c.year() + 1 ) == true ) ? 
                                    PensionDueDate.addDays(122) : PensionDueDate.addDays(121);
                            }
                        }
                        when else {
                            ret = false;
                        }
                    }
                }
            }
        }
        return ret;
    }
    private enum MONTHS {January, February, March, April,May,June,July,August,September,October,November,December}
    private static MONTHS getSelectedMonth(String CurrentMonth) {
        for (MONTHS m : MONTHS.values()) {
            if (String.valueOf(m) == CurrentMonth) {
                return m;
            }
        }
        return null;
    }
    private static Date getFormattedPensionDueDate(Date recapEndDate)
    {
        Date formattedDate = null;
        try
        {
            formattedDate = Date.newInstance(recapEndDate.year(), recapEndDate.month(), recapEndDate.day());
            return formattedDate;
        }
        catch(Exception ex){}
        return formattedDate;
    }
}