objects/Entities__c.object
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Foreign_Qualifications__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Foreign Qualifications</relationshipLabel>
        <relationshipName>Foreign_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Dist Of Col</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>North Carolina</fullName>
                </value>
                <value>
                    <fullName>North Dakota</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Foreign Qualification</label>
    <nameField>
        <label>Foreign Qualifications Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foreign Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/clsNewForeignQualifications.cls
Public class clsNewForeignQualifications{

    Public Foreign_Qualifications__c objForeignQua {get;set;}
    Public String EntityId;
    Public string retURL;
    Public List<Entities__c> lstEntity;
    Public clsNewForeignQualifications(ApexPages.StandardController controller){
        objForeignQua = new Foreign_Qualifications__c();
        lstEntity = new List<Entities__c> ();
        EntityId = apexPages.CurrentPage().getParameters().get('EntityId');
    }
    
    Public Pagereference Save(){
        if(EntityId != '' && EntityId != null){
            lstEntity = [select id, name from Entities__c where id =: EntityId limit 1];
            
            if(objForeignQua != null){
                objForeignQua.Name =  lstEntity[0].Name +' - ' +objForeignQua.State__c;  
                objForeignQua.Entity__c = lstEntity[0].id;
                insert objForeignQua;
            }
        }
        retURL = '/'+ EntityId;          
        Pagereference P = new Pagereference (retURL);
        P.setRedirect(True);
        return P;
    }
    
    Public Pagereference SaveandNew(){
        if(EntityId != '' && EntityId != null){
            lstEntity = [select id, name from Entities__c where id =: EntityId limit 1];
            
            if(objForeignQua != null){
                objForeignQua.Name =  lstEntity[0].Name +' - ' +objForeignQua.State__c;  
                objForeignQua.Entity__c = lstEntity[0].id;
                insert objForeignQua;
            }
        }
        Pagereference P = new Pagereference ('/apex/CreateNewForeignQualifications?Id='+EntityId);
        P.setRedirect(True);
        return P;
    }
    
    Public Pagereference Cancel(){
    
        retURL = '/'+ EntityId;          
        Pagereference P = new Pagereference (retURL);
        P.setRedirect(True);
        return P;
    
    }
    
    /////////////// Test Method /////////////////
    static testMethod void testPageMethods() {
    
         Entities__c en = new Entities__c();
             en.Name = 'Test';
             insert en;
             
         Foreign_Qualifications__c fq = new Foreign_Qualifications__c();
             fq.Name =  en.Name; 
             fq.State__c = 'Test';
             fq.Entity__c = en.id;
         insert fq ;
         
         apexPages.CurrentPage().getParameters().put('EntityId',en.id); 
         
         ApexPages.StandardController con = new ApexPages.StandardController(fq);
         clsNewForeignQualifications cls = new clsNewForeignQualifications(con);
         cls.Save();
         cls.Cancel();   
         
         Entities__c en1 = new Entities__c();
             en1.Name = 'Test';
             insert en1;
             
         Foreign_Qualifications__c fq1 = new Foreign_Qualifications__c();
             fq1.Name =  en1.Name; 
             fq1.State__c = 'Test';
             fq1.Entity__c = en1.id;
         insert fq1 ;
         
         apexPages.CurrentPage().getParameters().put('EntityId',en1.id); 
         
         ApexPages.StandardController con1 = new ApexPages.StandardController(fq1);
         clsNewForeignQualifications cls1 = new clsNewForeignQualifications(con1);
         cls1.SaveandNew();
        
    
    }
}