objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Business_County__c</fullName>
        <label>Business County</label>
        <length>152</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Registered_Agent_Address__c</fullName>
        <label>Registered Agent Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Registered_Agent_Name__c</fullName>
        <label>Registered Agent Name</label>
        <length>152</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registered_Agent_Services__c</fullName>
        <description>To tell us if this entity has registered agent services.</description>
        <inlineHelpText>Please select if this entity is using our registered agent services!</inlineHelpText>
        <label>Registered Agent Services</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>True</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
                <value>
                    <fullName>NWRA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RA_Address__mdt.object
<CustomObject>
    <description>RA Address on the Entity object</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address</description>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Agent_Name__c</fullName>
        <label>Agent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RA Address</label>
    <pluralLabel>RA Addresses</pluralLabel>
</CustomObject>

classes/Entity_BeforeUpdateHelper.cls
/*********************************
* Author      : Ifrahim Afzal
* Description : Class is invoked on Before update of the Trigger 
                (Process Builder - Entity - Logic Holder)
* Class       : Entity_BeforeUpdateHelper
**********************************/
public class Entity_BeforeUpdateHelper{
    
    public static Final String NWRA= 'NWRA';
    public static List<RA_Address__mdt> raAddress = new List<RA_Address__mdt>();
    public static Map<String,List<Entities__c>> state = new Map<String,List<Entities__c>>();
    
    /*********************************
    * Author      : Ifrahim Afzal
    * Description : Class is invoked on Before update of the Trigger 
                    Criteria : 
                             Registered Agent Services == NWRA
                             Organization State != NULL & State Exist in RA 
    * Function    : populateRA
    **********************************/
   
    public static void populateRA(List<Entities__c> newList, Map<Id, Entities__c> oldMap){
        try{
            List<Entities__c> entityList = new List<Entities__c>();
            
            for(Entities__c et : newList){                          /*Criteria for making a callout*/
                if(et.Registered_Agent_Services__c == NWRA && et.Organization_State__c != NULL && et.Organization_State__c != oldMap.get(et.Id).Organization_State__c){
                    entityList = new List<Entities__c>();
                    if(state.containsKey(et.Organization_State__c)){
                        entityList = state.get(et.Organization_State__c);
                    }
                    entityList.add(et);
                    state.put(et.Organization_State__c,entityList);
                }
            }
            
            if(!entityList.isEmpty()){
                raAddress = [Select Id,State__c,Address__c,Agent_Name__c,County__c from RA_Address__mdt Where State__c IN : state.keySet() Limit 5000];
                if(!raAddress.isEmpty()){
                    for(RA_Address__mdt ra : raAddress){
                        if(state.containsKey(ra.State__c)){
                            for(Entities__c et: state.get(ra.State__c)){
                                et.Registered_Agent_Address__c = ra.Address__c;
                                et.Registered_Agent_Name__c = ra.Agent_Name__c;
                                et.Business_County__c = ra.County__c;
                            }
                        }
                    }
                }
            }
            
        }catch(Exception e){
            System.debug('e'+e.getMessage());
        }
    }
    
}