objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Business_Purpose_2__c</fullName>
        <label>Business Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency Investing</fullName>
                </value>
                <value>
                    <fullName>Flips - Real Estate</fullName>
                </value>
                <value>
                    <fullName>Holding</fullName>
                </value>
                <value>
                    <fullName>Management</fullName>
                </value>
                <value>
                    <fullName>Rentals - Real Estate</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Opportunity Zone</fullName>
                </value>
                <value>
                    <fullName>Nominee Trustee</fullName>
                </value>
                <value>
                    <fullName>Brokerage Accounts Savings</fullName>
                </value>
                <value>
                    <fullName>Short Term Rental</fullName>
                </value>
                <value>
                    <fullName>Long Term Rental</fullName>
                </value>
                <value>
                    <fullName>Personal Residence</fullName>
                </value>
                <value>
                    <fullName>Cryptocurrency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Plan_Year_End__c</fullName>
        <label>Current Plan Year End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FU__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</description>
        <inlineHelpText>Did Anderson create the entity or was it created by an outside firm prior to the client arriving at Anderson?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anderson</fullName>
                    <default>true</default>
                    <label>Anderson</label>
                </value>
                <value>
                    <fullName>Client Formed</fullName>
                </value>
                <value>
                    <fullName>Shelf</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PlanType__c</fullName>
        <label>Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Admin Not Paid</fullName>
                    <isActive>false</isActive>
                    <label>Admin Not Paid</label>
                </value>
                <value>
                    <fullName>Admin Paid</fullName>
                    <isActive>false</isActive>
                    <label>Admin Paid</label>
                </value>
                <value>
                    <fullName>Money Purchase Plan</fullName>
                </value>
                <value>
                    <fullName>Profit Sharing Plan</fullName>
                </value>
                <value>
                    <fullName>ROBS Profit Sharing</fullName>
                </value>
                <value>
                    <fullName>ROBS Solo 401(k)</fullName>
                </value>
                <value>
                    <fullName>Solo 401(k)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Service</fullName>
                </value>
                <value>
                    <fullName>Admin Service</fullName>
                </value>
                <value>
                    <fullName>Prepaid Admin</fullName>
                </value>
                <value>
                    <fullName>Robs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_End__c</fullName>
        <label>First Tax Year End</label>
        <type>Date</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Fu__c</fullName>
        <formula>Entity__r.FU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fu</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization_State__c</fullName>
        <label>Organization State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <formula>TEXT(Entity__r.SLA__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLA</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SLA__c.object
<CustomObject>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Service</fullName>
                </value>
                <value>
                    <fullName>Documents Only</fullName>
                </value>
                <value>
                    <fullName>3rd Party Admin</fullName>
                </value>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SLA</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>SLA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PensionMonthEndCrtNoServSaleTest.cls
@isTest
private class PensionMonthEndCrtNoServSaleTest 
{
    @testSetup
    static void setup()
    {
        Account acc = new Account();
        acc.Name = 'Test Batch 3';
        insert acc;
        Campaign camp = new Campaign();
        camp.Name = 'Pension Renewals';
        camp.Status='planned';
        camp.IsActive=true;
        insert camp;
        
    }
    static testMethod void servMarch()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 03, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 03, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.SLA__c ='No Service';
            myEnt.FU__c = False;
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 05, 31));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    static testMethod void servJanuary()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 01, 20);
            myEnt.Current_Plan_Year_End__c =  date.newInstance(2021, 01, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.SLA__c ='No Service';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 03, 31));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
     static testMethod void servFebruary()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 02, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 02, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.SLA__c ='No Service';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 04, 30));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    static testMethod void servApril()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 04, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 04, 20);
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.Organization_State__c = 'Maine';
            myEnt.SLA__c ='No Service';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 06, 30));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    static testMethod void servMay()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 05, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 05, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.SLA__c ='No Service';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 07, 31));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    static testMethod void servJune()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 06, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 06, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.SLA__c ='No Service';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 08, 31));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    static testMethod void servJulyNextYearIsNotLeapYear()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 08, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 07, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 07, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.SLA__c ='No Service';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 09, 30));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    static testMethod void servJulyNextYearIsLeapYear()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 07, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2023, 07, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.SLA__c ='No Service';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2023, 09, 30));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
     static testMethod void servAugust()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 08, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 08, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 08, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.SLA__c ='No Service';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 10, 31));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
     static testMethod void servSeptember()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 09, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 09, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.SLA__c ='No Service';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 11, 30));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
     static testMethod void servOctober()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 10, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 10, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.SLA__c ='No Service';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 12, 31));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    
    /* static testMethod void testMethod12()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 07, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 07, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.SLA__c ='No Service';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2023, 09, 30));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);
    } */
    static testMethod void servNovember()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 11, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 11, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.SLA__c ='No Service';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 01, 31));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    static testMethod void servDecemberThisYearIsNotLeapYear()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 12, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2021, 12, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.SLA__c ='No Service';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2021, 02, 28));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    static testMethod void servDecemberThisYearIsLeapYear()
    {
        Account acc = [Select id from Account];
        Campaign camp =[Select id from Campaign ];
        List<Entities__c> updateList = new List<Entities__c>();
        Date todayDte = Date.today();
        Date januaryEnd = date.newInstance(2021, 05, 31);
        Integer janLstDay = januaryEnd.day();
        todayDte = januaryEnd;
        for(Integer i=0;i<5;i++)
        {
            Entities__c myEnt = new Entities__c();
            myEnt.Primary_Client__c = acc.id;    
            myEnt.Name = 'Pension - Annual Maintenance';
            myEnt.Origin__c = 'Anderson';
            myEnt.Year_End__c = date.newInstance(2020, 12, 20);
            myEnt.Current_Plan_Year_End__c = date.newInstance(2024, 12, 20);
            myEnt.Organization_State__c = 'Maine';
            myEnt.SLA__c ='No Service';
            myEnt.Business_Purpose_2__c ='Holding';
            myEnt.PlanType__c = 'Money Purchase Plan';
            Date mydate = date.parse('4/24/2021');
            myEnt.Prepaid_SLA_Date__c = mydate;
            myEnt.RecordTypeId = Schema.SObjectType.Entities__c.getRecordTypeInfosByName().get('Pension Plan').getRecordTypeId();
            updateList.add(myEnt);
        }
        insert updateList;
        
        Product2 prod = new Product2(Name = 'Pension - Annual Maintenance',
                                     Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod;
        Product2 prod2 = new Product2(Name = 'Tax Prep, 5500 Return',
                                      Family = '	Pension', Type__c='Renewals', Service_Fulfillment_Weight__c='1');
        insert prod2;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 350, IsActive = true);
        insert standardPrice;
        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod2.Id,
            UnitPrice = 500, IsActive = true);
        insert standardPrice2;
        
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale(Date.newInstance(2024, 02, 29));
        Id batchId = Database.executeBatch(createSale);
        List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
        System.debug('Opportunity'+query);   
        //System.assertEquals(query.size(),20);
        for(Opportunity opp: query)
        {
            System.assertEquals(query.size(), 5);
            
        }
        Test.stopTest();
        /*List<Opportunity> query =[Select id,Name,Entity__c,StageName,RecordType.Name,CloseDate from Opportunity ];
System.debug('Opportunity'+query);   
System.assertEquals(query.size(),15);*/
    }
    static testMethod void emptyConstructor()
    {
        Test.startTest();
        //  BatchableSaleCreationEntity createSale = new BatchableSaleCreationEntity(null);
        PensionMonthEndCrtNoServSale createSale = new PensionMonthEndCrtNoServSale();
        Test.stopTest();
        
    }
}