objects/Entities__c.object
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Renewal_Processing_Conga_Docs__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipName>Renewal_Conga_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conga Merge - Meeting Minutes</label>
    <nameField>
        <label>Renewal Conga Docs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conga Merge - Meeting Minutes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/renProcessCongaCmpController.cls
public class renProcessCongaCmpController {
    
    @AuraEnabled
    public static Renewal_Processing_Conga_Docs__c prepareRenProcConga(Id entityId){
        
        Entities__c currentEnt = [SELECT Id, Name FROM Entities__c WHERE Id = :entityId];
        List<Renewal_Processing_Conga_Docs__c> currentCongas = [SELECT Id FROM Renewal_Processing_Conga_Docs__c WHERE Entity_Name__c = :entityId LIMIT 1];
        List<Renewal_Processing_Conga_Docs__c> congaToSend = new List<Renewal_Processing_Conga_Docs__c>();
        
        if(currentCongas.size() == 1) {
            
            congaToSend.add(currentCongas[0]);            
            
        }
        
        if(currentCongas.size() != 1) {
            
            Renewal_Processing_Conga_Docs__c newConga = new Renewal_Processing_Conga_Docs__c();
            newConga.Name = 'Conga Merge for ' + currentEnt.Name;
            newConga.Entity_Name__c = currentEnt.Id;
            insert newConga;
            congaToSend.add(newConga);
            
        }
        
        
        return congaToSend[0];
    }
    
}