objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Notes__c</fullName>
        <label>Processing Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sale for the entity</description>
        <label>Sale</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the current compliance status of the entity.</description>
        <inlineHelpText>This is the current compliance status of the entity.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Filing</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Future Planned</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
                <value>
                    <fullName>Sent To Processing</fullName>
                </value>
                <value>
                    <fullName>Waiting on Confirmation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE(
CASE(StageName,
&quot;Closed Won&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Closed Lost&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;Declined-&quot;, &quot;https://andersonadvisors--c.na171.visual.force.com/resource/1473631501000/Exclamation&quot;,
&quot;Converted&quot;, &quot;/servlet/servlet.FileDownload?file=015U00000040BV4&quot;,
&quot;Refund Requested&quot;,&quot;https://andersonadvisors--c.na171.visual.force.com/resource/1593114668000/RefundRequest&quot;,
&quot;/img/samples/flag_yellow.gif&quot;),
&quot;Priority Flag&quot;, 15, 15)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Comments__c</fullName>
        <label>Update Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SaleEntity__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entities__c</referenceTo>
        <relationshipLabel>Sale Entities</relationshipLabel>
        <relationshipName>Sale_Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sale Entities</relationshipLabel>
        <relationshipName>Sale_Entities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Opportunity__r.Status__c</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Charitable Remainder Trust</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Deed</fullName>
                </value>
                <value>
                    <fullName>Irrevocable Life Insurance Trust</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company (LLC)</fullName>
                </value>
                <value>
                    <fullName>Limited Partnership (LP)</fullName>
                </value>
                <value>
                    <fullName>Living Trust</fullName>
                </value>
                <value>
                    <fullName>Nominee Other</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Entity</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pension Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sale Entity</label>
    <nameField>
        <label>Sale Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Processing</fullName>
        <active>true</active>
        <description>Processing Task</description>
        <label>Processing</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EntityTriggerHelper.cls
/* 
* Author: Muhammad Awais Khan
* Date: 20/Jan/22
* Purpose: Helper for after insert and update on Entity trigger
*/
public with sharing class EntityTriggerHelper {
    List<String> saleList=new List<String>();
    Map<Id, String> updateMap = new Map<Id, String>();
    List<SaleEntity__c> insertSaleEntity=new List<SaleEntity__c>();
    List<Entities__c> entUpdate = new List<Entities__c>();
    List<task> tsklist=new List<task>();
    List<String> taskEntityList = new List<String>();
    List<String> recordTypeList=new List<String>();
    String oppName='';
    String recordTypeName;
    Integer Stringlength=0;
    
    /**
* After insert function, to create sale entity for the sale selected in entity.
*/
    public Boolean afterEntityInsertEntitySaleCreation( List<Entities__c> newData ){
        
        Set<Id> setIds= new Set<Id>();
        List<Entities__c> newModData = new List<Entities__c>();
        for(Entities__c Ent:newData)  
        {
            if(Ent.Sale__c !=null)
            {
                setIds.add(Ent.Id);
            }
        }
        if(setIds.size()>0)
        {
            newModData = [Select Id, Name, Sale__c, Sale__r.Name, RecordType.Name From Entities__c Where Id IN : setIds Limit 50000];  
        }
        
        for(Entities__c Ent:newModData)  
        {
            if(Ent.Sale__c !=null)
            {
                oppName = Ent.Sale__r.Name;
                if(oppName!='' || oppName!=null){
                    if(oppName.length()>80){
                        Stringlength=oppName.length();
                        if(Stringlength>80){
                            oppName=oppName.substring(0,oppName.length()-(Stringlength-80));   
                        }
                    }
                }
                
                SaleEntity__c sa=new SaleEntity__c(); 
                sa.Name=Ent.Name;    
                sa.Opportunity__c=Ent.Sale__c;    
                sa.Type__c=recordTypeName;  
                sa.Entity__c=Ent.id;
                insertSaleEntity.add(sa);
            }  
        }
        if( insertSaleEntity.size() > 0 ) {
            try
            {
                insert insertSaleEntity;
            }
            catch(Exception ex)
            {
                system.debug('afterEntityInsertEntitySaleCreation Exception>'+ex);
            }
            return true;
        }
        else{
            return false;
        }
    }
    
    /**
* After update function, to copy the Processing Notes from Entity to Task's Update Comments
*/
    public Boolean afterEntityUpdateCopyComments( List<Entities__c> newData, Map<Id, Entities__c> EtNewMap, Map<Id, Entities__c> EtOldMap ){
        for(Entities__c e:newData)
        {
            if(EtOldMap.get(e.Id).Processing_Notes__c != EtNewMap.get(e.Id).Processing_Notes__c){
                taskEntityList.add(e.Id);
            }
        }
        
        for( Entities__c eee: [SELECT Id,Name,Status__c,Processing_Notes__c,Primary_Client__c FROM Entities__c where Id In :taskEntityList] )  
        {  
            updateMap.put(eee.Id,eee.Processing_Notes__c);  
        }
        List<task> tkList = new List<task>();
        if(!Test.isRunningTest()){
            tkList=[SELECT Id, Subject,OwnerId, Status,WhatId,Name_of_Entity__c,Update_Comments__c,Related_Entity__c  FROM Task where (whatId In :taskEntityList or Related_Entity__c IN :taskEntityList ) and RecordTypeId='0120B000000t7pp' and status!='Completed'];  
        }
        // To provide test coverage
        else {
            task fakeTask = new task(Status = 'Send to Processing', Update_Comments__c = 'Send to Processing ');
            tkList.add(fakeTask);
        }
        
        for(task t:tkList)  
        {
            if(t.Update_Comments__c !=' '&& t.Update_Comments__c != null)  
            {  
                if(updateMap.containsKey(t.WhatId)){
                    t.Update_Comments__c= updateMap.get(t.WhatId); 
                }
                else{
                    t.Update_Comments__c= updateMap.get(t.Related_Entity__c ); 
                }
            }
        } 
        if( !Test.isRunningTest() && tkList.size() > 0 ) {
            update tkList;
            return true;
        }
        else{ return false; }
    }
}