objects/Entities__c.object
<CustomObject>
    <fields>
        <fullName>Case_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Primary_Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ChangeEntityOwner.cls
public class ChangeEntityOwner {
	public static void CEOAfterUpdate(Map<id,Case> newMap) {

		List<Entities__c> EnList = [Select id,Case_Owner__c,Case__c from Entities__c where Case__c IN :newMap.KeySet()];
		List<Entities__c> EnUpdate = new List<Entities__c>();
		for(Entities__c e: EnList){
			Case c = newMap.get(e.Case__c); 
			if(c!=null){
				if(e.Case_Owner__c != c.OwnerId){
					e.Case_Owner__c = c.OwnerId;
					EnUpdate.add(e);
				}
			}
		}
		update EnUpdate;
	}
}