objects/Escalation__c.object
<CustomObject>
    <fields>
        <fullName>All_Services_Status__c</fullName>
        <label>All Services Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Step 1 - Supervisor</fullName>
                </value>
                <value>
                    <fullName>Step 2 - Manager</fullName>
                </value>
                <value>
                    <fullName>Step 3 - CEO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Created_by_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created by Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accounting Coordinators</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Advisor</fullName>
                </value>
                <value>
                    <fullName>Advisor Support Specialist</fullName>
                </value>
                <value>
                    <fullName>BCP</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping</fullName>
                </value>
                <value>
                    <fullName>Client Success Coordinator Admin</fullName>
                </value>
                <value>
                    <fullName>Law Coordinator</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Renewals</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalation_Reason__c</fullName>
        <label>Escalation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Roles Missing or Incorrect</fullName>
                </value>
                <value>
                    <fullName>Advisor note not Entered/Updated into the Client Strategy</fullName>
                </value>
                <value>
                    <fullName>Agreement is not legible</fullName>
                </value>
                <value>
                    <fullName>Agreement Not Entered Into Box</fullName>
                </value>
                <value>
                    <fullName>Agreement Not Redacted</fullName>
                </value>
                <value>
                    <fullName>Agreement not Removed from Sale</fullName>
                </value>
                <value>
                    <fullName>Case Description Not Updated</fullName>
                </value>
                <value>
                    <fullName>Case not updated or updated Incorrectly</fullName>
                </value>
                <value>
                    <fullName>Client complaining about turn around time</fullName>
                </value>
                <value>
                    <fullName>Client Information not updated</fullName>
                </value>
                <value>
                    <fullName>Client not contacted upon submission of docs</fullName>
                </value>
                <value>
                    <fullName>Client Platinum View not Updated</fullName>
                </value>
                <value>
                    <fullName>Client Strategy not Filled Out</fullName>
                </value>
                <value>
                    <fullName>Discount not Approved by Management</fullName>
                </value>
                <value>
                    <fullName>Entity Page Not Updated</fullName>
                </value>
                <value>
                    <fullName>Error on return</fullName>
                </value>
                <value>
                    <fullName>First Contact SOP Not Being Followed</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Missing or Incorrect Docs in Box</fullName>
                </value>
                <value>
                    <fullName>Missing or Incorrect Sale Campaign Name</fullName>
                </value>
                <value>
                    <fullName>Missing or Incorrect Service Items</fullName>
                </value>
                <value>
                    <fullName>Missing or Wrong Sale Entity Associated w/ Sale</fullName>
                </value>
                <value>
                    <fullName>Missing Payment Plan</fullName>
                </value>
                <value>
                    <fullName>No Blueprint Created w/in 2 days of Sale</fullName>
                </value>
                <value>
                    <fullName>No Follow Up on Task</fullName>
                </value>
                <value>
                    <fullName>No Follow Up Task Created</fullName>
                </value>
                <value>
                    <fullName>No Monthly Follow Up on Living Trust</fullName>
                </value>
                <value>
                    <fullName>No Sales Rep or Incorrect Sales Rep</fullName>
                </value>
                <value>
                    <fullName>No Temp Structure in Box</fullName>
                </value>
                <value>
                    <fullName>No Weekly  Follow Up on Service Items</fullName>
                </value>
                <value>
                    <fullName>Welcome Call SOP Not Being Followed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalation_Status__c</fullName>
        <inlineHelpText>Used by Supervisors to track the progress of resolving escalations.</inlineHelpText>
        <label>Escalation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Person_Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Escalations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Case_Escalation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Escalations</relationshipLabel>
        <relationshipName>Escalations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Escalations</relationshipLabel>
        <relationshipName>Escalations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Link__c</fullName>
        <label>Task Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Escalation</label>
    <nameField>
        <displayFormat>Escalation-{00000}</displayFormat>
        <label>Escalation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <recordTypes>
        <fullName>Bookkeeping</fullName>
        <active>true</active>
        <description>Task For Bookkeeping</description>
        <label>Bookkeeping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Call</fullName>
        <active>true</active>
        <description>Used for Calls.</description>
        <label>Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>Used for Emails</description>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <description>Tax Task</description>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TasksEscaltionClass.cls
global class TasksEscaltionClass implements 
    Database.Batchable<sObject>, Database.Stateful {
         private String query; 
        global Integer recordsProcessed = 0;
List<Escalation__c> WcEscaltions= new   List<Escalation__c>();
        
        List<task> taskList=new List<task>();
        global TasksEscaltionClass(string query){
            this.query = query;
            
        }
        global Database.QueryLocator start(Database.BatchableContext bc) {
                   
         return Database.getQueryLocator(this.query);
        }
        global void execute(Database.BatchableContext bc, List<task> tasktobeprocessed){
            
            
            for(task t:tasktobeprocessed){
                Escalation__c e= new Escalation__c();
                ID profileID=[Select id,Name from Profile where name ='Partner Community User'].id;
                e.Task_Link__c=t.id;
             List< User> ActiveUSer=[select id,isActive,Title,name from user where id=:t.OwnerId and isActive=True and Profileid!=:profileID limit 1];
                if(ActiveUSer.size()>0){
                       If(ActiveUSer[0].isActive){
                           if(ActiveUSer[0].Title!=null){
                                  if(ActiveUSer[0].Title=='Accounting Coordinator'){
                 		e.Department__c='Accounting Coordinators';       
                    }else if(ActiveUSer[0].Title.contains('Advisor Admin')){
                        e.Department__c='Admin';
                    }else if(ActiveUSer[0].Title.contains('Bookkeeper')|| ActiveUSer[0].Title.contains('Bookkeeping')){
                         e.Department__c='Bookkeeping';
                    }else if(ActiveUSer[0].Title=='Client Account Manager'){
                        e.Department__c='CAM';
                    }else if(ActiveUSer[0].Title.contains('Client Success Coordinator')){
                        e.Department__c='Client Success Coordinator Admin';
                    }else if(ActiveUSer[0].Title.contains('Law Coordinator')){
                        e.Department__c='Client Success Coordinator Admin';  }
                      else if(ActiveUSer[0].Title.contains('Tax')){
                          e.Department__c='Tax';
                    }else if(ActiveUSer[0].Title.contains('(BCP)') ){
                         e.Department__c='BCP';
                    }else if(ActiveUSer[0].Title.contains('Advisor Support Specialist') ){
                         e.Department__c='Advisor Support Specialist';
                    }
                    
                 
                }	
                           }
                 
                }
             
                e.Created_by_Automation__c=true;
                e.Escalation_Reason__c='Welcome Call SOP Not Being Followed';
                e.Related_Case_Escalation__c=t.WhatId;
                e.Related_Client__c=t.Client__c;
                e.Person_Responsible__c=t.OwnerId;
                e.Escalation_Status__c='Not Started';
                e.All_Services_Status__c='Step 1 - Supervisor';
                WcEscaltions.add(e);
				recordsProcessed=recordsProcessed+1;
             
            }
              try { 
             If(WcEscaltions.size()>0){ 
                 	recordsProcessed=recordsProcessed+1;
              upsert WcEscaltions;
     
             }
                  
             
         } catch (Exception ex) { 
         	System.Debug('Insert failed ' + ex);
         } 
       
          
            
            
            
          
        }
        global void finish(Database.BatchableContext bc){
               System.debug(recordsProcessed + ' records processed.');
           System.debug(WcEscaltions.size() + ' records size.');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
         integer cpuTime = Limits.getCpuTime();
            integer Queries = Limits.getQueries();
            system.debug('CPU Time: '+cpuTime);
            system.debug('Queries: '+Queries);
        }
}