objects/H2S__HarvestProject__c.object
<CustomObject>
    <description>HarvestSync for Salesforce - Project object used by the HarvestSync for Salesforce system integration when client does not already have a custom object for managing projects.</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <formula>H2S__Account__r.Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H2S__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>H2S__BurnPercent__c</fullName>
        <formula>if( H2S__TotalProjectHours__c &gt;0, H2S__TotalTime__c /  H2S__TotalProjectHours__c ,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Time Logged / Total Hour Budget</inlineHelpText>
        <label>Burn %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>H2S__HarvestProjectID__c</fullName>
        <description>Harvest&apos;s Unique ID for the Harvest Project. This value can retrieved from the the URL of Harvest&apos;s Project screen.</description>
        <externalId>true</externalId>
        <inlineHelpText>Harvest&apos;s Unique ID for the Harvest Project. This value can retrieved from the the URL of Harvest&apos;s Project screen.</inlineHelpText>
        <label>Harvest Project ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>H2S__ProjectCode__c</fullName>
        <displayFormat>PID-{0}</displayFormat>
        <inlineHelpText>Auto-assigned project ID.  Used to sync to Harvest.</inlineHelpText>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_Return__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax Returns</relationshipLabel>
        <relationshipName>Tax_Returns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax Return</label>
    <nameField>
        <displayFormat>TAX-{00000}</displayFormat>
        <label>Tax Return Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProjectRelatedListTax.cls
public class ProjectRelatedListTax {
    @AuraEnabled(cacheable=true)
    public static list <H2S__HarvestProject__c>  Getprojectbyid (String taxid){
        system.debug('::value a '+taxid);
        Tax_Return__c Taxret =[select id ,Client__c from Tax_Return__c where Id=:taxid];
        Id a=Taxret.Client__c;
        system.debug('::value a '+a);
        list<H2S__HarvestProject__c> Harvestpkg = [select id,name,Account_ID__c, H2S__BurnPercent__c ,H2S__ProjectCode__c,H2S__HarvestProjectID__c,H2S__Account__c  from H2S__HarvestProject__c where H2S__Account__c =:a];
        system.debug(Harvestpkg);
        return Harvestpkg;
    }
}