objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Article_category_type__c</fullName>
        <label>Article category type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Forms</fullName>
                </value>
                <value>
                    <fullName>Videos</fullName>
                </value>
                <value>
                    <fullName>Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Knowledge_Video_Link__c</fullName>
        <inlineHelpText>You can upload Knowledge article link, video link, box video link and google drive link</inlineHelpText>
        <label>Knowledge Link (Video/Document/Form)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Knowledge_video_FAQ_category__c</fullName>
        <description>Field add under the FAQ Section</description>
        <label>Knowledge video FAQ category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Knowledge_video_category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Entity Structuring</fullName>
                </value>
                <value>
                    <fullName>Estate Planning</fullName>
                </value>
                <value>
                    <fullName>Asset Protection</fullName>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Business Strategies</fullName>
                </value>
                <value>
                    <fullName>Business Formalities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Knowledge_video_category__c</fullName>
        <label>Knowledge video category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Article_category_type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Courses</fullName>
                </value>
                <value>
                    <fullName>FAQs</fullName>
                </value>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Stock Trading</fullName>
                </value>
                <value>
                    <fullName>Tax Strategies</fullName>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                </value>
                <value>
                    <fullName>Entrepreneurship</fullName>
                </value>
                <value>
                    <fullName>Past Webinars</fullName>
                </value>
                <value>
                    <fullName>Tax Tuesday</fullName>
                </value>
                <value>
                    <fullName>Podcasts</fullName>
                </value>
                <value>
                    <fullName>Espanol</fullName>
                </value>
                <value>
                    <fullName>Coffee with Carl</fullName>
                </value>
                <value>
                    <fullName>Toni Talks</fullName>
                </value>
                <value>
                    <fullName>Tax Tuesday Q &amp; A</fullName>
                    <isActive>false</isActive>
                    <label>Tax Tuesday Q &amp; A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

classes/VideosArticle.cls
/** A Rest webservice class is used to show the Video Article.
* @author Deepesh Kumar
* @version 1.0 - 5 Apr, 2020
*/
@RestResource(urlmapping='/VideosArticle/*')
global class VideosArticle {  
    @HttpGet
    global static List<knowledge__kav> getVideosArticles()
    {
        List<Knowledge__kav> finalList = new List<Knowledge__kav>();
        RestResponse res=RestContext.response;
        RestRequest req=RestContext.request;
        List<Knowledge__kav> videoarticleLists = [SELECT Id, Title,Knowledge_video_category__c,Article_category_type__c,Knowledge_Video_Link__c,Summary,Upload_File__Name__s FROM Knowledge__kav WHERE Knowledge_video_category__c != 'FAQs' AND Knowledge_Video_Category__c != NULL AND Knowledge_Video_Category__c != 'Tax Tuesday Q & A'];
        List<Knowledge__kav> FaqvideoarticlesList= [SELECT Id, Title,Knowledge_video_category__c,Article_category_type__c,Knowledge_video_FAQ_category__c,Knowledge_Video_Link__c,Summary,Upload_File__Name__s FROM Knowledge__kav WHERE Knowledge_video_category__c = 'FAQs'];
 		
        finalList.addAll(videoarticleLists);
        finalList.addAll(FaqvideoarticlesList);
        
        List<String> videoPickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Knowledge__kav.Knowledge_video_category__c.getDescribe();         
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            videoPickListValuesList.add(pickListVal.getLabel()); 
        }
        
        List<String> faqPickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResultFaq = Knowledge__kav.Knowledge_video_FAQ_category__c.getDescribe();         
        List<Schema.PicklistEntry> ple2 = fieldResultFaq.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple2){
            faqPickListValuesList.add(pickListVal.getLabel()); 
        }
        Set<String> videoFoldersInQuery = new Set<String>();
        Set<String> faqFoldersInQuery = new Set<String>();
        for(Knowledge__kav video : videoarticleLists ){
            videoFoldersInQuery.add(video.Knowledge_video_category__c);
        }
        
        for(Knowledge__kav video : FaqvideoarticlesList ){
            faqFoldersInQuery.add(video.Knowledge_video_FAQ_category__c);
        }

        for(String folderName : videoPickListValuesList){
            if(!videoFoldersInQuery.contains(folderName)){
                knowledge__kav knw = new knowledge__kav(Knowledge_video_category__c = folderName);
                finalList.add(knw);
         	}
        }
        for(String folderName : faqPickListValuesList){
            if(!faqFoldersInQuery.contains(folderName)){
                knowledge__kav knw = new knowledge__kav(Knowledge_video_category__c = 'FAQs', Knowledge_video_FAQ_category__c = folderName);
                finalList.add(knw);
            }
         }
		return finalList;
    }
}