objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>Sales_Rep__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spouse_E_Mail__c</fullName>
        <label>Spouse E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Spouse_Mobile__c</fullName>
        <label>Spouse Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Total_Income__c</fullName>
        <formula>X1099_Income__c  +   Dividend_Income__c  +  Investment_Income__c  +  Stock_Income__c  +  W_2_Income__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <label>Sales Rep</label>
    <nameField>
        <label>Sales Rep&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ctrlLeadRelatedList.cls
public class ctrlLeadRelatedList{
    public List<Lead> lstLead{get; set;}
    public string SalesRepid {get; set;}
    public string LeadId {get; set;}
    
   public ctrlLeadRelatedList(ApexPages.StandardController controller) {
        lstLead= new List<Lead>();
        SalesRepid = Apexpages.currentpage().getParameters().get('id');
        Set<Id> leadid = new Set<Id>();
        if(SalesRepid != null){
            lstLead = [select id,Name,Company,Total_Income__c,Email,Mobile_Number__c,Spouse_E_Mail__c,Spouse_Mobile__c from Lead where Sales_Rep__c =:SalesRepid];
        }
    }
 
}