objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Card_Month__c</fullName>
        <label>Card Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Year__c</fullName>
        <label>Card Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Number__c</fullName>
        <inlineHelpText>Please enter the complete credit card number without spaces or dashes</inlineHelpText>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <businessProcess>Asset Protection</businessProcess>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CreditCardInfo.cls
public class CreditCardInfo {

    public static boolean alreadyProcessed = false;
    
    public static void processOpp(List<Opportunity> newList) {
        
        system.debug('Inside credit card info class');
        if (alreadyProcessed == true) return;
        alreadyProcessed = true;
        
        system.debug('After static boolean');
        List<Opportunity> updateList = new List<Opportunity>();
        
        for (Opportunity opp : newList) {
            
            if ( opp.Card_Number__c == null && opp.ChargentSFA__Card_Number__c != null ) {
                
				system.debug('Inside record update section');
                opp.Card_Number__c   = opp.ChargentSFA__Card_Number__c;
                opp.Card_Month__c    = opp.ChargentSFA__Card_Month__c;
                opp.Card_Year__c     = opp.ChargentSFA__Card_Year__c;
      
            }
        }
       
    }
    
}