objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Pension_Due_Date_2__c</fullName>
        <label>Pension Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year_End_Month__c</fullName>
        <formula>Entity__r.Year_End_Month__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year End Month</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Pension_Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <description>Used for pension renewals.</description>
        <label>Pension Renewal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ManualPensionRenewalsLateFee300.cls
global class ManualPensionRenewalsLateFee300 implements Schedulable 
{
     global void execute(SchedulableContext sc) 
     {
        
         Id batchJobId1 = Database.executeBatch(new PensionRenewalsLateFee300('SELECT id,name,year_end_month__c, StageName, Pension_Due_Date_2__c FROM Opportunity WHERE RecordType.DeveloperName=\'Pension_Renewal\' AND (StageName=\'Qualification\' OR StageName=\'Fulfillment/Partial Payment\') AND Pension_Due_Date_2__c!=NULL AND Year_End_Month__c!=NULL',Date.today()), 25);
         System.debug('Batch1--'+batchJobId1);
         
     }

}