objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>210</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Transaction_Count__c</fullName>
        <label>Transaction Count</label>
        <summaryForeignKey>ChargentSFA__Transaction__c.ChargentSFA__Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Standard_Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <label>Standard Renewal</label>
    </recordTypes>
    <recordTypes>
        <fullName>State_Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <label>State Renewal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SFFbuploadBatchCall.cls
global class SFFbuploadBatchCall implements Schedulable {
    global void execute(SchedulableContext sc) {
     
        Id StandardrenewalRecordId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Standard_Renewal').getRecordTypeId();

        Id StaterenewalRecordId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('State_Renewal').getRecordTypeId();
        string taskQuery='';
        if(!Test.isRunningTest()){
            taskQuery='select id, name, AccountID, Billing_City__c, ChargentSFA__Billing_City__c from opportunity where stageName=\'Closed won\' and Name!=\'Platinum Subscription\' and closeDate=Today AND ChargentSFA__Transaction_Count__c > 0 and RecordType.Name = \'Entity Formation\'  and RecordType.Name != \'Pension Renewal\'and RecordTypeID !=\''+StandardrenewalRecordId+'\' and RecordTypeID !=\''+StaterenewalRecordId+'\' '; 
        }else{
            taskQuery='select id, name, AccountID, Billing_City__c, ChargentSFA__Billing_City__c from opportunity where stageName=\'Closed won\' and Name!=\'Platinum Subscription\' and closeDate=Today AND ChargentSFA__Transaction_Count__c > 0 and RecordType.Name = \'Entity Formation\'  and RecordType.Name != \'Pension Renewal\'and RecordTypeID !=\''+StandardrenewalRecordId+'\' and RecordTypeID !=\''+StaterenewalRecordId+'\' Limit 10';
        }
        
         
         Id batchJobId1;
          if(!Test.isRunningTest()){
          batchJobId1 = Database.executeBatch(new SFFBuploadBatchClass(taskQuery), 5);
         }else{
             batchJobId1 = Database.executeBatch(new SFFBuploadBatchClass(taskQuery), 200);
         }
      
    }
}