objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Entity_Type__c</fullName>
        <label>Product Entity Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>BOSS</fullName>
                </value>
                <value>
                    <fullName>Business Credit</fullName>
                </value>
                <value>
                    <fullName>C-Corp</fullName>
                </value>
                <value>
                    <fullName>Corp</fullName>
                </value>
                <value>
                    <fullName>Corp Headquarters</fullName>
                </value>
                <value>
                    <fullName>Deed Preparation</fullName>
                </value>
                <value>
                    <fullName>Document Drafting</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Irrevocable Trust</fullName>
                </value>
                <value>
                    <fullName>Joint Venture LLC</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>LIST00</fullName>
                </value>
                <value>
                    <fullName>Living Trust</fullName>
                </value>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>Mail Forwarding</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Pension</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Registered Agent Fee</fullName>
                </value>
                <value>
                    <fullName>Resident Agent</fullName>
                </value>
                <value>
                    <fullName>S-Corp</fullName>
                </value>
                <value>
                    <fullName>Series LLC</fullName>
                </value>
                <value>
                    <fullName>Titanium</fullName>
                </value>
                <value>
                    <fullName>Unlimited LLC</fullName>
                </value>
                <value>
                    <fullName>Unlimited LLC Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Valley</fullName>
                </value>
                <value>
                    <fullName>Vertucci Fulfillment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EditAll.cls
public with sharing class EditAll {
	ID oppyID;
	public List<OpportunityLineItem> lstOppyLineItems {get;set;}
	public EditAll(){
		oppyID = ApexPages.currentPage().getParameters().get('oppyID');
		lstOppyLineItems = [Select o.UnitPrice, o.Quantity,o.ServiceDate,o.TotalPrice, o.ListPrice, o.Id,  o.Description,o.PricebookEntry.Product2.Name,o.PricebookEntry.Product2.ProductCode,o.PricebookEntry.Product2.Family, o.PricebookEntry.Product2.Entity_Type__c 
							From OpportunityLineItem o 
							where OpportunityId = :oppyID
							order by Product_Family__c, Product_Entity_Type__c, UnitPrice desc];
	}
	public void save(){
		update lstOppyLineItems;
	}
	public PageReference cancel(){
		PageReference pageRef = new PageReference('/' + oppyID);
        pageRef.setRedirect(true);
        return pageRef;
	}
	public PageReference saveClose(){
		save();
		PageReference pageRef = new PageReference('/' + oppyID);
        pageRef.setRedirect(true);
        return pageRef;
	}
}