objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ChargentSFA__Card_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Number__c</fullName>
        <inlineHelpText>Please enter the complete credit card number without spaces or dashes</inlineHelpText>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ChargentSFA__Card_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/testCardInfo.cls
@isTest
public class testCardInfo {

  
    static testMethod void testOpp() {
        
        Opportunity opp=new opportunity();
        opp.name = 'Test Name';
        opp.StageName = 'Qualification';
        opp.CloseDate = system.today();
        opp.ChargentSFA__Card_Number__c = '4147000011112222';
        opp.ChargentSFA__Card_Month__c = '02';
        opp.ChargentSFA__Card_Year__c = '2028';
            
        insert opp;    
        update opp;   
    }
    
    
}