objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Anderson Services</fullName>
                </value>
                <value>
                    <fullName>Annual List</fullName>
                </value>
                <value>
                    <fullName>BK Consult</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping - Misc</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Tax Form</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Virtual</fullName>
                </value>
                <value>
                    <fullName>Certified Copy</fullName>
                </value>
                <value>
                    <fullName>Charitable Registration</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Corp Formation</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Deed</fullName>
                </value>
                <value>
                    <fullName>Dissolution</fullName>
                </value>
                <value>
                    <fullName>Doc Drafting</fullName>
                </value>
                <value>
                    <fullName>Estate</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Foreign Filing</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                </value>
                <value>
                    <fullName>Informational Only</fullName>
                </value>
                <value>
                    <fullName>IRS Form</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>LLC Formation</fullName>
                </value>
                <value>
                    <fullName>LP Formation</fullName>
                </value>
                <value>
                    <fullName>Meeting Minutes</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Formation</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>Pensions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SaleEntity__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sale Entities</relationshipLabel>
        <relationshipName>Sale_Entities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organizational_State__c</fullName>
        <formula>text(Entity__r.Organization_State__c)</formula>
        <label>Organizational State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Charitable Remainder Trust</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Deed</fullName>
                </value>
                <value>
                    <fullName>Irrevocable Life Insurance Trust</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company (LLC)</fullName>
                </value>
                <value>
                    <fullName>Limited Partnership (LP)</fullName>
                </value>
                <value>
                    <fullName>Living Trust</fullName>
                </value>
                <value>
                    <fullName>Nominee Other</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Entity</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pension Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sale Entity</label>
    <nameField>
        <label>Sale Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/unlimitedNomineeWYNV.cls
public class unlimitedNomineeWYNV implements Schedulable{
    public void execute(SchedulableContext sc)
    {
        nomineeRenewal();
    }
    
    public void nomineeRenewal(){
        
        Map<Id, Opportunity> capRenewals = new Map<Id, Opportunity>([SELECT Id FROM Opportunity WHERE Amount = 1092 AND StageName = 'Qualification' AND 
                                                                     RecordType.Name LIKE '%Renewal%' AND Id IN (SELECT Opportunity__c 
                                                                                                                 FROM SaleEntity__c 
                                                                                                                 WHERE (Type__c = 'Corporation' AND Organizational_State__c = 'Wyoming') 
                                                                                                                 OR Organizational_State__c = 'Nevada')]);
        
        Map<Id, Account> capClients = new Map<Id, Account>([SELECT Id FROM Account WHERE Id IN (SELECT AccountId FROM Opportunity WHERE Id =:capRenewals.keySet())]);
        
        List<OpportunityLineItem> newNomRenewals = new List<OpportunityLineItem>([Select Id FROM OpportunityLineItem WHERE Opportunity.StageName = 'Qualification' 
                                                                                  AND Opportunity.AccountId =: capClients.keySet() AND Opportunity.Name != 'Corporate Assistance Program Renewal' 
                                                                                  AND Product2.Name = 'Nominee Service Annual Renewal' AND CreatedDate = TODAY AND UnitPrice > 0 
                                                                                  AND OpportunityId IN (SELECT Opportunity__c 
                                                                                                        FROM SaleEntity__c 
                                                                                                        WHERE (Type__c = 'Corporation' AND Organizational_State__c = 'Wyoming') 
                                                                                                        OR Organizational_State__c = 'Nevada')
                                                                                 ]);
        
        if(!newNomRenewals.isEmpty()) {

            for(OpportunityLineItem oppLI : newNomRenewals){
                oppLI.UnitPrice = 0;              
            }
            
            update newNomRenewals;
        }
        
    }
}