objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Service_Fulfillment_Weight__c</fullName>
        <inlineHelpText>Measurement of fulfillment difficulty</inlineHelpText>
        <label>Service Fulfillment Weight</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Anderson Services</fullName>
                </value>
                <value>
                    <fullName>Annual List</fullName>
                </value>
                <value>
                    <fullName>BK Consult</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping - Misc</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Tax Form</fullName>
                </value>
                <value>
                    <fullName>Bookkeeping Virtual</fullName>
                </value>
                <value>
                    <fullName>Certified Copy</fullName>
                </value>
                <value>
                    <fullName>Charitable Registration</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Corp Formation</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Deed</fullName>
                </value>
                <value>
                    <fullName>Dissolution</fullName>
                </value>
                <value>
                    <fullName>Doc Drafting</fullName>
                </value>
                <value>
                    <fullName>Estate</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Foreign Filing</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                </value>
                <value>
                    <fullName>Informational Only</fullName>
                </value>
                <value>
                    <fullName>IRS Form</fullName>
                </value>
                <value>
                    <fullName>Land Trust</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>LLC Formation</fullName>
                </value>
                <value>
                    <fullName>LP Formation</fullName>
                </value>
                <value>
                    <fullName>Meeting Minutes</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Formation</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>Pensions</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityLineItemInsertHandlerTest.cls
@isTest (seeALLData = false)
public class OpportunityLineItemInsertHandlerTest {
    @testSetup
    public static void setupTestData(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        Opportunity Opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId = acc.Id;
        opp.StageName = 'Qualification';
        opp.CloseDate = Date.today();
        insert opp;
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        Product2 testProduct = new Product2(
            Name = 'Anderson Tax Advantage Package',
            IsActive = true
        );
        testProduct.Service_Fulfillment_Weight__c = '1';
        testProduct.Type__c = 'Tax';
        insert testProduct;
        Product2 testProduct2 = new Product2(
            Name = 'Tax Toolbox',
            IsActive = true
        );
        testProduct2.Service_Fulfillment_Weight__c = '1';
        testProduct2.Type__c = 'Tax';
        insert testProduct2;
        PricebookEntry testPbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = testProduct.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert testPbe;
        PricebookEntry testPbe2 = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = testProduct2.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert testPbe2;
    }
    
    @isTest
    public static void testServiceItemAdded(){
        Opportunity opp = [select id from opportunity limit 1];
        PricebookEntry testPbe = [select id,product2Id from pricebookentry where product2.name = 'Anderson Tax Advantage Package' limit 1];
        OpportunityLineItem item = new OpportunityLineItem();
        item.OpportunityId = opp.Id;
        item.UnitPrice = 0;
        item.Quantity = 1;
        item.Product2Id = testPbe.Product2Id;
        item.PricebookEntryId = testPbe.Id;
        insert item;
        List<OpportunityLineItem> oppItemList = [select id from opportunitylineitem where opportunityId =: opp.Id];
        system.assertEquals(2, oppItemList.size(), 'success');
    }
}