objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Sale</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Platinum Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platinum Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ctrlEntitySubscriptionListTest.cls
@isTest
private class ctrlEntitySubscriptionListTest {

    static testMethod void ctrlEntitySubscriptionListTest () {
        Pricebook2[] PBs = [Select p.Name, p.Id From Pricebook2 p where Name = 'Standard Price Book'];
        Opportunity o = new Opportunity();
        o.Name = 'Test Oppy';
        o.CloseDate = System.today();
        o.StageName = 'Closed Won';
        o.Pricebook2Id = PBs[0].Id;
        insert o;
      
        Subscription__c objsubscription =  new Subscription__c();
        objsubscription.Opportunity__c = o.id;
        insert objsubscription;
        
        Apexpages.currentpage().getParameters().put('id',o.id);
        ApexPages.StandardController stdCon = new ApexPages.StandardController(o);
        ctrlEntitySubscriptionList obictrlEbtSub = new ctrlEntitySubscriptionList(stdCon);
        
     
    }
}