objects/Tax_Return__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax Returns</relationshipLabel>
        <relationshipName>Tax_Returns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Year__c</fullName>
        <label>Tax Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Tax Return</label>
    <nameField>
        <displayFormat>TAX-{00000}</displayFormat>
        <label>Tax Return Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClientEntityTaxReturnsControllerTest.cls
@isTest(seeAllData=false)
public with sharing class ClientEntityTaxReturnsControllerTest {
    @isTest static void testTaxReturnController(){
       Account acc = new Account();
       acc.Name = 'Test Client';
       insert acc;

       Tax_Return__c taxReturn = new Tax_Return__c();
       taxReturn.Tax_Year__c = '2020';
       taxReturn.Client__c = acc.Id;
       insert taxReturn;
       
       Test.startTest();
       ClientEntityTaxReturnsController.getTaxReturns(acc.Id);
       Test.stopTest();
     
    }
}